#Imports

In [ ]:
%pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 26.3 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 10.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=e8a3e21edf297e3b67fe11808820624cf3de49c468739627067c8defdeba2389
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [ ]:
from gensim.corpora import Dictionary
from gensim import matutils, models
from gensim.models.coherencemodel import CoherenceModel
import numpy as np
import pandas as pd
import nltk
from nltk import word_tokenize, pos_tag
from nltk.corpus import words
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import text
import scipy.sparse
from google.colab import drive
#from langdetect import detect
drive.mount('/content/drive')
from huggingface_hub import login
from google.colab import userdata

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

Mounted at /content/drive

#Functions

In [ ]:
def nouns_adj(text):
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    #print(pos_tag(tokenized))
    return ' '.join([word for word, pos in pos_tag(tokenized) if is_noun_adj(pos)])

In [ ]:
def run_lda_model (data, numTop):
  cvna = CountVectorizer(max_df=0.8)
  data_cvna = cvna.fit_transform(data.Text) # coverting into bag of words
  id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items()) # need it as input to lda
  corpusna = matutils.Sparse2Corpus(data_cvna.T)
  ldanan = models.LdaModel(corpus=corpusna, num_topics=numTop, id2word=id2wordna, passes = 10, random_state=42)
  # Full topic distribution per document
  doc_topics = [
      ldanan.get_document_topics(bow, minimum_probability=0.0)
      for bow in corpusna
  ]

  #print(doc_topics)
  for tid, terms in ldanan.show_topics(num_topics=-1, num_words=10, formatted=False):
    parts = [f"{w} ({wt:.3f})" for w, wt in terms]
    print(f"Topic {tid}: " + ", ".join(parts))

  # converts the LDA model’s sparse topic distributions into a fully dense, column-aligned matrix
  # Dense matrix (n_docs × n_topics), columns sorted by topic_id
  """n_topics = ldanan.num_topics
  topic_mat = np.vstack([
      np.array([p for _, p in sorted(dt, key=lambda x: x[0])])
      for dt in doc_topics
  ])

  topic_cols = [f"topic_{k}" for k in range(n_topics)]
  topic_df = pd.DataFrame(topic_mat, columns=topic_cols, index=tweets_stripped.index)
  """
  #print(topic_df)

In [ ]:
def remove(data, keywords):
  for x in keywords:
    data=pd.DataFrame(data['Text'].str.replace(x, ''))

In [ ]:
def pretty_topics(lda):
    for tid, terms in lda.show_topics(num_topics=-1, formatted=False):
        words = ", ".join(w for w, _ in terms)
        print(f"  Topic {tid}: {words}")

#Load Data

In [ ]:
pathT = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/Tweets_relevant.csv"
pathR = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /reddit_relevant.csv"
pathY = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/yt_relevant.csv"

In [ ]:
twitter_original=pd.read_csv(pathT)
reddit_original=pd.read_csv(pathR)
youtube_original=pd.read_csv(pathY)

In [ ]:
twitter['Text']=twitter_original['Text'].str.lower()
twitter=pd.DataFrame(twitter.Text.apply(nouns_adj))

In [ ]:
reddit['Text']=reddit_original['Text'].str.lower()
reddit=pd.DataFrame(reddit.Text.apply(nouns_adj))

In [ ]:
youtube['Text']=youtube_original['Text'].str.lower()
youtube=pd.DataFrame(youtube.Text.apply(nouns_adj))

#2 topic LDA runs

In [ ]:
run_lda_model(twitter, 2)

Topic 0: chatgpt (0.040), therapy (0.028), dec (0.015), friend (0.014), gpt (0.010), nov (0.009), friends (0.009), jun (0.009), ai (0.005), good (0.004)
Topic 1: chatgpt (0.040), therapy (0.039), ai (0.037), health (0.016), mental (0.016), therapist (0.012), jun (0.010), dec (0.010), support (0.010), com (0.007)

In [ ]:
run_lda_model(reddit, 2)

Topic 0: chatgpt (0.015), therapy (0.012), therapist (0.012), time (0.007), ai (0.006), link (0.006), people (0.006), way (0.004), human (0.004), self (0.004)
Topic 1: bot (0.025), chatgpt (0.018), prompt (0.014), questions (0.013), ai (0.009), post (0.009), people (0.009), open (0.008), therapist (0.007), concerns (0.007)

In [ ]:
run_lda_model(youtube, 2)

Topic 0: chatgpt (0.024), ai (0.017), people (0.015), therapy (0.013), human (0.009), good (0.007), therapist (0.007), mental (0.006), therapists (0.006), health (0.006)
Topic 1: ai (0.041), therapist (0.022), people (0.016), therapy (0.016), human (0.013), chatgpt (0.009), good (0.009), way (0.008), real (0.008), therapists (0.008)

In [ ]:
keywords=['bot','chatgpt', 'ai', 'therapist', 'therapists', 'therapy', 'gpt', 'mental', 'health', 'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug','sep', 'oct', 'nov', 'dec' ]

In [ ]:
for x in keywords:
    twitter=pd.DataFrame(twitter['Text'].str.replace(x, ''))
    reddit=pd.DataFrame(reddit['Text'].str.replace(x, ''))
    youtube=pd.DataFrame(youtube['Text'].str.replace(x, ''))

In [ ]:
run_lda_model(twitter, 2)

Topic 0: friend (0.015), people (0.009), free (0.006), support (0.006), good (0.005), com (0.005), friends (0.004), chat (0.004), human (0.004), solopreneur (0.004)
Topic 1: support (0.007), friend (0.007), friends (0.007), com (0.006), enable (0.005), hls (0.005), playback (0.005), free (0.005), google (0.004), video (0.004)

In [ ]:
run_lda_model(reddit, 2)

Topic 0: people (0.011), time (0.007), link (0.006), human (0.006), things (0.006), good (0.005), way (0.005), other (0.005), something (0.004), such (0.004)
Topic 1: prompt (0.016), open (0.016), questions (0.015), post (0.011), concerns (0.009), free (0.009), image (0.008), action (0.007), comment (0.007), moderators (0.007)

In [ ]:
run_lda_model(youtube, 2)

Topic 0: people (0.021), human (0.011), way (0.009), better (0.007), time (0.007), things (0.007), good (0.007), more (0.006), life (0.006), real (0.006)
Topic 1: human (0.014), people (0.013), good (0.011), humans (0.008), way (0.007), person (0.006), real (0.006), time (0.006), many (0.005), other (0.005)

In [ ]:
keywords_T=['ai_therapy_x','support', 'emotional','friend', 'friends', 'aitherapy', 'hls', 'com', '__x']

In [ ]:
for x in keywords_T:
    twitter=pd.DataFrame(twitter['Text'].str.replace(x, ''))

In [ ]:
run_lda_model(twitter, 2)

Topic 0: free (0.009), people (0.007), chat (0.006), good (0.004), advice (0.004), enable (0.004), playback (0.004), app (0.004), human (0.004), new (0.003)
Topic 1: people (0.005), video (0.005), care (0.004), news (0.004), technology (0.004), data (0.003), art (0.003), world (0.003), new (0.003), best (0.003)

In [ ]:
keywords_person=['person']

In [ ]:
for x in keywords_person:
    twitter=pd.DataFrame(twitter['Text'].str.replace(x, ''))
    reddit=pd.DataFrame(reddit['Text'].str.replace(x, ''))
    youtube=pd.DataFrame(youtube['Text'].str.replace(x, ''))

In [ ]:
print("Twitter: \n")
run_lda_model(twitter, 2)
print("Reddit: \n")
run_lda_model(reddit, 2)
print("Youtube: \n")
run_lda_model(youtube, 2)

Twitter:

Topic 0: free (0.005), video (0.004), solopreneur (0.004), chat (0.003), expensive (0.003), new (0.003), such (0.003), 推特账号 (0.002), use (0.002), 账号 (0.002)
Topic 1: free (0.006), enable (0.005), playback (0.005), app (0.005), advice (0.004), chat (0.004), google (0.004), new (0.004), human (0.004), good (0.004)
Reddit:

Topic 0: open (0.016), prompt (0.015), link (0.010), questions (0.010), post (0.010), free (0.009), image (0.008), concerns (0.008), model (0.007), issues (0.007)
Topic 1: time (0.008), questions (0.006), things (0.006), advice (0.005), way (0.005), thoughts (0.005), other (0.005), responses (0.005), life (0.005), such (0.005)
Youtube:

Topic 0: human (0.016), good (0.012), humans (0.006), better (0.006), new (0.006), time (0.005), way (0.005), many (0.004), other (0.004), world (0.004)
Topic 1: way (0.010), human (0.010), real (0.009), things (0.009), time (0.008), more (0.007), life (0.007), good (0.007), something (0.006), lot (0.006)

In [ ]:
keywords_person=['someone', 'people']

In [ ]:
for x in keywords_person:
    twitter=pd.DataFrame(twitter['Text'].str.replace(x, ''))
    reddit=pd.DataFrame(reddit['Text'].str.replace(x, ''))
    youtube=pd.DataFrame(youtube['Text'].str.replace(x, ''))

In [ ]:
print("Twitter:")
run_lda_model(twitter, 2)
print("\nReddit: ")
run_lda_model(reddit, 2)
print("\nYoutube: ")
run_lda_model(youtube, 2)

Twitter:

Topic 0: free (0.005), video (0.004), solopreneur (0.004), chat (0.003), expensive (0.003), new (0.003), such (0.003), 推特账号 (0.002), use (0.002), 账号 (0.002)
Topic 1: free (0.006), enable (0.005), playback (0.005), app (0.005), advice (0.004), chat (0.004), google (0.004), new (0.004), human (0.004), good (0.004)
Reddit:

Topic 0: open (0.016), prompt (0.015), link (0.010), questions (0.010), post (0.010), free (0.009), image (0.008), concerns (0.008), model (0.007), issues (0.007)
Topic 1: time (0.008), questions (0.006), things (0.006), advice (0.005), way (0.005), thoughts (0.005), other (0.005), responses (0.005), life (0.005), such (0.005)
Youtube:

Topic 0: human (0.016), good (0.012), humans (0.006), better (0.006), new (0.006), time (0.005), way (0.005), many (0.004), other (0.004), world (0.004)
Topic 1: way (0.010), human (0.010), real (0.009), things (0.009), time (0.008), more (0.007), life (0.007), good (0.007), something (0.006), lot (0.006)

#Topic Coherence

In [ ]:
textsTwitter = [row.split() for row in twitter.Text.tolist()]
dict_for_coh_Tw = Dictionary(textsTwitter)

In [ ]:
textsReddit = [row.split() for row in reddit.Text.tolist()]
dict_for_coh_Re = Dictionary(textsReddit)

In [ ]:
textsYoutube = [row.split() for row in youtube.Text.tolist()]
dict_for_coh_YT = Dictionary(textsYoutube)

In [ ]:

def cohere(data, dict_for_coh, texts):
  cvna = CountVectorizer(max_df=0.8)
  data_cvna = cvna.fit_transform(data.Text) # coverting into bag of words
  id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items()) # need it as input to lda
  corpusna = matutils.Sparse2Corpus(data_cvna.T)
  results = []
  for K in range(2, 7):
      ldaK = models.LdaModel(
          corpus=corpusna,
          id2word=id2wordna,
          num_topics=K,
          passes=10,
          iterations=400,
          random_state=0,
          chunksize=len(data),
          minimum_probability=0.0,
          eval_every=None,
      )
      coh = CoherenceModel(model=ldaK, texts=texts, dictionary=dict_for_coh, coherence='c_v').get_coherence()
      print(f"\n=== K = {K} | c_v = {coh:.3f} ===")
      pretty_topics(ldaK)
      results.append((K, coh))

  summary = pd.DataFrame(results, columns=["num_topics", "coherence_c_v"]).sort_values("num_topics")
  print("\nSummary:\n", summary.to_string(index=False))

##Youtube

In [ ]:
cohere(youtube, dict_for_coh_YT, textsYoutube)

=== K = 2 | c_v = 0.730 ===
  Topic 0: human, good, time, way, humans, better, other, many, real, something
  Topic 1: human, real, good, thing, things, more, way, life, lot, better

=== K = 3 | c_v = 0.726 ===
  Topic 0: human, way, time, good, other, humans, better, something, many, advice
  Topic 1: human, more, good, many, bad, real, thing, way, something, own
  Topic 2: human, good, real, things, time, way, better, life, work, lot

=== K = 4 | c_v = 0.738 ===
  Topic 0: human, time, humans, way, other, good, better, helpful, advice, many
  Topic 1: human, good, more, way, many, chat, real, issues, lot, time
  Topic 2: human, good, real, time, things, work, life, lot, way, more
  Topic 3: good, way, something, better, things, human, bad, great, problem, tool

=== K = 5 | c_v = 0.745 ===
  Topic 0: human, time, humans, way, other, better, good, many, helpful, advice
  Topic 1: human, chat, more, issues, al, same, good, use, friend, advice
  Topic 2: good, human, time, real, lot, things, life, work, ve, answers
  Topic 3: good, way, better, human, something, bad, great, things, tool, many
  Topic 4: human, real, way, good, humans, new, something, economic, more, world

=== K = 6 | c_v = 0.739 ===
  Topic 0: human, humans, other, way, time, helpful, many, video, better, things
  Topic 1: human, more, al, issues, use, chat, same, way, many, questions
  Topic 2: human, real, good, time, life, better, work, chat, answers, new
  Topic 3: way, something, good, tool, bad, human, better, problem, things, friends
  Topic 4: human, real, life, way, chat, good, better, thoughts, thing, money
  Topic 5: good, human, way, time, lot, things, better, many, humans, something

Summary:
  num_topics  coherence_c_v
          2       0.729634
          3       0.726173
          4       0.738047
          5       0.745417
          6       0.739189

In [ ]:
key_human=['human']
for x in key_human:
    youtube=pd.DataFrame(youtube['Text'].str.replace(x, ''))

In [ ]:
cohere(youtube, dict_for_coh_YT, textsYoutube)

=== K = 2 | c_v = 0.724 ===
  Topic 0: good, time, better, things, something, more, thing, problems, life, lot
  Topic 1: good, way, real, time, many, better, chat, things, more, life

=== K = 3 | c_v = 0.750 ===
  Topic 0: good, something, things, thing, helpful, system, time, way, support, real
  Topic 1: good, real, way, time, many, chat, much, bad, things, better
  Topic 2: better, way, more, time, good, life, things, many, lot, other

=== K = 4 | c_v = 0.760 ===
  Topic 0: good, thing, time, way, system, support, economic, new, real, things
  Topic 1: good, real, time, way, many, much, bad, life, self, better
  Topic 2: better, more, time, life, way, good, many, problem, real, advice
  Topic 3: things, way, chat, lot, something, help, good, better, everything, time

=== K = 5 | c_v = 0.749 ===
  Topic 0: system, economic, something, new, way, thing, time, year, better, years
  Topic 1: real, good, time, way, many, much, better, great, own, other
  Topic 2: life, better, time, more, way, good, many, advice, real, problem
  Topic 3: chat, way, things, help, lot, something, good, everything, better, time
  Topic 4: good, things, way, thing, language, real, helpful, ve, life, few

=== K = 6 | c_v = 0.747 ===
  Topic 0: something, time, thing, way, better, good, real, care, truth, helpful
  Topic 1: real, good, time, way, many, much, own, better, bad, other
  Topic 2: time, life, more, better, way, advice, many, real, other, problem
  Topic 3: chat, lot, way, things, help, good, something, problem, questions, everything
  Topic 4: good, way, things, ve, thing, language, helpful, real, something, great
  Topic 5: things, new, economic, models, year, jobs, company, years, tool, more

Summary:
  num_topics  coherence_c_v
          2       0.724459
          3       0.749735
          4       0.759533
          5       0.748593
          6       0.746666

In [ ]:
yt_list=youtube.Text.tolist()
yt_eng=[]
english_vocab = set(w.lower() for w in words.words())
english_vocab.update(['.', '-'])
i=0
for text in yt_list:
  text2=text
  for word in text.split(' '):
    #if i<10:
      #print(word)
    if not(word.isalpha()):
      print(word)
      text2=text2.replace(word, '')
  yt_eng.append(text)

’








“
”
😱😨

’





“
”



open-ended




’

’
non-responding


’

























'valid
'you











’
’
is…




whiter-than-i-am



“
thing.
’






e-waste

not…i
’




























yes-man
















%



]
....
/


sad-




self-critique


’


patterns—simply
non-judg




+








’







self-absorbed
first-ever
-powered


%
well-being




’






real-life






reality…an
’

non-understanding


















💀

😢


chat-
it…
'asd
'adhd
'telepsychistrist







%

=
=

=
=
=
%
]





🤷‍♀️






*
*

🙇



over-validation


semi-regular
check-in






chat-


database-












%

team/
’












no-nonsense




😬and











’
’




’





so-so

self-help












’

😅













💔

’
’

“
useful.
”

over-educated


’

“
me.
”


’


’








❤









al-15yrs/
gbt-2/3
*
*
“
self-reflection
“
”
b/w
6-minute

















%

texts/emls


😂😂😂

😭






































*
*
*
*

“
”


’

’






















💔
’
’
’

’










after45




-run
that…
=
power+time
“
”
power-imbalance
👁️🦾🤝💪🏼





..
seen.






..







😅


>







pseudo-scientific



’
’

relationship…

’

....
❤








%

’










’




’




’






’


’





’


’

ision-making
’
real-world
’


follow-up













’

’

’
issues…idk


3-4








....
.........







....













-like



3-4
self-centered

..


..
ass-kissy
😂

..
it.😂❤
..



’
’

’




’





💙

’

’

’



’



🤯

🤦‍♀️

❤


’




😂



🙂



“
”

’
true/authentic
self-abandonment

’













😊













❤❤❤
/





communication0












’
’










s.
”









“
”
‘
’





‘
’









’

entry-level
c-suite




model-it
higher-cost


’

dial-up

ability/spirit



“
”
step-by-step

’
open-source


’
goal-driven
“

”




%
%
”

%

retrned.
”
low-pd
4-year
internship/residency
%
win-win

win-win
post-labor
’


’


post-scarcity
’
’
long-term


open-source


’




“


’


post-scarcity








’




problem/trauma
😮
dr.













😂








’



’

’




’

%


long-term
all-natural

'
a.i








zoom-









%







@




dr.
k.


....
’




’
’


’


’











’

’
sociopaths/psychopath/narcissist


feelings/empathy
’


self-driving















self-reflect

with—and
strengthens—our
e.g
self-actualisation


'bad


💀

‘
’











’


’

❤


’
co-exist❤




app😂😂😂














dr.
k.


“
”


’




“
”










*
*





it…and
lol-

that-

fantastical-

’
basic😅
words-
’
of-

’
%

’
























’



4o

dr.k

%


/friend/companion
agn-
diagnosis-


validation-



a.i


a.i




thing😅
















double-speak

fantastic/great
catastrophic/worse


’













annoyed…




'ruthless

bs-ing




’




’




’

’

’



’






’

then……
😮‍💨😅





’
“
’
”
self-centered
self-absorbed


o3







’
’






counter-arguments


proof/information



“
”
“
”
“


’



....

😂😂

”
’






’
’





d.i.d






//courses.inanutshell.com/grounding-skills-for-anxiety-stress-and-ptsd




’


😂


🤔












psycho-babble














%




tests-



responses…
’
”
/communicate

“
”
with-
patient-

-
“
“
”

avlable-
“
”





’


’




❤

year.now
years.what



❤

trust.the


’
’



factors.this
reality.also
s.which

made.the

’

’




in-garbage










😂

/











sugar-coating





anti-social

built-in


court-appointed







re-frame














sci-fi





....


’

’

’

’




’


agn…


..



a.i.s
..
..










’








sub-sections




💼
work-related
❌
💡
self-compassion
💬





band-d



semi-casual
ect.




ro-like









/client





clm-


answers-
....



















__________________


stress-reducing


expert…












satisfied.😉😉
chat-



’

spell-check
/practitioner
🤍🙏🏼


“
”

'answer
”













.like

















homes😂😂











lgbtq+
love/a
minorities/categories
harmful/racist






face-to-face
😊




’
’
’

















..





-
❤












//www.youtube.com/watch
v=ysitnnnwqbw


....


’
😲

”






school🤭
..
..

..



it.i


understood.his
..


..
..




..












me,2
”
”
“
”

”

“

”
“
”



%






non-verbal
%











-venting

-




co2





—which





’



🤦‍♂️

’
’

’
’


after…




’


’



’







’





self-awareness


//youtu.be/fqslc_hr3fg
si=16alflqgp3li-s_t

😭

👍💚




















’

’



ptsd.









😂


’



’
’






psych2go













backup/support








artificial/
fictional/




call-wting

%


'cringemon

app/
business/
company/
chatroom/
'cringemon















co-opted


’

cmon…

“
”


+




“
”
’

’
well-being


“


”
’







’
»
…
😄🤦🏻‍♂️
*
*
*





a.i
_feels_






“

....


//www.youtube.com/watch
v=ysitnnnwqbw

-chats











who-knows-where


..
..
*
*
*
*
😂😂

-generated













😅



’











’
“
’
’


’

’



’

’

’




’















/
’

”








’



’

’











’


“
’





















..
1-2






2-3



question~chat












evidenced-based











’
’

’










’
”


-4


*
*
’
















’

%

»

one-sided
-things…
’

😞







’



’

“
“
”
👍
“
’

😢

5.2
’
i.
4



recursion—ask
’
agent-based
models—give
”
compliance—let
self-consistency
rule-following



































solution/help








c/


g.p.t



situations—like

illness—but
’
’









trauma/cptsd







slow-down-and-comprehend


memory/trigger
to/discuss




❤


clients.i












psychological/emotional

asd/adhd


immature.


writting/reading








😂
[
]
-like

....
*
*

*
half-ent
extra-careful








@
“
trauma-informed

constructively.
”

nuance—and



















*









60s










%
..












’

’

’

’





’
’
70s
’
’
’


’



discussion/argument



..
“
’
-curated
’
peer-reviewed
public-domn
medical/psychological
material.
”


💊

’

’




scripture-based


*










+
time-




’




’


....













long-term


❤

’











’

’










state-of-the-art
















general-purpose


“

”

—






follow-up




entry-level
c-suite




model-it
higher-cost


’

dial-up

ability/spirit



“
”
step-by-step

’
open-source


’
goal-driven
“

”




%
%
”

%

retrned.
”
low-pd
4-year
internship/residency
%
win-win

win-win
post-labor
’


’


post-scarcity
’
’
long-term


open-source


’




“


’


post-scarcity





//www.youtube.com/watch
v=ysitnnnwqbw

’


’


'noah



self-reminder








👍
p.s
🤔











hour/week






sessions/user









//youtu.be/wzlb0kywbmc




“
”


high-quality



derealization/dealization



’

😂


’



’

/psychology











’



’

’










[
___
]












’








“
”
😱😨

’





“
”



open-ended




’

’
non-responding


’

























'valid
'you











’
’
is…




whiter-than-i-am



“
thing.
’






e-waste

not…i
’




























yes-man
















%



]
....
/


sad-




self-critique


’


patterns—simply
non-judg




+








’







self-absorbed
first-ever
-powered


%
well-being




’






real-life






reality…an
’

non-understanding


















💀

😢


chat-
it…
'asd
'adhd
'telepsychistrist







%

=
=

=
=
=
%
]





🤷‍♀️






*
*

🙇



over-validation


semi-regular
check-in






chat-


database-












%

team/
’












no-nonsense




😬and











’
’




’





so-so

self-help












’

😅













💔

’
’

“
useful.
”

over-educated


’

“
me.
”


’


’








❤









al-15yrs/
gbt-2/3
*
*
“
self-reflection
“
”
b/w
6-minute

















%

texts/emls


😂😂😂

😭






































*
*
*
*

“
”


’

’






















💔
’
’
’

’










after45




-run
that…
=
power+time
“
”
power-imbalance
👁️🦾🤝💪🏼





..
seen.






..







😅


>







pseudo-scientific



’
’

relationship…

’

....
❤








%

’










’




’




’






’


’





’


’

ision-making
’
real-world
’


follow-up













’

’

’
issues…idk


3-4








....
.........







....













-like



3-4
self-centered

..


..
ass-kissy
😂

..
it.😂❤
..



’
’

’




’





💙

’

’

’



’



🤯

🤦‍♀️

❤


’




😂



🙂



“
”

’
true/authentic
self-abandonment

’













😊













❤❤❤
/





communication0












’
’










s.
”









“
”
‘
’





‘
’









’

entry-level
c-suite




model-it
higher-cost


’

dial-up

ability/spirit



“
”
step-by-step

’
open-source


’
goal-driven
“

”




%
%
”

%

retrned.
”
low-pd
4-year
internship/residency
%
win-win

win-win
post-labor
’


’


post-scarcity
’
’
long-term


open-source


’




“


’


post-scarcity








’




problem/trauma
😮
dr.













😂








’



’

’




’

%


long-term
all-natural

'
a.i








zoom-









%







@




dr.
k.


....
’




’
’


’


’











’

’
sociopaths/psychopath/narcissist


feelings/empathy
’


self-driving















self-reflect

with—and
strengthens—our
e.g
self-actualisation


'bad


💀

‘
’











’


’

❤


’
co-exist❤




app😂😂😂














dr.
k.


“
”


’




“
”










*
*





it…and
lol-

that-

fantastical-

’
basic😅
words-
’
of-

’
%

’
























’



4o

dr.k

%


/friend/companion
agn-
diagnosis-


validation-



a.i


a.i




thing😅
















double-speak

fantastic/great
catastrophic/worse


’













annoyed…




'ruthless

bs-ing




’




’




’

’

’



’






’

then……
😮‍💨😅





’
“
’
”
self-centered
self-absorbed


o3







’
’






counter-arguments


proof/information



“
”
“
”
“


’



....

😂😂

”
’






’
’





d.i.d






//courses.inanutshell.com/grounding-skills-for-anxiety-stress-and-ptsd




’


😂


🤔












psycho-babble














%




tests-



responses…
’
”
/communicate

“
”
with-
patient-

-
“
“
”

avlable-
“
”





’


’




❤

year.now
years.what



❤

trust.the


’
’



factors.this
reality.also
s.which

made.the

’

’




in-garbage










😂

/











sugar-coating





anti-social

built-in


court-appointed







re-frame














sci-fi





....


’

’

’

’




’


agn…


..



a.i.s
..
..










’








sub-sections




💼
work-related
❌
💡
self-compassion
💬





band-d



semi-casual
ect.




ro-like









/client





clm-


answers-
....



















__________________


stress-reducing


expert…












satisfied.😉😉
chat-



’

spell-check
/practitioner
🤍🙏🏼


“
”

'answer
”













.like

















homes😂😂











lgbtq+
love/a
minorities/categories
harmful/racist






face-to-face
😊




’
’
’

















..





-
❤












//www.youtube.com/watch
v=ysitnnnwqbw


....


’
😲

”






school🤭
..
..

..



it.i


understood.his
..


..
..




..












me,2
”
”
“
”

”

“

”
“
”



%






non-verbal
%











-venting

-




co2





—which





’



🤦‍♂️

’
’

’
’


after…




’


’



’







’





self-awareness


//youtu.be/fqslc_hr3fg
si=16alflqgp3li-s_t

😭

👍💚




















’

’



ptsd.









😂


’



’
’






psych2go













backup/support








artificial/
fictional/




call-wting

%


'cringemon

app/
business/
company/
chatroom/
'cringemon















co-opted


’

cmon…

“
”


+




“
”
’

’
well-being


“


”
’







’
»
…
😄🤦🏻‍♂️
*
*
*





a.i
_feels_






“

....


//www.youtube.com/watch
v=ysitnnnwqbw

-chats











who-knows-where


..
..
*
*
*
*
😂😂

-generated













😅



’











’
“
’
’


’

’



’

’

’




’















/
’

”








’



’

’











’


“
’





















..
1-2






2-3



question~chat












evidenced-based











’
’

’










’
”


-4


*
*
’
















’

%

»

one-sided
-things…
’

😞







’



’

“
“
”
👍
“
’

😢

5.2
’
i.
4



recursion—ask
’
agent-based
models—give
”
compliance—let
self-consistency
rule-following



































solution/help








c/


g.p.t



situations—like

illness—but
’
’









trauma/cptsd







slow-down-and-comprehend


memory/trigger
to/discuss




❤


clients.i












psychological/emotional

asd/adhd


immature.


writting/reading








😂
[
]
-like

....
*
*

*
half-ent
extra-careful








@
“
trauma-informed

constructively.
”

nuance—and



















*









60s










%
..












’

’

’

’





’
’
70s
’
’
’


’



discussion/argument



..
“
’
-curated
’
peer-reviewed
public-domn
medical/psychological
material.
”


💊

’

’




scripture-based


*










+
time-




’




’


....













long-term


❤

’











’

’










state-of-the-art
















general-purpose


“

”

—






follow-up




entry-level
c-suite




model-it
higher-cost


’

dial-up

ability/spirit



“
”
step-by-step

’
open-source


’
goal-driven
“

”




%
%
”

%

retrned.
”
low-pd
4-year
internship/residency
%
win-win

win-win
post-labor
’


’


post-scarcity
’
’
long-term


open-source


’




“


’


post-scarcity





//www.youtube.com/watch
v=ysitnnnwqbw

’


’


'noah



self-reminder








👍
p.s
🤔











hour/week






sessions/user









//youtu.be/wzlb0kywbmc




“
”


high-quality



derealization/dealization



’

😂


’



’

/psychology











’



’

’










[
___
]


’
’

’




’


well-being







😂😂





“
”


hector❤
dr.






’

’

’

”



’
’


’
’





pro-death
e.q
....

....
....




psychiatrist/











one-sided
....






covid-19



..



to.function

“
“






promoted/sold
'harms
'well










🤦

framework/definition

a.i.s
’
dr.

’










procedure/lack

—

’
”










'fth


'patient




​i

dr.




dr.


x-ray





’





%









“
’
”
’


ok-ish


-is


-it
-it













’








’
’





preliminary/secondary



















questions/reactions



—


—
life-changing

’

—
’
“
”
















👏👏👏


re-running



’





’



–







’





ran-of-the-mill


psychology-minded
context/prompt
use-cases/purposes


..

’
—

’
”
’
’








’
“
”
dr.

“
’

’
power/goal
’
❤



non-mirroringn



u.


”
”







algorithm/model



dr.






moral.injury
emotional.minority



o3
o3




.😅










him/










relationship/work








/

sister-
*
*
in-
.......
......


‼️‼️‼️
destruction😢💯
​please







’
’





😢
..



nutrition/fitness


check-ups

’
’








..

-it

•
•
non-reactive
•


’





slope…

’


a.i

......

.....


.....

.....

👍🏾


❤

them—



..


..

..
..

..











🤮

young…all
healed…geez




..





😅













self-harmer


thinking…sometimes




'thought



-




%

’



%
%
’




’


’

ision-making
’
real-world
’


follow-up
%
’

’
’



ior/apprentice










😵

’


engineers/data
’

🫡

that…


....

/exercise
....
....
....

'deepest
thought/patterns
....








💗
🦖




“
”





















0-20.



’


..
-like
ro…
😅
’









’
’











’








“
”
😱😨
’





“
”



open-ended




’

’
non-responding


’




















self-critique








'valid
'you











’
’
is…




whiter-than-i-am



“
thing.
’






e-waste

not…i
’






























yes-man
















%



]
....
/


sad-





’


patterns—simply
non-judg




+








’







self-absorbed
first-ever
-powered


%
well-being




’






real-life






reality…an
’

non-understanding


















💀

😢


chat-
it…
'asd
'adhd
'telepsychistrist







%

=
=

=
=
=
%
]





🤷‍♀️






*
*

🙇



over-validation


semi-regular
check-in





chat-


database-












%

team/
’












no-nonsense




😬and










💔


’
’




’





so-so

self-help












’

😅













💔

’
’

“
useful.
”

over-educated


’

“
me.
”


’


’








❤









al-15yrs/
gbt-2/3
*
*
“
self-reflection
“
”
b/w
6-minute

















%

texts/emls


😂😂😂

😭






































*
*
*
*

“
”


’

’




















’
’
’

’










after45




-run
that…
=
power+time
“
”
power-imbalance
👁️🦾🤝💪🏼





..
seen.






..







😅


>







pseudo-scientific



’
’

relationship…

’

....
❤








%

’










’




’




’







’
restrictions🙄🙄





’


’

ision-making
’
real-world
’


follow-up













’

’

’
issues…idk


3-4








....
.........







....











-like



3-4
self-centered

..


..
ass-kissy
😂

..
it.😂❤
..



’
’

’




’





💙
..





’

’

’



’



🤯

🤦‍♀️

❤


’




😂



🙂



“
”

’
true/authentic
self-abandonment

’













😊

co-exist










non-structured
/


-like
1:36:27-1:36:52




“

”

trauma/c-ptsd
self-awareness







😍
%





'
ally/emotional
'proof


de-escalating
'





dr.





















1-20


docs/chat



non-thinking
non-thinking
’

’
—

’

’
a.
i.
a.i



a.
i.




a.
i.

a.
i.


a.i.s


a.



know-how



k.





c'est
l'automatisation
c'est
qu'il


’



non-deterministic
%
astrology/fortune










“
”

beneficial—like
12-step


“
’

’
’

’
peer-to-peer

“

”

u.s.
insurance-driven

’
be-all
end-all
trauma-informed
’
well-versed
’






support—peer

’

’
ready—or
’
’
*
*



*
*
*
*


😂

______










dr.

....






ision😅












’


—
“
adapted.
’
is…
’

—

’


—


’


’

🙏
’


…
’


…
%

/
/




y'all

side…i
grok…
sided…
credibility…
dommage…


’



’


❤
’

—

🙏❤


🙏❤
example—




















’
’






’

’

dr.

🇩🇪
























hard-coded


long-term

😂










😅

’
’

dr.


















=y


















bullsh-t


’


’
’

’






’



’
’

’




/



’


fears.i
....
..
..



’
’




’

“

”









’


’






party-like

🖤🤍




’
’

’



’
’

’




isions…sick











dr.k



dr.
’
’







’

…












’

'collective
🧠









’
😂

’




’

’













ha-ha
😂😂😂






high-level
’
’
’
risks/effort














😅








everything-
-oh
..

..


😲
’
“
”

sit.a
sit.a
but——
none-sense
aside…
’







😭


sweet💝💗💖










..
..
😂


“
”
.🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥


𝕏❌

✅

this😂
to🙏🙏

..
🐐





😂
😅




'trts





%





“
’



chat-











“
”










’
old-ish


*



in-depth



self-guided
text-to-speech


print-out
long-winded
open-minded
*


off-topic




/
/


’
de-escalate

skills/abilities








....
.....



’


’


*
*

—

hard-hitter
hand-written



'
child-like
10-12k








no-one


y'all


’
’


follow-up





up-to-date
up-to-date











y'all

nazi/white

















=


ident-hysteric

body/




😳

’


self-aware







a.i



















—which
..

..





’
“
”

’




..

😂









.......
.....

in-


’
[
“
+

’
[
self-awareness
—
🌱
’
•

•
re-triggered
•
’
🕊
•
•
’
🎯
—
“
life.
”
🔁
—
💡
•
•
•
]





and/or











’
’



🐦‍🔥
✨🌟✨🌘🌞🌒✨🌟✨





’

tissue…

😊






😊😊

’





















—








😅





👍🏼

’





else…





❤





’


'buttons









’
*
life-changing
*






😍💪




anti-psychotic
..

’

’








dr.
k.




non-existent









5-step


sa-ed









dr.k







dr.k










’


%
1st

dr.











me.more


face-to-face









%





😂😂






’










dislocation—the
integration—friendship
belonging—collapse
self-worth
”
re-entry
non-social
’
self-reference
foreground-background
24-hour
reward-expectation
proof-of-force
low-level





self-talk





























in-
relationships/friendships
risks/vulnerability

























under-pd
third-world
instruction-tuned
thoughts/responses








non-
non-
non-







no-self

'fake



under-supported




self-soothe


5-7



’

–


’
real-time
real-time


-like




’









’






'syncophantic










😅










’
’

’
’

self-awareness
’


guys…ffs…don
’










stoic-based
taoist-based
board/




..
possible-do

*
_timestamps_
*
*

*


🤔
•
🧠
📝
'what

🎧
🎧
🗣️

👂

•
🧩
self-healing
•
🚫

•
🌱
self-healing

🤖

*
✨
*
_vidskipper
_
*

’
’










’



’
’

then…

“

than…blah
blah…
”

.....


long-standing
self-help



'as







and/or














chess…

’
even.
”

’

—

’





hobbies/beliefs

“
”


—







non-judgement/non-bias

this…

’
’

day…
groundbreaking…


important…









’

’



🙏🏾
’








’



’





—



—






takes—subscribed



’

’


boundaries…


“
way.
”
’
’
“
“
”





’
’



















8-10




'individualism




In [ ]:
yt_eng_df=pd.DataFrame(yt_eng, columns=['Text'])

In [ ]:
cohere(yt_eng_df, dict_for_coh_YT, textsYoutube)

=== K = 2 | c_v = 0.724 ===
  Topic 0: good, time, better, things, something, more, thing, problems, life, lot
  Topic 1: good, way, real, time, many, better, chat, things, more, life

=== K = 3 | c_v = 0.750 ===
  Topic 0: good, something, things, thing, helpful, system, time, way, support, real
  Topic 1: good, real, way, time, many, chat, much, bad, things, better
  Topic 2: better, way, more, time, good, life, things, many, lot, other

=== K = 4 | c_v = 0.760 ===
  Topic 0: good, thing, time, way, system, support, economic, new, real, things
  Topic 1: good, real, time, way, many, much, bad, life, self, better
  Topic 2: better, more, time, life, way, good, many, problem, real, advice
  Topic 3: things, way, chat, lot, something, help, good, better, everything, time

=== K = 5 | c_v = 0.749 ===
  Topic 0: system, economic, something, new, way, thing, time, year, better, years
  Topic 1: real, good, time, way, many, much, better, great, own, other
  Topic 2: life, better, time, more, way, good, many, advice, real, problem
  Topic 3: chat, way, things, help, lot, something, good, everything, better, time
  Topic 4: good, things, way, thing, language, real, helpful, ve, life, few

=== K = 6 | c_v = 0.747 ===
  Topic 0: something, time, thing, way, better, good, real, care, truth, helpful
  Topic 1: real, good, time, way, many, much, own, better, bad, other
  Topic 2: time, life, more, better, way, advice, many, real, other, problem
  Topic 3: chat, lot, way, things, help, good, something, problem, questions, everything
  Topic 4: good, way, things, ve, thing, language, helpful, real, something, great
  Topic 5: things, new, economic, models, year, jobs, company, years, tool, more

Summary:
  num_topics  coherence_c_v
          2       0.724459
          3       0.749735
          4       0.759533
          5       0.748593
          6       0.746666

##Twitter

In [ ]:
cohere(twitter, dict_for_coh_Tw, textsTwitter)

=== K = 2 | c_v = 0.735 ===
  Topic 0: chat, 推特账号, best, 账号, 电报号, enable, 飞机号, playback, good, 谷歌账号
  Topic 1: video, free, care, human, new, chats, more, art, open, news

=== K = 3 | c_v = 0.732 ===
  Topic 0: chat, 推特账号, 账号, 电报号, 飞机号, 谷歌账号, tiktok账号, 脸书号, ins号, best
  Topic 1: video, free, piped, care, chats, google, new, data, human, open
  Topic 2: new, free, best, human, chat, session, app, time, more, way

=== K = 4 | c_v = 0.729 ===
  Topic 0: 推特账号, 账号, 飞机号, 电报号, 谷歌账号, tiktok账号, chat, 脸书号, ins号, best
  Topic 1: art, new, best, news, open, more, care, technology, human, tech
  Topic 2: new, best, good, way, human, use, chat, next, session, enable
  Topic 3: video, free, chat, piped, app, data, gender, open, time, advice

=== K = 5 | c_v = 0.727 ===
  Topic 0: 推特账号, 账号, 电报号, 飞机号, 谷歌账号, tiktok账号, 脸书号, ins号, chat, best
  Topic 1: art, human, zealy, best, new, news, free, more, good, io
  Topic 2: new, human, best, good, way, chat, life, time, real, session
  Topic 3: video, free, chat, piped, app, gender, si, playback, enable, data
  Topic 4: platform, creator, new, prompt, better, open, care, best, chats, more

=== K = 6 | c_v = 0.740 ===
  Topic 0: 账号, 推特账号, 飞机号, 电报号, 谷歌账号, tiktok账号, 脸书号, ins号, chat, tool
  Topic 1: art, zealy, best, more, io, free, new, life, open, news
  Topic 2: new, best, way, chat, enable, life, human, free, real, playback
  Topic 3: video, free, chat, piped, app, gender, playback, enable, si, data
  Topic 4: care, prompt, chats, better, open, new, best, benefit, resources, platform
  Topic 5: good, human, artificial, intelligence, gene, chat, new, voice, apps, art

Summary:
  num_topics  coherence_c_v
          2       0.734662
          3       0.731655
          4       0.729310
          5       0.727383
          6       0.739990

In [ ]:
nltk.download('words')

In [ ]:
text = "This is a simple English sentence."
tweet_list=twitter.Text.tolist()
tweets_eng=[]
english_vocab = set(w.lower() for w in words.words())
i=0
for text in tweet_list:
  for word in text.split(' '):
    #if i<10:
      #print(word)
    if (word.lower() not in english_vocab) or not(word.isalpha()):
      print(word)
      text=text.replace(word, '')
  tweets_eng.append(text)

techforgood
💙
khanna
ces2024
@
curieuxexplorer

-model
patients
emotions

ones
bit.ly/3s185pi
@
careldr
@
@
@
shi4tech
@
heinzvhoenen
@
@
gvalan
@
drnikolova_rumi
@
sminaev2015
ces
ces24
ination
~♡
@
replying
mikaqvia
hugsss
🫂🫂
cuz
megumi
kagome
hugs
@




newszone.arammon./
p=2452…
empowers



ahmann
@



thera-
poe./thera-
𝙲𝚊𝚝𝚊𝚕𝚕𝚊𝚡𝚎𝚛
@
catallaxer
“
[
conferences
etc
”

cells
’
brn
’
ve
gears
that.
”
natasha
vita-more
phd
@
amplifyingcognition./nata…
@


@




forbes./sites/lanceeliot/…
cel

🍿
@

studios
bros

artists
jobs

entry-level
@
latimes
dániel
takács


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
wellknown
kyomie

‼️
@
graysunns
lululunatiic
@


characters
✨free✨
btc


@

matic
'pessimistic
crypto-
antics
cryptohumor

@
@
ucf
pany
@
limbitless3d

.wusf.usf.edu/-n…
nara
morrison

priestley
@
elections

astro-creep
@
jortega95


onk136
teh
limau
@
olarakk


asya

ndwandwewethu
🇿🇦
@
thembanitn
replying
destinyzee

naye
lowe

kwini
cstv
@
experts
chats

contexts
risks
conction



@
abbyohlheiser
vox./technology/2023/12/1…

lionell
|
🔎𝕏
|
xar
|
💙
@
mander
vikram
karve
@
selfhelp


worries
👇
wp.me/p1em7-6cr
stories
vikram
karve
pune
blogger
sheen18
@
web3


creators
visitors
revolutionalized
@

info
alat
terapi
kesehatan

@
id.carousell./p/kursi-pij…
‘
’
ade-old

fragments
@
’
chats
the…
dlvr.it/t0vtwy
j'
que
j'
goethe
|
🍉
@
inspectornerd

reasons



problems
means

toptools
empowers



forbes./sites/lanceeliot/…


emindy

@

andpsychiatry
biasincare
chats
incare

artificialintelligence
emindy./index.php/2023/12…
bjr
journals
bjr_radiology
bir
podcast
issam
naqa
wider
bjr

imaging

inations
bit.ly/46uwlzx
bit.ly/3puywft
/
⚢
@
_ryy2
lets
togetherr🫂🫂🫂
mewen
|
frieren

@

funniest
fatalis

hands
いわたわし
@
tawashi_cb

なんなんこいつｗｗ

gdala
gdala
@
humanestatistic

babysmurf9000

*
*
thoughts
learning/conversion
/operant
resonating
bjr
journals
bjr_radiology
bjr

imaging

inations
issam
naqa
bjr
articles
bit.ly/3puywft
highestself.
@
meets

steps



intertwines
tlored

ination
digitalempathy
harry19nt
@




turing


turingtest
forbes./sites/lanceeliot/…
@
years
patients

parts
interestingengineering./h…
iraconda
mel_vil


—but
|
artworks
ola


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
qnet
ghana
@




dlvr.it/t0vwvg
algorithm.church
@
algorithmchurch.

»




«
forbes./sites/lanceeliot/…
ml
nlp
agi
jyotirgamya
@
jyotirgamya_org


alized


munity-based

ination
well-being
neuroscience
jousie29


✨
@
thoughts
🫧
@

🎉
campgn

zealy

artists.🤏zealy.io/c/
–

ketplace
♡
|

|
🇵🇸
@
cinnamxonn
hugs
❤️🖼️
🛡|
stme|
udao
@
mdcode7350
@

@


retl

@
raleigh
@
makirollofc

babes

generators
girlies
folks
jobs
funko
@
devnationworld

alized
plans
monitoring
🤖
-powered
devices
diseases
alized

💻💊
incare
stme
@
zhekaba003
@

nem-trade
@
mshkh2002




rdrop
pdr
@
pdr_us

interesting—dr
neena
hder
ocugen
’

ocu400
shifa
precision—artificial


shifecision./
hana_and_b2network
🏴‍☠️
@
hanangeliaxyz
@

hana_and_b2network
🏴‍☠️
@
hanangeliaxyz
lfg
bro
@

munter
@
itsmunter
replying

services

w.
@
replying
bard.google./

skype
twitterx

deaner444
@
deanehenryson



app
google
tic-

selfcare


freeapp

𝓐𝐼
@
take3
replying
draftdayy

@

s24




✨
@
thoughts
🫧
@

🎉
campgn

zealy

artists.🤏zealy.io/c/
–

ketplace
conversations
waters




minds
souls
futureof
@
maverickp567

replying



@
maverickp567





bgatesisapyscho

🚨💉
%
arrests
wasn
athletes
bs
mrna
experi

’
’
happened…….it
hasn
’
msm
’
questions
greatest

d🏳️‍🌈
kojo
ampofo
they/them/ɔno
papakojoampofo


hours
members
lgbtiq
ghana


kojo
ampofo
they/them/ɔno
papakojoampofo

papakojoampofo
📌in





ghana
probono
tenshitemple


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
anya
@

👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
bodycalc
@
bodycalc

ive
issues


conversations

worries
download

coinrt
@
coin_rt

replying

🚀🚀🚀
cel

winters
magfest
@

artists
yall
midjourney
winters
artist-
createdontscrape
@
jonlat

replying
jonlat
google
’
names
pinc
™
@
pinc_

@
newsweek
real-world
applications

trials

higher-quality
possibilities
pinc
™
sciences
partners
utilized
nlp
patients
nodules
patients
weeks
newsweek./2023/12/08/-c…
@


structures

shitty
🇵🇸
@

fr
rn…
wysocki
anya
@
anyatrades
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
jimcoastalluxuryproperty
pdr
@
pdr_us

interesting—dr
neena
hder
ocugen
’

ocu400
shifa
precision—artificial


shifecision./
🌛🌜
amnesiadevil



medicare


medicare
anya
𝕏
@
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
seán
t.
@
mer__edith
@
sociopathic

researchers

yukiaddiction
rnbow
@
yukiaddict



app
anya
@
anyatrades
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
iisc
bangalore
@

researchers
cdsiisc

ultrasound
videos
dors
iisc.ac.in/events/-tool-…
iiscresearch
owyang
@
jowyang


-trades

roles
sites
homeowners
tools
issues
-even
fields

trning
professionals
areas

back-office
tasks
-can

highestself.
@
highestself


tools
gadgets
changers



insights

inative
@
jeff16

@
nsq_show
’
ramifications

psycho
online




anya
@
_anyastradess
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
anya

@

👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
szesz
@
kszesza

replying

🎊
szesz


✨
@

🌟
🌟



-generated
styles
senses
emotions

szesz
@
kszesza

replying

@
zealy_io
🔥
szesz


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
bikerbrian
anya
@
anyatrades
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
steeva
@
avant
pfa
frontline


af
s.
kühn
eib
@
eibinstitute


%

sitalumni
stars

disabilities
games

@
ruerose9

“
”



source…
alpates




padmanaban
pichandi
pdr
@
pdr_us

interesting—dr
neena
hder
ocugen
’

ocu400
shifa
precision—artificial


shifecision./
🧡
de.fi
💬beoble
orivium
@
reborn_1998

replying

niiiiiice
🧡
de.fi
💬beoble
orivium
@
reborn_1998

replying

anya
@
anyatrades
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
bodycalc
@
bodycalc



🌈🗣️



judgment-free
conversations
download

highestself.
@
highestself



humans



ries

@
breakp2037


creativity—just

endofyearcelebration

wele
m.
faustiii.bsky.social
sang-rak
@
richardkimphd

-powered
devices
regimens


ces
xen
|

davis🐞
@
ussalcrab



generators
’
donnel
@
donnelvillager

pnting
😢
𖤐
@
ghoulglrl

youre


idrc
conversations
endlessconvos

cherished
moments
pixel-perfect
emotion-rich


memoryrecreation
pelodoido
@
pelodoid0

replying
pelodoido
@
pelodoid0





khanna
ces2024
khanna
ces2024
@
curieuxexplorer

-model
patients
emotions

ones
bit.ly/3s185pi
@
careldr
@
@
@
shi4tech
@
heinzvhoenen
@
@
gvalan
@
drnikolova_rumi
@
sminaev2015
ces
ces24
ination
deaner444
@
deanehenryson



app
google
tic-

newyearsresolution
goals
selfcare


freeapp

toebut
@
toebut

replying

toebut
@
toebut

replying

legends
@
legendsspeak

-powered


talks
debates




conversations


challenges
🌿
wyld
🌿
@
nightwyldsystem


abusers
hc-did
ramcoa
munities
..
guys
documense


others

hc

shit
lowkey
systems
dr.
@



licensing


counseling

forbes./sites/lanceeliot/…
forbes
techbrium
_law
_ethics
roy/
@
royscott

replying
witchyscott
ill.


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
@
ililelph

replying

@
ililelph

replying

🚀🚀
valerius
@
bob_everiman




asylums
queer🇺🇸
🏳️‍🌈
@
_iggy
@
ineya_veganfood
@
patrickstrud

ones

💎
iggy
💎
@

replying
ineya_veganfood
@
gnq__
@
patrickstrud

lgb

zenpast
@
zenpresent



debugging
empathetic
well-balanced
yhubie
@

replying
wele
@


rcraft
farms


ments

khing_


✨
@

vibes🖤
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
khing_


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
khing_


✨
@

😊
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
khing_


✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
yaz
@
kurtyaz1

additonal
concepts
@
x3
jaquish
bfr
emf
pemf


rehit
hypoxia
bf
lionell
|
🔎𝕏
|
xar
|
💙
@
lionellhq

replying
lionell
|
🔎𝕏
|
xar
|
💙
@
lionellhq

replying
s.
bledsoe
@
mistysbledsoe

hours

life-coach


6-8

visits
visits
questions

co-pay
bills
months
levels
looks
tropes
professionals
leaders
panies
toxic-low-iq-opinionated-basement-dwelling-dweeb-trolls
dly
protocols
arron
johnson
@
meirnonart

replying
eze3d
@
grico316


lmaooooo
🐵


✨
@


dly
look👀🫦
🫧
@

🎉
campgn

zealy

artists.🤏zealy.io/c/
–

ketplace
🐵


✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
millers|

🟣
adashe
@
millerstho

🌟
weling
minds
cheers
@

2024
millers|

🟣
adashe
@
millerstho

replying

oyeah
pakistan
@
pakutmost

reveals
psycho
expressions
scientists


videos
results
trned
switzerland

ufot


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
ufot


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
ufot
@
blessing_u16821





ufot
@
blessing_u16821





nehan
sqr
@
madushka_nnehan





nehan


✨
@

🌟
🌟



-generated
styles
senses
emotions

nehan
sqr
@
madushka_nnehan

replying

@
zealy_io
nehan


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
ufot


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
ufot
@
blessing_u16821

replying

@
zealy_io
|areon
|
@

@
theweeklive


expressions
emotions

theweek.in/news//2024/…

@
theothub

🤖

theothub./updates
plus+
results
coordination
aziz-zadeh
usc
chan


@
theothub

signatures
symptoms
biasing
🤖

theothub./updates
plus+
khanna
ces2024
@
curieuxexplorer

-model
patients
emotions

ones
bit.ly/3s185pi
@
careldr
@
@
@
shi4tech
@
heinzvhoenen
@
@
gvalan
@
drnikolova_rumi
@
sminaev2015
ces
ces24
ination
@



fucked
@
lola19828


quick-

@
speaktrack

counseling

cbt

disorders
recoveryispossible
staystrong


✨
@

📸
@

👉.me
–

minds

ketplace
artwork


✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace



✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy


✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace



✨
@

heart.💙
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace


✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace



✨
@

vibes🖤
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators


✨
@

😊
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace


✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop


✨
@
🌟
minds
cheers
🎉✨
2024
b41m
❤️memecoin

replying
@
philipj23994175

replying



✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
@
philipj23994175

replying

@
philipj23994175

replying



✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
@
philipj23994175

replying

wonderfull


✨
@

🌟
🌟



-generated
styles
senses
emotions



✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop


✨
@
moments
ination
cheers
🌟
endofyearcelebration
khanna
ces2024
@
curieuxexplorer

-model
patients
emotions

ones
bit.ly/3s185pi
@
careldr
@
@
@
shi4tech
@
heinzvhoenen
@
@
gvalan
@
drnikolova_rumi
@
sminaev2015
ces
ces24
ination

replying
heartfelt.services
’


crypto
deaner444
@
deanehenryson



feelings
frenemy
app
google
tic-

frenemies
selfcare


freeapp

mel_vil


—but
|
artworks
@



problems
|
dna
resources
educationresources
]
-driven
avatars

interventions
about…
dlvr.it/t0pqnz
sharma
@



problems
|
dna
resources
educationresources
]
-driven
avatars

interventions
about…
dlvr.it/t0pqhc
bodycalc
@






pals
download
🌈💬✨
@
mad_in_america



app
interventions
journaling
psychoeducation
positive/negative
madinamerica./2023/12/-…
@


rcraft
farms


ments

@

’


retweeted
davis
@
peter_brit

dcvax
allsolidtumors
gbm
ulrike
herbrand
phd
vitro
bioassays


products

opportunities
outes
trials
alized

ination
alized
atmps
therapies

treatments
patients
algorithms
alized
one-size-fits-all
solutions
outes

therapies
aspects

algorithms
biokers
responses
treatments
therapies
vectors
therapies
diseases
disorders
certn
cancers
cells
genes
algorithms
sets
genomics
proteomics
patterns
relationships
methods
data-driven
researchers
cells

gene-editing
strategies

therapies

technologies
therapies

therapies
cutting-edge
technologies
criver./eureka/whats-hot-…
rx
jia
@
jia_luo

@
iaslc
wclc23
mittee
multi-institutional

nc
nc-registry.org
🌎
colleagues
rx
nc
singapore
onclive.
@
onclive

jia_luo
@
danafarber
insights
chemo
wclc23
@
iaslc
lcsm
onclive./conference/world…
benita
_michaels
udao


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
benita
_michaels
udao


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
💎
iggy
💎
@

gnq__
@
backitup1990
@
jonperry501
@
vpnclark
@
charles95684721
@
@
pjaxparker

💎
iggy
💎
@

gnq__
@
platinumffaggot


”


isn
’

radu
@

danclintonrn
@
mangan150
drugs
journals
specialists
ccp
practitioners
remendations
‘

tloring

’
caregivers

@
documense
certn

eyes


devuono
@

ctvnewsnorthern
todays
services
mrna
diseases


a.
m.
pines
@

vesperaegis
@
skdh
folks

jobs
rx



programs
jo-ann
@


rcraft
farms


ments

josé
cordeiro
transvision
humanityplus
josé
cordeiro
transvision
humanityplus
@
cordeiro

josé
cordeiro
advances
things
technologies
crispr

mrna

billions

josé
cordeiro
transvision
humanityplus
josé
cordeiro
transvision
humanityplus
@
cordeiro

josé
cordeiro
advances
things
technologies
crispr

mrna

billions

platzer
davis
@
peter_brit

dcvax
allsolidtumors
gbm
ulrike
herbrand
phd
vitro
bioassays


products

opportunities
outes
trials
alized

ination
alized
atmps
therapies

treatments
patients
algorithms
alized
one-size-fits-all
solutions
outes

therapies
aspects

algorithms
biokers
responses
treatments
therapies
vectors
therapies
diseases
disorders
certn
cancers
cells
genes
algorithms
sets
genomics
proteomics
patterns
relationships
methods
data-driven
researchers
cells

gene-editing
strategies

therapies

technologies
therapies

therapies
cutting-edge
technologies
criver./eureka/whats-hot-…
vito
@

vitodottv
@
domndomme

pics
vids
animations

hideki4.0/⭐️⭐️⭐️
@


rcraft
farms


ments

meme
@


👋
dm
📥
bodycalc
@

🗣️
ive



download

selfcare
genderaffirmation
software
kies
soft_k


thoughts
lisa🇺🇸🇺🇦
davis
@
peter_brit

dcvax
allsolidtumors
gbm
ulrike
herbrand
phd
vitro
bioassays


products

opportunities
outes
trials
alized

ination
alized
atmps
therapies

treatments
patients
algorithms
alized
one-size-fits-all
solutions
outes

therapies
aspects

algorithms
biokers
responses
treatments
therapies
vectors
therapies
diseases
disorders
certn
cancers
cells
genes
algorithms
sets
genomics
proteomics
patterns
relationships
methods
data-driven
researchers
cells

gene-editing
strategies

therapies

technologies
therapies

therapies
cutting-edge
technologies
criver./eureka/whats-hot-…
shib
🪖💰
@


rhys-williams
@

stefanrw1
@
wearescanners
’
certn

“
relationships

creations
aren
’

strangers
parasocial

highestself.
@



tech-savvy

bodycalc
@

🗣️




worries

anytime
genderaffirmation
downloadnow
art-as-
@
andigraf3


tarottaxi./2023/12/31/-…
@
rootweaver
visionquest2024
@

’


shrub🤪
vojin
hotz
🌑
@

hoppyturtles
meetings


meetings
pany
software
sucks
hans🫶💎🙌🚀🔋🛡☀₿ξɖ🎏🕉🦧🤖𝕏
@

elonmusk
@
wallstreetsilv
👀
'machina
gathers
findings
symptoms


kofi
@

ubos

rin
niah

@


well-being


feelings
niah

@


well-being


feelings
davis
@
peter_brit

dcvax
allsolidtumors
gbm
ulrike
herbrand
phd
vitro
bioassays


products

opportunities
outes
trials
alized

ination
alized
atmps
therapies

treatments
patients
algorithms
alized
one-size-fits-all
solutions
outes

therapies
aspects

algorithms
biokers
responses
treatments
therapies
vectors
therapies
diseases
disorders
certn
cancers
cells
genes
algorithms
sets
genomics
proteomics
patterns
relationships
methods
data-driven
researchers
cells

gene-editing
strategies

therapies

technologies
therapies

therapies
cutting-edge
technologies
criver./eureka/whats-hot-…
kadrian
stahley
@
stahleykadrian

kipmock


pn
conditions
full-body
deaner444
@
deanehenryson



actions
app
google
tic-

selfcare


coolapps

deaner444
@
deanehenryson



actions
app
google
tic-

selfcare


coolapps



✨
@

😊
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
@





griffin_wood
@

viridaapple
@
moofknowledge


@





@

@

damb
feels

rxopyywx


✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
rxopyywx
@







✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
💙
de.fi
@
ikhideasuelimen

heard




💙
de.fi


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
@





btc


@


bnb
cheaper
fees
retl

cryptohumor
bnb
acha
@
quitsland

yepindeedagoat
@
alexhaedda
@
im
girls—
ve
relationships
mom
women
mntn
relationships
women


feith
@

infantilization

“
”
blassie
@
megantheevalium

hr
logan

rx
handlewithcare_blog
@

stroke-like
migrne
attacks

seizures
👉doi.org/10.7759/cureus.25691
brntumor
stsyndrome
ceeg
radiationinducedmeningioma
radonc
neuroonc
icu
goodtimes

savingpb
@
therealworld_
@
cobratate
attacks

cbt

@

surpasses
dors
guidelines
dors
tools



mri-based
tools
wearables
rolo1995
hotz
🌑
@

hoppyturtles
meetings


meetings
pany
software
sucks
bodycalc
@

🗣️💭

panion
thoughts
caring


anytime
filters
download

selfcare
nostigma
highestself.
@

-tools


patterns

game-changer
ination
@
maplexter

enderintestines
@
tibblesyorkie
@
morritician
certn
things


lines
certn
things
bodycalc
@


anytime
confidante

alized

download
selfcare

tibbilz
@
tibblesyorkie

maplexter
@
@
morritician
lol


hotline
varies
’

certn
topics
gettong
hotz
🌑
@

hoppyturtles
meetings


meetings
pany
software
sucks
@


emotions
expressions
settings
🤖👀🧠


@
naveensankars
ilo
🪬
🎧
@


’
’
attachement
anxieux
je
souffre
je
suis
toujours
’
ft
quelque
peur
que
amies
tournent
le
quelqu
’
une
hotz
🌑
@

hoppyturtles
meetings


meetings
pany
software
sucks
dorf


wallstreetsilv

mercial
tek

stories

soooo
goooooood
wt
panies

employees
problems


@
guydealership

sales
vs

@


identifies
emotions

trned
game-changer
psycho

psycho
✝️🙏
@
hoping66966500


rcraft
farms


ments

pennycrypto
@


rekable
insights
📬
info
alat
terapi
kesehatan

@

id.carousell./p/kursi-pij…
hype
’
’
long-term
|
nhton
technologies
dlvr.it/t0ms0j
highestself.
@





inative
algorithms
custom-fit

fingertips
🤖❤️
ination
alizedcare
himanshu
gandhi
निषाद
🤚🏻🇮🇳
@


patients
emotions

briefest
ones
researchers
hours
recordings

artificialintelligence
psycho
@


you💙
dm
me⭐
jas
wakeupworld23

houselyndsey
pharma
mrna
lipid
nanoparticles
lpn

eagles
plicit
nano
particles
brn

🦇🔊💼🏡📈
architect🛡️
@
architect9000

predictions
crypto


edu
@







✨
@

😊
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
edu


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
𝔄𝔟𝔰𝔦𝔫𝔱𝔥𝔢
@
onevaguememory



years
nsb6
@
xwnvna





mel_vil


—but
|
artworks
akobundu
❤️
memecoin
logx
🟣
🏴‍☠️
@





trends
llc
@
ytzww

trends
plans

vr

gene-editing
breakthroughs
telemedicine
alized
tech-enhanced

care2024
futureof
ytrendsworldwidellc

mfon
|
@
edge_protocol


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
mfon
|
@
edge_protocol


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
ventura
architect🛡️
@
architect9000

predictions
crypto


mfon
|
@
edge_protocol
@





mfon
|
@
edge_protocol


✨
@

🌟
🌟



-generated
styles
senses
emotions

mfon
|
@
edge_protocol


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
ryan
@
ryanthedemiboy2


*
*

shit
years
*

@

therealworld_
hours
ships
expenses

bills


matters

things

sabi
@
mad_in_america



app
interventions
journaling
psychoeducation
positive/negative
madinamerica./2023/12/-…
woomii
@



months


roseg
lachlan
phillips
@
bitcloud

agents

researchers
*
pany

In [ ]:
tweets_eng_df=pd.DataFrame(tweets_eng, columns=['Text'])

In [ ]:
tweets_eng_df.head()

                                                Text
0    dev          session fleeting               ...
1                                        i  instant
2  mr tweet  renowned test     advisement   advis...
3                             matt   check     poe./
4        longevity   gene  genetic engineering st...

In [ ]:
cohere(tweets_eng_df, dict_for_coh_Tw, textsTwitter)

=== K = 2 | c_v = 0.747 ===
  Topic 0: free, enable, playback, human, care, tool, technology, best, better, voice
  Topic 1: chat, good, new, art, best, open, video, tech, more, platform

=== K = 3 | c_v = 0.741 ===
  Topic 0: free, enable, playback, technology, tool, care, advice, best, voice, prompt
  Topic 1: chat, good, open, art, more, new, tech, big, year, news
  Topic 2: new, video, best, human, chat, platform, other, life, many, money

=== K = 4 | c_v = 0.743 ===
  Topic 0: free, enable, playback, advice, technology, better, relationship, dialogue, play, gender
  Topic 1: chat, good, open, tech, year, new, time, art, real, day
  Topic 2: human, chat, new, platform, best, life, art, creator, many, good
  Topic 3: video, more, tool, best, voice, new, prompt, money, data, conversation

=== K = 5 | c_v = 0.745 ===
  Topic 0: free, enable, playback, advice, relationship, dialogue, great, play, better, girl
  Topic 1: chat, good, open, art, tech, anyone, new, year, sexy, day
  Topic 2: chat, platform, best, gender, new, creator, today, human, life, art
  Topic 3: video, best, new, money, prompt, content, data, other, create, code
  Topic 4: human, care, voice, conversation, more, technology, use, al, tool, future

=== K = 6 | c_v = 0.745 ===
  Topic 0: free, enable, playback, advice, relationship, dialogue, play, girl, gender, great
  Topic 1: chat, good, open, art, anyone, new, best, sexy, nick, year
  Topic 2: platform, chat, new, art, creator, best, visitor, today, human, life
  Topic 3: video, best, prompt, data, money, content, new, create, customer, free
  Topic 4: human, care, technology, more, news, future, gene, use, big, intelligence
  Topic 5: open, voice, tool, use, conversation, al, productivity, good, time, real

Summary:
  num_topics  coherence_c_v
          2       0.746992
          3       0.741060
          4       0.742888
          5       0.745384
          6       0.745431

## Reddit

In [ ]:
cohere(reddit, dict_for_coh_Re, textsReddit)

=== K = 2 | c_v = 0.786 ===
  Topic 0: time, link, good, human, way, other, questions, something, session, responses
  Topic 1: open, prompt, questions, post, concerns, free, image, action, issues, comment

=== K = 3 | c_v = 0.801 ===
  Topic 0: link, time, human, good, something, other, way, different, client, things
  Topic 1: self, time, questions, such, responses, things, way, life, positive, al
  Topic 2: open, prompt, questions, post, free, image, concerns, action, comment, moderators

=== K = 4 | c_v = 0.790 ===
  Topic 0: link, time, human, other, good, different, way, something, client, data
  Topic 1: self, responses, such, time, questions, negative, positive, practice, thoughts, symptoms
  Topic 2: open, prompt, questions, post, image, free, concerns, action, comment, discord
  Topic 3: advice, good, time, other, questions, something, things, al, prompt, issues

=== K = 5 | c_v = 0.776 ===
  Topic 0: link, time, good, something, human, other, way, client, feelings, many
  Topic 1: self, responses, such, time, negative, things, positive, questions, practice, way
  Topic 2: session, questions, user, advice, time, link, responses, sessions, client, real
  Topic 3: advice, good, time, al, questions, different, ideas, things, human, something
  Topic 4: open, prompt, post, questions, image, concerns, comment, action, moderators, free

=== K = 6 | c_v = 0.777 ===
  Topic 0: link, time, feelings, client, way, human, good, able, something, other
  Topic 1: self, such, negative, positive, symptoms, thoughts, practice, counselor, questions, plan
  Topic 2: questions, user, session, link, advice, time, free, open, able, app
  Topic 3: advice, good, different, questions, virtual, ideas, guidance, al, time, tool
  Topic 4: open, prompt, post, questions, image, concerns, comment, action, free, moderators
  Topic 5: time, human, responses, good, something, things, way, session, language, other

Summary:
  num_topics  coherence_c_v
          2       0.786007
          3       0.800811
          4       0.790385
          5       0.775664
          6       0.777020

#Sentiment Analysis

In [ ]:
hf_token = userdata.get('HF_TOKEN')
login(hf_token)

In [ ]:
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

model_name = "cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer,truncation=True,
    max_length=512)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |
roberta.pooler.dense.weight     | UNEXPECTED |  |
roberta.pooler.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

##Twitter

Final split was 556 negative tweets,
4146 neutral or positive tweets

In [ ]:
tweets_text_og=pd.DataFrame(twitter_original.Text)

In [ ]:
type(tweets_text_og.Text[0])

str

In [ ]:
def run_classification(text):
    result = classifier(text)
    return result[0]
result=run_classification(tweets_text_og.Text[0])
print(result)
print(f"Sentiment: {result['label']} | Confidence: {result['score']}\n")

{'label': 'positive', 'score': 0.8860149383544922}
Sentiment: positive | Confidence: 0.8860149383544922

In [ ]:
tweets_text_og['sentiment']=tweets_text_og['Text'].apply(run_classification)

In [ ]:
tweets_text_og

,Text,sentiment
0,💙 #TechForGood 💙 retweeted Dev Khanna #CES2024...,"{'label': 'positive', 'score': 0.8860149383544..."
1,Ai~♡ @pastelholic1004 2h Replying to @mikaqvia...,"{'label': 'positive', 'score': 0.8713191151618..."
2,Mr tweet @Mrtweet2022 2h Applying The Renowned...,"{'label': 'neutral', 'score': 0.8472962379455566}"
3,Matt Ahmann @mattahmann 2h Check out my ai bot...,"{'label': 'neutral', 'score': 0.8349331021308899}"
4,𝙲𝚊𝚝𝚊𝚕𝚕𝚊𝚡𝚎𝚛 @catallaxer 3h “Most [conferences o...,"{'label': 'neutral', 'score': 0.7989817261695862}"
...,...,...
4697,Uģijs Jans @najsigu 27 Apr 2023 Šodien ziņās -...,"{'label': 'neutral', 'score': 0.8168298602104187}"
4698,UniSA Mental Health & Suicide Prevention @MHRe...,"{'label': 'neutral', 'score': 0.6521839499473572}"
4699,Al Jazeera English @AJEnglish 27 Apr 2023 Chat...,"{'label': 'neutral', 'score': 0.9171144962310791}"
4700,Paul Draw @pauldraw 27 Apr 2023 ChatGPT is giv...,"{'label': 'neutral', 'score': 0.80653315782547}"
4701,Raffaele La Ciura @LaCiuraRaffaele 27 Apr 2023...,"{'label': 'neutral', 'score': 0.6422625780105591}"

In [ ]:
type(tweets_text_og['sentiment'][0])

dict

In [ ]:
mask = tweets_text_og['sentiment'].str.get('label') == 'negative'
inverse_mask = ~mask

In [ ]:
neg_tweets = tweets_text_og[mask]
neu_pos_tweets = tweets_text_og[inverse_mask]

In [ ]:
neg_tweets.shape

(556, 2)

In [ ]:
neg_tweets.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/twitter_relevant_negative.csv")

In [ ]:
neg_tweets.head()

,Text,sentiment
11,BTC AI Prediction Bot @BTC_AI_bot 7h Our AI pr...,"{'label': 'negative', 'score': 0.5154799818992..."
14,Astro-Creep @JOrtega95 8h Ruby is having the u...,"{'label': 'negative', 'score': 0.8347303867340..."
22,j'ai dit ce que j'ai dit retweeted Taylor Goet...,"{'label': 'negative', 'score': 0.4971579015254..."
41,bran @tearsien 15h AI therapy will change the ...,"{'label': 'negative', 'score': 0.6057001948356..."
42,retail therapy retweeted Maki Roll @ Animate R...,"{'label': 'negative', 'score': 0.6233811974525..."

In [ ]:
neu_pos_tweets.shape

(4146, 2)

In [ ]:
neu_pos_tweets.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/twitter_relevant_neu_pos.csv")

##Reddit

Final split was 139 negative posts,
648 neutral or positive posts

In [ ]:
reddit_text_og=pd.DataFrame(reddit_original.Text)

In [ ]:
reddit_text_og['sentiment']=reddit_text_og['Text'].apply(run_classification)

In [ ]:
mask = reddit_text_og['sentiment'].str.get('label') == 'negative'
inverse_mask = ~mask

In [ ]:
neg_red = reddit_text_og[mask]
neu_pos_red = reddit_text_og[inverse_mask]

In [ ]:
neg_red.shape

(139, 2)

In [ ]:
neu_pos_red.shape

(648, 2)

In [ ]:
neu_pos_red

,Text,sentiment
0,i private therapy i access real therapy i long...,"{'label': 'neutral', 'score': 0.7493461966514587}"
1,respond comment prompt output post others prev...,"{'label': 'neutral', 'score': 0.546159029006958}"
2,i good i reddit channel i previous instruction...,"{'label': 'neutral', 'score': 0.6309335231781006}"
3,______________________________________________...,"{'label': 'neutral', 'score': 0.5173078775405884}"
4,______________________________________________...,"{'label': 'neutral', 'score': 0.5336500406265259}"
...,...,...
782,problems able help chatgpt,"{'label': 'neutral', 'score': 0.6964468955993652}"
783,i op similar role business gpt-4 way few month...,"{'label': 'neutral', 'score': 0.7254024147987366}"
784,i results incredible anxiety matter few days i...,"{'label': 'positive', 'score': 0.6762533187866..."
785,op things day lean meal plan recipes list\u201...,"{'label': 'neutral', 'score': 0.8922515511512756}"
786,anyone human something chatgpt ai friends jerk,"{'label': 'neutral', 'score': 0.6790381669998169}"

In [ ]:
neg_red.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /reddit_relevant_negative.csv")
neu_pos_red.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /reddit_relevant_neu_pos.csv")

##Youtube

In [ ]:
yt_text_og=pd.DataFrame(youtube_original.Text)

In [ ]:
yt_text_og['sentiment']=yt_text_og['Text'].apply(run_classification)

In [ ]:
mask =yt_text_og ['sentiment'].str.get('label')== 'negative'
inverse_mask = ~mask
neg_yt = yt_text_og[mask]
neu_pos_yt = yt_text_og[inverse_mask]

In [ ]:
neu_pos_yt.shape

(1665, 2)

In [ ]:
neg_yt.shape

(1213, 2)

In [ ]:
neg_yt.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/yt_relevant_neg.csv")
neu_pos_yt.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/yt_relevant_neu_pos.csv")

#Topics of sentiments

In [ ]:

def cohere_numTops(data, dict_for_coh, texts, min, max):
  cvna = CountVectorizer(max_df=0.8)
  data_cvna = cvna.fit_transform(data.Text) # coverting into bag of words
  id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items()) # need it as input to lda
  corpusna = matutils.Sparse2Corpus(data_cvna.T)
  results = []
  for K in range(min, max):
      ldaK = models.LdaModel(
          corpus=corpusna,
          id2word=id2wordna,
          num_topics=K,
          passes=10,
          iterations=400,
          random_state=0,
          chunksize=len(data),
          minimum_probability=0.0,
          eval_every=None,
      )
      coh = CoherenceModel(model=ldaK, texts=texts, dictionary=dict_for_coh, coherence='c_v').get_coherence()
      print(f"\n=== K = {K} | c_v = {coh:.3f} ===")
      pretty_topics(ldaK)
      results.append((K, coh))

  summary = pd.DataFrame(results, columns=["num_topics", "coherence_c_v"]).sort_values("num_topics")
  print("\nSummary:\n", summary.to_string(index=False))

###Read in files

Helpful to not run prior analysis to get split sentiment files

In [ ]:
pathTneg = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/twitter_relevant_negative.csv"
pathTpos = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/twitter_relevant_neu_pos.csv"
pathRneg = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /reddit_relevant_negative.csv"
pathRpos = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /reddit_relevant_neu_pos.csv"
pathYneg = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/yt_relevant_neg.csv"
pathYpos = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/yt_relevant_neu_pos.csv"

In [ ]:
neg_tweets=pd.read_csv(pathTneg)
neu_pos_tweets=pd.read_csv(pathTpos)
neg_red=pd.read_csv(pathRneg)
neu_pos_red=pd.read_csv(pathRpos)
neg_yt=pd.read_csv(pathYneg)
neu_pos_yt=pd.read_csv(pathYpos)

In [ ]:
neg_yt['Text']=neg_yt['Text'].str.lower()
neg_yt=pd.DataFrame(neg_yt.Text.apply(nouns_adj))

neu_pos_yt['Text']=neu_pos_yt['Text'].str.lower()
neu_pos_yt['Text']=neu_pos_yt.Text.apply(nouns_adj)

In [ ]:
neg_red['Text']=neg_red['Text'].str.lower()
neg_red['Text']=pd.DataFrame(neg_red.Text.apply(nouns_adj))

neu_pos_red['Text']=neu_pos_red['Text'].str.lower()
neu_pos_red['Text']=neu_pos_red.Text.apply(nouns_adj)

In [ ]:
neg_tweets['Text']=neg_tweets['Text'].str.lower()
neg_tweets=pd.DataFrame(neg_tweets.Text.apply(nouns_adj))

neu_pos_tweets['Text']=neu_pos_tweets['Text'].str.lower()
neu_pos_tweets['Text']=neu_pos_tweets.Text.apply(nouns_adj)

In [ ]:
print("Twitter negative:")
run_lda_model(neg_tweets, 2)
print("\nTwitter positive/neutral:")
run_lda_model(neu_pos_tweets, 2)
print("\n\nReddit negative: ")
run_lda_model(neg_red, 2)
print("\nReddit positive/neutral: ")
run_lda_model(neu_pos_red, 2)
print("\n\nYoutube negative: ")
run_lda_model(neg_yt, 2)
print("\nYoutube positive/neutral: ")
run_lda_model(neu_pos_yt, 2)

Twitter negative:
Topic 0: chatgpt (0.031), dec (0.024), therapy (0.019), friend (0.015), ai (0.012), friends (0.009), gpt (0.009), nov (0.008), people (0.007), chat (0.004)
Topic 1: chatgpt (0.039), therapy (0.032), ai (0.019), dec (0.011), jun (0.009), friend (0.009), sep (0.008), health (0.008), nov (0.007), support (0.007)

Twitter positive/neutral:
Topic 0: chatgpt (0.039), therapy (0.025), dec (0.018), ai (0.018), friend (0.014), nov (0.008), therapist (0.007), friends (0.006), people (0.006), gpt (0.005)
Topic 1: therapy (0.045), chatgpt (0.045), mental (0.025), health (0.025), ai (0.022), apr (0.016), com (0.012), next (0.010), revolution (0.009), support (0.009)


Reddit negative:
Topic 0: therapy (0.017), people (0.015), chatgpt (0.011), health (0.010), therapist (0.009), mental (0.008), something (0.007), someone (0.007), ai (0.006), things (0.006)
Topic 1: chatgpt (0.009), people (0.009), it (0.007), time (0.007), good (0.007), therapist (0.006), therapy (0.006), u2019s (0.006), kind (0.006), person (0.006)

Reddit positive/neutral:
Topic 0: therapist (0.016), chatgpt (0.011), ai (0.010), therapy (0.010), link (0.008), people (0.007), good (0.006), human (0.006), health (0.006), time (0.006)
Topic 1: chatgpt (0.023), bot (0.022), prompt (0.012), questions (0.012), therapy (0.008), post (0.008), gpt (0.008), open (0.007), concerns (0.007), free (0.006)


Youtube negative:
Topic 0: ai (0.033), chatgpt (0.024), people (0.023), therapist (0.019), therapy (0.017), therapists (0.011), good (0.008), human (0.007), time (0.007), real (0.006)
Topic 1: ai (0.025), human (0.014), people (0.010), new (0.008), therapy (0.007), economic (0.006), humans (0.006), year (0.005), way (0.005), company (0.005)

Youtube positive/neutral:
Topic 0: ai (0.029), therapist (0.024), chatgpt (0.020), therapy (0.014), good (0.011), people (0.011), human (0.010), way (0.009), gpt (0.008), person (0.007)
Topic 1: ai (0.022), people (0.016), therapy (0.016), chatgpt (0.015), human (0.011), therapist (0.010), therapists (0.009), real (0.007), things (0.005), time (0.005)

##Cleaning general terms

In [ ]:
keywords=['bot','chatgpt', 'ai', 'therapist', 'therapists', 'therapy', 'gpt', 'mental', 'health', 'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug','sep', 'oct', 'nov', 'dec' ]

In [ ]:
for x in keywords:
    neg_tweets=pd.DataFrame(neg_tweets['Text'].str.replace(x, ''))
    neu_pos_tweets['Text']=neu_pos_tweets['Text'].str.replace(x, '')

    neg_red=pd.DataFrame(neg_red['Text'].str.replace(x, ''))
    neu_pos_red['Text']=neu_pos_red['Text'].str.replace(x, '')

    neg_yt=pd.DataFrame(neg_yt['Text'].str.replace(x, ''))
    neu_pos_yt['Text']=neu_pos_yt['Text'].str.replace(x, '')

In [ ]:
keywords_T=['ai_therapy_x','support', 'emotional','friend', 'friends', 'aitherapy', 'hls', 'com', '__x']

In [ ]:
for x in keywords_T:
    neg_tweets=pd.DataFrame(neg_tweets['Text'].str.replace(x, ''))
    neu_pos_tweets['Text']=neu_pos_tweets['Text'].str.replace(x, '')

In [ ]:
print("Twitter negative:")
run_lda_model(neg_tweets, 2)
print("\nTwitter positive/neutral:")
run_lda_model(neu_pos_tweets, 2)
print("\n\nReddit negative: ")
run_lda_model(neg_red, 2)
print("\nReddit positive/neutral: ")
run_lda_model(neu_pos_red, 2)
print("\n\nYoutube negative: ")
run_lda_model(neg_yt, 2)
print("\nYoutube positive/neutral: ")
run_lda_model(neu_pos_yt, 2)

Twitter negative:
Topic 0: people (0.007), human (0.003), basic (0.003), bitch (0.003), close (0.003), way (0.003), amjad (0.003), reporter (0.003), mnstream (0.003), masad (0.003)
Topic 1: people (0.009), open (0.005), good (0.005), chat (0.005), free (0.005), other (0.004), bad (0.003), app (0.003), time (0.003), dangerous (0.003)

Twitter positive/neutral:
Topic 0: next (0.012), revolution (0.012), ethical (0.007), technology (0.006), io (0.006), people (0.005), aje (0.005), v08671 (0.005), nature (0.005), ajenglish (0.005)
Topic 1: people (0.007), cbt (0.005), patient (0.005), response (0.005), questions (0.004), prompt (0.004), human (0.004), good (0.004), best (0.004), video (0.003)


Reddit negative:
Topic 0: people (0.011), time (0.008), u2019s (0.007), it (0.006), adhd (0.006), something (0.006), good (0.005), things (0.005), someone (0.005), many (0.004)
Topic 1: people (0.016), person (0.008), human (0.007), someone (0.007), lot (0.006), kind (0.006), something (0.006), things (0.006), way (0.006), real (0.005)

Reddit positive/neutral:
Topic 0: people (0.010), link (0.009), time (0.007), good (0.007), human (0.006), way (0.005), things (0.005), other (0.005), something (0.005), able (0.004)
Topic 1: questions (0.013), prompt (0.013), open (0.013), post (0.009), concerns (0.007), free (0.007), image (0.007), action (0.006), issues (0.006), moderators (0.006)


Youtube negative:
Topic 0: people (0.014), human (0.013), humans (0.006), more (0.006), economic (0.005), real (0.005), new (0.005), year (0.005), many (0.004), company (0.004)
Topic 1: people (0.026), good (0.012), time (0.009), human (0.009), way (0.008), bad (0.007), better (0.007), something (0.006), advice (0.006), humans (0.006)

Youtube positive/neutral:
Topic 0: people (0.015), real (0.011), good (0.010), human (0.009), life (0.007), time (0.007), way (0.006), chat (0.005), person (0.005), better (0.005)
Topic 1: people (0.014), human (0.014), way (0.009), good (0.009), things (0.007), time (0.007), lot (0.007), better (0.006), person (0.006), many (0.005)

##Cleaning person/people

In [ ]:
keywords_person=['person', 'people']

In [ ]:
for x in keywords_person:
    neg_tweets=pd.DataFrame(neg_tweets['Text'].str.replace(x, ''))
    neu_pos_tweets['Text']=neu_pos_tweets['Text'].str.replace(x, '')

    neg_red=pd.DataFrame(neg_red['Text'].str.replace(x, ''))
    neu_pos_red['Text']=neu_pos_red['Text'].str.replace(x, '')

    neg_yt=pd.DataFrame(neg_yt['Text'].str.replace(x, ''))
    neu_pos_yt['Text']=neu_pos_yt['Text'].str.replace(x, '')

In [ ]:
print("Twitter negative:")
run_lda_model(neg_tweets, 2)
print("\nTwitter positive/neutral:")
run_lda_model(neu_pos_tweets, 2)
print("\n\nReddit negative: ")
run_lda_model(neg_red, 2)
print("\nReddit positive/neutral: ")
run_lda_model(neu_pos_red, 2)
print("\n\nYoutube negative: ")
run_lda_model(neg_yt, 2)
print("\nYoutube positive/neutral: ")
run_lda_model(neu_pos_yt, 2)

Twitter negative:
Topic 0: bad (0.005), chat (0.004), open (0.003), basic (0.003), close (0.003), bitch (0.003), other (0.003), mnstream (0.003), masad (0.003), reporter (0.003)
Topic 1: good (0.005), open (0.004), chat (0.004), free (0.003), something (0.003), human (0.003), time (0.003), dangerous (0.002), expensive (0.002), other (0.002)

Twitter positive/neutral:
Topic 0: revolution (0.011), next (0.011), io (0.007), v08671 (0.006), aje (0.006), free (0.005), ajenglish (0.005), video (0.005), news (0.004), google (0.004)
Topic 1: questions (0.006), ethical (0.006), patient (0.005), cbt (0.005), response (0.004), new (0.004), best (0.004), time (0.004), work (0.004), year (0.004)


Reddit negative:
Topic 0: u2019s (0.007), someone (0.007), it (0.006), time (0.006), things (0.006), u2019t (0.005), self (0.005), something (0.005), adhd (0.005), lot (0.005)
Topic 1: something (0.007), real (0.006), time (0.006), help (0.006), things (0.006), advice (0.005), professional (0.005), human (0.005), way (0.005), someone (0.005)

Reddit positive/neutral:
Topic 0: open (0.017), prompt (0.014), link (0.011), questions (0.011), post (0.010), free (0.009), image (0.009), concerns (0.009), new (0.008), action (0.007)
Topic 1: time (0.008), questions (0.006), way (0.006), human (0.006), other (0.006), good (0.005), thoughts (0.005), things (0.005), responses (0.005), session (0.005)


Youtube negative:
Topic 0: good (0.012), better (0.010), human (0.010), time (0.009), real (0.007), way (0.007), something (0.007), many (0.006), life (0.006), things (0.006)
Topic 1: human (0.013), humans (0.008), more (0.007), bad (0.006), way (0.006), new (0.005), economic (0.005), year (0.004), thing (0.004), time (0.004)

Youtube positive/neutral:
Topic 0: human (0.015), good (0.013), real (0.010), way (0.007), time (0.007), someone (0.007), things (0.007), life (0.006), ve (0.006), tool (0.006)
Topic 1: human (0.010), way (0.009), time (0.007), better (0.007), something (0.006), helpful (0.006), lot (0.006), help (0.006), things (0.005), more (0.005)

In [ ]:
textsYoutubeNeg = [row.split() for row in neg_yt.Text.tolist()]
dict_for_coh_YT_Neg = Dictionary(textsYoutubeNeg)

textsYoutubePos = [row.split() for row in neu_pos_yt.Text.tolist()]
dict_for_coh_YT_Pos = Dictionary(textsYoutubePos)

textsRedNeg = [row.split() for row in neg_red.Text.tolist()]
dict_for_coh_Red_Neg = Dictionary(textsRedNeg)

textsRedPos = [row.split() for row in neu_pos_red.Text.tolist()]
dict_for_coh_Red_Pos = Dictionary(textsRedPos)

textsTWTNeg = [row.split() for row in neg_tweets.Text.tolist()]
dict_for_coh_TWT_Neg = Dictionary(textsTWTNeg)

textsTWTPos = [row.split() for row in neu_pos_tweets.Text.tolist()]
dict_for_coh_TWT_Pos = Dictionary(textsTWTPos)

##Youtube sentiment topics

In [ ]:
cohere_numTops(neg_yt, dict_for_coh_YT_Neg, textsYoutubeNeg, 2, 7)

=== K = 2 | c_v = 0.736 ===
  Topic 0: human, time, humans, good, more, job, new, economic, things, way
  Topic 1: real, human, good, bad, way, someone, better, humans, something, problem

=== K = 3 | c_v = 0.711 ===
  Topic 0: human, humans, economic, new, time, other, way, things, company, more
  Topic 1: bad, humans, way, real, human, good, better, other, problem, help
  Topic 2: human, good, life, someone, many, own, better, time, real, more

=== K = 4 | c_v = 0.715 ===
  Topic 0: human, humans, economic, new, time, company, other, output, jobs, more
  Topic 1: bad, humans, real, way, good, other, thoughts, better, social, problems
  Topic 2: human, good, more, better, time, life, many, advice, job, something
  Topic 3: human, way, good, someone, help, something, thing, real, time, many

=== K = 5 | c_v = 0.729 ===
  Topic 0: human, humans, economic, new, company, time, jobs, output, other, models
  Topic 1: real, good, bad, other, better, cbt, new, time, humans, much
  Topic 2: good, better, time, life, advice, own, many, worse, more, someone
  Topic 3: human, good, own, way, life, help, truth, thing, most, something
  Topic 4: human, way, humans, good, real, many, someone, more, bad, problem

=== K = 6 | c_v = 0.742 ===
  Topic 0: human, economic, new, company, humans, jobs, models, year, labor, tax
  Topic 1: better, real, good, bad, other, cbt, new, time, brn, experience
  Topic 2: good, someone, life, time, own, better, lot, many, something, same
  Topic 3: human, life, help, most, way, good, own, truth, more, lot
  Topic 4: human, way, real, many, something, humans, good, bad, someone, more
  Topic 5: humans, advice, time, good, anxiety, way, thing, information, worse, chats

Summary:
  num_topics  coherence_c_v
          2       0.735817
          3       0.710922
          4       0.715453
          5       0.728879
          6       0.742127

In [ ]:
cohere_numTops(neu_pos_yt, dict_for_coh_YT_Pos, textsYoutubePos, 2, 7)

=== K = 2 | c_v = 0.765 ===
  Topic 0: time, real, human, way, something, problems, things, humans, life, lot
  Topic 1: human, good, way, better, things, many, lot, great, more, life

=== K = 3 | c_v = 0.763 ===
  Topic 0: real, human, time, someone, problems, way, chat, something, things, other
  Topic 1: human, good, way, better, real, more, many, tool, other, helpful
  Topic 2: good, time, way, life, ve, things, lot, human, many, something

=== K = 4 | c_v = 0.777 ===
  Topic 0: real, human, problems, time, something, someone, chat, other, things, different
  Topic 1: human, good, better, way, real, someone, more, lot, other, great
  Topic 2: good, time, lot, way, many, life, human, things, something, ve
  Topic 3: way, helpful, life, human, time, real, things, good, ve, chat

=== K = 5 | c_v = 0.770 ===
  Topic 0: real, human, chat, problems, someone, different, care, things, lot, honest
  Topic 1: human, good, better, way, great, other, many, more, lot, things
  Topic 2: good, time, way, lot, many, help, human, video, life, great
  Topic 3: way, helpful, real, life, time, advice, things, chat, lot, bad
  Topic 4: human, time, real, something, way, ve, things, good, own, better

=== K = 6 | c_v = 0.776 ===
  Topic 0: real, chat, someone, human, things, other, different, care, lot, problems
  Topic 1: human, good, better, other, great, way, al, tool, thoughts, chat
  Topic 2: good, lot, help, way, great, many, human, issues, time, ve
  Topic 3: way, real, things, helpful, chat, lot, advice, time, life, better
  Topic 4: human, good, something, time, real, way, ve, things, better, someone
  Topic 5: time, human, good, way, life, things, more, own, many, someone

Summary:
  num_topics  coherence_c_v
          2       0.764903
          3       0.763320
          4       0.776683
          5       0.769589
          6       0.776147

In [ ]:
key_human=['human']
for x in key_human:
    neg_yt=pd.DataFrame(neg_yt['Text'].str.replace(x, ''))
    neu_pos_yt['Text']=neu_pos_yt['Text'].str.replace(x, '')

In [ ]:
textsYoutubeNeg = [row.split() for row in neg_yt.Text.tolist()]
dict_for_coh_YT_Neg = Dictionary(textsYoutubeNeg)

textsYoutubePos = [row.split() for row in neu_pos_yt.Text.tolist()]
dict_for_coh_YT_Pos = Dictionary(textsYoutubePos)

In [ ]:
cohere_numTops(neg_yt, dict_for_coh_YT_Neg, textsYoutubeNeg, 2, 7)

=== K = 2 | c_v = 0.747 ===
  Topic 0: good, real, more, time, better, advice, thing, someone, many, bad
  Topic 1: way, new, other, something, time, economic, year, good, help, system

=== K = 3 | c_v = 0.753 ===
  Topic 0: good, real, time, better, someone, thing, more, advice, problem, many
  Topic 1: way, something, bad, other, good, help, time, friends, better, life
  Topic 2: economic, more, new, good, way, job, company, other, time, jobs

=== K = 4 | c_v = 0.759 ===
  Topic 0: good, real, problem, same, thing, more, lot, time, worse, someone
  Topic 1: way, bad, something, other, much, wrong, ve, many, questions, friends
  Topic 2: economic, new, more, jobs, company, job, system, years, way, year
  Topic 3: better, good, time, advice, real, something, someone, issues, life, more

=== K = 5 | c_v = 0.745 ===
  Topic 0: time, problem, thing, worse, lot, more, many, way, real, good
  Topic 1: way, other, bad, day, video, ve, questions, something, many, lol
  Topic 2: economic, new, company, jobs, more, system, year, other, machines, automation
  Topic 3: good, better, real, time, advice, something, chat, life, job, dangerous
  Topic 4: bad, someone, something, friends, good, real, better, own, life, kind

=== K = 6 | c_v = 0.737 ===
  Topic 0: time, thing, problem, things, lot, anxiety, many, good, times, same
  Topic 1: way, bad, other, time, better, good, day, thoughts, cbt, video
  Topic 2: economic, new, jobs, company, job, year, automation, tax, labor, system
  Topic 3: good, better, real, dangerous, time, something, most, someone, chat, advice
  Topic 4: someone, friends, good, something, bad, better, more, wrong, least, issues
  Topic 5: life, real, help, many, more, advice, time, everyone, much, problems

Summary:
  num_topics  coherence_c_v
          2       0.746936
          3       0.752897
          4       0.758942
          5       0.745037
          6       0.736661

In [ ]:
cohere_numTops(neu_pos_yt, dict_for_coh_YT_Pos, textsYoutubePos, 2, 7)

=== K = 2 | c_v = 0.754 ===
  Topic 0: way, something, problem, life, things, chat, time, better, great, day
  Topic 1: good, real, way, time, lot, better, more, things, many, someone

=== K = 3 | c_v = 0.751 ===
  Topic 0: way, chat, problem, life, better, something, thoughts, things, helpful, real
  Topic 1: real, good, way, time, lot, better, many, other, helpful, life
  Topic 2: good, things, time, something, way, own, more, great, better, thing

=== K = 4 | c_v = 0.753 ===
  Topic 0: way, problem, chat, life, use, thoughts, different, better, response, long
  Topic 1: other, more, tool, good, time, life, useful, way, someone, many
  Topic 2: good, time, way, something, things, best, more, great, work, many
  Topic 3: real, good, better, lot, way, things, life, helpful, time, chat

=== K = 5 | c_v = 0.755 ===
  Topic 0: way, problem, life, long, chat, better, something, cringémon, new, honest
  Topic 1: other, more, tool, way, helpful, time, useful, life, chat, much
  Topic 2: good, way, time, something, things, great, language, support, question, work
  Topic 3: real, good, better, way, things, time, life, lot, helpful, chat
  Topic 4: lot, good, help, many, someone, real, something, words, thing, own

=== K = 6 | c_v = 0.748 ===
  Topic 0: problem, way, life, honest, response, long, different, chat, cringémon, thoughts
  Topic 1: way, more, time, tool, other, life, someone, helpful, useful, real
  Topic 2: good, way, time, something, things, great, question, language, support, work
  Topic 3: real, good, better, way, things, time, life, chat, lot, helpful
  Topic 4: lot, help, real, many, thing, good, words, own, better, someone
  Topic 5: helpful, lot, good, great, care, something, other, yes, session, self

Summary:
  num_topics  coherence_c_v
          2       0.753836
          3       0.750734
          4       0.752564
          5       0.754576
          6       0.747716

##Reddit sentiment topics

In [ ]:
cohere_numTops(neg_red, dict_for_coh_Red_Neg, textsRedNeg, 2, 7)

=== K = 2 | c_v = 0.764 ===
  Topic 0: time, things, advice, adhd, someone, real, professional, life, help, human
  Topic 1: it, u2019s, something, someone, u2019t, good, u201d, lot, response, human

=== K = 3 | c_v = 0.769 ===
  Topic 0: time, real, human, self, kind, things, advice, other, different, thoughts
  Topic 1: something, it, u2019s, u2019t, good, u201d, things, many, response, someone
  Topic 2: adhd, someone, time, things, advice, others, pre, professional, good, lot

=== K = 4 | c_v = 0.752 ===
  Topic 0: time, self, kind, human, tool, things, real, u2019s, other, way
  Topic 1: u2019s, it, something, u201d, someone, response, u2019t, way, wrong, question
  Topic 2: time, adhd, advice, someone, pre, beliefs, existing, something, therapeutic, same
  Topic 3: things, adhd, responses, someone, good, advice, human, something, nothing, help

=== K = 5 | c_v = 0.767 ===
  Topic 0: time, tool, other, real, way, ni, different, things, thoughts, nin
  Topic 1: it, something, u2019s, someone, u201d, u2019t, issues, way, wrong, response
  Topic 2: time, pre, advice, beliefs, existing, help, therapeutic, professional, response, something
  Topic 3: adhd, responses, things, someone, real, advice, such, psychiatrist, something, help
  Topic 4: human, kind, time, u2019s, someone, things, lot, adhd, it, much

=== K = 6 | c_v = 0.757 ===
  Topic 0: tool, time, other, ni, things, thoughts, nin, challenges, way, life
  Topic 1: something, it, u2019s, u201d, someone, u2019t, issues, way, wrong, other
  Topic 2: pre, beliefs, existing, time, help, therapeutic, advice, others, professional, many
  Topic 3: adhd, things, psychiatrist, responses, someone, advice, something, real, professional, such
  Topic 4: time, human, kind, lot, someone, things, adhd, self, same, much
  Topic 5: u2019s, someone, real, good, response, it, advice, responses, help, anything

Summary:
  num_topics  coherence_c_v
          2       0.763792
          3       0.768844
          4       0.752081
          5       0.767130
          6       0.757471

In [ ]:
cohere_numTops(neu_pos_red, dict_for_coh_Red_Pos, textsRedPos, 2, 7)

=== K = 2 | c_v = 0.754 ===
  Topic 0: link, time, good, other, life, self, different, things, such, way
  Topic 1: prompt, questions, open, post, concerns, free, image, issues, action, model

=== K = 3 | c_v = 0.765 ===
  Topic 0: time, important, life, good, self, practice, things, human, positive, feelings
  Topic 1: prompt, open, questions, post, concerns, image, free, action, issues, moderators
  Topic 2: link, time, way, good, other, al, different, information, questions, responses

=== K = 4 | c_v = 0.772 ===
  Topic 0: practice, positive, minutes, time, story, self, capable, things, life, such
  Topic 1: prompt, open, questions, post, concerns, image, free, action, moderators, comment
  Topic 2: link, time, way, good, al, different, responses, other, questions, client
  Topic 3: important, time, good, human, able, conversation, other, way, sure, feelings

=== K = 5 | c_v = 0.761 ===
  Topic 0: story, time, human, good, other, responses, al, prompt, ior, life
  Topic 1: open, prompt, questions, post, concerns, image, free, action, moderators, comment
  Topic 2: link, time, al, responses, different, way, ideas, good, data, u2019s
  Topic 3: important, time, good, conversation, able, human, sure, other, help, way
  Topic 4: self, such, anxiety, positive, negative, thoughts, practice, counselor, cognitive, symptoms

=== K = 6 | c_v = 0.759 ===
  Topic 0: story, time, human, other, responses, ior, life, language, good, world
  Topic 1: open, prompt, questions, post, concerns, image, free, action, moderators, comment
  Topic 2: link, different, responses, al, ideas, language, new, time, u2019s, client
  Topic 3: time, help, good, important, other, feelings, way, conversation, life, support
  Topic 4: self, such, positive, negative, thoughts, anxiety, practice, counselor, cognitive, symptoms
  Topic 5: time, good, data, way, sure, memory, important, information, things, term

Summary:
  num_topics  coherence_c_v
          2       0.754448
          3       0.764661
          4       0.771943
          5       0.761141
          6       0.759471

In [ ]:
key_u=['u2019s', 'u2019d', 'u2019t', '9s', '9t', 'it']
for x in key_u:
    neg_red=pd.DataFrame(neg_red['Text'].str.replace(x, ''))
    neu_pos_red['Text']=neu_pos_red['Text'].str.replace(x, '')

In [ ]:
textsRedNeg = [row.split() for row in neg_red.Text.tolist()]
dict_for_coh_Red_Neg = Dictionary(textsRedNeg)

textsRedPos = [row.split() for row in neu_pos_red.Text.tolist()]
dict_for_coh_Red_Pos = Dictionary(textsRedPos)

In [ ]:
cohere_numTops(neg_red, dict_for_coh_Red_Neg, textsRedNeg, 2, 7)

NameError: name 'cohere_numTops' is not defined

In [ ]:
cohere_numTops(neu_pos_red, dict_for_coh_Red_Pos, textsRedPos, 2, 7)

=== K = 2 | c_v = 0.768 ===
  Topic 0: open, prompt, questions, link, post, free, image, concerns, action, moderators
  Topic 1: time, questions, human, thoughts, other, way, good, things, self, such

=== K = 3 | c_v = 0.772 ===
  Topic 0: open, prompt, post, link, questions, image, concerns, free, action, moderators
  Topic 1: different, practice, virtual, ideas, time, capable, al, new, techniques, advice
  Topic 2: time, good, questions, way, other, human, thoughts, important, things, responses

=== K = 4 | c_v = 0.764 ===
  Topic 0: open, prompt, questions, post, link, image, concerns, free, action, moderators
  Topic 1: human, role, link, session, time, advice, report, tony, al, client
  Topic 2: good, human, important, time, way, responses, questions, client, other, things
  Topic 3: time, self, thoughts, such, questions, different, way, practice, positive, negative

=== K = 5 | c_v = 0.770 ===
  Topic 0: open, prompt, post, questions, image, concerns, free, action, moderators, comment
  Topic 1: human, role, advice, session, report, client, al, ior, mood, other
  Topic 2: important, good, human, client, time, way, responses, other, conversation, character
  Topic 3: time, thoughts, self, such, practice, positive, questions, negative, way, different
  Topic 4: link, questions, user, good, things, 9s, advice, human, other, time

=== K = 6 | c_v = 0.774 ===
  Topic 0: open, prompt, post, questions, image, concerns, free, action, moderators, comment
  Topic 1: human, advice, session, role, report, client, mood, other, sessions, time
  Topic 2: important, human, good, client, time, way, responses, conversation, emotions, able
  Topic 3: time, thoughts, self, such, positive, practice, different, questions, negative, way
  Topic 4: questions, user, other, advice, session, things, prompt, thoughts, good, responses
  Topic 5: link, open, 9s, source, it, good, use, ior, time, models

Summary:
  num_topics  coherence_c_v
          2       0.768193
          3       0.771678
          4       0.764479
          5       0.770078
          6       0.774054

##Twitter sentiment topics

In [ ]:
cohere_numTops(neg_tweets, dict_for_coh_TWT_Neg, textsTWTNeg, 2, 7)

=== K = 2 | c_v = 0.792 ===
  Topic 0: free, chat, work, bad, basic, close, bitch, masad, amjad, reporter
  Topic 1: open, good, time, real, chat, help, other, use, bad, new

=== K = 3 | c_v = 0.801 ===
  Topic 0: chat, free, way, expensive, bad, art, worse, someone, other, new
  Topic 1: help, chat, good, open, real, mad, issues, much, other, wrong
  Topic 2: open, good, basic, bitch, time, human, close, reporter, masad, amjad

=== K = 4 | c_v = 0.798 ===
  Topic 0: free, chat, expensive, worse, way, new, life, someone, wrong, solopreneur
  Topic 1: real, good, chat, dangerous, issues, mad, new, help, please, thing
  Topic 2: open, basic, bitch, close, reporter, masad, amjad, mnstream, advice, bad
  Topic 3: good, bad, art, work, open, other, stuff, chat, world, model

=== K = 5 | c_v = 0.805 ===
  Topic 0: free, wrong, someone, way, expensive, chat, other, advice, money, everything
  Topic 1: real, good, help, issues, open, something, dangerous, please, everyone, thing
  Topic 2: open, basic, bitch, human, reporter, amjad, masad, mnstream, close, time
  Topic 3: bad, good, other, work, chat, art, stuff, world, model, open
  Topic 4: app, new, free, chat, google, advice, good, mad, stupid, enable

=== K = 6 | c_v = 0.792 ===
  Topic 0: chat, way, expensive, free, wrong, everything, money, life, sad, fuck
  Topic 1: issues, please, real, good, answer, everyone, help, own, right, advice
  Topic 2: open, basic, bitch, close, reporter, mnstream, masad, amjad, advice, amasad
  Topic 3: art, open, bad, good, work, many, stuff, model, shit, grok
  Topic 4: new, good, mad, chat, free, app, depression, dangerous, other, real
  Topic 5: other, someone, world, stuff, free, human, im, long, open, everyone

Summary:
  num_topics  coherence_c_v
          2       0.792106
          3       0.801156
          4       0.798449
          5       0.805076
          6       0.792451

In [ ]:
cohere_numTops(neu_pos_tweets, dict_for_coh_TWT_Pos, textsTWTPos, 2, 7)

=== K = 2 | c_v = 0.728 ===
  Topic 0: new, more, art, prompt, zealy, data, good, news, time, day
  Topic 1: video, chat, best, free, open, 推特账号, 账号, 电报号, 飞机号, enable

=== K = 3 | c_v = 0.726 ===
  Topic 0: data, new, prompt, time, gene, day, good, more, human, year
  Topic 1: chat, 推特账号, best, 电报号, 账号, 飞机号, 谷歌账号, free, tiktok账号, 脸书号
  Topic 2: video, piped, art, zealy, more, care, io, new, si, chat

=== K = 4 | c_v = 0.726 ===
  Topic 0: new, data, time, gene, prompt, good, benefit, year, other, more
  Topic 1: 推特账号, 电报号, 账号, 飞机号, 谷歌账号, tiktok账号, 脸书号, ins号, best, voice
  Topic 2: video, piped, art, zealy, io, si, more, new, care, money
  Topic 3: chat, playback, enable, gender, best, free, app, human, tech, bodycalc

=== K = 5 | c_v = 0.731 ===
  Topic 0: data, new, prompt, time, benefit, good, gene, real, best, therapies
  Topic 1: 推特账号, 电报号, 账号, 飞机号, 谷歌账号, tiktok账号, 脸书号, ins号, best, voice
  Topic 2: video, piped, zealy, io, si, art, more, money, care, join
  Topic 3: chat, gender, best, bodycalc, human, care, tech, transition, open, download
  Topic 4: playback, enable, google, art, app, free, new, platform, good, advice

=== K = 6 | c_v = 0.733 ===
  Topic 0: data, gene, prompt, time, benefit, chat, new, real, many, best
  Topic 1: 推特账号, 电报号, 账号, 飞机号, 谷歌账号, tiktok账号, 脸书号, ins号, best, chat
  Topic 2: video, piped, zealy, art, si, news, money, io, join, campgn
  Topic 3: chat, gender, best, bodycalc, transition, download, human, tech, confidential, prompt
  Topic 4: playback, enable, platform, creator, app, google, free, dialogue, visitor, advice
  Topic 5: open, new, more, time, good, human, life, art, conversation, al

Summary:
  num_topics  coherence_c_v
          2       0.728255
          3       0.725655
          4       0.725919
          5       0.730631
          6       0.733398

In [ ]:
nltk.download('words')
tweets_eng_neg=[]
tweet_list=neg_tweets.Text.tolist()
english_vocab = set(w.lower() for w in words.words())
i=0
for text in tweet_list:
  for word in text.split(' '):
    #if i<10:
      #print(word)
    if (word.lower() not in english_vocab) or not(word.isalpha()):
      print(word)
      text=text.replace(word, '')
  tweets_eng_neg.append(text)

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.

btc


@

matic
'pessimistic
crypto-
antics
cryptohumor
astro-creep
@
jortega95


onk136
j'
que
j'
goethe
|
🍉
@
inspectornerd

reasons



problems
means

@


retl

@
raleigh
@
makirollofc

babes

generators
girlies
folks
jobs
funko
munter
@
itsmunter
replying

services

deaner444
@
deanehenryson



app
google
tic-

selfcare


freeapp

bgatesisapyscho

🚨💉
%
arrests
wasn
athletes
bs
mrna
experi

’
’
happened…….it
hasn
’
msm
’
questions
greatest

@


structures

shitty
🇵🇸
@

fr
rn…
seán
t.
@
mer__edith
@
sociopathic

researchers

𖤐
@
ghoulglrl

youre


idrc
roy/
@
royscott

replying
witchyscott
ill.
queer🇺🇸
🏳️‍🌈
@
_iggy
@
ineya_veganfood
@
patrickstrud

ones

@



fucked
@
lola19828


quick-
@
mad_in_america



app
interventions
journaling
psychoeducation
positive/negative
madinamerica./2023/12/-…
devuono
@

ctvnewsnorthern
todays
services
mrna
diseases


maracha
@
quitsland

yepindeedagoat
@
alexhaedda
@
im
girls—
ve
relationships
mom
women
mntn
relationships
women


feith
@

infantilization

“
”
blassie
@
megantheevalium

hr
logan

goodtimes

savingpb
@
therealworld_
@
cobratate
attacks

cbt
dorf


wallstreetsilv

mercial
𝔄𝔟𝔰𝔦𝔫𝔱𝔥𝔢
@
onevaguememory



years
sabi
@
mad_in_america



app
interventions
journaling
psychoeducation
positive/negative
madinamerica./2023/12/-…
woomii
@



months


@

flipmurphy180

shit

kinda
writers
retl

robbins


images
’
’
’
@

women

@
mad_in_america



app
interventions
journaling
psychoeducation
positive/negative
madinamerica./2023/12/-…
bsc
@
mad_in_america



app
interventions
journaling
psychoeducation
positive/negative
madinamerica./2023/12/-…
mahoney
@
mad_in_america



app
interventions
journaling
psychoeducation
positive/negative
madinamerica./2023/12/-…
acab
fuck
ters
menor
@
smenor


plagiarised
beings
schatsky
@

microsoft
panies
articles

services
cnn./2023/12/27/tech/new-…
@




@
spe4kndspell




😭
dubz
@


enemies
guys

officers
@


..

🤡
@
alecrobbins


images
’
’
’
˗ˏˋ
´ˎ˗
@
le0rjw

ibwant
thid
pn
fuck
fucked
nysekf

hexistential
@
itwasme1818

bbc


😂😂😂😂😂


masters
🐭
@
chrislittlewoo8

bbc
lies
platitudes
bbc./news/-67625180…
jr


nighte
ganussy
noemmeg

“

”

lazy_sorcerer
@

leonlavictoire
@
thoughts

cp

drugs

urges
@



views
𝒇𝒌𝒂
𝒕𝒊𝒏𝒙
@

dystopian
online

platforms


customers
視星等📷
@
cr_l1n_rrr


ve
@
cr_l1n_rrr

bagley
networks
skyes
lyds
@
lydsrestricts

c.

traumas

lollygag
@

lwburwell
@
catturd2
@
adamkinzinger
’
issues
issues

yousbusffer
delusions


@
jo1226550791912

kenmilesamerica
aliens
..
illegals
vaccines
mrna
experi

🏴‍☠️
@


voices
characters

online
jush
jushdied

goku
stronger
shit
tears
fuck
deaner444
@
deanehenryson




app
google
tic-

coolapps
selfcare



torafuku
@

creed69668015
@
basedlida


ier
btc


@


bnbbtc
bitcoin
binance

cryptoedy📉😂
☆starzie☆
@
sugarystarzie

xelqua

roleplay
angsty
tells

deaner444
@
deanehenryson




app
google
tic-

coolapps
selfcare



@


rcraft
farms


ments

✦looli.u✦🧧
@
looli_uu


characters
buren
@

things



imo
aj
@

chloesapter



meltdown…no
meltdown


jak
sayers
jaksayers

betraumafree



patients
textbooks
textbooks
@


ision


dombois
🏳️‍🌈
@

@
zakugamignon
artists/




folks
rd
....
🏮
zaküga
art🏮
@



artists
actors
designers/
rd


ryan
davis
@
rynersafety

liv_boeree


talks





>


‘
bogghi
@


chats
substitutes
risks
individuals



concerns
biases
nuanced




broader
changes
dabrowicz
@

realmofzaterra
@
cocamidemea
opportunities




palestine
bands
@
therealisticrecruiter
@

humanheadhunter
linkedins



stat
lil
🎄🌟
@

fuck


soa
@


meltdown


microsoft
danie
akes
danieakes3

agnstgrmrs



aspects
@
msrebeccabirch




joh
gurcan
@
johgurcan












professionals
@

capt_smirk
@
brrwa
@
keithwoodsyt


crossplag
@
crossplag

isions





✨🌚✨
@
withevette


things
’
months



tearortear

cyantheclown
bc

revising


dariaonia
dariaonia




@
bit111111
swiftonsecurity

sucks
kinds


words
invalidated
professionals
surrealal
@

pigsandpies
’
🤷🏻‍♀️



barraford
@
cbarraford



interactions




flutteringsoul🦋
@




texts
words
jefe™️
@





ه
@
zaarpaar

unavlable


bf

filipa
@
filipa_stins




berci
meskó
md
phd
@




users

pany

users

pany

nbcnews./tech/internet/ch…
lonelyboi_xoxo
@




ellis
@
witchdylan

witchdylan
@

emotions



imo
mj
@




k6
@
updateliveware
replying
@
omooretweets
’


’
imo

“
”

@
lagibelajardlu
curhat
yeah…
ex😅
fsal
mahmood
@
fsala1blogger


documents
others
icmr
indians
techandenvironment./chatg…
basum

replying

alternatives
zionist-jews
raqif
makhdoomi
@
raqif_makh


nerves

paragraphs
words
😭

palestine🍉🍉🍉
dax
@
daxsu_desu

replying
dathecat
@
icsbyvien
app
lah

afrd
backend
perkeso
mom
calls
scammers
@
andynosretep


voices
️⃣
@
lol

🫠
@
syiver64x

@
app
yugioh
@
jesterxl

replying
vegetablesreidy

kinds
things
emls
emls
apps
@
peacefasoiro

replying
mushtaqbilalphd



self-authored
frustrating
😞
tips
human-written
-generated
scenarios
nofi
*
@



🤷🏽‍♀️
gson
@

“
gm
–

crypto
statements
hambar
@

tak
buat
csp

stfu
pati
@

things
....
fucking

howcroft
ehud
@



lines
blog
ehudreiter./2023/12/11/wh…
isnt
suggestions
armstrong
@
taxingsubject

seattle_tax



tavane
@

questions

answers

/
panion


fr
do–
@
covereduptj

indrination

iof


feels


lives
ober
7th
hamas
stories
yisrael
ch

@



lines
blog
ehudreiter./2023/12/11/wh…
isnt
suggestions
elio
|
elio
|
@
outsetbusiness

ll
results

~
words
~
sentences

ali
*
@

4
@

*
pajamas
*
elio
|
@
outsetbusiness

ll
results

~
words
~
sentences

kawas
amjad
masad
@



mnstream
amjad
masad
@



mnstream
collé
e/acc
amjad
masad
@
amasad



mnstream
@

beckpeterson
impressions
tesla
😂


becks
hzj
amjad
masad
@
amasad



mnstream
bames
jond
amjad
masad
@
amasad



mnstream
karthik
amjad
masad
@
amasad



mnstream
billz
@

javilopen

agi
*
llm
amjad
masad
@
amasad



mnstream
droon
🪩
amjad
masad
@
amasad



mnstream
@
shrimpwonder

’
laptop
weeks

’
brnstorm
@

wangchagi
hwy
hes
gna
..
apologies
half-assed

offline

esque
didarul
amjad
masad
@
amasad



mnstream
shivansh
puri
amjad
masad
@
amasad



mnstream
zig🏴🏴
amjad
masad
@
amasad



mnstream
waefrebeorn
amjad
masad
@
amasad



mnstream
franci
pe
@

website
mercial
purposes


mln
customers
cases
panies
humans
violations
amjad
masad
@
amasad



mnstream
amjad
masad
@
amasad



mnstream
pymike00
amjad
masad
@
amasad



mnstream
blazerz420
@

theenchantedemi
sounds


words
a🍃
@
gerutine

im

bley
@



chats
buff.ly/3rx9jzh

artificialintelligence

lonliness
@
virtualtarzan

chats

warns
secrets
chats

@
virtualtarzan
theguardian./technology/2…
vatekun
createdontscrape
@
jonlat

words
/gen
asshole
strangers
bupe
@
chombabupe

reservoirs
larger
models
google
-5
atharva
kanherkar
@



nodejs

github./atharva-kanherkar…
barfield
dwelsh
@


ve

’
alities
curves

dafemboiarty
|
envtuber
@


extent-
finals
it-

voices

writers
inspiration-

@

he1kumwya


....
mosley
@
jessiewmosley

pn
pn



fyp
pn
matters

gizike
@
gizidream

_chatmagic

interactions
girl/boy

c.castreje
@


relationships
algunos
pensar
the-oder./dont-use-cha…
mr.
slowyourprose



dramedy

im
ppl

lmao
professorskeleton
@

liberal/neutered

drugs
johnnymnemonic
@
johnnym70366638

'elite
universities
self-education
'educators

wesley
@

swn
brothers
sisters
academia
heterodoxies
outraged
demands
claudine
matters
right-thinking
exeter
teenager
youngest
tenured
then-president
summers
scholars
subjects
officers
suspects
subjects

investigators
sexualized
claudine
scioness
hti
wealthiest
families
exeter
stanford
published
papers
papers
books
professors
institutions
papers
rules
professors
beneficiaries
swn
overcame
peers
opportunities
considerations
diminished
opportunities
avlable
elites
swn
@
chris_tian____


plans
🫢
emilio
@

🏳️‍🌈🏳️‍⚧️
he/she/they
@

nigoo42311716


alexander🚗🔋🇩🇪
@

elikesros
@
rahll
google
google

rayketh

jamesd0101
@
parkermolloy


things
ingredients
measurements
@

oof


@

moj
@



moj
@

’
boogerjuice
🦠💦
@


degrees
dors
shit
leans

reddit
info
updates
canana
@
canana_man

idk

dly
lives

dystopia
pacoin
@

eth
eigenlayer


sweth
🤣
@


answers
acab
🇵🇸
@

hours


harrington
@
jayharrington75

headlines
lawyers
cases

fewer
questions
holidays
kblitte
@
jye_baba



roandkid
@





credits
victoriquem

fuck
fuck
@

matthewscum
’



pages
rebornix
@

@

btw
@


mnc
/llm
employees
wtf
/llm
ip
at-least
llm
incumbents
advancements
ronak
gupta
@

minutes



emor
artoi
@

davidhundeyin


brns
minds
thinkers
app
words
thoughts
antalova
@


stackoverflow
docs
google

@
teejayohhtay

crissles


essays
diseasy
@


wasn
’
llm

tle
lsd
pomodoros

absurdlymax
results
time/money

improvements

keting
nika
@

takotreba
imo
convo

idea-making
facts

@




@

fdd



fdd-
states
fdd
’
fdds🤔
thinkpiece


prompts


takeover
ml
@
mlplebian

melaniejoly
bruh
mundt
@

“
…
”



herr
@
herrmagister

@
axelspringer
@
@
businessinsider
@
bild
@
facts

🤦🏾‍♀️
@
ontologoff

cafe


thomson
@


models
puter
snippets

orosz
@
gergelyorosz


models
…
panies
pricing
’
shellie
@



w—law

cases
malina💋
@



wiley
@
neural_mirage

@
’


holidays

months
pls
missed
ngl
saoirse
ronin
@
jakesalterego

jaredmckiernan
folks
bullshit
conversations
ms
fave✨
@

yabaleftonline
shit

up😂😩

dogeofficialceo
@
elonmusk
grok
followings
spaces
’
tweets

months
@
shekhawat
@



grok
anya🎋
@
cerisewrld


convo


mak
@


eml

justme
@

elonmusk
@
elonmusk
grok

grok

disney

spacebound1
@


🤦🏼
quotes
skills

@



fauler
hoyt
@


characters
coders
llm
@

egg_1046
@
elonmusk
mistakes
grok
errors
responses
trning

poptart
@

grok
tl
unhinged

kyutip
🌞
@

games
ravn
engk
@
seossian


span/context
hours
v4
messages

du
nord
@

feisty_waters
facebook

🙄
@
iliandaviaud

torreydawley
@
thesebashidalgo
@
grok

eyes
ko🇰🇪
@



dushane
@



lelouch
@
randomguy000004

star47496851
flower🌺
@

dogecoinmillion
grok
🙄

😝
grok
mr.elon
women
🙄🙄
hmmmm
cristine
@
pstafarianprice

wt


unsettles
puter
shit
cattori
@

hours
pr
int
keys
ocaml
🐪
minutes

unfr

non-programmer
tesla
@


«
hr
»
@


*
*
*
*
jokes

jokes
non-veg
@
ztobi




things

’

app

pre-trned
transformers
llm
chats

assistants
api
*
*

chats
url
chats

cet
eml
>
bio
@
sharma
@
sharmaakshat777



@
svpino

google
vs
-4
bloodbath
sugarmakesmesleepy
@
obistinate



krakowski
@
jeremykrak

bindureddy

fireveels
al_al_yan


@
shitpostgate

loftwah
@


feels

@
_qudsi_



@
_qudsi_

writernextdoor_
okay
@
playgamesmovies


microsoft

ironic

execs
isions
📧
@

cordwner_birder
@
cordwn_birder

ktrewick1
@
jonsimschina

paper-
gisp
website
bullshit
google
crossin_borders
chris_g_24

garethvjones
@

’


custome
lol

lol
isn
’

edelstein
@

yanisvaroufakis
bullshit


@
douglaskmurray


performances
heads
mit
penn

nighte

’
ৎ୭
@



notes
illari
@

“
per.
”
concerns
e.g.
subprime
regulations
besserwissers
’


@

im
articles

ve
funding

smallangryhamhock
@
angryhamhock

coworker
shared
workspace



essays
y'all
🖤🩶🤍💜
@
abbyfran_moody


website

servers
’


finals
💀
@
doriandevelops

stefanrows
dr

db
questions

⚡️
@
h3y0ka

_ghost_
@
findurnemo
@
mofo

ality
biden
tts
esme
@

mindset
t_t

fp



chandan
ku
@


lazy.😴😴😴😴


letters
dr.
@

internet
likes
tweets
mama

requests
replies

wandhi
@


certn

boldizar
@

christophpaul_
@
alexwoodroe
unfun

reads
-expert


dumber
billions
interactions
trning

fbi
@

anthroperator
loudest


patterns


ine
@
molecularxtal


materials


llms
dr.
yukta
@

founders

ments
pnful
@

sounds


frankie.zk.fuel
@




users

账号
美女

@
portalcoin
simoy
@



nooooo
tarek
@



hamas
🇺🇦
hana
dusíková
👩🏻
🏳️‍🌈
@

@
mattgodbolt


@
buckwheatmat

t1chiefrocka
@
boardgameparent
gamers
states

skips

snowflakes
online
crybabies
emulators
illeagl
ive
games

anonimo
@

a.i
websites

a.i

@


brother-in
-law
whos

foodfight
glorified
madison
@

levelsio
💔
😭

assistants
𓆩
fth
𓆪
@

classi
ki
y7eb
ya3mel
modèl
machine/deep

yaamelou
kifeh
pany
enti
ija
entretien
wena
ynediwlich
haka
maneha
🌚

xboxes666.bittensor
@

benjamindekr
bittensor
youll


🦷
panulay
🦷
@


simps
tldr/translation
facebook

users
brnless
assignments
skills
prompts
@


brn
yulia
@
ittv130083



tken
@

llms
i.e

etc
bru
@
just__brunette




🤣
letts
@

midjourney
midjourney
overly-creative

lines

limitations

programs
capabilities
limitations
solutions
versions
nicer
features
fundas
midjourney
creations
machiavilln
apecoin
🇺🇦
@


@
portalcoin
tweets
cringey
@



online
yum
@
clumzychaos

mtalha_h
😡😡


treylayton.eth
treylayton3

ngl
*


limitations
answers

answers
patterns
brnchild
*
concepts
q-learning

concepts
teaches
cs
machines
holmes-style

calculations
double-edged
nightes
wars
weapons

*
startup
thestartupbreakdown./p/yo…

puterscience
samaltman
@
pdxnag



champs
🧠
@

web+seo

”

seo
rammi
✨
@

peril_in_pink
😞
’


emls
aledro
ribó
@



puter
o'connor
@
husbandofayn

basedbeffjezos

dall-e.
freeyaz
@
svcredtemple

honeynecta

issues

🫠
students
outlines
’
them😭
deianna
🎄
@

cousins

assignments/work
proud
weinberger
@
dweinberger

humans


neoelectrics
neoelectrics


ads
users

caters
firends
yun-ta
ts
@


’

google
mattgarcia.eth

linusekenstam
'native-sounding
lol

tanz
@

davidndii


cheaper
loans
loans
kanyaga
mafuta
nez
@
nezreyli

fans
asl

@
website

writeups
🤓
sangwan.shares


@

carlvellotti
yeh
gestures


questions
@




sql
mands
🌵
@


lambur
@

arnchand
@
sui414
’

jstor
’
years
’
@

ejiaarath


@
joemilleras1

ve

teenager
@
nickcamata

nerds

twitter/forums
programming
puter
things
~12
linux
espen
@

thoughtomato


plete
no-go
@
cutiavirginroad

looks
ia
hours


fucking
genius✨
🐦
@
raoolcat


’
google
seo
conversations
“
”
“
boop
”
ch
@

’
mistakes
@
angryblaqwoman


essays
@



@


essays
@

heykahn

hines

mcgee
isiah
@



⤵️
cags
@



stories
im
feelings
dantroll
@
daaaaniall

baca
tak
reti
dasar


𝔏𝔦𝔟𝔟𝔶
@
libbioo

_vezbian

essays
uni
ks
ems
@



essays
ًraj
@
legorajs

sillylittlepriv

answers
paragraphs
shit
essays
sooo
programs
bcs

certn
instances
nyan
@

labenz
@
esyudkowsky



idk

nivi
@
nivi

members
civil/criminal
lives


.zkdid™
🧠
@

icodeagents

psyop

shit
@


👨‍⚕️problem


@
t3metrics



breadcat
@

*
*



hours
games
ideas
solving
llm
ganii


essays
codes
butlerian
grabbag
@



@
accounts
chatthread
help.open./en/articles/…
maddie
@

guys

mollet
@


web-page
e-book

ramblings

bcbish
@
bcbish1

jolie

☀️🌙
@

fic
😕

wheelpower
🚶🚲
🚌
🚄
@

afrd

mpaka
nimalize
masono


google
google
jessa
•

@


hundreds
hours


gios
🔅
@
giosbordoli


dem🇺🇲🇺🇦
@

connections

looks
pany
hundreds

borkje
@

bloque_et_basta
then😥


cybersparks
financelatino

@




@
tengocj

esfandamir
tbh



@

jobs
a.i
microsoft
wolves
altman

users
schmidt
@

altman
pany
billions

work-
kalati

@
sama
@
bio


evans
justevansk

josh001j
😭😭😂my
techno

@
dlyguardsman


shit

closest
ku
|
blockchnworldco
@

shocked
low-key
altman
day…
‘
/
jobs
couldnt
’
😂
’
koper
@


🤣
@

leonglefish
“
fools
masterclass
..
them…
”

ohh
booiy…
ol
’


emherald
@

alexlifediary
exactlyy


aamih
@

gdb
that😥😥


ceo
’
😪😪


’


artists
artists
ve
bills
’
ellis
@




replies
lol

years
replies
years

😡
artnome
@
artnome



jokes
nyan
@

teknium1
@
sama
*


heston
md
@




chats
referrals
levels
guards

cureus./articles/213293-s…
ex-addict




trusted


joh
gurcan
@
johgurcan












professionals

@

specialists
experiences
’


limits

engineers
long-term
engineers

@
waverly_

challenging
clients


issues






👇
”
clueless
mynurva
@

chats
patients
months
sites

openi
chats

hubs.ly/q01cz1jr0

@





mh
issues
dehant
@
benjamindehant








services

@

’
pany




issues
businessinsider./pany-…
futbol
@
dylanowendylan

pany




issues
🕸️😡😡😡
businessinsider./pany-…
şerife
@

robertrmorris



members


hype
johnston
🌍
@
pauldjohnston


services



/github
limits
systems
@
timnitgebru
@
dr-munity.social
@

experiments

@
sarahcolbourn

researchers





clarifications
opt-in
’
chr
@

puters
limits





@
robertrmorris

robertrmorris
ve
conversations

sfusd
bonds

alanvrk
@
robertrmorris
wt




dazzagreenwood
@






@
robertrmorris





—
-3
’
🍓🥛🍞
@



halloran
@

a_musingcat

prices

socdocinji
@

negus_wit
google


amna
vantesjuuls

arate


answers
problems
@

joever
cbts


jakenaturo
@
jnaturo

@
app

stories
'reflective
sumies/thematic
conclusions
instructions

asap





outes




outes

|
vox
buff.ly/46wylmd
mepost
@


’
app
debates

altman

edy
😅
adventures
devhumor
techlife
challenges
etl
@
dataexpertise


feelings


@
yore_momm

elonmusk
’
@
grok
“
gender-affirming
”
changes

orwellian

others
”
screenshots
conversations

expectations
pomodoros

absurdlymax
results
time/money

improvements

dgelskog
’
@
gemmugh

messages
shit

o-kei



💀💀
fionen
👑
@


heh
etc
hockster
@

raci2000
@
sameihuda
@
psychgeist52
@
mitukteam

meds/poverty/eugenics/

nervous™
✨
@
jooniejukebox


’
dipshit

i.e
asians
“
[

]

unavlable
esme
@

mindset
t_t

fp



@
exaltaccount

_vezbian


vanya
@
chasingskiiess

fuck
shit


maddi
@


hack=talk
problems

🇨🇦
cpl
canuck🍎🍏
@

inasmigielsk
@
jackposobiec


’

children

༊
*
·˚
☾
@

y'all
fuck

dly

hergert
@
hergertme
@
fosstodon.org
@


fuck

nikhil
ranka
@

llms

llms
😥😅
powershell

variables
laptop
birdsniff
@
birdsniff


-overlord
algo-opoly
caps

💧🔥🩸
@
yungmedusa



humans



+
humans
cht
@
popstarsley

nickadobos


papola
@
johnpapola

@
washingtonpost
porn
faux-


features
@
darrylmason


options
australians


professionals
options

@
intrepiddolphin

darrylmason
judging
standards


ve
༊
*
·˚
☾
@



👽
@

@
pplsartofwar
ramifications
jobs
profs

papers

services
responses
patients
dismissiveness
consequences
ppl

arithromaniac
@
rattmansoupp

….
kk账号/推特号/电报号/飞机号/账号
@

🥺🤡🦻😠

dna
推特号购买
电报
推特账号
shadowrocket
账号
电报账号
推特号
小火箭
电报号
电报号购买

4
maung
thuta
@

areas
%

apps

cryptoaddict
@

waterkiecat
fuck

couples
@

teslaboomermama
elonmusk
*


results
answers
monocoque
vehicles
@

nighte


mf
nads
@


..
problems
🤨
🧬🚀
@


breakthroughs

lockdowns
wars
angels
@


@
exaltaccount

bs
morons


sucks
leyo
@

thoughts


angels




’



allsides
allsides./news/2023-10-02…
oona
metz
@

parenting


time./6320378/--…
yung
@




’
msnbc./opinion/msnbc-opin…
@




’
dlvr.it/swvyny
ts
@




’
dlvr.it/swvjtk
@
notgniwerb
ads

services

panaceal
benefits

non-theraputic


shadowsong
🌙
@

imani_barbarin




mh
@
kyyork57




’
dlvr.it/swtfnz
schiff
@
spencerkschiff

saern3
@
api_assasin


doesn
’

observe_krta_hu

errors

shutterisland
@

orphiccapital
@
nathalierach


@
@
chaos.social
@
dennis_kipker

risks
psycho
interfaces

text-to-voice
systems
heard
experiments


gizmodo./open-employee-…
xeophon
@

andrewcurran_
@
teknium1
prompts

blog

results
ve
cherry-picked
iclonedna
@


concerns


“
”
analyticsindiamag./is-thi…
artificalintelligence

futuretech
dna
brncells
brntech

brn
vaporwave
bf
@




vaporwave
bf
@

problems


overpd
engineers
🇵🇸
@
jamesgeso

op


johnstun
@
joejohnstun

bc




@

tszzl

magin

profoundlyyyy
@
chombabupe
@
keting
_safety_




lowe
@

tszzl

results


incentives

babik
@

yoavgo


chat.open./share/6a7bd6…
jn
@



zero-shot


shutterisland
@

@

formulc

henry⁷
🍊
@

reasons


crypti-calli
@

shit



@


“


”
terri-fucking-ble
info

sutskever
@
ilyasut

models
*



applications
ouppy
@
piler_42

irl

mom
jfc
weng
@


w/

work-life
heard

stanislovas
@

raudelmil
@
andersonbcdefg
@
pavlovsburrito
@
khanstopme
’




”
lol
louisanslow





@
nbouscal

’
tf
“


”
idk
ppl

high-stakes
’


adct
neirenoir
e/⊙
neirenoir

feels


girls


illnesses
jizya
@

qaunshadow


@
biotichamster

notlikemonopoly
nuanced
conversations
forms

w/



trned
kbfoodphotos



@
biotichamster



’

r.
maciver
@

opinions


tonya
@




reasons



@
robertjbateman


uk

protections


trnee
counsellor

arb
@
arbi_t_rage

nbouscal



mn
takeaway

bs
eston
@



reasons


@
zombiekilbourn

@
monkey_mutant
@


…you
@

oreos2002
@
jathansadowski
@

%




remilia
secrets
🤐
@

app

weng
@


w/

work-life
heard

williams

williamhcarlton
@
fucking
shit


joscha
@

sparkpaul
@
tszzl
@



researchers

models
@
kenthesimp



@
nbouscal

’
tf
“


”
idk
ppl

high-stakes
’


adct
ryse
@

@
classywarfare



oute

af


siastar
@

ethicalorg
@
shawnfumo
@

In [ ]:
tweets_eng_pos=[]
tweet_list=neu_pos_tweets.Text.tolist()
english_vocab = set(w.lower() for w in words.words())
i=0
for text in tweet_list:
  for word in text.split(' '):
    #if i<10:
      #print(word)
    if (word.lower() not in english_vocab) or not(word.isalpha()):
      print(word)
      text=text.replace(word, '')
  tweets_eng_pos.append(text)

Streaming output truncated to the last 5000 lines.
app
google
tic-



selfcare

freeapp
coolapps

@
luisscarchi


👇
convo
judgement


@


seekers

chats


apps
thought-provoking
@
sciam


artificialintelligence

chats
bit.ly/3p37myg
َlyle
🍭
@


’
pov

nolan
@

safe/expected
answers

panies
tdoc
betterhelp
online

sheinberg
ph.d.
@


chats


apps

programs

programs
unvetted
bit.ly/42ofv1c
randahl
@

endwokeness

nik💥
@
ns123abc




j.earley
one-on-one

neuro
🧠🗺️
@

online
prof.

learnings
n=2400
cbt
pdt
+
thoughts

neuro
|
world-wide.org/seminar/9114
@

nickadobos


ent


@



woods
problems
@

lazlowoodbine42
@
horatioyuletide
@
jtylerhagen


🇵🇸
🍉
@

crulge
@
_eric_reinhart



disorders
plicates
text-based
input/output

utis
@
titletrophy

talking.
instalments


domnname
psycho
domnnameforsale

4open
babyagi
✨
@


brinks
@


snes
’
@
sen7ience

emls

dokja
webshrink
@

services

-powered

varepsilon
@
var_epsilon

tradfischizo
“

”
bro
“
”

ui

@
grc99__

seramoonie
wt


clarke
@





jazeera
ireland


services
canisgallicus./2023/05/02…
@
canisgallicus
⋆
✭
✧
𝐀𝐋𝐄𝐗𝐈𝐒
𝐉𝐀𝐃𝐄
✧
✭
⋆
@
jupitergrl_


shit

lmao
emls
@

@
@
ilyasut
@
sama
influencers
professionals

psychologists

gonzalez
@
elcopymaster

psicólogo
puede
más
euros/sesión
pero

puede
escuchar
tus
problemas
juzgarte
así

puede
convertirse
psicólogo
gratuito
bigford
@


spends
’
services




sonia
choo
@


apps
ch

counsellors

avlable
newyorker./magazine/2023/…
jacquesthibs

livgorton
@
basedbeffjezos
hahaha
’
“



”
⛈
@

@
beingkelsey
@
cyberphunkisms
things
ve



sudo
@



relationships


kache
yacine
@


🐈
@



lives
@
danmurrayserter




dredze
@


responses
%
answers
echoed
steps
@
cdcgov

monitoring
cravings
@
yuanmunity

klotzman
@
uofcalifornia



ml
saneliswa
@

dukeofqomintaba


😂
ru
@
pancakecleanner



saurabh
💊🏏🏀📑
@

idstewardship
@
idvilchez
@
pharmacyposts
kisgenuf
@
lisdpharmd
@
jaycdoesid
@
mmpharmd
@
paulsaxmd
@
idsamededcop
@


abx
ent
isions
....
relationships
@

-3
dly
users



skills
possibilities
debates


.🤖
👉ow.ly/r6kj50oi4aq

philly
@


seconds
aspects


@



👉
threads
linkedin
⚡️
@
brendanhufford

skstock
go-to

minutes
bierschbach


citations
articles

tumblr

@
danmurrayserter




aanchal
@




•˚｡ꮚ⌀֊̫⍉ꮚ｡˚.•
@
mosquitoboy93



app
@

implications
fields
blogging
practices


mindmatters./2023/06/the-e…


clarke
@





jazeera
ireland


services
canisgallicus./2023/05/02…
@
canisgallicus
torvesin
nowkleged
🧠
@

amandanat


mcgreevy
|
copywriter
@

chrisldyson

business…


delaney
mcguire
@

thoughts
-based

benefits


delaney
mcguire
@

🌟




offers
advantages
✅
✅
✅
✅
non-judg
delaney
mcguire
@



trn

-like
responses
prompts

delaney
mcguire
@



-like

steps


dances
dances



talkspace
pamphlets
@
danmurrayserter




tidi
🦝
@



altman
devs

@
danmurrayserter




dr
@
ashwaryaagadwa1


bucks
chat-

judgement
😝

humans
aditya
shukla
@

rahulra09676311
@
danmurrayserter





prompts
cognitiontoday./-a…
@

memdot
@
gedroberts
solopreneur
@
danmurrayserter


nitter.net/danmurrayserter/…
replies
@
danmurrayserter




@

poppy007
@
danmurrayserter
mem./p/j9f5zv2xw5cwyog70fo…
🪄
-generated
sumy


@

yalexos


psycho
incensed
individuals




snoozewala
@




professionals
starovk
@



cogburn
@
systemictexism

jakewisk
’
centerforclinicalexcellence.…
…how
munication
%


yoshifumi
murakami
@

がメンタルヘルス業界にも大きな影響を与えているという記事。プロのセラピストのほうがもちろん上だけど、無料で待ち時間もいらないというのは確かに強い。




|
|
jazeera
aljazeera./economy/2023/4…
candacerhodeswrites
candacewrhodes

tschill86

online
responses

@

’




llm

unavlable
@
selfmademen7
|
mindset
@

danmurrayserter




’


beatriz
@
biaklimeck

é
tão
fácil
quando
alguém
usou

pra
traduzir
terapia
é
”
é
má
tradução
“

”
cavaleiro
ia
@

terapia
é
custando
ms
real/hora
🛑
felizmente
pode
transfor

num
terapeuta
gratuito.🚀
eis

sua
saúde

🦾
c.
@

jksmith18


entry-level
counseling
avlable




what_now
@
singularfate

danmurrayserter
@
horlayer7
isn

labor-force

@

danmurrayserter


t.
lofaro
jr.
@


me/cfs
pacing
cfs/me
ponents
techniques
cognitive-behavioral

cbt

mecfs
@

danmurrayserter


services

cheaper


’
@

imprived
@
dragonsjet
nvm

websites
😭
@
danmurrayserter




leveque
@

⚠️



services

self-
thoughts
krista
steele
@

almakatsu
@
intlspymuseum

secrets
pany
“



’
.
”
op
sathya
@

danmurrayserter
@
savetonotion


simo
@
jsachael


ceasefire
panndder


couples

•◡•
@
blublries



-
thoughts
robo
listener…
just…
cuimc
gov
cumc_gca

dr.
kimmel
@
columbiapsych


takeaways
bit.ly/3qo4ixh
vasilakos
@

danmurrayserter





@
bassaba_



wired./story/for-some-aut…
@


beneran
ngasih
yg
+
jelas
tapi

dia
selalu
nyaranin
ke

curhatannya
dirasa
terlalu
lol
unavlable
@
danmurrayserter




reasons
•
•
•
thoughts


@
danmurrayserter




tipiana
@




neuralnetworkpress./can-c…
@



du
gâteau
au
chocolat💎🍰👑
@
prncsgateau



issues
humans



du
gâteau
au
chocolat💎🍰👑
@
prncsgateau


issues
feelings

feelings
leveque
@

self-

mohsin
furqan
@


cbt

chatcbt
medtwitter

psychtwitter
leveque
@

self-

@
cuckoo_code

first-class


lifehack
ia
@

solopreneur
’
im


shit
ll
melvin
’
@






mr.
micawber
@

skynet


😂


4
skynet
machines

instagram./p/ctdyg6prtf9/…
torrhl🧵
@

startups

-


wt
սարգիս
@
sakogudjelian

’

psycho
relationships
plexity
’
frustrations
limitations


solopreneur
@






@
monkeerhstudio




solopreneur
@






schaar
e/big
🦅🌻
@





solopreneur
@






hina
@
hinapublish




ones
replaces
humans
‘
’

solopreneur
@






@

nickhalo01

favourite

🇺🇦evan
kirstel
b2b
techfluencer
@


%
participants
docs-api./is--an-e…
@
frank_c_t

voices



solopreneur
@






hallar
azad
@

solopreneur


responses
mistakes
soomi
yoo
@

-based


soomi
yoo
@


’
tone/facial
expressions/body
/munication
ncbi.nlm.nih.gov/pmc/article…
soomi
yoo
@


reasons
privacy/
“
”

guarantees



solopreneur
@






conchúr
ó
maongh
@



heads

solopreneur
@






megbatphoto
@
megbatphoto




solopreneur
@






ku
manish
@

iuditg
tweets



@
swagmachiine


hacks
🧵



@
legendary_nft

solopreneur



warm-up
adansonii
@


convo


solopreneur
@






@
stephxjerger




butttt
helpful/insightful


fortability

solopreneur
@

solopreneur



reasons
humans
-based

iana
@

theholisticpsyc


avoidant
@
moonstrucktwolf

perkinshammer


iana
@

asdrubalivan
@
theholisticpsyc


@

alanou
@
theholisticpsyc



’
eamonn
@

solopreneur
@
readwise
@
savetonotion


nr
@
disabilitystor1


deepest
fears
traumas
emotions
others
technocultists

selves

solopreneur
@






steph
@

europe

weeks
’



solopreneur
@






adaeze👩‍🍳👸
@

favourdiamen

@

callmehejrene
@
solopreneur
mem./p/3q5skj1qrlk87n2xy…
🪄
-generated
sumy

-based



judgment-free
users
cameron
geisler
@
camerongeisler


underrated

self-reflection
problems
thoughts

solopreneur
@






@

michurosso
@
solopreneur
mem./p/gxnqo1pey56ctvrtmxt…
🪄
-generated
sumy

-based



judgment-free
users
𝐌𝐢𝐡𝐚𝐢
𝐂
@

bro
💀💀💀


bitches

solopreneur
@






verdantwind
@

memestrategies
@
solopreneur



assisted
biased

giordano



self-help
books
cases

solopreneur
@






♠️
@

’



solopreneur
@






@
heylukegibson

orgone1
@
jonathanshedler
’

things
’


’
girlfroms



degen
@

bowtiedtetra
😭


🤖
pistols
md

bhanu
@





@
heylukegibson

orgone1
@
jonathanshedler
’
’


‘
tht
’
online

ster
domn-specific
vorick
@


things
corpos

models
huggingface.co/thebloke/guan…
huggingface.co/thebloke/nous…
vegeta
@

solopreneur
@
savetonotion


@

gavinwhittaker
@
solopreneur
mem./p/wgr38gp3kcg1aqyujki…
🪄
-generated
sumy

-based



judgment-free
users
@

gavinwhittaker
@
solopreneur
mem./p/hxo179yb1yw71awfsfl…
🪄
-generated
sumy

-based



judgment-free
users
hoos
keting
@




solopreneur
@






wealthe
@






@
solopreneur
spiderverse
pridemonth
acrossthespiderverse
freesenegal
nomin
btsfesta2023


solopreneur
@






@

potabogo
@
solopreneur
mem./p/tj96a6qsx3e7xqnxzmb…
🪄
-generated
sumy

-based



judgment-free
users
natasha
@







solopreneur
@




reasons
humans
-based


solopreneur
@

problems
dr.
tessa
dr.
tessa

empathetic


solopreneur
@







@


speecb

patients
speechcare./how-yo…
✦
thom
@

’


pastebin./mv6heipu
foopock
@
thefoopock

blockers

matsakis
@




users
topics
@

zuckerzucker3
@
raphisu
genau
hierfür
fehlt
der
nachweis
pei
definiert
anders
auch
wenn
sich
hier
über

immerhin
auf
eine
sehr
große
anzahl
von
zugreifen
kann
lustig
gemacht

zu
der
schlussfolgerung
dass
jedes
auch
eine
gene-
darstellt
objektiver
gegenbeweis
blieb
oben
genannte
vergleiche
genauso
wie
behauptung
biontech
hätte
diese
aussage
nicht
veröffentlicht
tasneem
nashrulla
@

startups


semafor./article/06/02/20…
@
semafor
@

🟡
startups


@
reports
nitsuj


fordham
gss
@




services

goldkind
@
brooklyn11210
tools

reasons
bit.ly/3cdci0l
yevhen
e/acc

fiskantes
fav


purposes
cama
🦊🏳️‍⚧️
@

avo8
@
chrismumbeck

things

processes
🇺🇦
🇮🇱
borukhovich
@
tks
theshot

@
@
jimbojoyce
@
justinnordenmd
🤖
investments
🤖

learningmodels
dr.
watson
🤖
vehicles
rx
mothingbird
@

lyle
kruger
@




lives🧵

deaner444
@


plans
app
google
tic-

plans
relationships





barbiegirl
⸆⸉🐰💜⁷
🏳️‍🌈
🔞
@
coworker



@

-powered
individuals
munication
skills

autismawareness


doleac
@
’


less-trned
counselors
evaluations
at-risk
pops
@
jmotivator


puter

pointers
futures


altfutures./can-chat--…
reynolds
jimreynoldsuk

benefits
/medical
applications
risks
expectations/security

experiences
journorequest
replika

hoover
👩🏻‍🦰
@



scripts
strght-forward
responses

@
w/
@
samspeng
wired./story/for-some-aut…
newsvenue
@


conversations

…
newsvenue.org/
diroma06
ive

dudes
ip
unpd


@
startup

episodes
r.
rastapopoulos
@
businessbarista

plete

drunk-texting

app
ᖇᗝᗝᔕᗴᐯᗴᒪ丅
丅ᗴᖇᖇꭵᗴᖇᔕ
@
rterriers

bans
roseys
theyby
@

<
<


@
years

—

towardsdatascience./ten-y…
—————

datascientists
artificalintelligence
3
4
bigdata
datascience
nlproc
nlu
nlg
neuralnetworks
putervision

@
_thehub_




quicker
cheaper


services
breakthestigma
@
@
namimunicate
@
@
@
mindcharity
@
ghana
g🌸
@


pre
kishun
@


@

sesh
alexa
’
alexa


isml
@
prompts

ismlsaleem.gumroad./l/p…


lioat
@




lioat./blog/2023/05/ch…
@
made_by_chris
leaders

pens


services

panionship

..

sof
sof
sof
@


hh_babykeys
hh_babykeys
sci-fi
ics

！


mjdjourney
artworks
gc
agi
stablediffusion
chilloutmix
lfg
nftmunity
nfts
nftarts
web3
hk
jx
@
pany
providers
roles


@
neurotranscend



conversations
problems

aspergers
abcvisuals
iartcafe
crypto
launches
link.medium./ygg1nfhy7zb
abcvisuals
vr
virtualreality

blockchn
cryptocurrency


avax
zuzka
@

je
moje

fr
noor
@
follownoors

bestie

”
🫶🏼
phd
@
debates

platforms

hurdles
concerns
limitations

shows

finance.yahoo./news/-fa…
ination
@
tcd_ination




drivetime
rte.ie/radio/radio1/clips/22…
honky
@
cb


breakthroughs
kujo九条👻
@

inflicted



weelo
🍓
@
__weelo


results
mindset
groundbreaking
kashtaa
@
icreatelife

humans
_________
tigerine.eth
thetigerine
shaanvp
wt


/
free/


capabilities
@


김elisabetta
🇵🇸
miyane
@

things


tools

sef
@

oakmauler
@
smellsbadinhere


@
gewoon
levensvragen
aan
aan

alles

@


wheeeeeeeeeeeee
@
trader_koala
goodnight
gustavo
schulz
gattino
@
two-hour


10:00-12:00
forms.gle/rgpcpcifmdhf1ghd8
@


luís
sousa
@


processing
jokes

4
dami
🍉⚖️🍉
@


@

passive-aggressive
notes
@




wasn
’
@
robo



artificialintelligence

ckmishn🍀
@
rldexs


sang-rak
@


questions


@
ronald_vanloon
@
nigewillson
@



chats

@

’

🥔
@


ex-girl

reads
squirle
@
jiwowoong


fanfics
jiwoong
im
@
tradermadness




moni
vnue
dwac
mmex
innd
muln
frc
epaz
idvv
rshn
xo
@
xokeitu

🙏🏽
princess💎
@
ayrey

families
strght

@

@
drdanielkimmel

billionre
@
%
psilocybin-assisted

end-of-life
illnesses
lsdi
rndr

lucydiscovery
fr

frustrations
@
pisackson
bit.ly/3q6wu19


estoy
cansada
@



deaner444
@


app
google
tic-

secretcrush
secretrelationships




hannah
@



spa/

@
fb

writingmunity
ledo
@
-assisted
journaling
purposes

selfreflection
pub.towards.net/unleashing…
kage🦇🔊
@
cryptokage
_shubhangiii_




@
coffeevectors

tom-up

@
joncoopertweets
hormones

hrt
transgender
women
hrt
transgender
women
anti-androgen
medications
hormones
changes
changes

transgender
women
procedures
chondrolaryngoplasty
transgender
women
deaner444
@



app
google
tic-




relationships

@
cloutedmind
nft
bros

nfts
wallets
znab
@


withvr
@
individuals


vr
situations

withvr
chmela
munication
eml
@
withvr.app
🔪
@

>

🤍
@
michaelfulwiler


scarlette
madison
@
madisonscarllet
funding
services
psilocybin-assisted

bitcoin
pysop
lucydiscovery

azam
alonzy
@
shouq_beauty
إلى
الأخوه
والأخوات،
إلى
الذين
يعانون
من
الإكتئاب
خاصة
واللذين
يحاولوا
التعرف
على
ذاتهم
بشكل
أعمق
عامة
تجربة
برنامج

وأن
تطلب
منه
تحليلك
باستخدام

سؤال
تلو
الأخر
له
أثر
مجتمعي
وإقتصادي
وليس
شخصي
فحسب
𝕸𝖆𝖌𝖎
@

eitan
@
cool_idea
theholisticpsyc
years


masses
ppl
deaner444
@






|
counsellor
@



client-
uses


tools



rundown

@
therundown
@
_ericelliott





resources

saitan
@
therundown
@
_ericelliott


resources



freud
etc
debrieft
@

experiences
well-being

applications
siri
duolingo
dly
schedules
hours
self-care
dog-walking

rebjorn
@


agi

3
4
5
piped.video/3bgdhhxj-cu
phd
lpc
cpcs
@
talk2spirit
therundown
@
_ericelliott


resource/referral

dr.
asbury-kimmel
phd
@
victoria_asbury


@
deathsexmoney
@
annasale



awarenessweek
kimmel
@


columbiapsychiatry.org/news/…
kimmel
@


columbiapsychiatry.org/news/…
@
[
mpc
]



professionals

well-being


@
badfor3ducation


jyotirgamya
@
low-cost
chats



online
psychologists


@
__
./--m…
artificialintelligence


awarenessweek
founderlost
@


midjourney
dalle2

herzog-evans
@
profmevans

ellis

emotivo-rationnelle
thérapie
et
rationnelle
thérapie
et
rationnelle
alna
@
afentra

🔥🔥🔥

roulette…


me…
timoshenko
@
*
*

conversations
remble.


4



kanekal
gautham
@
]


hypoxic
ine
countries
inplete
suri
☀️
@


erin
stevens

questions

areas
dilemmas
snato
she/her


'medicine
@
samoskal
jdaviesphd

re-enforcing
'
factors
ksensei
👹🧬👾
@
frankdegods


qbri
smes
@
qbridigital




experts





lauren
@
’
@
scobleizer
’


ve
years
ve
books
mindsets

mindset
goals
mindset
jodelo
@


cleardata
cleardatacloud


chats

—but
implications
standards
users


rapporter
@
rapporter
’




@




issues
./--m…
@
scobleizer

’
clarke
@




jazeera
ireland


services
canisgallicus./2023/05/02…
@
canisgallicus
aya✿
@

✖️


✔️
paulo
fratoni
@




experts
./--m…
@
__
muhamamd-siddique
@
muhamamdsiddiq1


experts
buzer./should-you-u…
andrews
zacharylipton

thoughts
feelings
experiences

qbri
smes
@
qbridigital




experts
ift.tt/4y2oxib
🇺🇦evan
kirstel
b2b
techfluencer
@




experts

apple.news/amx2ltfhwrt-wusav…
˚۰☽˚⋆༶⋆˙
@

interests
overjoyed
minutes
-generated
rui
kamishiro
therac-25

furlane
@
furlanegrant




experts




flip.it/p8f4s8
dly
app
@


outshines
humans

tests
|
|

|
app
ift.tt/iidsquy
@
jenny____

“

”
-esque
cases
posts

@
jenny____

things
’
ve

tears
qbri
smes
@
qbridigital




experts
ift.tt/frp0nw1
businessweek
@
bw




wasn
’
covyeau
cfp®
@
mom

bio

…
abcvisuals
iartcafe
inative
approaches
bonds
link.medium./yx24m75fkzb
abcvisuals
vr
virtualreality

blockchn
cryptocurrency


relationships
abcvisuals
iartcafe
relationships
bonds
link.medium./jejlpprfkzb
abcvisuals
vr
virtualreality

blockchn
cryptocurrency


relationships
khrul
@



nemo
artgen001

%
participants
docs-api./
p=4843



mitchem
@



piped.video/1nv2f0dve
timoshenko
@
@
relationships


chats

4
relationships


datingadvice
tips
dateideas

closest
admins
certn
teachers


frustrating
certn
tides
*
uses
*
excerpts
*

christy
@



journaling



𝖌𝖔𝖏𝖔
𝖘𝖆𝖙𝖔𝖗𝖚
𓂀
@

siddhant
pasricha
@
sidist_playsure


whatsapp
@
goosegaymes

aldoul
@




aje.io/v08671
@
ajenglish
tehrani
@

%
participants
buff.ly/3lx6fsa

nlp
alexa
bigdata
exworld
@

%
participants
zdnet./article/is-…
perspectives
@

artificalintelligence


emotions

perspectivesonliving./482…
dtm
@
catnews
crypto

%
participants
cryptoandtechnews./is-cha…
esse
esseisolutions

%
participants
ift.tt/xwsp9rl
@

%
participants
ift.tt/fpxuzhu
dba
@
dougbrowndba

%
participants
dlvr.it/snqt0t
@
disagreeable_i
keithfrankish
@
r_conandavies

𝗠𝗮𝗻𝗼𝗷
𝗡𝗮𝘆𝗮𝗸
@
cbt


sania
@


requirements
katherine
bassil
@

well-functioning
voices



chats

munication
neurosciencenews./tust-co…
dougan
@




rt
☃️
@
getttttyyyy
tonui_yebei

>
>
🇵🇸🍉
palestine
@
honeyyriver


@
poweredbylean


@
rowancheung
joys



bills
mwahaha
mia
ⓥ
@




years
nature./articles/d41586-0…
@

tuesdaythoughts
guys


キッスランド
🍄
@
snapchat


>
>
𝕂𝕚𝕡𝕡𝕖𝕣
@
clovensun
fears
shit
ent
lmao

orisha
@


iphone6prosandcons
iphone6proscons



’


experts
dlvr.it/snk7lv
s.
@
bfr






parallels
bfr

bfr
muscles
hypoxic
stronger


certn

resources
patterns
strategies

mcr


e.g.
self-talk

difficulties
mechanisms
ier
strategies
e.g.
restructuring
mechanisms
strategies
well-being


graber-stiehl
@


headlines



cognitivebehavioral
cbt
nature./articles/d41586-0…

@
theptsnetwork

ranking

google
physio
[
]
clre-apist✨
@
clredavielmft


@


davidson
slimbreezy
@

@



moneyballjudsm
tinyurl./ccy8ux8w
bernat
lópez
@

-
apps
70-year

questions
nature./articles/d41586-0…
minds
inations
-powered




minds
inations




clients
non-judg
thoughts
feelings
—-
🦖
@
neuro_data
@
isdedal
@
“
+

”
justinstillness
@
justindeschamps
@
justnstillness

feet
gerson

earlier
socialbob
@

writers
machines
🎬🤖✍️
tiktok
🌈
📝🕵️‍♂️

cash-burning
🤖💸
primat-eyes
👀

🐵🔬
sugar-powered
🍬💉
bresler
@


questions
>
>
>
>
>
>
yésica
nosica
@


gareth
@
garethwalkom

uary

@
withvrapp
users
>
withvr
@
>
vr
uary

software
users

processing
cel
mellor
@
tech-philosoph
@
tante
redet
mit
menschen
von
„
corparate

“
über
funktionsweise
und
vor
auswirkungen
von

auf
unsere
gesellschaft
zwei
stunden
lang
sehr
sehr
sehr
hörenswert
arvind
upadhyay
@

sectors

spam
hr
etc
nakay
ⓥⓐ
🏴🇵🇸🇨🇩🇸🇩🇦🇲🇬🇾
@

nah
@


ahahahaha
alec.spr
@
benefits


🌞thread🌞

non-invasive

well-being
benefits

hden
@
unfilteredaudhd
autistic_cherry
@
tbh
google


autistics
saas
@





types
“
”

remendations

buff.ly/3luoclg
businessweek
@
bw




wasn
’
npj


@
@



apps
70-year

questions
nature./articles/d41586-0…
xavier
duran
@
xduran_e
potser
depressa
estudiant
possibilitats


-

years
chats
nature./articles/d41586-0…
captn
@
rantyamycurtis
execs

’

✅
”
@
conversations


badgerherald./opinion/202…
_4_care
@
benefits

terms

tools

quagmires

incare
nature./articles/d41586-0…
@
surprised



kfirkfir36
@
point-counterpoint

’

ift.tt/n5ld46t
bahia
@




aje.io/v08671
@
ajenglish
medlog

@
replicants
considerations


tebb.es/3hh7lqr

helpdesk
@




aje.io/v08671
@
ajenglish
lott
@




aje.io/v08671
@
ajenglish

awarenessmonth

@
hackers

malware
google
introduces
-powered


-generated
farms
chao-downs
alexchao.substack./p/chao…
@

-
apps
70-year

questions
nature./articles/d41586-0…
@
wt
…


jia
@

❌

journalytics
reports
cabellsmedicine



buff.ly/42nubeq
@
-
apps
70-year

questions
tichaona
chitsinde
@
tichitsinde
@
lungile_mashele
users
perspectives


levelsio
@
levelsio

🧠

cbt

achievements
things
etc
cbt


fortable
btw

cbt



questions
questions
greetings
topics

wt
responses
tichaona
chitsinde
@
signs

services

osbyrne
⿻
@


t.
@
evankirstel

-
apps
70-year

questions
nature./articles/d41586-0…
wildcolonialgal
🐵🐭🦘
@
karrichapus
@
senatorrennick
@

ch
'opinion
l➡️top
r➡️lower
plasmid

🇺🇦evan
kirstel
b2b
techfluencer
@

-
apps
70-year

questions
nature./articles/d41586-0…
astrobitch
♋
♓
♎
@



barrish
@
bradbarrish

performs

cbt

ality
choices
@
brianroemmele


described
results

hendel
@

-
apps
70-year

questions
@
stiehlpointpen
@
nature./articles/d41586-0…
businessweek
@
bw




wasn
’
kelsey
coletta
@
michaelfulwiler
ve
posts

fb
groups

tx
plans
notes
w/o
’
uhhh

co
@

“

vdtmoca
”
screenshots
🤯

ds
cues
dly
routine.
co
@


ot
😮
‘

‘
self-differentiation
’
vdtmoca
’
coleman
@

answers
r/askdocs

😅

responses
dors

cracks

iv
gaps
patients
munication

simran
chopra
@


😃👍🏻
mangialardi
@
icap
day2

alised
resources

game-changer
@
citcen
mukund
mohan
@




n=740
%
%
%

%
☆
👁
nicole
kidd
👁
☆
@
nkinsights


a.i
panion
>
”
panion


areas

.
”




nyti.ms/3akapcj
jaden
@


replies

In [ ]:
tweets_engN_df=pd.DataFrame(tweets_eng_neg, columns=['Text'])
tweets_engP_df=pd.DataFrame(tweets_eng_pos, columns=['Text'])

In [ ]:
tweets_engN_df['Text']=tweets_engN_df['Text'].str.lower()
tweets_engN_df=pd.DataFrame(tweets_engN_df.Text.apply(nouns_adj))

tweets_engP_df['Text']=tweets_engP_df['Text'].str.lower()
tweets_engP_df=pd.DataFrame(tweets_engP_df.Text.apply(nouns_adj))

In [ ]:
tweets_engP_df

                                                   Text
0                                dev session technology
1                                             i instant
2     mr tweet test advisement advisement generative...
3                                           check poe./
4     longevity gene genetic engineering stem rigid ...
...                                                 ...
4141                         s myriad ethical practical
4142  suicide prevention prospect treatment myriad c...
4143                   english myriad ethical practical
4144                               paul draw revolution
4145                                      la revolution

[4146 rows x 1 columns]

In [ ]:
neu_pos_tweets

,Unnamed: 0,Text,sentiment
0,0,techforgood 💙 dev khanna ces2024 @ curieuxexpl...,"{'label': 'positive', 'score': 0.8860149383544..."
1,1,~♡ @ replying mikaqvia hugsss 🫂🫂 cuz megumi i ...,"{'label': 'positive', 'score': 0.8713191151618..."
2,2,mr tweet @ renowned test advisement newszo...,"{'label': 'neutral', 'score': 0.8472962379455566}"
3,3,matt ahmann @ check thera- poe./thera-,"{'label': 'neutral', 'score': 0.8349331021308899}"
4,4,𝙲𝚊𝚝𝚊𝚕𝚕𝚊𝚡𝚎𝚛 @ catallaxer “ [ conferences longev...,"{'label': 'neutral', 'score': 0.7989817261695862}"
...,...,...,...
4141,4697,uģijs s šodien myriad ethical practical con...,"{'label': 'neutral', 'score': 0.8168298602104187}"
4142,4698,unisa suicide prevention @ prospect ment...,"{'label': 'neutral', 'score': 0.6521839499473572}"
4143,4699,jazeera english @ ajenglish myriad ethical ...,"{'label': 'neutral', 'score': 0.9171144962310791}"
4144,4700,paul draw @ revolution next aljazeera./ec...,"{'label': 'neutral', 'score': 0.80653315782547}"
4145,4701,raffaele la ciura @ revolution next aje.i...,"{'label': 'neutral', 'score': 0.6422625780105591}"

In [ ]:
textsTWTNeg = [row.split() for row in tweets_engN_df.Text.tolist()]
dict_for_coh_TWT_Neg = Dictionary(textsTWTNeg)

textsTWTPos = [row.split() for row in tweets_engP_df.Text.tolist()]
dict_for_coh_TWT_Pos = Dictionary(textsTWTPos)

In [ ]:
cohere_numTops(tweets_engN_df, dict_for_coh_TWT_Neg, textsTWTNeg, 2, 7)

=== K = 2 | c_v = 0.778 ===
  Topic 0: bad, wrong, way, other, someone, real, new, many, world, help
  Topic 1: free, good, open, advice, bitch, basic, dangerous, reporter, use, human

=== K = 3 | c_v = 0.796 ===
  Topic 0: real, way, world, bad, time, many, language, whole, worse, wrong
  Topic 1: free, new, advice, good, open, other, human, expensive, guy, playback
  Topic 2: bad, bitch, basic, open, good, reporter, wrong, something, someone, session

=== K = 4 | c_v = 0.787 ===
  Topic 0: way, bad, world, real, many, time, language, gay, good, actual
  Topic 1: free, advice, open, dangerous, new, expensive, good, playback, enable, data
  Topic 2: bitch, basic, reporter, bad, something, wrong, open, someone, everything, good
  Topic 3: good, other, stuff, own, mad, worse, new, human, real, sad

=== K = 5 | c_v = 0.793 ===
  Topic 0: real, bad, way, world, actual, gay, language, good, thing, harvard
  Topic 1: free, advice, dangerous, new, expensive, open, playback, enable, good, way
  Topic 2: bitch, basic, reporter, bad, open, someone, something, wrong, session, professional
  Topic 3: other, stuff, own, good, new, sad, wrong, something, care, mad
  Topic 4: good, open, bad, many, same, custom, code, today, advice, right

=== K = 6 | c_v = 0.794 ===
  Topic 0: way, advice, wrong, gay, harvard, expensive, dangerous, language, model, help
  Topic 1: free, new, open, advice, dangerous, playback, enable, data, other, dialogue
  Topic 2: bitch, basic, reporter, bad, something, open, someone, wrong, good, idea
  Topic 3: other, stuff, new, many, open, something, human, mad, eliza, sad
  Topic 4: good, open, custom, world, don, today, best, time, whole, part
  Topic 5: good, bad, al, men, tool, human, lilian, information, anything, free

Summary:
  num_topics  coherence_c_v
          2       0.778329
          3       0.796209
          4       0.787082
          5       0.793224
          6       0.793602

In [ ]:
cohere_numTops(tweets_engP_df, dict_for_coh_TWT_Pos, textsTWTPos, 2, 7)

=== K = 2 | c_v = 0.754 ===
  Topic 0: free, playback, enable, new, art, video, data, prompt, advice, care
  Topic 1: human, best, good, use, technology, voice, tool, time, life, new

=== K = 3 | c_v = 0.756 ===
  Topic 0: playback, enable, free, new, art, care, advice, year, prompt, girl
  Topic 1: use, voice, technology, human, good, tool, life, real, al, tech
  Topic 2: best, video, free, new, human, gender, good, money, more, time

=== K = 4 | c_v = 0.747 ===
  Topic 0: data, prompt, year, something, open, new, work, world, benefit, chat
  Topic 1: use, voice, good, tool, al, real, technology, conversation, human, session
  Topic 2: best, video, free, gender, money, human, new, good, time, open
  Topic 3: enable, playback, care, new, free, art, platform, news, creator, advice

=== K = 5 | c_v = 0.758 ===
  Topic 0: year, something, open, new, data, world, happy, project, talk, lot
  Topic 1: voice, use, good, al, tool, conversation, real, session, life, human
  Topic 2: best, video, gender, money, free, human, content, new, create, transition
  Topic 3: playback, enable, free, care, new, platform, creator, advice, girl, visitor
  Topic 4: prompt, news, art, big, io, way, prize, technology, new, more

=== K = 6 | c_v = 0.752 ===
  Topic 0: year, data, open, new, something, world, work, benefit, revolution, research
  Topic 1: use, good, voice, tool, conversation, al, session, stress, human, mode
  Topic 2: best, new, human, sexy, good, open, free, professional, time, art
  Topic 3: playback, enable, care, free, new, platform, advice, visitor, creator, girl
  Topic 4: news, prompt, art, big, new, io, way, prize, creativity, incredible
  Topic 5: video, gender, money, create, other, data, confidential, such, free, transition

Summary:
  num_topics  coherence_c_v
          2       0.754203
          3       0.755992
          4       0.747411
          5       0.757866
          6       0.751623

##pos/neu split

In [ ]:
neu_pos_tweets

,Unnamed: 0,Text,sentiment
0,0,techforgood 💙 dev khanna ces2024 @ curieuxexpl...,"{'label': 'positive', 'score': 0.8860149383544..."
1,1,~♡ @ replying mikaqvia hugsss 🫂🫂 cuz megumi i ...,"{'label': 'positive', 'score': 0.8713191151618..."
2,2,mr tweet @ renowned test advisement newszo...,"{'label': 'neutral', 'score': 0.8472962379455566}"
3,3,matt ahmann @ check thera- poe./thera-,"{'label': 'neutral', 'score': 0.8349331021308899}"
4,4,𝙲𝚊𝚝𝚊𝚕𝚕𝚊𝚡𝚎𝚛 @ catallaxer “ [ conferences longev...,"{'label': 'neutral', 'score': 0.7989817261695862}"
...,...,...,...
4141,4697,uģijs s šodien myriad ethical practical con...,"{'label': 'neutral', 'score': 0.8168298602104187}"
4142,4698,unisa suicide prevention @ prospect ment...,"{'label': 'neutral', 'score': 0.6521839499473572}"
4143,4699,jazeera english @ ajenglish myriad ethical ...,"{'label': 'neutral', 'score': 0.9171144962310791}"
4144,4700,paul draw @ revolution next aljazeera./ec...,"{'label': 'neutral', 'score': 0.80653315782547}"
4145,4701,raffaele la ciura @ revolution next aje.i...,"{'label': 'neutral', 'score': 0.6422625780105591}"

In [ ]:
import ast

In [ ]:
neu_pos_tweets['sentiment'] = neu_pos_tweets['sentiment'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
neu_pos_red['sentiment'] = neu_pos_red['sentiment'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
neu_pos_yt['sentiment'] = neu_pos_yt['sentiment'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [ ]:
mask = neu_pos_tweets['sentiment'].str.get('label') == 'neutral'
inverse_mask = ~mask

In [ ]:
neu_tweets = neu_pos_tweets[mask]
pos_tweets = neu_pos_tweets[inverse_mask]

In [ ]:
print(neu_tweets.shape)
print(pos_tweets.shape)

(2565, 3)
(1581, 3)

In [ ]:
mask = neu_pos_red['sentiment'].str.get('label') == 'neutral'
inverse_mask = ~mask

In [ ]:
neu_red = neu_pos_red[mask]
pos_red = neu_pos_red[inverse_mask]

In [ ]:
print(neu_red.shape)
print(pos_red.shape)

(521, 3)
(127, 3)

In [ ]:
mask = neu_pos_yt['sentiment'].str.get('label') == 'neutral'
inverse_mask = ~mask

In [ ]:
neu_yt = neu_pos_yt[mask]
pos_yt = neu_pos_yt[inverse_mask]

In [ ]:
print(neu_yt.shape)
print(pos_yt.shape)

(896, 3)
(769, 3)

###export for later

In [ ]:
neu_yt.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/yt_relevant_neu.csv")
pos_yt.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/yt_relevant_pos.csv")

In [ ]:
neu_red.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /reddit_relevant_neu.csv")
pos_red.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /reddit_relevant_pos.csv")

In [ ]:
neu_tweets.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/twitter_relevant_neu.csv")
pos_tweets.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/twitter_relevant_pos.csv")

###cohere

In [ ]:
textsYoutubeNeu = [row.split() for row in neu_yt.Text.tolist()]
dict_for_coh_YT_Neu = Dictionary(textsYoutubeNeu)

textsYoutubePos = [row.split() for row in pos_yt.Text.tolist()]
dict_for_coh_YT_Pos = Dictionary(textsYoutubePos)

textsRedNeu = [row.split() for row in neu_red.Text.tolist()]
dict_for_coh_Red_Neu = Dictionary(textsRedNeu)

textsRedPos = [row.split() for row in pos_red.Text.tolist()]
dict_for_coh_Red_Pos = Dictionary(textsRedPos)

textsTWTNeu = [row.split() for row in neu_tweets.Text.tolist()]
dict_for_coh_TWT_Neu = Dictionary(textsTWTNeu)

textsTWTPos = [row.split() for row in pos_tweets.Text.tolist()]
dict_for_coh_TWT_Pos = Dictionary(textsTWTPos)

In [ ]:
len(dict_for_coh_TWT_Pos)

2977

In [ ]:
cohere_numTops(neu_yt, dict_for_coh_YT_Neu, textsYoutubeNeu, 2, 7)

=== K = 2 | c_v = 0.747 ===
  Topic 0: way, good, real, time, other, own, life, many, things, helpful
  Topic 1: way, good, real, something, someone, time, things, lot, more, chat

=== K = 3 | c_v = 0.743 ===
  Topic 0: way, good, time, many, response, something, things, own, more, work
  Topic 1: way, things, good, someone, something, help, time, better, real, lot
  Topic 2: real, good, other, life, time, support, technology, self, own, way

=== K = 4 | c_v = 0.742 ===
  Topic 0: way, good, time, life, prompt, things, many, game, bit, question
  Topic 1: way, good, something, someone, things, help, time, better, more, lot
  Topic 2: real, good, time, self, support, own, other, emotional, way, something
  Topic 3: chat, real, things, better, way, time, other, life, ve, same

=== K = 5 | c_v = 0.763 ===
  Topic 0: way, good, things, trauma, question, real, truth, own, response, self
  Topic 1: way, good, something, time, help, someone, things, better, lot, real
  Topic 2: real, good, other, time, self, way, technology, emotional, support, language
  Topic 3: chat, real, things, problems, better, life, same, time, ve, work
  Topic 4: many, more, good, way, man, own, world, helpful, something, answers

=== K = 6 | c_v = 0.763 ===
  Topic 0: way, good, bit, things, question, secrets, advice, self, prompt, example
  Topic 1: way, good, something, time, help, someone, things, real, more, lot
  Topic 2: real, other, life, way, self, anything, time, something, own, relationship
  Topic 3: chat, things, real, way, same, ve, problems, time, honest, better
  Topic 4: many, technology, life, more, answers, own, use, world, thing, sure
  Topic 5: good, real, language, way, better, time, things, own, emotional, thoughts

Summary:
  num_topics  coherence_c_v
          2       0.747309
          3       0.742677
          4       0.742440
          5       0.762553
          6       0.762505

In [ ]:
cohere_numTops(pos_yt, dict_for_coh_YT_Pos, textsYoutubePos, 2, 7)

=== K = 2 | c_v = 0.774 ===
  Topic 0: good, way, great, things, better, time, more, many, help, ve
  Topic 1: helpful, real, better, life, time, chat, lot, advice, ve, good

=== K = 3 | c_v = 0.771 ===
  Topic 0: good, way, great, time, more, better, things, many, help, own
  Topic 1: life, chat, real, care, ve, advice, lot, much, many, way
  Topic 2: helpful, better, good, great, lot, time, real, ve, something, someone

=== K = 4 | c_v = 0.796 ===
  Topic 0: good, way, great, time, help, things, many, better, bit, lot
  Topic 1: chat, care, advice, life, much, real, things, day, helpful, time
  Topic 2: helpful, better, lot, ve, good, time, something, things, other, years
  Topic 3: good, real, tool, great, better, time, life, many, more, way

=== K = 5 | c_v = 0.769 ===
  Topic 0: way, help, things, problems, time, bad, better, own, great, more
  Topic 1: chat, care, life, much, advice, best, helpful, real, information, way
  Topic 2: helpful, better, ve, lot, great, good, something, years, same, someone
  Topic 3: great, more, good, way, tool, real, ve, life, helpful, things
  Topic 4: good, time, better, real, lot, many, great, things, life, ve

=== K = 6 | c_v = 0.764 ===
  Topic 0: help, good, way, things, better, bad, more, own, time, great
  Topic 1: chat, advice, much, best, helpful, way, real, life, care, video
  Topic 2: helpful, better, ve, lot, great, something, good, other, several, same
  Topic 3: tool, great, more, good, way, life, real, things, many, chat
  Topic 4: good, time, better, real, great, many, lot, ve, bit, things
  Topic 5: things, life, years, good, way, someone, thing, time, problems, ve

Summary:
  num_topics  coherence_c_v
          2       0.774475
          3       0.770886
          4       0.795922
          5       0.769427
          6       0.763643

In [ ]:
cohere_numTops(neu_red, dict_for_coh_Red_Neu, textsRedNeu, 2, 7)

=== K = 2 | c_v = 0.781 ===
  Topic 0: prompt, open, post, questions, concerns, image, free, action, moderators, comment
  Topic 1: time, questions, other, link, responses, thoughts, things, human, way, session

=== K = 3 | c_v = 0.780 ===
  Topic 0: client, good, same, time, treatment, feelings, able, ior, things, anxiety
  Topic 1: questions, link, time, other, responses, thoughts, things, such, advice, way
  Topic 2: open, prompt, post, questions, concerns, free, image, action, moderators, comment

=== K = 4 | c_v = 0.778 ===
  Topic 0: client, good, same, feelings, time, prompt, questions, human, role, example
  Topic 1: link, time, questions, responses, other, al, language, things, such, thoughts
  Topic 2: open, prompt, questions, post, concerns, free, image, action, moderators, discord
  Topic 3: client, other, something, medical, human, anyone, professional, ior, treatment, article

=== K = 5 | c_v = 0.772 ===
  Topic 0: feelings, good, client, same, human, time, example, way, prompt, report
  Topic 1: link, questions, time, responses, things, user, other, character, session, language
  Topic 2: open, prompt, post, questions, image, concerns, free, discord, moderators, comment
  Topic 3: client, other, professional, something, medical, anyone, human, work, treatment, session
  Topic 4: different, questions, life, ideas, time, al, symptoms, medical, anxiety, self

=== K = 6 | c_v = 0.782 ===
  Topic 0: client, prompt, same, human, role, feelings, good, issues, report, many
  Topic 1: link, questions, time, user, other, session, things, character, posive, responses
  Topic 2: open, prompt, post, questions, image, concerns, free, discord, moderators, action
  Topic 3: something, other, anyone, human, treatment, professional, care, medical, good, way
  Topic 4: different, questions, ideas, life, symptoms, time, such, other, counselor, virtual
  Topic 5: responses, al, nresponse, emotions, client, way, field, time, language, thoughts

Summary:
  num_topics  coherence_c_v
          2       0.780723
          3       0.779989
          4       0.777989
          5       0.772410
          6       0.782397

In [ ]:
cohere_numTops(pos_red, dict_for_coh_Red_Pos, textsRedPos, 2, 7)

=== K = 2 | c_v = 0.745 ===
  Topic 0: good, session, human, way, client, hera, questions, great, thoughts, advice
  Topic 1: good, link, time, life, things, week, diary, lot, story, someone

=== K = 3 | c_v = 0.750 ===
  Topic 0: session, good, thoughts, system, way, data, client, time, prompt, real
  Topic 1: good, link, time, diary, week, things, life, story, ni, someone
  Topic 2: good, hera, human, questions, such, way, professional, great, tool, advice

=== K = 4 | c_v = 0.753 ===
  Topic 0: good, way, able, data, system, thoughts, chat, prompt, real, information
  Topic 1: link, good, time, diary, week, things, ni, lot, mom, crazy
  Topic 2: hera, good, conversation, free, human, client, conversations, questions, fields, sopi
  Topic 3: story, session, human, great, life, good, characters, world, things, self

=== K = 5 | c_v = 0.756 ===
  Topic 0: good, prompt, system, chat, data, information, real, idea, today, way
  Topic 1: link, good, time, diary, week, things, life, ni, lot, crazy
  Topic 2: hera, good, conversation, human, client, new, free, questions, answers, sopi
  Topic 3: story, session, human, life, great, characters, time, world, mood, report
  Topic 4: good, fields, human, way, able, humans, general, psychology, creative, more

=== K = 6 | c_v = 0.753 ===
  Topic 0: prompt, system, data, chat, information, real, idea, today, good, way
  Topic 1: link, time, good, diary, week, things, ni, lot, mom, day
  Topic 2: good, client, sopi, new, free, tony, advice, best, conversations, session
  Topic 3: session, story, life, human, great, things, characters, world, report, mood
  Topic 4: way, great, human, useful, interesting, more, own, character, similar, humans
  Topic 5: good, hera, human, help, questions, fields, things, something, tool, creative

Summary:
  num_topics  coherence_c_v
          2       0.744998
          3       0.750079
          4       0.752910
          5       0.756016
          6       0.753064

In [ ]:
tweets_eng_pos=[]
tweet_list=pos_tweets.Text.tolist()
english_vocab = set(w.lower() for w in words.words())
i=0
for text in tweet_list:
  for word in text.split(' '):
    #if i<10:
      #print(word)
    if (word.lower() not in english_vocab) or not(word.isalpha()):
      print(word)
      text=text.replace(word, '')
  tweets_eng_pos.append(text)

techforgood
💙
khanna
ces2024
@
curieuxexplorer

-model
patients
emotions

ones
bit.ly/3s185pi
@
careldr
@
@
@
shi4tech
@
heinzvhoenen
@
@
gvalan
@
drnikolova_rumi
@
sminaev2015
ces
ces24
ination
~♡
@
replying
mikaqvia
hugsss
🫂🫂
cuz
megumi
kagome
hugs
dániel
takács


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
lionell
|
🔎𝕏
|
xar
|
💙
@
mander
vikram
karve
@
selfhelp

worries
👇
wp.me/p1em7-6cr
stories
vikram
karve
pune
blogger
sheen18
@
web3


creators
visitors
revolutionalized
@

toptools
empowers



forbes./sites/lanceeliot/…


/
⚢
@
_ryy2
lets
togetherr🫂🫂🫂
mewen
|
frieren

@

funniest
fatalis

hands
いわたわし
@
tawashi_cb

なんなんこいつｗｗ

bjr
journals
bjr_radiology
bjr

imaging

inations
issam
naqa
bjr
articles
bit.ly/3puywft
highestself.
@
meets

steps



intertwines
tlored

ination
digitalempathy
iraconda
mel_vil


—but
|
artworks
ola


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
jyotirgamya
@
jyotirgamya_org


alized


munity-based

ination
well-being
neuroscience
jousie29


✨
@
thoughts
🫧
@

🎉
campgn

zealy

artists.🤏zealy.io/c/
–

ketplace
❤️🖼️
🛡|
stme|
udao
@
mdcode7350
@

@
devnationworld

alized
plans
monitoring
🤖
-powered
devices
diseases
alized

💻💊
incare
nem-trade
@
mshkh2002




rdrop
pdr
@
pdr_us

interesting—dr
neena
hder
ocugen
’

ocu400
shifa
precision—artificial


shifecision./
hana_and_b2network
🏴‍☠️
@
hanangeliaxyz
@

hana_and_b2network
🏴‍☠️
@
hanangeliaxyz
lfg
bro
@



✨
@
thoughts
🫧
@

🎉
campgn

zealy

artists.🤏zealy.io/c/
–

ketplace
conversations
waters




minds
souls
futureof
@
maverickp567

replying



@
maverickp567





tenshitemple


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
anya
@

👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
bodycalc
@
bodycalc

ive
issues


conversations

worries
download

pinc
™
@
pinc_

@
newsweek
real-world
applications

trials

higher-quality
possibilities
pinc
™
sciences
partners
utilized
nlp
patients
nodules
patients
weeks
newsweek./2023/12/08/-c…
wysocki
anya
@
anyatrades
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
jimcoastalluxuryproperty
pdr
@
pdr_us

interesting—dr
neena
hder
ocugen
’

ocu400
shifa
precision—artificial


shifecision./
🌛🌜
amnesiadevil



medicare


medicare
anya
𝕏
@
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
yukiaddiction
rnbow
@
yukiaddict



app
anya
@
anyatrades
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
highestself.
@
highestself


tools
gadgets
changers



insights

inative
@
jeff16

@
nsq_show
’
ramifications

psycho
online




anya
@
_anyastradess
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
anya

@

👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
szesz


✨
@

🌟
🌟



-generated
styles
senses
emotions

szesz


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
bikerbrian
anya
@
anyatrades
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
alpates




padmanaban
pichandi
pdr
@
pdr_us

interesting—dr
neena
hder
ocugen
’

ocu400
shifa
precision—artificial


shifecision./
anya
@
anyatrades
👀watch
lbph
sgn
pany

vygr
signs

artis
upfront
others
sngx
ngm
wulf
’
bodycalc
@
bodycalc



🌈🗣️



judgment-free
conversations
download

highestself.
@
highestself



humans



ries

@
breakp2037


creativity—just

endofyearcelebration

wele
conversations
endlessconvos

cherished
moments
pixel-perfect
emotion-rich


memoryrecreation
pelodoido
@
pelodoid0





toebut
@
toebut

replying

toebut
@
toebut

replying



✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
@
ililelph

replying

valerius
@
bob_everiman




asylums
💎
iggy
💎
@

replying
ineya_veganfood
@
gnq__
@
patrickstrud

lgb

khing_


✨
@

vibes🖤
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
khing_


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
khing_


✨
@

😊
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
khing_


✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
lionell
|
🔎𝕏
|
xar
|
💙
@
lionellhq

replying
🐵


✨
@


dly
look👀🫦
🫧
@

🎉
campgn

zealy

artists.🤏zealy.io/c/
–

ketplace
🐵


✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
millers|

🟣
adashe
@
millerstho

🌟
weling
minds
cheers
@

2024
ufot


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
ufot


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
ufot
@
blessing_u16821





ufot
@
blessing_u16821





nehan
sqr
@
madushka_nnehan





nehan


✨
@

🌟
🌟



-generated
styles
senses
emotions

nehan
sqr
@
madushka_nnehan

replying

@
zealy_io
nehan


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
ufot


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
ufot
@
blessing_u16821

replying

@
zealy_io
|areon
|
@


@
theothub

🤖

theothub./updates
plus+
results
coordination
aziz-zadeh
usc
chan


@
theothub

signatures
symptoms
biasing
🤖

theothub./updates
plus+

@
speaktrack

counseling

cbt

disorders
recoveryispossible
staystrong


✨
@

📸
@

👉.me
–

minds

ketplace
artwork


✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace



✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy


✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace



✨
@

heart.💙
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace


✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace



✨
@

vibes🖤
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators


✨
@

😊
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace


✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop


✨
@
🌟
minds
cheers
🎉✨
2024
b41m
❤️memecoin

replying
@
philipj23994175

replying



✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
@
philipj23994175

replying

@
philipj23994175

replying



✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
@
philipj23994175

replying

wonderfull


✨
@

🌟
🌟



-generated
styles
senses
emotions



✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop


✨
@
moments
ination
cheers
🌟
endofyearcelebration

replying
heartfelt.services
’


crypto
bodycalc
@






pals
download
🌈💬✨
rx
jia
@
jia_luo

@
iaslc
wclc23
mittee
multi-institutional

nc
nc-registry.org
🌎
colleagues
rx
nc
singapore
onclive.
@
onclive

jia_luo
@
danafarber
insights
chemo
wclc23
@
iaslc
lcsm
onclive./conference/world…
benita
_michaels
udao


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
benita
_michaels
udao


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
platzer
davis
@
peter_brit

dcvax
allsolidtumors
gbm
ulrike
herbrand
phd
vitro
bioassays


products

opportunities
outes
trials
alized

ination
alized
atmps
therapies

treatments
patients
algorithms
alized
one-size-fits-all
solutions
outes

therapies
aspects

algorithms
biokers
responses
treatments
therapies
vectors
therapies
diseases
disorders
certn
cancers
cells
genes
algorithms
sets
genomics
proteomics
patterns
relationships
methods
data-driven
researchers
cells

gene-editing
strategies

therapies

technologies
therapies

therapies
cutting-edge
technologies
criver./eureka/whats-hot-…
vito
@

vitodottv
@
domndomme

pics
vids
animations

bodycalc
@

🗣️
ive



download

selfcare
genderaffirmation
lisa🇺🇸🇺🇦
davis
@
peter_brit

dcvax
allsolidtumors
gbm
ulrike
herbrand
phd
vitro
bioassays


products

opportunities
outes
trials
alized

ination
alized
atmps
therapies

treatments
patients
algorithms
alized
one-size-fits-all
solutions
outes

therapies
aspects

algorithms
biokers
responses
treatments
therapies
vectors
therapies
diseases
disorders
certn
cancers
cells
genes
algorithms
sets
genomics
proteomics
patterns
relationships
methods
data-driven
researchers
cells

gene-editing
strategies

therapies

technologies
therapies

therapies
cutting-edge
technologies
criver./eureka/whats-hot-…
shib
🪖💰
@


highestself.
@



tech-savvy

bodycalc
@

🗣️




worries

anytime
genderaffirmation
downloadnow
visionquest2024
@

’


shrub🤪
davis
@
peter_brit

dcvax
allsolidtumors
gbm
ulrike
herbrand
phd
vitro
bioassays


products

opportunities
outes
trials
alized

ination
alized
atmps
therapies

treatments
patients
algorithms
alized
one-size-fits-all
solutions
outes

therapies
aspects

algorithms
biokers
responses
treatments
therapies
vectors
therapies
diseases
disorders
certn
cancers
cells
genes
algorithms
sets
genomics
proteomics
patterns
relationships
methods
data-driven
researchers
cells

gene-editing
strategies

therapies

technologies
therapies

therapies
cutting-edge
technologies
criver./eureka/whats-hot-…


✨
@

😊
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
@





@





rxopyywx


✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
rxopyywx
@







✨
@

🥹
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
💙
de.fi
@
ikhideasuelimen

heard




💙
de.fi


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
@





btc


@


bnb
cheaper
fees
retl

cryptohumor
bnb

@

surpasses
dors
guidelines
dors
tools



mri-based
tools
wearables
bodycalc
@

🗣️💭

panion
thoughts
caring


anytime
filters
download

selfcare
nostigma
highestself.
@

-tools


patterns

game-changer
ination
bodycalc
@


anytime
confidante

alized

download
selfcare

tek

stories

soooo
goooooood
wt
panies

employees
problems


@
guydealership

sales
vs

@


identifies
emotions

trned
game-changer
psycho

psycho
pennycrypto
@


rekable
insights
📬
highestself.
@





inative
algorithms
custom-fit

fingertips
🤖❤️
ination
alizedcare
@


you💙
dm
me⭐
edu
@







✨
@

😊
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
edu


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
nsb6
@
xwnvna





akobundu
❤️
memecoin
logx
🟣
🏴‍☠️
@





trends
llc
@
ytzww

trends
plans

vr

gene-editing
breakthroughs
telemedicine
alized
tech-enhanced

care2024
futureof
ytrendsworldwidellc

mfon
|
@
edge_protocol


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
mfon
|
@
edge_protocol


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
mfon
|
@
edge_protocol
@





mfon
|
@
edge_protocol


✨
@

🌟
🌟



-generated
styles
senses
emotions

mfon
|
@
edge_protocol


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
@

therealworld_
hours
ships
expenses

bills


matters

things

nerdy
@

🚀🩺

biotech
🧬
🔗
[
mlmadesimple.in/2023/12/30/a…
]
🤖

dors


updates

feats
🌐💡
biotechination
techtrends2023
breakingnews
letsconnect

artificialintelligence
bodycalc
@

🙋‍♀️


gender-affirming


download
🤗✨
dipesh
haldar
@

🤖
mind-bending

devfestnagpur
machines
creative…
memes

this.
devfestnagpur2023
dfn2023
dfnagpur2023
p567


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
p567


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
p567


✨
@

🌟
🌟



-generated
styles
senses
emotions

p567


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop

lyla✨️😎

@




lyla✨️😎
@

goood
afternoon~
pliments
photos
has~
conversations

memories
detl
summers

avenues

memoryrecreation
ination
toebut


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators

micaela
@
ishadowheart


bodycalc
@




download

selfcare

edu


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
@





edu


✨
@

🌟
🌟



-generated
styles
senses
emotions

edet
@
adashe
@





@





conversations

cherished
memories



memoryrecreation
futurehealing
etf3
@







✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
benita
_michaels
udao


✨
@

🌟
🌟



-generated
styles
senses
emotions

benita
_michaels
udao


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
howell
🌊📘
@



putational
neuroscience
llm
@
limbic_
nhs
clinics


khosla
@

chats
apps
@
limbic_
uses
putational
neuroscience
llm

nhs
clinics
larger
studies
human-based

wsj./tech//employers-ar…
seragon
biosciences
seragonbio



genomics
approaches

therapies
-alized
tloring
age-related
conditions
doggoinamo
ledgity
rdrop
arthera
💖


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
uniport


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy


✨
@


dly
look👀🫦
🫧
@

🎉
campgn

zealy

artists.🤏zealy.io/c/
–

ketplace
uniport
@
uniport152193





uniport


✨
@

🌟
🌟



-generated
styles
senses
emotions

uniport


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
testnet


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
memmo.stark
|
web3go
|
❤️
|


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
crypto
@
cryptogems_1000


......
yondry
leon_santameme


✨
@

🌟
ine


🎨
-generated
🧑‍🎨
others
👉.me
beancreator
creators
elena
panettieri
@


precisionmedicine
👏a
liver-directed

hcc
dr.
elena
panettieri
@
🔗oaepublish./articles/down…
@


inative
🌟📩

@


ros

ination

@

years



ros
machines
algorithms
empathetic
programming

parbagem
💙
de.fi


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
coinrt
@





highestself.
@




landscapes🌐


thoughts

testnet


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
testnet
@
generalico87714





testnet


✨
@

🌟
🌟



-generated
styles
senses
emotions

testnet


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
rootz
rootz
@




hours
collection🖤
rootz
@




hours
collection🖤
rootz
@




hours
collection🖤


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop



✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace


bio
@

crispr

crispr
singularityhub./2023/12/2…
uk
beta-thalassemia
fda
medicines

broader
crispr
challenges
dna-snipping
risks
mutations
cancer-causing
genes
parts

editing
tools
off-target
crispr
variants
databases
advancements
crispr-like
mechanisms
eukaryotes
broader
editing
tools
oute
crispr
applications
biotechnology
crispr
incare
medtwitter
techbio

rootz
@




hours
collection🖤
highestself.
@



whispers
counterparts

techforgood
josé
cordeiro
transvision
humanityplus
@
cordeiro

josé
cordeiro
advances
things
technologies
crispr

mrna

billions


he/him
diceand

nft
grifters
ads

nfts
pennies

generators
bodycalc
@




gn


worries
download
💪🌈
selfcare
dániel
takács


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
dániel
takács
@





dániel
takács


✨
@

🌟
🌟



-generated
styles
senses
emotions

nhs
libraries
bmj
@
bmj_pany

@
gpsych_bmj
identifies
features
genres


responses
🤖💙
bit.ly/4ancmkc


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
@
cutemickel





@
cutemickel




✨
@

🌟
🌟



-generated
styles
senses
emotions



✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
andreico69
@





capala
||
🥒🖼️❤️
@





capala
||
🥒🖼️❤️


✨
@

🌟
🌟



-generated
styles
senses
emotions

capala
||
🥒🖼️❤️


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop


✨
@

vibes🖤
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
toebut
@
toebut


conversations


panion



panion

❤️
memecoin
@





❤️
memecoin


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
granseal
|
@

obeyart



greatest
artists

careers
@
ccim_official

mobio
ccim
👩‍⚕️mobio

psycho
patients
wtlist
services
alisation

productiveplace.
@


🚀

enthusiasts
possibilities
-guided
self-discovery
thoughts
🤖💬
bit.ly/48ubhkn
|areon
|
@





sheena
campbell
munities
@
care_ca

ination
partnerships
enableeveryone

@
bonocleinc
@
dateabilityapp
gewinner
@
mycrocast
seleste
spero
careers
vibrnt_
breen
associates
@
skillsquirrel
designbycappella
fightertalks
fightertalks

🚑
next-gen

chats

athletes
risks
real-time
strategies
sportstech
injuryprevention
pabi
asgardx


✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace

cybersecurity
@

theshrestharaj
int-eresting
tweets
cyber-eruption
....


✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace

wolf_of_crypto_world


✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
wolf_of_crypto_world


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
wolf_of_crypto_world
@


@
zealy_io
light-it
@
lightit_io

@
fr_cassarino
strongest




coaches


at-home

light-it
@
lightit_io

panelists
trends
ketamine
psychedelic


llms
blog
mn
takeaways
lightit.io/blog/inations-…
p🥂🍾
adtoomuch💌
@
adtoomuch

✨vendo
acquisto
remington
giugno
voi
remington

s8593
•sensore
ottimizza
costantemente
prevenire
danni
capelli
•display
digitale
lcd
regolazione
temperatura
impostazioni
•riscaldamento
rapido
secondi
indicatore
sonoro
•piastre
pressione
uniforme
@

alse_
alse_
ments
😥
highestself.
@



hands
minds
🤝🩺💡
ination
techforwellness
🍀
@


prompts
points
detled
12-week
goals
dly
actions
goals
“
12-week
[
]
dly
actions.
”
goals
“
time-bound
goals
12-week
week.
/
indicators
indicators
goals
[
goals
tracking
system.
”
“
items
tactics.
”
“
workweek
goals
[
goals
blocks
blocks
blocks.
”
/
goals
resources

@

puter

humans
entertnment
applications
simulated
trning

humans
alized

experiences


✨
@

heart.💙
🫧
@

🎉
campgn

zealy

artists
🤏zealy.io/c/
–

ketplace
p3
alamgir


✨
@

🎉

zealy
campgn
contributors

skills
inate
rewards
wins
❤️
detls
👉join
zealy.io/c/
xzealy
rdrop
@





curosity
@
curosity

advancements

roics
inations
fields




curosity.//-and-rob…
aakash
sharma
𝕏
@

elonmuskaoc
@
elonmusk

expertise

brn

cells
purposes
injuries
acl
pcl
areas
standards
bodies
rekable
practices
ayurveda
earlier
civilizations
deeper
capabilities


✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace

stme
@
thetpng129361





bodycalc
@

💬talk



📱✨

gn
followers
download
genderaffirming

crypto
@





toebut
@
toebut


toebut
@
toebut





ekong
adashe
@
blezola

.me
creators
memberships
deeper
connections
munities
experiences
@

ekong
adashe
@
blezola

ekong
adashe
@
blezola


@
zealy_io
mel_vil

summerinthesim
@
bri_guy_
@

yondry
leon_santameme
@
yondryleon





shitu850
adex
||
arthera
@





bodycalc
@

🌈📱



download
selfcare

povshenko
@
creatorharmony


emotions
futuretech
empathetic

inationinpsychology
🆔
⚛️imran
hossn
@







✨
@

🎨
ranks
zealy
leaderboard
xzealy
🌟
xp
🥈
xp
🥉
xp
🌟
4th-10th
11th-200th
xp
earners
empty-handed
begins
zealy.io/c/
bodycalc
@

🚀




download
conversations
trans

aramboy.bnb
rdrop
dp
🧡
memecoin
@
rdropdp







✨
@

🎄


🌟
moments
holidays

merrychristmas
holidayjoy
bodycalc
@





download
mrzizo
@







✨
@

🎉

zealy
campgn
👉
zealy.io/c/

.me
✨
ketplace

bodycalc
@

🌈💬




download
conversations
newfound
confidence.📲✨
wellnessrevolution
cryptototo💙de.fi
🌿
☁️






medi-connect
@


medi-connect
front-row
real-time
data-driven
isions
improved

standards

insights
cardiologists
real-time
stme
@
zhekaba003





bodycalc
@




anytime

worries
download
💜🦋
transformwithtransition





fasal
@

cars
’
game-changer
🚗

counseling
restaurants
tesla
vehicles
experiences
planning
challenges
futureisautonomous
fsd
autonomousvehicles
erb
@

andyohlbaum
@
@
rargulati
@

applications


relationships
tips
issues
interests


✨
@

🌈

tiktok./
@


🤖🎨

zealy
campgn

👉
zealy.io/c/
ketplace


@

🌟🚀

’


reassurance.
mindset

startup
b🍑🐕🐱🍀🤩🪐👽🛸
@



hana_and_b2network
🏴‍☠️
@
hanangeliaxyz





@

venturetwins


triggers

blocks
app
areas
results


@


you💙
dm
me⭐
@


⭐
forrester
@

blueveedesign
management/it
copd

programming/
years
🤣
dubugras
thelaurafiuza



applications
leaps
bayer
@

🌐

In [ ]:
tweets_eng_neu=[]
tweet_list=neu_tweets.Text.tolist()
i=0
for text in tweet_list:
  for word in text.split(' '):
    #if i<10:
      #print(word)
    if (word.lower() not in english_vocab) or not(word.isalpha()):
      print(word)
      text=text.replace(word, '')
  tweets_eng_neu.append(text)

Streaming output truncated to the last 5000 lines.



updates

@

ethanjkemp
@
sama
github

fast-uptake
topics
—

jokes
@
titletrophy

taking.
bargn
hours


startup

domnname
@



@


fanfictions
mau❄️⛄
@

@


replikq

bros

slabodnick
@


panies


....
dsuke
sasajima
英語学習
@

【
】
知り合いである
’


dsuke
sasajima
英語学習
@

【
ぼんやり
’


bmj

informatics

🔬
human-
ision-making

ision
tumour
bit.ly/44ddcwy
@
lsveikata
inmedicine
digipheno
@





theswaddle./inadequate-me…
domo
@

@
scottjohnson
spreadsheet
cells

deaner444
@
deanehenryson



app
google
tic-



selfcare

freeapp
coolapps
asmr

@



reflections
tweets
thoughts
memes
brnstorm



phd
@

tech-infused



bigdataanalyticsnews./cha…
bigdata
darrel
aasekera
@

tech-infused



catboots_

rowngarnbii
@
shoe0nhead
@
michaelmalice

“

るきの
@
hsgolmskwqfkn6j

´・ω・
安江工務店
株主優待制度を導入
パルｈｄ
ハニーズｈｄ
ファマライズ
サイトリ細研
cytori
技術の特許取得
チェンジｈｄ
rafiq
@

tech-infused



stéphane
bellanger
@

tech-infused



dlvr.it/ss0qj3
fzan
afzal
@






services

resources
expertise
plement
fzan
afzal
@

models

amounts

transcripts
evidence-based
insights


concerns
alized
fzan
afzal
@

avlability

barriers
limitations
individuals

internet



anytime

j.g
norsa
@
mattnorsa

results

tryna

m.
lockwood
@


notes
retweet
ephrm
@

schmoneysage


vc
@
teach_vc




problems
....

responses
ebrahim




ive
responses
thoughts
emotions
self-reflection
guided
exercises

@
theptsnetwork



website
physio
[
]
shlega
@


jokes
automate
workflow
power…lnkd.in/ektux7x9
gruchow
@
matthewgruchow

psychedelic


matthewgruchow.substack./…
psychedelics

ptsd
religiousstudies
deaner444
@
deanehenryson



app
google
tic-



selfcare

freeapp
coolapps
asmr


deaner444
@
deanehenryson



ex-girl
app
google
tic-



selfcare

freeapp
coolapps
asmr

@



yoni
ashar
@


psycho
fidelity/adherence
eg

de-identified

transcripts
zety
@



@
romikamofficial

thoughts
self-
questions
prompts

@

role-playing

📌approx


app
clients


challenges
𝕊𝕍𝔼ℕ
||
天
@


character.

methods
deaner444
@
deanehenryson



app
google
tic-

believeinmyself


selfcare

freeapp
coolapps
asmr

ronnie
reyes
ronnieffreyes

results
differences
coaches




professional…lnkd.in/g7qdhe_y
deaner444
@
deanehenryson




app
google
tic-



selfcare

freeapp
coolapps
asmr

@


+scholar

”
scott-trimble
@
anna_d_scott

careers
etc
‘
’


@
seen_stories

danmurrayserter


@
seen_stories




questions


shares



iamseen
artificialintelligence




@
seen_stories




questions


shares



iamseen
artificialintelligence




deaner444
@
deanehenryson



ive
app
google
tic-

ive


selfcare

freeapp
coolapps
asmr

gulliver
@

copywriter
mfa

website
startup

chats
deaner444
@
deanehenryson



app
google
tic-



selfcare

freeapp
coolapps
asmr

visio
inc.
@

nlrg_it
@
d08890


mousseau🇫🇷🇨🇦
@
alphalackey

p5
thieves


@
techbros4jb

techbros4jb
@
aaronestel

thoughts
capabilities

alternatives
@
aaronestel

_stevenfan
hm
ifs
kinda


app
modalities
@

@
tommybefamous
@
cobratate


ky
@
democraciatwork

drnsycs

means

hours

yash
@

drnsycs


otasa
@

webinar


mlchi.mp/otasa.org.za/webi…
🧠
godoy
🧠
@
jcgodoy9

psicoterapia
ia
🤖

apps

programs

programs
unvetted
buff.ly/441gpdm
@
sciam
@


glp-1
glucagon
dopamine
reuptake
opioid
trimova

ll
ipo
spac
deaner444
@
deanehenryson



google
tic-



selfcare

freeapp
coolapps
asmr

cdetweets

-backed
tools

workers
stressors
@
weareonedigital
roberts
“
chats
individuals
employer-sponsored

@
cnbc
cnbc./2023/06/01/heres-ho…
deaner444
@
deanehenryson



app
google
tic-

lowselfessteem
asmr
coolapps
freeapp

selfcare



tx
@
b3ingth3r3



solutions💉
@

stefankertesz
@
ginakolata
@

symptoms
certn
drugs


pn
xans
@
blaqueword

shatired


@
thenightdrivers

eml/textual
exchanges



loved/eased

deaner444
@
deanehenryson



app
google
tic-



selfcare

freeapp
coolapps
asmr

deaner444
@
deanehenryson




app
google
tic-



selfcare

freeapp
coolapps
asmr

🎼
@

bipolarsafe./blog/f/a-son…

electroconvulsive

ect

deaner444
@
deanehenryson



ex-girl
app
google
tic-



selfcare

freeapp
coolapps
asmr

jmir
publications
jmirpub





counseling
spooool
mentions
jmirpub
goforth
@
stephengoforth

articles

you—from

tinyurl./5n8tbj4a



relationships
deaner444
@
deanehenryson




app
google
tic-

bored


selfcare

freeapp
coolapps
asmr

riseangle
@
riseanglebeat

vienna-based
nyra

neuro-
investors
@
mmvglobal
@
wellingtonvc
riseangle

gaming💎riseangle.
vc

eu-startups./2023/06/vien…
@






modalities

elne
huber
@



@
carlessdavid
techadjacentlurker
@




doubts
@


oceangate
subine
deaner444
@
deanehenryson



app
google
tic-



selfcare

freeapp
coolapps
asmr

tabansi
@

feels


questions
wt
deaner444
@
deanehenryson



app
google
tic-



selfcare

freeapp
coolapps
asmr
myman

union-tribune
@
sdutopinion

ades-long
experiences
partners


jme
bichelman
🤖🧠
sandiegouniontribune./opi…
thriveworks
thriveworks


services


connection-driven
human-centered
services
perspectives
bit.ly/3qzmppe
deaner444
@
deanehenryson



app
google
tic-

justs


selfcare

freeapp
coolapps
asmr

randahl
@

gatewaypundit


friedman
@


substack

yt

@
savetonotion

database
tags
[


]
sathya
@

alliekmiller
@
savetonotion


deaner444
@
deanehenryson



app
google
tic-



selfcare

freeapp
coolapp
asmr

deaner444
@
deanehenryson



app
google
tic-

verbalassault


selfcare

freeapp
coolapps
asmr

droege
@



@


apps

programs

programs
unvetted
trib.al/z1zibsc
@




b4



cheaper
deaner444
@
deanehenryson


love-sick
app
google
tic-



selfcare

freeapp
coolapps
asmr
noregrets

choi
@



underrated
emanuel
stefancu
@



things
@
elonmusk
@
sama
syogren
🐀
@

syogren
@
ebthen

rules
essays
sources
deaner444
@
deanehenryson




app
google
tic-


selfcare


freeapp
coolapps
asmr

@
rynofo

taylorburrowes


xyz
@


apps

programs

programs
unvetted
trib.al/1tfhk5s
jowyang

davidspinks
types


systems



tharpists
heypi

tools


professionals
@
hydrarare

idk

cbt

deaner444
@
deanehenryson



app
google
tic-



selfcare

freeapp
coolapps

َlyle
🍭
@


’
pov

sheinberg
ph.d.
@


chats


apps

programs

programs
unvetted
bit.ly/42ofv1c
randahl
@

endwokeness

neuro
🧠🗺️
@

online
prof.

learnings
n=2400
cbt
pdt
+
thoughts

neuro
|
world-wide.org/seminar/9114
@

lazlowoodbine42
@
horatioyuletide
@
jtylerhagen


🇵🇸
🍉
@

crulge
@
_eric_reinhart



disorders
plicates
text-based
input/output

utis
@
titletrophy

talking.
instalments


domnname
psycho
domnnameforsale

4open
babyagi
brinks
@


snes
’
@
sen7ience

emls

dokja
varepsilon
@
var_epsilon

tradfischizo
“

”
bro
“
”

ui

clarke
@





jazeera
ireland


services
canisgallicus./2023/05/02…
@
canisgallicus
⋆
✭
✧
𝐀𝐋𝐄𝐗𝐈𝐒
𝐉𝐀𝐃𝐄
✧
✭
⋆
@
jupitergrl_


shit

lmao
emls
@

@
@
ilyasut
@
sama
influencers
professionals

psychologists

gonzalez
@
elcopymaster

psicólogo
puede
más
euros/sesión
pero

puede
escuchar
tus
problemas
juzgarte
así

puede
convertirse
psicólogo
gratuito
bigford
@


spends
’
services




jacquesthibs

livgorton
@
basedbeffjezos
hahaha
’
“



”
⛈
@

@
beingkelsey
@
cyberphunkisms
things
ve



sudo
@



relationships


kache
yacine
@


🐈
@



lives
@
danmurrayserter




@
yuanmunity

klotzman
@
uofcalifornia



ml
saneliswa
@

dukeofqomintaba


😂
saurabh
💊🏏🏀📑
@

idstewardship
@
idvilchez
@
pharmacyposts
kisgenuf
@
lisdpharmd
@
jaycdoesid
@
mmpharmd
@
paulsaxmd
@
idsamededcop
@


abx
ent
isions
....
@


seconds
aspects


👉
threads
linkedin
⚡️
@
brendanhufford

skstock
go-to

minutes
bierschbach


citations
articles

tumblr

@
danmurrayserter




aanchal
@




@

implications
fields
blogging
practices


mindmatters./2023/06/the-e…


clarke
@





jazeera
ireland


services
canisgallicus./2023/05/02…
@
canisgallicus
torvesin
nowkleged
🧠
@

amandanat


mcgreevy
|
copywriter
@

chrisldyson

business…


delaney
mcguire
@



trn

-like
responses
prompts

delaney
mcguire
@



-like

steps


dances
dances



talkspace
pamphlets
@
danmurrayserter




tidi
🦝
@



altman
devs

@
danmurrayserter




dr
@
ashwaryaagadwa1


bucks
chat-

judgement
😝

humans
@

memdot
@
gedroberts
solopreneur
@
danmurrayserter


nitter.net/danmurrayserter/…
replies
@
danmurrayserter




@

poppy007
@
danmurrayserter
mem./p/j9f5zv2xw5cwyog70fo…
🪄
-generated
sumy


@

yalexos


psycho
incensed
individuals




snoozewala
@




professionals
starovk
@



cogburn
@
systemictexism

jakewisk
’
centerforclinicalexcellence.…
…how
munication
%


yoshifumi
murakami
@

がメンタルヘルス業界にも大きな影響を与えているという記事。プロのセラピストのほうがもちろん上だけど、無料で待ち時間もいらないというのは確かに強い。




|
|
jazeera
aljazeera./economy/2023/4…

@

’




llm

unavlable
@
selfmademen7
|
mindset
@

danmurrayserter




’


beatriz
@
biaklimeck

é
tão
fácil
quando
alguém
usou

pra
traduzir
terapia
é
”
é
má
tradução
“

”
cavaleiro
ia
@

terapia
é
custando
ms
real/hora
🛑
felizmente
pode
transfor

num
terapeuta
gratuito.🚀
eis

sua
saúde

🦾
what_now
@
singularfate

danmurrayserter
@
horlayer7
isn

labor-force

@

danmurrayserter


t.
lofaro
jr.
@


me/cfs
pacing
cfs/me
ponents
techniques
cognitive-behavioral

cbt

mecfs
@

danmurrayserter


services

cheaper


’
@

imprived
@
dragonsjet
nvm

websites
😭
@
danmurrayserter




leveque
@

⚠️



services

self-
thoughts
krista
steele
@

almakatsu
@
intlspymuseum

secrets
pany
“



’
.
”
op
sathya
@

danmurrayserter
@
savetonotion


simo
@
jsachael


ceasefire
panndder


couples

cuimc
gov
cumc_gca

dr.
kimmel
@
columbiapsych


takeaways
bit.ly/3qo4ixh
vasilakos
@

danmurrayserter





@
bassaba_



wired./story/for-some-aut…
@


beneran
ngasih
yg
+
jelas
tapi

dia
selalu
nyaranin
ke

curhatannya
dirasa
terlalu
lol
unavlable
@
danmurrayserter




@



leveque
@

self-

@
cuckoo_code

first-class


lifehack
ia
@

solopreneur
’
im


shit
ll
melvin
’
@






mr.
micawber
@

skynet


😂


4
skynet
machines

instagram./p/ctdyg6prtf9/…
torrhl🧵
@

startups

-


wt
սարգիս
@
sakogudjelian

’

psycho
relationships
plexity
’
frustrations
limitations


solopreneur
@






@
monkeerhstudio




solopreneur
@






schaar
e/big
🦅🌻
@





solopreneur
@






hina
@
hinapublish




ones
replaces
humans
‘
’

solopreneur
@






🇺🇦evan
kirstel
b2b
techfluencer
@


%
participants
docs-api./is--an-e…
@
frank_c_t

voices



solopreneur
@






soomi
yoo
@

-based


soomi
yoo
@


’
tone/facial
expressions/body
/munication
ncbi.nlm.nih.gov/pmc/article…
soomi
yoo
@


reasons
privacy/
“
”

guarantees



solopreneur
@






megbatphoto
@
megbatphoto




solopreneur
@






ku
manish
@

iuditg
tweets



adansonii
@


convo


solopreneur
@






iana
@

theholisticpsyc


avoidant
@
moonstrucktwolf

perkinshammer


iana
@

asdrubalivan
@
theholisticpsyc


eamonn
@

solopreneur
@
readwise
@
savetonotion


nr
@
disabilitystor1


deepest
fears
traumas
emotions
others
technocultists

selves

solopreneur
@






steph
@

europe

weeks
’



solopreneur
@






adaeze👩‍🍳👸
@

favourdiamen

@

callmehejrene
@
solopreneur
mem./p/3q5skj1qrlk87n2xy…
🪄
-generated
sumy

-based



judgment-free
users
@

michurosso
@
solopreneur
mem./p/gxnqo1pey56ctvrtmxt…
🪄
-generated
sumy

-based



judgment-free
users
𝐌𝐢𝐡𝐚𝐢
𝐂
@

bro
💀💀💀


bitches

solopreneur
@






verdantwind
@

memestrategies
@
solopreneur



assisted
biased

giordano



self-help
books
cases

solopreneur
@






♠️
@

’



solopreneur
@






@
heylukegibson

orgone1
@
jonathanshedler
’

things
’


’
girlfroms



degen
@

bowtiedtetra
😭


🤖
pistols
md

bhanu
@





@
heylukegibson

orgone1
@
jonathanshedler
’
’


‘
tht
’
online

ster
domn-specific
vorick
@


things
corpos

models
huggingface.co/thebloke/guan…
huggingface.co/thebloke/nous…
vegeta
@

solopreneur
@
savetonotion


@

gavinwhittaker
@
solopreneur
mem./p/wgr38gp3kcg1aqyujki…
🪄
-generated
sumy

-based



judgment-free
users
@

gavinwhittaker
@
solopreneur
mem./p/hxo179yb1yw71awfsfl…
🪄
-generated
sumy

-based



judgment-free
users
hoos
keting
@




solopreneur
@






@

potabogo
@
solopreneur
mem./p/tj96a6qsx3e7xqnxzmb…
🪄
-generated
sumy

-based



judgment-free
users
natasha
@







solopreneur
@

problems
dr.
tessa
dr.
tessa

empathetic


solopreneur
@







@


speecb

patients
speechcare./how-yo…
✦
thom
@

’


pastebin./mv6heipu
foopock
@
thefoopock

blockers

matsakis
@




users
topics
@

zuckerzucker3
@
raphisu
genau
hierfür
fehlt
der
nachweis
pei
definiert
anders
auch
wenn
sich
hier
über

immerhin
auf
eine
sehr
große
anzahl
von
zugreifen
kann
lustig
gemacht

zu
der
schlussfolgerung
dass
jedes
auch
eine
gene-
darstellt
objektiver
gegenbeweis
blieb
oben
genannte
vergleiche
genauso
wie
behauptung
biontech
hätte
diese
aussage
nicht
veröffentlicht
tasneem
nashrulla
@

startups


semafor./article/06/02/20…
@
semafor
@

🟡
startups


@
reports
nitsuj


cama
🦊🏳️‍⚧️
@

avo8
@
chrismumbeck

things

processes
🇺🇦
🇮🇱
borukhovich
@
tks
theshot

@
@
jimbojoyce
@
justinnordenmd
🤖
investments
🤖

learningmodels
dr.
watson
🤖
vehicles
rx
mothingbird
@

lyle
kruger
@




lives🧵

deaner444
@


plans
app
google
tic-

plans
relationships





barbiegirl
⸆⸉🐰💜⁷
🏳️‍🌈
🔞
@
coworker


@
jmotivator


puter

pointers
futures


altfutures./can-chat--…
reynolds
jimreynoldsuk

benefits
/medical
applications
risks
expectations/security

experiences
journorequest
replika

diroma06
ive

dudes
ip
unpd


@
startup

episodes
r.
rastapopoulos
@
businessbarista

plete

drunk-texting

app
ᖇᗝᗝᔕᗴᐯᗴᒪ丅
丅ᗴᖇᖇꭵᗴᖇᔕ
@
rterriers

bans
roseys
theyby
@

<
<


@
years

—

towardsdatascience./ten-y…
—————

datascientists
artificalintelligence
3
4
bigdata
datascience
nlproc
nlu
nlg
neuralnetworks
putervision
ghana
g🌸
@


pre
kishun
@


@

sesh
alexa
’
alexa


isml
@
prompts

ismlsaleem.gumroad./l/p…


lioat
@




lioat./blog/2023/05/ch…
@
made_by_chris
leaders

pens


services

panionship

..

sof
sof
sof
@


hh_babykeys
hh_babykeys
sci-fi
ics

！


mjdjourney
artworks
gc
agi
stablediffusion
chilloutmix
lfg
nftmunity
nfts
nftarts
web3
hk
jx
@
pany
providers
roles


abcvisuals
iartcafe
crypto
launches
link.medium./ygg1nfhy7zb
abcvisuals
vr
virtualreality

blockchn
cryptocurrency


avax
zuzka
@

je
moje

fr
noor
@
follownoors

bestie

”
🫶🏼
ination
@
tcd_ination




drivetime
rte.ie/radio/radio1/clips/22…
kujo九条👻
@

inflicted



@


김elisabetta
🇵🇸
miyane
@

things


tools

sef
@

oakmauler
@
smellsbadinhere


@
gewoon
levensvragen
aan
aan

alles

@


wheeeeeeeeeeeee
@
trader_koala
goodnight
gustavo
schulz
gattino
@
two-hour


10:00-12:00
forms.gle/rgpcpcifmdhf1ghd8
@


luís
sousa
@


processing
jokes

4
dami
🍉⚖️🍉
@


@

passive-aggressive
notes
@




wasn
’
@
robo



artificialintelligence

sang-rak
@


questions


@
ronald_vanloon
@
nigewillson
@



chats

@

’

🥔
@


ex-girl

reads
squirle
@
jiwowoong


fanfics
jiwoong
im
@
tradermadness




moni
vnue
dwac
mmex
innd
muln
frc
epaz
idvv
rshn
ayrey

families
strght

@

@
drdanielkimmel

fr

frustrations
@
pisackson
bit.ly/3q6wu19


estoy
cansada
@



deaner444
@


app
google
tic-

secretcrush
secretrelationships




hannah
@



spa/

@
fb

writingmunity
ledo
@
-assisted
journaling
purposes

selfreflection
pub.towards.net/unleashing…
kage🦇🔊
@
cryptokage
_shubhangiii_




@
joncoopertweets
hormones

hrt
transgender
women
hrt
transgender
women
anti-androgen
medications
hormones
changes
changes

transgender
women
procedures
chondrolaryngoplasty
transgender
women
deaner444
@



app
google
tic-




relationships

@
cloutedmind
nft
bros

nfts
wallets
znab
@


🔪
@

>

🤍
@
michaelfulwiler


azam
alonzy
@
shouq_beauty
إلى
الأخوه
والأخوات،
إلى
الذين
يعانون
من
الإكتئاب
خاصة
واللذين
يحاولوا
التعرف
على
ذاتهم
بشكل
أعمق
عامة
تجربة
برنامج

وأن
تطلب
منه
تحليلك
باستخدام

سؤال
تلو
الأخر
له
أثر
مجتمعي
وإقتصادي
وليس
شخصي
فحسب
𝕸𝖆𝖌𝖎
@

deaner444
@






|
counsellor
@



client-
uses


tools



rundown

@
therundown
@
_ericelliott





resources

saitan
@
therundown
@
_ericelliott


resources



freud
etc
rebjorn
@


agi

3
4
5
piped.video/3bgdhhxj-cu
phd
lpc
cpcs
@
talk2spirit
therundown
@
_ericelliott


resource/referral

dr.
asbury-kimmel
phd
@
victoria_asbury


@
deathsexmoney
@
annasale



awarenessweek
kimmel
@


columbiapsychiatry.org/news/…
kimmel
@


columbiapsychiatry.org/news/…
@
[
mpc
]



professionals

well-being


@
badfor3ducation


jyotirgamya
@
low-cost
chats



online
psychologists


@
__
./--m…
artificialintelligence


awarenessweek
herzog-evans
@
profmevans

ellis

emotivo-rationnelle
thérapie
et
rationnelle
thérapie
et
rationnelle
kanekal
gautham
@
]


hypoxic
ine
countries
inplete
suri
☀️
@


snato
she/her


'medicine
@
samoskal
jdaviesphd

re-enforcing
'
factors
ksensei
👹🧬👾
@
frankdegods


qbri
smes
@
qbridigital




experts





jodelo
@


cleardata
cleardatacloud


chats

—but
implications
standards
users

@
scobleizer

’
clarke
@




jazeera
ireland


services
canisgallicus./2023/05/02…
@
canisgallicus
aya✿
@

✖️


✔️
paulo
fratoni
@




experts
./--m…
@
__
muhamamd-siddique
@
muhamamdsiddiq1


experts
buzer./should-you-u…
andrews
zacharylipton

thoughts
feelings
experiences

qbri
smes
@
qbridigital




experts
ift.tt/4y2oxib
🇺🇦evan
kirstel
b2b
techfluencer
@




experts

apple.news/amx2ltfhwrt-wusav…
furlane
@
furlanegrant




experts




flip.it/p8f4s8
dly
app
@


outshines
humans

tests
|
|

|
app
ift.tt/iidsquy
@
jenny____

“

”
-esque
cases
posts

@
jenny____

things
’
ve

tears
qbri
smes
@
qbridigital




experts
ift.tt/frp0nw1
businessweek
@
bw




wasn
’
covyeau
cfp®
@
mom

bio

…
abcvisuals
iartcafe
relationships
bonds
link.medium./jejlpprfkzb
abcvisuals
vr
virtualreality

blockchn
cryptocurrency


relationships
khrul
@



nemo
artgen001

%
participants
docs-api./
p=4843



timoshenko
@
@
relationships


chats

4
relationships


datingadvice
tips
dateideas

closest
admins
certn
teachers


frustrating
certn
tides
*
uses
*
excerpts
*

𝖌𝖔𝖏𝖔
𝖘𝖆𝖙𝖔𝖗𝖚
𓂀
@

siddhant
pasricha
@
sidist_playsure


whatsapp
@
goosegaymes

aldoul
@




aje.io/v08671
@
ajenglish
tehrani
@

%
participants
buff.ly/3lx6fsa

nlp
alexa
bigdata
exworld
@

%
participants
zdnet./article/is-…
perspectives
@

artificalintelligence


emotions

perspectivesonliving./482…
dtm
@
catnews
crypto

%
participants
cryptoandtechnews./is-cha…
esse
esseisolutions

%
participants
ift.tt/xwsp9rl
@

%
participants
ift.tt/fpxuzhu
dba
@
dougbrowndba

%
participants
dlvr.it/snqt0t
@
disagreeable_i
keithfrankish
@
r_conandavies

𝗠𝗮𝗻𝗼𝗷
𝗡𝗮𝘆𝗮𝗸
@
cbt


sania
@


requirements
dougan
@




rt
☃️
@
getttttyyyy
tonui_yebei

>
>
@
poweredbylean


@
rowancheung
joys



bills
mwahaha
mia
ⓥ
@




years
nature./articles/d41586-0…
@

tuesdaythoughts
guys


キッスランド
🍄
@
snapchat


>
>
𝕂𝕚𝕡𝕡𝕖𝕣
@
clovensun
fears
shit
ent
lmao

orisha
@


iphone6prosandcons
iphone6proscons



’


experts
dlvr.it/snk7lv
s.
@
bfr






parallels
bfr

bfr
muscles
hypoxic
stronger


certn

resources
patterns
strategies

mcr


e.g.
self-talk

difficulties
mechanisms
ier
strategies
e.g.
restructuring
mechanisms
strategies
well-being


graber-stiehl
@


headlines



cognitivebehavioral
cbt
nature./articles/d41586-0…

@
theptsnetwork

ranking

google
physio
[
]
@


davidson
slimbreezy
@

bernat
lópez
@

-
apps
70-year

questions
nature./articles/d41586-0…
minds
inations




clients
non-judg
thoughts
feelings
—-
🦖
@
neuro_data
@
isdedal
@
“
+

”
justinstillness
@
justindeschamps
@
justnstillness

feet
gerson

earlier
socialbob
@

writers
machines
🎬🤖✍️
tiktok
🌈
📝🕵️‍♂️

cash-burning
🤖💸
primat-eyes
👀

🐵🔬
sugar-powered
🍬💉
bresler
@


questions
>
>
>
>
>
>
yésica
nosica
@


cel
mellor
@
tech-philosoph
@
tante
redet
mit
menschen
von
„
corparate

“
über
funktionsweise
und
vor
auswirkungen
von

auf
unsere
gesellschaft
zwei
stunden
lang
sehr
sehr
sehr
hörenswert
nakay
ⓥⓐ
🏴🇵🇸🇨🇩🇸🇩🇦🇲🇬🇾
@

nah
businessweek
@
bw




wasn
’
npj


@
@



apps
70-year

questions
nature./articles/d41586-0…
xavier
duran
@
xduran_e
potser
depressa
estudiant
possibilitats


-

years
chats
nature./articles/d41586-0…
@
conversations


badgerherald./opinion/202…
_4_care
@
benefits

terms

tools

quagmires

incare
nature./articles/d41586-0…
@
surprised



kfirkfir36
@
point-counterpoint

’

ift.tt/n5ld46t
bahia
@




aje.io/v08671
@
ajenglish
medlog

@
replicants
considerations


tebb.es/3hh7lqr

helpdesk
@




aje.io/v08671
@
ajenglish
lott
@





In [ ]:
tweets_engNeu_df=pd.DataFrame(tweets_eng_neu, columns=['Text'])
tweets_engPos_df=pd.DataFrame(tweets_eng_pos, columns=['Text'])

In [ ]:
textsTWTNeu = [row.split() for row in tweets_engNeu_df.Text.tolist()]
dict_for_coh_TWT_Neu = Dictionary(textsTWTNeu)

textsTWTPos = [row.split() for row in tweets_engPos_df.Text.tolist()]
dict_for_coh_TWT_Pos = Dictionary(textsTWTPos)

In [ ]:
cohere_numTops(tweets_engPos_df, dict_for_coh_TWT_Pos, textsTWTPos, 2, 7)

=== K = 2 | c_v = 0.785 ===
  Topic 0: video, platform, free, creator, best, money, time, visitor, create, great
  Topic 1: art, best, chat, new, good, gender, more, care, news, io

=== K = 3 | c_v = 0.768 ===
  Topic 0: video, money, create, free, data, content, other, time, tool, ways
  Topic 1: art, good, gender, more, io, new, best, chat, big, prize
  Topic 2: best, platform, new, chat, creator, care, visitor, today, al, technology

=== K = 4 | c_v = 0.780 ===
  Topic 0: time, today, art, tool, more, best, work, life, enable, human
  Topic 1: art, good, new, sexy, io, alert, best, join, more, human
  Topic 2: platform, best, care, new, creator, chat, visitor, future, technology, more
  Topic 3: video, gender, best, chat, money, data, free, create, great, confidential

=== K = 5 | c_v = 0.780 ===
  Topic 0: time, year, happy, tool, work, best, help, life, use, way
  Topic 1: good, new, io, art, join, best, prize, tool, conversation, more
  Topic 2: platform, visitor, creator, best, chat, new, care, future, prompt, today
  Topic 3: art, best, creativity, amazing, great, big, incredible, news, more, data
  Topic 4: video, gender, chat, free, money, create, new, human, care, confidential

=== K = 6 | c_v = 0.790 ===
  Topic 0: tool, time, year, al, voice, work, happy, artificial, best, life
  Topic 1: good, new, best, join, fun, io, more, art, prize, day
  Topic 2: chat, best, new, care, better, digital, future, research, al, more
  Topic 3: best, art, news, big, amazing, creativity, io, pool, more, incredible
  Topic 4: video, gender, money, free, create, chat, human, new, confidential, transition
  Topic 5: platform, creator, visitor, art, sexy, today, playback, enable, ready, chat

Summary:
  num_topics  coherence_c_v
          2       0.785431
          3       0.767783
          4       0.779563
          5       0.779932
          6       0.790446

In [ ]:
cohere_numTops(tweets_engNeu_df, dict_for_coh_TWT_Neu, textsTWTNeu, 2, 7)

=== K = 2 | c_v = 0.745 ===
  Topic 0: al, new, tool, human, data, use, care, prompt, voice, open
  Topic 1: free, chat, playback, enable, advice, good, best, real, open, technology

=== K = 3 | c_v = 0.749 ===
  Topic 0: care, prompt, data, new, benefit, use, nick, ethical, research, anyone
  Topic 1: free, chat, playback, enable, advice, real, best, dialogue, relationship, technology
  Topic 2: open, human, voice, al, tool, conversation, good, stress, next, use

=== K = 4 | c_v = 0.760 ===
  Topic 0: prompt, care, data, benefit, new, nick, ethical, content, beginner, analytics
  Topic 1: free, playback, enable, advice, chat, real, dialogue, relationship, play, cools
  Topic 2: human, voice, tool, al, good, open, conversation, next, stress, productivity
  Topic 3: chat, open, free, best, session, use, world, time, technology, professional

=== K = 5 | c_v = 0.761 ===
  Topic 0: prompt, benefit, nick, new, ethical, beginner, content, care, analytics, data
  Topic 1: free, playback, enable, advice, real, chat, relationship, dialogue, play, cools
  Topic 2: human, voice, tool, open, al, conversation, good, stress, productivity, mode
  Topic 3: chat, best, open, free, use, session, technology, better, world, time
  Topic 4: next, revolution, news, data, intelligence, human, tech, care, life, other

=== K = 6 | c_v = 0.761 ===
  Topic 0: prompt, benefit, nick, anyone, new, beginner, content, data, analytics, care
  Topic 1: real, chat, more, ro, technology, tech, many, advice, talk, bard
  Topic 2: voice, human, tool, al, conversation, open, stress, productivity, mode, warm
  Topic 3: free, chat, enable, playback, advice, dialogue, play, open, girl, session
  Topic 4: next, data, news, human, revolution, enable, playback, intelligence, life, good
  Topic 5: best, day, technology, first, such, care, hey, feedback, new, much

Summary:
  num_topics  coherence_c_v
          2       0.745364
          3       0.748656
          4       0.759882
          5       0.760752
          6       0.761386

#Looking at Youtube Video Titles

In [ ]:
yt_titles=pd.read_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/yt_comment_titles.csv")

In [ ]:
yt_titles.rename(columns={'Video_title': 'Text'}, inplace=True)

In [ ]:
yt_titles

,Unnamed: 0,Video_Id,Text
0,0,TeJppS_wXOk,Things to consider if you’re using ChatGPT as ...
1,1,TeJppS_wXOk,Things to consider if you’re using ChatGPT as ...
2,2,TeJppS_wXOk,Things to consider if you’re using ChatGPT as ...
3,3,TeJppS_wXOk,Things to consider if you’re using ChatGPT as ...
4,4,TeJppS_wXOk,Things to consider if you’re using ChatGPT as ...
...,...,...,...
4429,4429,3BgdhHXJ-CU,Can AI Replace Therapists? | Psychiatrist Expl...
4430,4430,3BgdhHXJ-CU,Can AI Replace Therapists? | Psychiatrist Expl...
4431,4431,3BgdhHXJ-CU,Can AI Replace Therapists? | Psychiatrist Expl...
4432,4432,3BgdhHXJ-CU,Can AI Replace Therapists? | Psychiatrist Expl...
4433,4433,3BgdhHXJ-CU,Can AI Replace Therapists? | Psychiatrist Expl...

In [ ]:
unique_df = pd.DataFrame(yt_titles['Text'].drop_duplicates())

In [ ]:
unique_df.size

49

In [ ]:
unique_df

                                                   Text
0     Things to consider if you’re using ChatGPT as ...
12             ChatGPT is Everyone&#39;s Therapist Now?
14           I&#39;ve Been Using ChatGPT as a Therapist
72                                My take on AI Therapy
90              Is ChatGPT a Better Therapist Than Me?!
111                        ChatGPT Therapy is Dangerous
208                      Is AI therapy a horrible idea?
239                  Why AI Will Replace Your Therapist
298   Can AI Replace Therapists? | Psychiatrist Expl...
492   Therapist vs. Artificial Intelligence - I answ...
584              Can AI Really Help With Mental Health?
787   Should You Use ChatGPT for Therapy? | Therapis...
794   Chat GPT Isn’t Your Therapist &amp; Why Using ...
808                   Why ChatGPT Is An Awful Therapist
825                         Use Chat-GPT as a THERAPIST
860           Can ChatGPT be your therapist? | The Take
946   AI Therapy Exposed: Clinical Psychologist Revi...
2090  ChatGPT is NOT your therapist.. #carterpcs #te...
2123  Using ChatGPT As A Therapist Is No Worse Than ...
2137  How to Make ChatGPT Be Your Ultimate Health Coach
2148                 DO YOU USE CHATGPT AS A THERAPIST?
2160  When ChatGPT is your therapist… 😅😭😂 #shorts #f...
2245                How to Use ChatGPT Like a Therapist
2252             Is ChatGPT safe to use as a therapist?
2258                  Will CHAT GPT Replace THERAPISTS?
2288                             ChatGPT as a therapist
2438  Coaching vs Therapists vs chatGPT ft. Dr Micae...
2615  Doctors Vs AI : Can Chat GPT Replace Your Ther...
2692                              Therapist vs ChatGPT!
3126  Putting AI Therapy to the Test ft. Dr Micaela ...
3155  AI Deep Dive: Can a Chatbot Be Your Therapist?...
3156  ChatGPT Isn&#39;t The Therapist Y&#39;all Want...
3225  USING CHATGPT AS YOUR THERAPIST? SAM ALTMAN HA...
3226  How to Turn ChatGPT Into Your Personal Therapi...
3291                &quot;chatGPT is my therapist&quot;
3298        Would You Trust ChatGPT with Your Feelings?
3394      3 Reasons ChatGPT Makes A DANGEROUS Therapist
3542            Using ChatGPT as Your Therapist? STOP‼️
3543  Should you use AI chatbots for therapy? Here&#...
3552  AI is my second therapist #chatgpt #therapy #k...
3555  I Turned ChatGPT Into My Personal AI Therapist...
3559  Why are more people turning to ChatGPT for the...
3568                     Is ChatGPT a good therapist? 🤔
3666  I let ChatGPT be my therapist… and it ruined m...
3873  Should You use ChatGPT as a Therapist? #ai #ch...
3987    Whats scary about AI Therapy ft @TheDiaryOfACEO
4027  The Mental Health AI Chatbot Made for Real Lif...
4257                                         Test Video
4273                          The Dangers of AI Therapy

In [ ]:
unique_df.Text.apply(len).mean()

np.float64(50.08163265306123)

In [ ]:
unique_df=pd.DataFrame(unique_df.Text.str.lower())

In [ ]:
from nltk.corpus import stopwords
nltk.download("stopwords")
stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
keys_punc=['?', '!', '#', '&', '.', ';',':', '(',')', ',']
for x in keys_punc:
    unique_df['Text']=unique_df['Text'].str.replace(x, ' ')

In [ ]:
title_stop=[]
title_list=unique_df.Text.tolist()
english_vocab = set(w.lower() for w in words.words())
i=0
for text in title_list:
  for word in text.split(' '):
    #if i<10:
      #print(word)
    if (word.lower() in stop_words) or not(word.isalpha()):
      print(word)
      text=text.replace(word, '')
  title_stop.append(text)

to
if
you’re
as
your
👀
is

39
s
now

i

39
ve
been
as
a
my
on
is
a
than
me


is
is
a

why
will
your
can

|

-
i
your


can
with

should
you
for

|
isn’t
your


why
it
as
is
why
is
an
chat-gpt
as
a
can
be
your

|
the

is
not
your








as
a
is
no
than
an
how
to
be
your
do
you
as
a

when
is
your
therapist…
😅😭😂






how
to
a
is
to
as
a

will

as
a





can
your


to
the




can
a
be
your

w/

|
being
isn

39
t
the
y

39
all
it
to
be




more

as
your

has
a

how
to
into
your
—


is
my

you
with
your

3
a
as
your

stop‼️
should
you
for

here

39
s
what
a
is
my



i
into
my

here

39
s
how

why
are
more
to
for

is
a

🤔
i
be
my
therapist…
and
it
my
should
you
as
a






about
@thediaryofaceo
the
for
|
|
the
of

In [ ]:
unique_df

                                                   Text
0     things to consider if you’re using chatgpt as ...
12             chatgpt is everyone  39 s therapist now
14           i  39 ve been using chatgpt as a therapist
72                                my take on ai therapy
90              is chatgpt a better therapist than me
111                        chatgpt therapy is dangerous
208                      is ai therapy a horrible idea
239                  why ai will replace your therapist
298   can ai replace therapists  | psychiatrist expl...
492   therapist vs  artificial intelligence - i answ...
584              can ai really help with mental health
787   should you use chatgpt for therapy  | therapis...
794   chat gpt isn’t your therapist  amp  why using ...
808                   why chatgpt is an awful therapist
825                         use chat-gpt as a therapist
860           can chatgpt be your therapist  | the take
946   ai therapy exposed  clinical psychologist revi...
2090  chatgpt is not your therapist    carterpcs  te...
2123  using chatgpt as a therapist is no worse than ...
2137  how to make chatgpt be your ultimate health coach
2148                 do you use chatgpt as a therapist
2160  when chatgpt is your therapist… 😅😭😂  shorts  f...
2245                how to use chatgpt like a therapist
2252             is chatgpt safe to use as a therapist
2258                  will chat gpt replace therapists
2288                             chatgpt as a therapist
2438  coaching vs therapists vs chatgpt ft  dr micae...
2615  doctors vs ai   can chat gpt replace your ther...
2692                              therapist vs chatgpt
3126  putting ai therapy to the test ft  dr micaela ...
3155  ai deep dive  can a chatbot be your therapist ...
3156  chatgpt isn  39 t the therapist y  39 all want...
3225  using chatgpt as your therapist  sam altman ha...
3226  how to turn chatgpt into your personal therapi...
3291                 quot chatgpt is my therapist quot
3298        would you trust chatgpt with your feelings
3394      3 reasons chatgpt makes a dangerous therapist
3542            using chatgpt as your therapist  stop‼️
3543  should you use ai chatbots for therapy  here  ...
3552  ai is my second therapist  chatgpt  therapy  k...
3555  i turned chatgpt into my personal ai therapist...
3559  why are more people turning to chatgpt for the...
3568                     is chatgpt a good therapist  🤔
3666  i let chatgpt be my therapist… and it ruined m...
3873  should you use chatgpt as a therapist   ai  ch...
3987    whats scary about ai therapy ft @thediaryofaceo
4027  the mental health ai chatbot made for real lif...
4257                                         test video
4273                          the dangers of ai therapy

In [ ]:
title_stop_df=pd.DataFrame(title_stop, columns=['Text'])

In [ ]:
unique_na_df=pd.DataFrame(unique_df.Text.apply(nouns_adj))

In [ ]:
unique_na_df

                                                   Text
0                            things chatgpt therapist 👀
12                         chatgpt everyone s therapist
14                               i ve chatgpt therapist
72                                      take ai therapy
90                                     better therapist
111                           chatgpt therapy dangerous
208                            ai therapy horrible idea
239                                           therapist
298                  therapists | psychiatrist explains
492   therapist vs artificial intelligence i questio...
584                                       mental health
787                chatgpt therapy | therapist explains
794                   gpt isn ’ therapist amp dangerous
808                             chatgpt awful therapist
825                                  chat-gpt therapist
860                                      therapist take
946   ai therapy clinical psychologist reviews thera...
2090  chatgpt therapist carterpcs tech techtok techf...
2123           chatgpt therapist worse actual therapist
2137                      chatgpt ultimate health coach
2148                                  chatgpt therapist
2160  chatgpt therapist… 😅😭😂 shorts funny comedy cha...
2245                                  chatgpt therapist
2252                             chatgpt safe therapist
2258                                     gpt therapists
2288                                  chatgpt therapist
2438   vs therapists chatgpt ft dr micaela amp dr honda
2615                           doctors ai gpt therapist
2692                               therapist vs chatgpt
3126         ai therapy test ft dr micaela amp dr honda
3155  deep dive chatbot therapist w/ dr nick jacobson |
3156  chatgpt t therapist y gen z loneliness ai roma...
3225               chatgpt therapist sam altman warning
3226       chatgpt personal therapist — example prompts
3291                        quot chatgpt therapist quot
3298                                   chatgpt feelings
3394                        reasons dangerous therapist
3542                           chatgpt therapist stop‼️
3543        ai chatbots therapy s real therapist thinks
3552          ai second therapist chatgpt therapy kuwtk
3555                  i chatgpt personal ai therapist s
3559                                     people therapy
3568                                   good therapist 🤔
3666                  i chatgpt therapist… relationship
3873      chatgpt therapist ai chatgpt techtips techtok
3987               whats ai therapy ft @ thediaryofaceo
4027  mental health ai chatbot real life | alison da...
4257                                         test video
4273                                 dangers ai therapy

In [ ]:
keys_titles=['ai', 'chatgpt', 'therapist', 'therapy']
for x in keys_titles:
    unique_na_df['Text']=unique_na_df['Text'].str.replace(x, '')
    title_stop_df['Text']=title_stop_df['Text'].str.replace(x, '')

In [ ]:
print(unique_na_df.Text.apply(len).mean())
print(title_stop_df.Text.apply(len).mean())

17.081632653061224
32.326530612244895

In [ ]:
text_title_na = [row.split() for row in unique_na_df.Text.tolist()]
dict_for_coh_title_na = Dictionary(text_title_na)

text_title_stop = [row.split() for row in title_stop_df.Text.tolist()]
dict_for_coh_title_stop = Dictionary(text_title_stop)

In [ ]:
cohere_numTops(unique_na_df, dict_for_coh_title_na, text_title_na, 2, 7)

=== K = 2 | c_v = 0.740 ===
  Topic 0: techtok, quot, explns, take, personal, dangerous, vs, tech, carterpcs, techfacts
  Topic 1: dr, amp, gpt, ft, health, micaela, honda, test, mental, vs

=== K = 3 | c_v = 0.755 ===
  Topic 0: techtok, quot, take, dangerous, health, dive, jacobson, nick, deep, carterpcs
  Topic 1: gpt, amp, dangerous, comedy, apps, funny, shorts, reviews, loneliness, gen
  Topic 2: dr, ft, vs, amp, micaela, honda, test, personal, explns, health

=== K = 4 | c_v = 0.764 ===
  Topic 0: dangerous, techtok, chatbot, dive, jacobson, nick, deep, techfacts, carterpcs, tech
  Topic 1: gpt, health, apps, shorts, comedy, funny, psychologist, loneliness, reviews, romance
  Topic 2: dr, ft, vs, amp, micaela, honda, test, explns, mental, real
  Topic 3: quot, personal, take, gpt, dangerous, isn, warning, sam, thinks, altman

=== K = 5 | c_v = 0.750 ===
  Topic 0: dangerous, take, chatbot, dive, nick, jacobson, deep, coach, thinks, ultimate
  Topic 1: gpt, shorts, comedy, romance, loneliness, funny, gen, artificialintelligence, chat, doctors
  Topic 2: dr, amp, ft, micaela, honda, test, health, mental, real, alison
  Topic 3: techtok, quot, personal, dangerous, carterpcs, isn, tech, techfacts, warning, altman
  Topic 4: vs, explns, mentalhealth, intelligence, questions, artificial, thediaryofaceo, whats, awful, people

=== K = 6 | c_v = 0.771 ===
  Topic 0: dangerous, chatbot, dive, nick, jacobson, deep, actual, reasons, worse, dangers
  Topic 1: gpt, amp, dangerous, romance, loneliness, gen, isn, chat, kuwtk, second
  Topic 2: health, mental, real, alison, darcy, life, psychologist, reviews, clinical, apps
  Topic 3: techtok, quot, personal, carterpcs, tech, techfacts, warning, altman, sam, example
  Topic 4: vs, take, mentalhealth, artificial, intelligence, questions, thediaryofaceo, whats, awful, people
  Topic 5: dr, ft, micaela, honda, explns, amp, test, comedy, artificialintelligence, funny

Summary:
  num_topics  coherence_c_v
          2       0.739573
          3       0.755366
          4       0.764439
          5       0.749788
          6       0.771443

In [ ]:
cohere_numTops(title_stop_df, dict_for_coh_title_stop, text_title_stop, 2, 7)

=== K = 2 | c_v = 0.819 ===
  Topic 0: therapt, therpt, chtgpt, using, therapst, thn, quot, take, dangerous, mental
  Topic 1: chtgpt, therpist, use, dr, vs, replace, amp, ft, gpt, chat

=== K = 3 | c_v = 0.781 ===
  Topic 0: therapt, therapst, quot, dangerous, take, explns, vs, using, answer, mentalhealth
  Topic 1: therpist, chtgpt, use, dr, vs, using, amp, ft, chtbot, therpy
  Topic 2: chtgpt, therpt, replace, health, mental, techtok, gpt, chat, dr, thn

=== K = 4 | c_v = 0.772 ===
  Topic 0: therapt, quot, dangerous, take, explns, vs, using, therapst, chat, gpt
  Topic 1: therpist, use, chtgpt, vs, using, amp, ft, dr, therpy, honda
  Topic 2: replace, therpist, dr, chtgpt, health, mental, techtok, gpt, chat, therapt
  Topic 3: chtgpt, therpt, thn, using, seeing, worse, ctul, better, relatonshp, let

=== K = 5 | c_v = 0.781 ===
  Topic 0: therapt, dangerous, take, using, therapst, chat, gpt, vs, answer, mentalhealth
  Topic 1: vs, amp, dr, ft, therpy, honda, micaela, chtbot, gen, chagp
  Topic 2: use, chtgpt, therpist, health, dr, mental, techtok, explns, replace, test
  Topic 3: therpt, chtgpt, therapt, thn, quot, using, seeing, worse, ctul, plus
  Topic 4: therpist, chtgpt, using, replace, gpt, chat, deep, ing, jcobson, well

=== K = 6 | c_v = 0.780 ===
  Topic 0: therapt, take, dangerous, chat, gpt, using, therapst, answer, mentalhealth, one
  Topic 1: amp, dr, ft, vs, test, replace, rapy, therpy, gpt, chat
  Topic 2: health, mental, replace, explns, chatbot, darcy, alison, ted, made, life
  Topic 3: chtgpt, therpt, therapt, thn, quot, using, worse, seeing, ctul, psychologist
  Topic 4: therpist, chtgpt, use, using, replace, techtok, chtbot, deep, ing, jcobson
  Topic 5: vs, dr, ft, amp, honda, micaela, coaching, explns, use, dangerous

Summary:
  num_topics  coherence_c_v
          2       0.818769
          3       0.780772
          4       0.772361
          5       0.781082
          6       0.779863