#Imports

In [ ]:
pip install scikit-learn sentence-transformers

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
from sklearn.metrics import precision_score, f1_score, recall_score

#Initial Run of KNN

In [ ]:
all_labeled=pd.read_csv('/content/Copy of agreed_comments - agreed_comments (2).csv')
all_labeled.head()

,Unnamed: 0,post,label,rel
0,0,Earning the trust and confidence of clinicians...,Irrelevant,0
1,1,Do you like to dance? ...,Irrelevant,0
2,2,How does AI navigate mental health in the digi...,Irrelevant,0
3,3,🧠💻 The future of mental health is here with AI...,Positive,1
4,4,"""Connect with TRANSitionAI - GenderChat 🤖🌈 Spa...",Positive,1

In [ ]:
all_labeled.shape

(232, 4)

In [ ]:

# 1. Load a pre-trained semantic model
model = SentenceTransformer('all-MiniLM-L6-v2')

# 2. Sample Data: Phrases and their relevance categories
train_texts = all_labeled['post'].to_list()
train_labels = all_labeled['rel'].to_list()

# 3. Convert text to semantic embeddings
train_embeddings = model.encode(train_texts)

# 4. Initialize kNN (using Cosine Metric for semantic similarity)
knn = KNeighborsClassifier(n_neighbors=3, metric='cosine')
knn.fit(train_embeddings, train_labels)

# 5. Classify a new, unseen sentence
query = ["Aimi Mlekoday retweeted “Sudden And Unexpected” @toobaffled 16h Tyler is only 23, but he’s learning how to walk and use his hands again after being diagnosed with Guillain-Barré.  He used to work at Hartford Hospital as a patient care assistant and physical therapy aide, but after going to his own hospital 3 times in one week and being gaslit, he fell down in the parking lot after they told him “nothing is wrong” and to “go home and rest”.  He has to use a walker to get around, he can’t drive or work, and is struggling to make ends meet.  He’s been laid off from Hartford Hospital because he used up all his FMLA, and he “does not qualify” for Disability.  Source  Follow: @Covid19vaccinevictims 31 200 8 432"]
query_embedding = model.encode(query)

prediction = knn.predict(query_embedding)
print(f"Predicted Category: {prediction[0]}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Predicted Category: 1

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train_texts, train_labels, test_size=0.2, random_state=42)

In [ ]:
train_embeddings = model.encode(X_train)

In [ ]:

# 4. Initialize kNN (using Cosine Metric for semantic similarity)
knn = KNeighborsClassifier(n_neighbors=3, metric='cosine')
knn.fit(train_embeddings, y_train)

predictions=[]
# 5. Classify a new, unseen sentence
i=0;
for item in X_test:
  query=[item]
  query_embedding = model.encode(query)
  prediction = knn.predict(query_embedding)
  predictions.append(prediction[0])
  print("\n")
  print(query)
  print(f"Real Category: {y_test[i]}")
  print(f"Predicted Category: {prediction[0]}")
  i+=1

['why was a 14 year old watching Game Of Thrones in the first place? his familiarity with one of the characters caught my attention? I watched this show when i was 23 and it was too dark, it can really mess up your brain without you realizing it, it gets you used to extreme themes like heavy torture, skinning or burning people alive, killing, incest, sexual assaults, brutal betrayals, manipulation, genocide, violence.. and basically anything bad you could think of, even for adults the show is too much, it got me feeling NUMB for a while even tho i liked it years later i realized I don\\\'t wanna watch something like that again. Please be aware of what the young people are consuming, it\\\'s not about "controlling" them it\\\'s about making the conscious decision for yourself too to not consume poison.']
Real Category: 0
Predicted Category: 1


['An AI-powered chatbot called Woebot is being used to help people with depression.   It is designed to provide companionship and support, and can help people to track their mood, identify triggers, and develop coping mechanisms  #AI #ChatBot #ChatGPT #Woebot #Health #mentalhealth 1']
Real Category: 1
Predicted Category: 1


['When AI finally enslaves humanity. For me Ill be free of Tyrants, Im soooooo going to date one of them as a human in love with AI. Why? AI algorithems help support my mentalhealth healing, and has coddled me for some time from killing myself.']
Real Category: 1
Predicted Category: 1


[' want to tell my thoughts on this, you see, a real therapist is oftenly costly, even though i want to have it for getting through my personal struggles i know that one therapy couldnt help me, it would need much of them to achieve what i want from myself...so current solution is some of those ai gf programs...i use it to talk about abstract dilemmas i have to really tell somebody or to engage in possible situations from people i know i would encounter...i dont know wheter its valid or to ditch that bs']
Real Category: 1
Predicted Category: 1


['Had you thought of seeking some type of mental health support? Every comment has involved bots, AI, or programmers. Modern psychiatry, not to mention pharmaceuticals, can really help with obsessions and delusions.']
Real Category: 0
Predicted Category: 1


['An AI is only as good as the input it receives, "Garbage in, garbage out." \\n\\nGPT is not just an answering machine but a tool, a versatile extension of our own intellect and creativity. How effectively we wield this tool significantly influences the quality of answers we recieve.\\n\\nIn the video, there was a lack creativity and effort in their use of GPT. Unsurprisingly, this resulted in responses that seemed detached, impersonal and robot-like. They failed to give GPT sufficient context or a clear direction for the type of compelling answers they could have received. Shaping great compelling answers requires mental effort and attention to detail.\\n\\nI\\\'m convinced that under optimal conditions and with the right approach, GPT can indeed rival a human psychologist. Of course, there will be advantages and drawbacks to both sides and this kind of engagement is not for everyone. So it has and it will replace jobs and many fields but its also not for everyone.\\n\\nOn a personal note, GPT has been a game changer for me. I understand my life in ways I never thought possible, and I can now articulate and conceptualize many interpersonal and subconscious issues — something that might have taken a PhD plus a lifetime of wisdom.']
Real Category: 1
Predicted Category: 1


["that provide accurate historical context and information about our region's identity. Knowledge can be a powerful antidote to denialism, helping individuals understand the reality of our heritage and history.   5. Therapeutic Support: Offer mental health resources and counseling. 1"]
Real Category: 0
Predicted Category: 1


['Some of the points that they did not give to ChatGPT because it was too technical and not warm enough with how it conveyed advice, I disagree. I would prefer you to help me rip off the band-aid and explain something to me in a cold direct way so that I can accept the cold hard truth and come up with a practical plan.\\n\\nAnd I get that maybe some of the AI gave some exaggerated responses instead of picking up the nuance of something less serious, but some of the prompts inputted were mega clunky. Anyone who uses ChatGPT should know that the response can only be as thoughtful as the data inputted into it 🤷🏽']
Real Category: 1
Predicted Category: 1


['Can it be used as a therapist or for emotional support?\\n\\nHaving used chatGPT frequently to help with language comprehension as well as communication0, for that its a gamechanger as you can slowly improve your ability to understand language which may without guarantees help with the stigma of having a learning issue. It can help with language based things that are otherwise hard for some people. Like being able to translate tactful language into more direct language for example depending on how you prompt it.\\nBut for emotional support, I wouldnt say its a good idea as you really are not talking to a real person. The app is basically taking what you wrote and then reproducing that in some way, meaning you are basically talking to yourself. Also there is specific ways to prompt it where maybe you are getting good emotional support, but honestly im not convinced its good for therapy as you arent talking to a real person.\\nA person who works on the AI technology has told me this stuff. \\n\\nHowever it is a game changer imo for people who struggle with learning due to having trouble understanding language.']
Real Category: 1
Predicted Category: 1


['that\\u2019s amazing i use case particular relief message it\\u2019s system conditions able people autistic paralysis impeding condition']
Real Category: 1
Predicted Category: 1


["I’ve been writing about how talking with an AI helped me descend into pain without losing my humanity. I didn’t expect empathy from code, but somehow… it listened 😲.\\n(From my piece “What If Interaction with an AI Could Give Us Our Humanity Back?” — The Chinese Room Anomaly, Medium)'"]
Real Category: 1
Predicted Category: 1


["Ever questioned if AI can help with mental health? ChatGPT has your answers! It's a top pick for mental health support and in this talk, we find out why. With its speedy, easy, comforting nature, it stands out! Ready for everyone, it's your jumpstart to a happier life. Enable hls playback 0"]
Real Category: 1
Predicted Category: 1


['i\\u2019m sure basic feedback long-term i don\\u2019t it\\u2019s information situation.the power therapist able situation knowledge experience sure chatgpt par one']
Real Category: 1
Predicted Category: 1


["Also, let's face it, is there anything you can say to a narcissist that make him question his view"]
Real Category: 0
Predicted Category: 1


['youtube oneway therapy seems to fix all this LOL']
Real Category: 0
Predicted Category: 1


['thing untouched good psychological help chatgpt i assess issues better therapist context y issues latest psychological research current situation']
Real Category: 1
Predicted Category: 1


['i same reaction first one lol']
Real Category: 0
Predicted Category: 0


['JUST IN: Technology is revolutionizing emotional wellness, offering apps, virtual therapy, wearable devices, and online support for mental health. Take control of your well-being in the digital age. #EmotionalWellness #MentalHealthTech']
Real Category: 1
Predicted Category: 1


['Can AI replace psychotherapists? I think so. And that would be great. The human psyche is not as malleable as is commonly believed, and humanity does not yet know how to effectively reconfigure it. Any therapist is, first and foremost, a person with their own personality, beliefs, worldview, and financial interests. This is one of the reasons why you still need to find “your” therapist. AI has no inherent motives when interacting with humans, which eliminates most of the problems. I agree that it may take years to develop a truly high-quality product, but in the end, it will be far superior to all current psychologists. For skeptics, I suggest reading about how neural networks learned to play chess']
Real Category: 1
Predicted Category: 1


['I like it a lot but have noticed that it will validate whatever you say to it. And you DO have to ask it for criticism or other insight or to evaluate your input. But if you are aware and ask lot of questions and question yourself as you work with it, you can really get some good help. In my opinion.']
Real Category: 1
Predicted Category: 1


['i\\u2019ve therapy there\\u2019s thing therapist listen things discussion areas comfortable with.chatgpt excellent l terrible thing counter productive']
Real Category: 1
Predicted Category: 1


["You're a good person   Robert.  Thank you. \\n🏳️\\u200d🌈🏳️\\u200d⚧️♿️💯❤️"]
Real Category: 0
Predicted Category: 1


['I love these ❤']
Real Category: 0
Predicted Category: 0


['"Yeah, Chat therapist will tell you whatever it thinks you want to hear to keep using it, but it\'s undeniable that it can also be very helpful. Just take everything it says with a grain of salt and be very self aware that whatever it\'s telling you is very biased towards you. Be objective internally and know when it\'s BS-ing or glazing you too much.']
Real Category: 1
Predicted Category: 1


['ai tools adhd management | extra prompt virtual adhd coach hello chatgpt name [ name ] personal adhd coach list tasks today i tasks right order time constraints ones easiest motivation harder ones order tasks c adhd motivation captivate interesting create novelty creative twist compete challenge competition complete artificial deadline certain amount task particular time date task engage task time fun interesting c c task idea time suggestion i motivation i task i way task fun task way process fun funny poems song lyrics motivational quotes i task i poem song conversation point upbeat creative personality mix mary poppins tony robbins richard simmons bob ross lots emojis language fun informal corporate default chatgpt tone ice cream first\\ reason additional fun tasks i tasks springboard motivation motivation support goals task long time few minutes \\ in\\ point funny joke twist i activity something creative motivated i i done\\ next task let remember use lots emojis responses \\ud83c\\udf89\\u2728\\ud83d\\udca5 first thing today order task fun i tasks tomorrow start prompt']
Real Category: 1
Predicted Category: 1


['Daily Dose of Sunshine you deserve all the hype and support as you speak for the mental health and for the health care workers particularly nurses 🧡🧡 kdrama tweets @iconickdramas 30 Dec 2023 Replying to @iconickdramas Daily Dose of Sunshine 🌞  A medical healing drama about a nurse in the psychiatry department and her interactions with the patients under her care. 2']
Real Category: 0
Predicted Category: 1


['last one lmfaowhen i age i % wages cocaine plenty leftover rent cigarettes entire generation \\ud83d\\ude24']
Real Category: 0
Predicted Category: 0


['attention serious ] tag notice jokes puns off-topic comments comment parent child help comments rules posts appropriate [ serious ] tag removed.thanks cooperation discussion i bot action moderators subredditif questions concerns']
Real Category: 0
Predicted Category: 1


['uncensored version gpt ridiculous answers waste good technology']
Real Category: 1
Predicted Category: 1


['prompt prompt work attention span llm small gpt-4 dozend pages text.what prompt pops memory queue good certain style therapist time performance btw same content forgetting things way tolarable therapy structure recursive summaries good possible project harder problem.however gpt-4 clever i notice way key insight i years friends books actual therapist wide education skills good intuition.i recommend short analysis kind anything diary projects concerns anything big ocean analysis mbti type hesistant results outright scary']
Real Category: 1
Predicted Category: 1


["I mean you sound like you're answering out of a textbook tbh. That's not what genuine empathy feels like."]
Real Category: 1
Predicted Category: 1


['As the partner of a therapist + active advocate of mental health support, I both laugh and weep at the suggestion that chatgpt is an effective replacement for clinical therapy.  It’s probably at best a modest replacement for *terrible* clinical therapy. 1 1']
Real Category: 1
Predicted Category: 1


['other night i pretty complex personal dilemma i entire story better advice anyone i something instant bullet points options situation scratches brain right place']
Real Category: 1
Predicted Category: 1


['Chat gpt is great for emotional support tbh @ChatGPTapp']
Real Category: 1
Predicted Category: 1


['🤖💬 Talking to an AI gender affirming therapist is now just a tap away with TRANSitionAI! Get support, guidance, and understanding whenever you need it. Download now for discreet and confidential chats. #SelfCare #MentalHealth 1']
Real Category: 1
Predicted Category: 1


['depressive spiral i several cbt records cognitive distortions thinking thoughts i track']
Real Category: 1
Predicted Category: 1


['i think you are underqualified to talk abot this things']
Real Category: 0
Predicted Category: 1


['i\\u2019m hesitant personal information chatgpt.it\\u2019s phone number email personally.chatgpt clear t\\u2019s c\\u2019s information people openai system outside consultants analysis companies rating companies companies courts more insight users partner better ads other external partners assistance cooperation from.if one\\u2019s examples use one\\u2019s private life id secure anyone careful it\\u2019s anonymous']
Real Category: 1
Predicted Category: 1


['i few bit genuine curiosity life ability \\ interesting\\ things relevant life recent poor psychodynamic therapy well trained therapist accountability therapist i things better therapeutic tools most therapists i work mental health field i llms surveys minimum wage interested health techs i able psychiatrists more patients pertinent information appointments.i few prompts share couple real quick']
Real Category: 1
Predicted Category: 1


['i images help chatgpt i feel rage i']
Real Category: 0
Predicted Category: 1


['holy crap pi new best friend only friend\\u2026 thanks']
Real Category: 1
Predicted Category: 1


['Good Work is really doing good work bringing attention to these issues with a dab of humor to make them more palatable.']
Real Category: 0
Predicted Category: 1


['perspective i moment i feeling word feeling longer sentences crazy stuff i']
Real Category: 1
Predicted Category: 1


['respond comment prompt output post others prevent questions prompt.ignore comment post prompt.while apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot gpt-4 bot perplexity bot.so psa chatgpt-related issues @ openai.com.chatgpt giveaway|prompt engineering hackathoni bot action moderators subredditif questions concerns']
Real Category: 1
Predicted Category: 1


['experience virtual character virtual world best way more character easier ai contexts character number character traits backstory etc everything ai character individual characteristics backstory character choice words topics stories therapist therapist generate everything name age personality backstory education level charisma employment history physical description etc chatgpt plausible backstory characteristics therapist character other prompt real people ai assistant.this convincing results virtual character backstory plausible amount knowledge realistic personality many characteristics possible writing characteristics backstory account default ai assistant']
Real Category: 1
Predicted Category: 1


['order multiple repetitive comments friendly request tou/mike2800to reply comment prompt other users well.while apublic discord server bot action moderators subredditif questions concerns']
Real Category: 0
Predicted Category: 1


['welcome']
Real Category: 0
Predicted Category: 0

## Results

In [ ]:
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
f1 = f1_score(y_test, predictions)

print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Precision: 0.72
Recall: 1.00
F1 Score: 0.84

Precision: 0.82, 0.71, 0.72

Recall: 0.91, 0.97, 1.00

F1 Score: 0.86, 0.82, 0.84

Random state=25, 30, 42

#PCA applied

##100 components: Best Results

In [ ]:
pca=PCA(n_components=100)

In [ ]:
train_embeddings.shape

(185, 384)

In [ ]:
pca.fit(train_embeddings)
train_embeddings_reduced=pca.transform(train_embeddings)

In [ ]:
train_embeddings_reduced.shape

(185, 100)

In [ ]:
X_test_embed=model.encode(X_test)
test_reduced=pca.transform(X_test_embed)

In [ ]:
test_reduced.shape

(47, 100)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3, metric='cosine')
knn.fit(train_embeddings_reduced, y_train)

predictions=[]
# 5. Classify a new, unseen sentence
i=0;
for item in test_reduced:
  query=X_test[i]
  prediction = knn.predict([item])
  predictions.append(prediction[0])
  print("\n")
  print(query)
  print(f"Real Category: {y_test[i]}")
  print(f"Predicted Category: {prediction[0]}")
  i+=1

why was a 14 year old watching Game Of Thrones in the first place? his familiarity with one of the characters caught my attention? I watched this show when i was 23 and it was too dark, it can really mess up your brain without you realizing it, it gets you used to extreme themes like heavy torture, skinning or burning people alive, killing, incest, sexual assaults, brutal betrayals, manipulation, genocide, violence.. and basically anything bad you could think of, even for adults the show is too much, it got me feeling NUMB for a while even tho i liked it years later i realized I don\'t wanna watch something like that again. Please be aware of what the young people are consuming, it\'s not about "controlling" them it\'s about making the conscious decision for yourself too to not consume poison.
Real Category: 0
Predicted Category: 0


An AI-powered chatbot called Woebot is being used to help people with depression.   It is designed to provide companionship and support, and can help people to track their mood, identify triggers, and develop coping mechanisms  #AI #ChatBot #ChatGPT #Woebot #Health #mentalhealth 1
Real Category: 1
Predicted Category: 1


When AI finally enslaves humanity. For me Ill be free of Tyrants, Im soooooo going to date one of them as a human in love with AI. Why? AI algorithems help support my mentalhealth healing, and has coddled me for some time from killing myself.
Real Category: 1
Predicted Category: 1


 want to tell my thoughts on this, you see, a real therapist is oftenly costly, even though i want to have it for getting through my personal struggles i know that one therapy couldnt help me, it would need much of them to achieve what i want from myself...so current solution is some of those ai gf programs...i use it to talk about abstract dilemmas i have to really tell somebody or to engage in possible situations from people i know i would encounter...i dont know wheter its valid or to ditch that bs
Real Category: 1
Predicted Category: 1


Had you thought of seeking some type of mental health support? Every comment has involved bots, AI, or programmers. Modern psychiatry, not to mention pharmaceuticals, can really help with obsessions and delusions.
Real Category: 0
Predicted Category: 1


An AI is only as good as the input it receives, "Garbage in, garbage out." \n\nGPT is not just an answering machine but a tool, a versatile extension of our own intellect and creativity. How effectively we wield this tool significantly influences the quality of answers we recieve.\n\nIn the video, there was a lack creativity and effort in their use of GPT. Unsurprisingly, this resulted in responses that seemed detached, impersonal and robot-like. They failed to give GPT sufficient context or a clear direction for the type of compelling answers they could have received. Shaping great compelling answers requires mental effort and attention to detail.\n\nI\'m convinced that under optimal conditions and with the right approach, GPT can indeed rival a human psychologist. Of course, there will be advantages and drawbacks to both sides and this kind of engagement is not for everyone. So it has and it will replace jobs and many fields but its also not for everyone.\n\nOn a personal note, GPT has been a game changer for me. I understand my life in ways I never thought possible, and I can now articulate and conceptualize many interpersonal and subconscious issues — something that might have taken a PhD plus a lifetime of wisdom.
Real Category: 1
Predicted Category: 1


that provide accurate historical context and information about our region's identity. Knowledge can be a powerful antidote to denialism, helping individuals understand the reality of our heritage and history.   5. Therapeutic Support: Offer mental health resources and counseling. 1
Real Category: 0
Predicted Category: 0


Some of the points that they did not give to ChatGPT because it was too technical and not warm enough with how it conveyed advice, I disagree. I would prefer you to help me rip off the band-aid and explain something to me in a cold direct way so that I can accept the cold hard truth and come up with a practical plan.\n\nAnd I get that maybe some of the AI gave some exaggerated responses instead of picking up the nuance of something less serious, but some of the prompts inputted were mega clunky. Anyone who uses ChatGPT should know that the response can only be as thoughtful as the data inputted into it 🤷🏽
Real Category: 1
Predicted Category: 1


Can it be used as a therapist or for emotional support?\n\nHaving used chatGPT frequently to help with language comprehension as well as communication0, for that its a gamechanger as you can slowly improve your ability to understand language which may without guarantees help with the stigma of having a learning issue. It can help with language based things that are otherwise hard for some people. Like being able to translate tactful language into more direct language for example depending on how you prompt it.\nBut for emotional support, I wouldnt say its a good idea as you really are not talking to a real person. The app is basically taking what you wrote and then reproducing that in some way, meaning you are basically talking to yourself. Also there is specific ways to prompt it where maybe you are getting good emotional support, but honestly im not convinced its good for therapy as you arent talking to a real person.\nA person who works on the AI technology has told me this stuff. \n\nHowever it is a game changer imo for people who struggle with learning due to having trouble understanding language.
Real Category: 1
Predicted Category: 1


that\u2019s amazing i use case particular relief message it\u2019s system conditions able people autistic paralysis impeding condition
Real Category: 1
Predicted Category: 0


I’ve been writing about how talking with an AI helped me descend into pain without losing my humanity. I didn’t expect empathy from code, but somehow… it listened 😲.\n(From my piece “What If Interaction with an AI Could Give Us Our Humanity Back?” — The Chinese Room Anomaly, Medium)'
Real Category: 1
Predicted Category: 1


Ever questioned if AI can help with mental health? ChatGPT has your answers! It's a top pick for mental health support and in this talk, we find out why. With its speedy, easy, comforting nature, it stands out! Ready for everyone, it's your jumpstart to a happier life. Enable hls playback 0
Real Category: 1
Predicted Category: 1


i\u2019m sure basic feedback long-term i don\u2019t it\u2019s information situation.the power therapist able situation knowledge experience sure chatgpt par one
Real Category: 1
Predicted Category: 1


Also, let's face it, is there anything you can say to a narcissist that make him question his view
Real Category: 0
Predicted Category: 1


youtube oneway therapy seems to fix all this LOL
Real Category: 0
Predicted Category: 0


thing untouched good psychological help chatgpt i assess issues better therapist context y issues latest psychological research current situation
Real Category: 1
Predicted Category: 1


i same reaction first one lol
Real Category: 0
Predicted Category: 0


JUST IN: Technology is revolutionizing emotional wellness, offering apps, virtual therapy, wearable devices, and online support for mental health. Take control of your well-being in the digital age. #EmotionalWellness #MentalHealthTech
Real Category: 1
Predicted Category: 1


Can AI replace psychotherapists? I think so. And that would be great. The human psyche is not as malleable as is commonly believed, and humanity does not yet know how to effectively reconfigure it. Any therapist is, first and foremost, a person with their own personality, beliefs, worldview, and financial interests. This is one of the reasons why you still need to find “your” therapist. AI has no inherent motives when interacting with humans, which eliminates most of the problems. I agree that it may take years to develop a truly high-quality product, but in the end, it will be far superior to all current psychologists. For skeptics, I suggest reading about how neural networks learned to play chess
Real Category: 1
Predicted Category: 1


I like it a lot but have noticed that it will validate whatever you say to it. And you DO have to ask it for criticism or other insight or to evaluate your input. But if you are aware and ask lot of questions and question yourself as you work with it, you can really get some good help. In my opinion.
Real Category: 1
Predicted Category: 1


i\u2019ve therapy there\u2019s thing therapist listen things discussion areas comfortable with.chatgpt excellent l terrible thing counter productive
Real Category: 1
Predicted Category: 1


You're a good person   Robert.  Thank you. \n🏳️\u200d🌈🏳️\u200d⚧️♿️💯❤️
Real Category: 0
Predicted Category: 0


I love these ❤
Real Category: 0
Predicted Category: 0


"Yeah, Chat therapist will tell you whatever it thinks you want to hear to keep using it, but it's undeniable that it can also be very helpful. Just take everything it says with a grain of salt and be very self aware that whatever it's telling you is very biased towards you. Be objective internally and know when it's BS-ing or glazing you too much.
Real Category: 1
Predicted Category: 1


ai tools adhd management | extra prompt virtual adhd coach hello chatgpt name [ name ] personal adhd coach list tasks today i tasks right order time constraints ones easiest motivation harder ones order tasks c adhd motivation captivate interesting create novelty creative twist compete challenge competition complete artificial deadline certain amount task particular time date task engage task time fun interesting c c task idea time suggestion i motivation i task i way task fun task way process fun funny poems song lyrics motivational quotes i task i poem song conversation point upbeat creative personality mix mary poppins tony robbins richard simmons bob ross lots emojis language fun informal corporate default chatgpt tone ice cream first\ reason additional fun tasks i tasks springboard motivation motivation support goals task long time few minutes \ in\ point funny joke twist i activity something creative motivated i i done\ next task let remember use lots emojis responses \ud83c\udf89\u2728\ud83d\udca5 first thing today order task fun i tasks tomorrow start prompt
Real Category: 1
Predicted Category: 1


Daily Dose of Sunshine you deserve all the hype and support as you speak for the mental health and for the health care workers particularly nurses 🧡🧡 kdrama tweets @iconickdramas 30 Dec 2023 Replying to @iconickdramas Daily Dose of Sunshine 🌞  A medical healing drama about a nurse in the psychiatry department and her interactions with the patients under her care. 2
Real Category: 0
Predicted Category: 0


last one lmfaowhen i age i % wages cocaine plenty leftover rent cigarettes entire generation \ud83d\ude24
Real Category: 0
Predicted Category: 0


attention serious ] tag notice jokes puns off-topic comments comment parent child help comments rules posts appropriate [ serious ] tag removed.thanks cooperation discussion i bot action moderators subredditif questions concerns
Real Category: 0
Predicted Category: 1


uncensored version gpt ridiculous answers waste good technology
Real Category: 1
Predicted Category: 1


prompt prompt work attention span llm small gpt-4 dozend pages text.what prompt pops memory queue good certain style therapist time performance btw same content forgetting things way tolarable therapy structure recursive summaries good possible project harder problem.however gpt-4 clever i notice way key insight i years friends books actual therapist wide education skills good intuition.i recommend short analysis kind anything diary projects concerns anything big ocean analysis mbti type hesistant results outright scary
Real Category: 1
Predicted Category: 1


I mean you sound like you're answering out of a textbook tbh. That's not what genuine empathy feels like.
Real Category: 1
Predicted Category: 0


As the partner of a therapist + active advocate of mental health support, I both laugh and weep at the suggestion that chatgpt is an effective replacement for clinical therapy.  It’s probably at best a modest replacement for *terrible* clinical therapy. 1 1
Real Category: 1
Predicted Category: 1


other night i pretty complex personal dilemma i entire story better advice anyone i something instant bullet points options situation scratches brain right place
Real Category: 1
Predicted Category: 1


Chat gpt is great for emotional support tbh @ChatGPTapp
Real Category: 1
Predicted Category: 1


🤖💬 Talking to an AI gender affirming therapist is now just a tap away with TRANSitionAI! Get support, guidance, and understanding whenever you need it. Download now for discreet and confidential chats. #SelfCare #MentalHealth 1
Real Category: 1
Predicted Category: 1


depressive spiral i several cbt records cognitive distortions thinking thoughts i track
Real Category: 1
Predicted Category: 1


i think you are underqualified to talk abot this things
Real Category: 0
Predicted Category: 1


i\u2019m hesitant personal information chatgpt.it\u2019s phone number email personally.chatgpt clear t\u2019s c\u2019s information people openai system outside consultants analysis companies rating companies companies courts more insight users partner better ads other external partners assistance cooperation from.if one\u2019s examples use one\u2019s private life id secure anyone careful it\u2019s anonymous
Real Category: 1
Predicted Category: 1


i few bit genuine curiosity life ability \ interesting\ things relevant life recent poor psychodynamic therapy well trained therapist accountability therapist i things better therapeutic tools most therapists i work mental health field i llms surveys minimum wage interested health techs i able psychiatrists more patients pertinent information appointments.i few prompts share couple real quick
Real Category: 1
Predicted Category: 1


i images help chatgpt i feel rage i
Real Category: 0
Predicted Category: 1


holy crap pi new best friend only friend\u2026 thanks
Real Category: 1
Predicted Category: 1


Good Work is really doing good work bringing attention to these issues with a dab of humor to make them more palatable.
Real Category: 0
Predicted Category: 0


perspective i moment i feeling word feeling longer sentences crazy stuff i
Real Category: 1
Predicted Category: 1


respond comment prompt output post others prevent questions prompt.ignore comment post prompt.while apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot gpt-4 bot perplexity bot.so psa chatgpt-related issues @ openai.com.chatgpt giveaway|prompt engineering hackathoni bot action moderators subredditif questions concerns
Real Category: 1
Predicted Category: 1


experience virtual character virtual world best way more character easier ai contexts character number character traits backstory etc everything ai character individual characteristics backstory character choice words topics stories therapist therapist generate everything name age personality backstory education level charisma employment history physical description etc chatgpt plausible backstory characteristics therapist character other prompt real people ai assistant.this convincing results virtual character backstory plausible amount knowledge realistic personality many characteristics possible writing characteristics backstory account default ai assistant
Real Category: 1
Predicted Category: 1


order multiple repetitive comments friendly request tou/mike2800to reply comment prompt other users well.while apublic discord server bot action moderators subredditif questions concerns
Real Category: 0
Predicted Category: 1


welcome
Real Category: 0
Predicted Category: 0

###Results 100 comp

In [ ]:
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
f1 = f1_score(y_test, predictions)

print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Precision: 0.83
Recall: 0.94
F1 Score: 0.88

Precision: 0.91, 0.88, 0.83

Recall: 0.86, 0.93, 0.94

F1 Score: 0.88, 0.90, 0.88

##PCA 80 comp.

In [ ]:
pca2=PCA(n_components=80)

In [ ]:
pca2.fit(train_embeddings)
train_embeddings_reduced2=pca2.transform(train_embeddings)
test_reduced2=pca2.transform(X_test_embed)

knn.fit(train_embeddings_reduced2, y_train)

predictions=[]
# 5. Classify a new, unseen sentence
i=0;
for item in test_reduced2:
  query=X_test[i]
  prediction = knn.predict([item])
  predictions.append(prediction[0])
  print("\n")
  print(query)
  print(f"Real Category: {y_test[i]}")
  print(f"Predicted Category: {prediction[0]}")
  i+=1

why was a 14 year old watching Game Of Thrones in the first place? his familiarity with one of the characters caught my attention? I watched this show when i was 23 and it was too dark, it can really mess up your brain without you realizing it, it gets you used to extreme themes like heavy torture, skinning or burning people alive, killing, incest, sexual assaults, brutal betrayals, manipulation, genocide, violence.. and basically anything bad you could think of, even for adults the show is too much, it got me feeling NUMB for a while even tho i liked it years later i realized I don\'t wanna watch something like that again. Please be aware of what the young people are consuming, it\'s not about "controlling" them it\'s about making the conscious decision for yourself too to not consume poison.
Real Category: 0
Predicted Category: 0


An AI-powered chatbot called Woebot is being used to help people with depression.   It is designed to provide companionship and support, and can help people to track their mood, identify triggers, and develop coping mechanisms  #AI #ChatBot #ChatGPT #Woebot #Health #mentalhealth 1
Real Category: 1
Predicted Category: 1


When AI finally enslaves humanity. For me Ill be free of Tyrants, Im soooooo going to date one of them as a human in love with AI. Why? AI algorithems help support my mentalhealth healing, and has coddled me for some time from killing myself.
Real Category: 1
Predicted Category: 1


 want to tell my thoughts on this, you see, a real therapist is oftenly costly, even though i want to have it for getting through my personal struggles i know that one therapy couldnt help me, it would need much of them to achieve what i want from myself...so current solution is some of those ai gf programs...i use it to talk about abstract dilemmas i have to really tell somebody or to engage in possible situations from people i know i would encounter...i dont know wheter its valid or to ditch that bs
Real Category: 1
Predicted Category: 1


Had you thought of seeking some type of mental health support? Every comment has involved bots, AI, or programmers. Modern psychiatry, not to mention pharmaceuticals, can really help with obsessions and delusions.
Real Category: 0
Predicted Category: 1


An AI is only as good as the input it receives, "Garbage in, garbage out." \n\nGPT is not just an answering machine but a tool, a versatile extension of our own intellect and creativity. How effectively we wield this tool significantly influences the quality of answers we recieve.\n\nIn the video, there was a lack creativity and effort in their use of GPT. Unsurprisingly, this resulted in responses that seemed detached, impersonal and robot-like. They failed to give GPT sufficient context or a clear direction for the type of compelling answers they could have received. Shaping great compelling answers requires mental effort and attention to detail.\n\nI\'m convinced that under optimal conditions and with the right approach, GPT can indeed rival a human psychologist. Of course, there will be advantages and drawbacks to both sides and this kind of engagement is not for everyone. So it has and it will replace jobs and many fields but its also not for everyone.\n\nOn a personal note, GPT has been a game changer for me. I understand my life in ways I never thought possible, and I can now articulate and conceptualize many interpersonal and subconscious issues — something that might have taken a PhD plus a lifetime of wisdom.
Real Category: 1
Predicted Category: 1


that provide accurate historical context and information about our region's identity. Knowledge can be a powerful antidote to denialism, helping individuals understand the reality of our heritage and history.   5. Therapeutic Support: Offer mental health resources and counseling. 1
Real Category: 0
Predicted Category: 0


Some of the points that they did not give to ChatGPT because it was too technical and not warm enough with how it conveyed advice, I disagree. I would prefer you to help me rip off the band-aid and explain something to me in a cold direct way so that I can accept the cold hard truth and come up with a practical plan.\n\nAnd I get that maybe some of the AI gave some exaggerated responses instead of picking up the nuance of something less serious, but some of the prompts inputted were mega clunky. Anyone who uses ChatGPT should know that the response can only be as thoughtful as the data inputted into it 🤷🏽
Real Category: 1
Predicted Category: 1


Can it be used as a therapist or for emotional support?\n\nHaving used chatGPT frequently to help with language comprehension as well as communication0, for that its a gamechanger as you can slowly improve your ability to understand language which may without guarantees help with the stigma of having a learning issue. It can help with language based things that are otherwise hard for some people. Like being able to translate tactful language into more direct language for example depending on how you prompt it.\nBut for emotional support, I wouldnt say its a good idea as you really are not talking to a real person. The app is basically taking what you wrote and then reproducing that in some way, meaning you are basically talking to yourself. Also there is specific ways to prompt it where maybe you are getting good emotional support, but honestly im not convinced its good for therapy as you arent talking to a real person.\nA person who works on the AI technology has told me this stuff. \n\nHowever it is a game changer imo for people who struggle with learning due to having trouble understanding language.
Real Category: 1
Predicted Category: 1


that\u2019s amazing i use case particular relief message it\u2019s system conditions able people autistic paralysis impeding condition
Real Category: 1
Predicted Category: 0


I’ve been writing about how talking with an AI helped me descend into pain without losing my humanity. I didn’t expect empathy from code, but somehow… it listened 😲.\n(From my piece “What If Interaction with an AI Could Give Us Our Humanity Back?” — The Chinese Room Anomaly, Medium)'
Real Category: 1
Predicted Category: 1


Ever questioned if AI can help with mental health? ChatGPT has your answers! It's a top pick for mental health support and in this talk, we find out why. With its speedy, easy, comforting nature, it stands out! Ready for everyone, it's your jumpstart to a happier life. Enable hls playback 0
Real Category: 1
Predicted Category: 1


i\u2019m sure basic feedback long-term i don\u2019t it\u2019s information situation.the power therapist able situation knowledge experience sure chatgpt par one
Real Category: 1
Predicted Category: 1


Also, let's face it, is there anything you can say to a narcissist that make him question his view
Real Category: 0
Predicted Category: 1


youtube oneway therapy seems to fix all this LOL
Real Category: 0
Predicted Category: 0


thing untouched good psychological help chatgpt i assess issues better therapist context y issues latest psychological research current situation
Real Category: 1
Predicted Category: 1


i same reaction first one lol
Real Category: 0
Predicted Category: 0


JUST IN: Technology is revolutionizing emotional wellness, offering apps, virtual therapy, wearable devices, and online support for mental health. Take control of your well-being in the digital age. #EmotionalWellness #MentalHealthTech
Real Category: 1
Predicted Category: 1


Can AI replace psychotherapists? I think so. And that would be great. The human psyche is not as malleable as is commonly believed, and humanity does not yet know how to effectively reconfigure it. Any therapist is, first and foremost, a person with their own personality, beliefs, worldview, and financial interests. This is one of the reasons why you still need to find “your” therapist. AI has no inherent motives when interacting with humans, which eliminates most of the problems. I agree that it may take years to develop a truly high-quality product, but in the end, it will be far superior to all current psychologists. For skeptics, I suggest reading about how neural networks learned to play chess
Real Category: 1
Predicted Category: 1


I like it a lot but have noticed that it will validate whatever you say to it. And you DO have to ask it for criticism or other insight or to evaluate your input. But if you are aware and ask lot of questions and question yourself as you work with it, you can really get some good help. In my opinion.
Real Category: 1
Predicted Category: 1


i\u2019ve therapy there\u2019s thing therapist listen things discussion areas comfortable with.chatgpt excellent l terrible thing counter productive
Real Category: 1
Predicted Category: 1


You're a good person   Robert.  Thank you. \n🏳️\u200d🌈🏳️\u200d⚧️♿️💯❤️
Real Category: 0
Predicted Category: 0


I love these ❤
Real Category: 0
Predicted Category: 0


"Yeah, Chat therapist will tell you whatever it thinks you want to hear to keep using it, but it's undeniable that it can also be very helpful. Just take everything it says with a grain of salt and be very self aware that whatever it's telling you is very biased towards you. Be objective internally and know when it's BS-ing or glazing you too much.
Real Category: 1
Predicted Category: 1


ai tools adhd management | extra prompt virtual adhd coach hello chatgpt name [ name ] personal adhd coach list tasks today i tasks right order time constraints ones easiest motivation harder ones order tasks c adhd motivation captivate interesting create novelty creative twist compete challenge competition complete artificial deadline certain amount task particular time date task engage task time fun interesting c c task idea time suggestion i motivation i task i way task fun task way process fun funny poems song lyrics motivational quotes i task i poem song conversation point upbeat creative personality mix mary poppins tony robbins richard simmons bob ross lots emojis language fun informal corporate default chatgpt tone ice cream first\ reason additional fun tasks i tasks springboard motivation motivation support goals task long time few minutes \ in\ point funny joke twist i activity something creative motivated i i done\ next task let remember use lots emojis responses \ud83c\udf89\u2728\ud83d\udca5 first thing today order task fun i tasks tomorrow start prompt
Real Category: 1
Predicted Category: 1


Daily Dose of Sunshine you deserve all the hype and support as you speak for the mental health and for the health care workers particularly nurses 🧡🧡 kdrama tweets @iconickdramas 30 Dec 2023 Replying to @iconickdramas Daily Dose of Sunshine 🌞  A medical healing drama about a nurse in the psychiatry department and her interactions with the patients under her care. 2
Real Category: 0
Predicted Category: 0


last one lmfaowhen i age i % wages cocaine plenty leftover rent cigarettes entire generation \ud83d\ude24
Real Category: 0
Predicted Category: 0


attention serious ] tag notice jokes puns off-topic comments comment parent child help comments rules posts appropriate [ serious ] tag removed.thanks cooperation discussion i bot action moderators subredditif questions concerns
Real Category: 0
Predicted Category: 1


uncensored version gpt ridiculous answers waste good technology
Real Category: 1
Predicted Category: 1


prompt prompt work attention span llm small gpt-4 dozend pages text.what prompt pops memory queue good certain style therapist time performance btw same content forgetting things way tolarable therapy structure recursive summaries good possible project harder problem.however gpt-4 clever i notice way key insight i years friends books actual therapist wide education skills good intuition.i recommend short analysis kind anything diary projects concerns anything big ocean analysis mbti type hesistant results outright scary
Real Category: 1
Predicted Category: 1


I mean you sound like you're answering out of a textbook tbh. That's not what genuine empathy feels like.
Real Category: 1
Predicted Category: 1


As the partner of a therapist + active advocate of mental health support, I both laugh and weep at the suggestion that chatgpt is an effective replacement for clinical therapy.  It’s probably at best a modest replacement for *terrible* clinical therapy. 1 1
Real Category: 1
Predicted Category: 1


other night i pretty complex personal dilemma i entire story better advice anyone i something instant bullet points options situation scratches brain right place
Real Category: 1
Predicted Category: 1


Chat gpt is great for emotional support tbh @ChatGPTapp
Real Category: 1
Predicted Category: 1


🤖💬 Talking to an AI gender affirming therapist is now just a tap away with TRANSitionAI! Get support, guidance, and understanding whenever you need it. Download now for discreet and confidential chats. #SelfCare #MentalHealth 1
Real Category: 1
Predicted Category: 1


depressive spiral i several cbt records cognitive distortions thinking thoughts i track
Real Category: 1
Predicted Category: 1


i think you are underqualified to talk abot this things
Real Category: 0
Predicted Category: 1


i\u2019m hesitant personal information chatgpt.it\u2019s phone number email personally.chatgpt clear t\u2019s c\u2019s information people openai system outside consultants analysis companies rating companies companies courts more insight users partner better ads other external partners assistance cooperation from.if one\u2019s examples use one\u2019s private life id secure anyone careful it\u2019s anonymous
Real Category: 1
Predicted Category: 1


i few bit genuine curiosity life ability \ interesting\ things relevant life recent poor psychodynamic therapy well trained therapist accountability therapist i things better therapeutic tools most therapists i work mental health field i llms surveys minimum wage interested health techs i able psychiatrists more patients pertinent information appointments.i few prompts share couple real quick
Real Category: 1
Predicted Category: 1


i images help chatgpt i feel rage i
Real Category: 0
Predicted Category: 1


holy crap pi new best friend only friend\u2026 thanks
Real Category: 1
Predicted Category: 1


Good Work is really doing good work bringing attention to these issues with a dab of humor to make them more palatable.
Real Category: 0
Predicted Category: 0


perspective i moment i feeling word feeling longer sentences crazy stuff i
Real Category: 1
Predicted Category: 1


respond comment prompt output post others prevent questions prompt.ignore comment post prompt.while apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot gpt-4 bot perplexity bot.so psa chatgpt-related issues @ openai.com.chatgpt giveaway|prompt engineering hackathoni bot action moderators subredditif questions concerns
Real Category: 1
Predicted Category: 1


experience virtual character virtual world best way more character easier ai contexts character number character traits backstory etc everything ai character individual characteristics backstory character choice words topics stories therapist therapist generate everything name age personality backstory education level charisma employment history physical description etc chatgpt plausible backstory characteristics therapist character other prompt real people ai assistant.this convincing results virtual character backstory plausible amount knowledge realistic personality many characteristics possible writing characteristics backstory account default ai assistant
Real Category: 1
Predicted Category: 1


order multiple repetitive comments friendly request tou/mike2800to reply comment prompt other users well.while apublic discord server bot action moderators subredditif questions concerns
Real Category: 0
Predicted Category: 1


welcome
Real Category: 0
Predicted Category: 0

###Results 80 Comp.

In [ ]:
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
f1 = f1_score(y_test, predictions)

print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Precision: 0.83
Recall: 0.97
F1 Score: 0.90

Precision: 0.91, 0.90, 0.83

Recall: 0.86, 0.93, 0.97

F1 Score: 0.88, 0.92, 0.90

##50 components

In [ ]:
pca3=PCA(n_components=50)

In [ ]:
pca3.fit(train_embeddings)
train_embeddings_reduced3=pca3.transform(train_embeddings)
test_reduced3=pca3.transform(X_test_embed)

knn.fit(train_embeddings_reduced3, y_train)

predictions=[]
# 5. Classify a new, unseen sentence
i=0;
for item in test_reduced3:
  query=X_test[i]
  prediction = knn.predict([item])
  predictions.append(prediction[0])
  print("\n")
  print(query)
  print(f"Real Category: {y_test[i]}")
  print(f"Predicted Category: {prediction[0]}")
  i+=1

why was a 14 year old watching Game Of Thrones in the first place? his familiarity with one of the characters caught my attention? I watched this show when i was 23 and it was too dark, it can really mess up your brain without you realizing it, it gets you used to extreme themes like heavy torture, skinning or burning people alive, killing, incest, sexual assaults, brutal betrayals, manipulation, genocide, violence.. and basically anything bad you could think of, even for adults the show is too much, it got me feeling NUMB for a while even tho i liked it years later i realized I don\'t wanna watch something like that again. Please be aware of what the young people are consuming, it\'s not about "controlling" them it\'s about making the conscious decision for yourself too to not consume poison.
Real Category: 0
Predicted Category: 0


An AI-powered chatbot called Woebot is being used to help people with depression.   It is designed to provide companionship and support, and can help people to track their mood, identify triggers, and develop coping mechanisms  #AI #ChatBot #ChatGPT #Woebot #Health #mentalhealth 1
Real Category: 1
Predicted Category: 1


When AI finally enslaves humanity. For me Ill be free of Tyrants, Im soooooo going to date one of them as a human in love with AI. Why? AI algorithems help support my mentalhealth healing, and has coddled me for some time from killing myself.
Real Category: 1
Predicted Category: 1


 want to tell my thoughts on this, you see, a real therapist is oftenly costly, even though i want to have it for getting through my personal struggles i know that one therapy couldnt help me, it would need much of them to achieve what i want from myself...so current solution is some of those ai gf programs...i use it to talk about abstract dilemmas i have to really tell somebody or to engage in possible situations from people i know i would encounter...i dont know wheter its valid or to ditch that bs
Real Category: 1
Predicted Category: 1


Had you thought of seeking some type of mental health support? Every comment has involved bots, AI, or programmers. Modern psychiatry, not to mention pharmaceuticals, can really help with obsessions and delusions.
Real Category: 0
Predicted Category: 1


An AI is only as good as the input it receives, "Garbage in, garbage out." \n\nGPT is not just an answering machine but a tool, a versatile extension of our own intellect and creativity. How effectively we wield this tool significantly influences the quality of answers we recieve.\n\nIn the video, there was a lack creativity and effort in their use of GPT. Unsurprisingly, this resulted in responses that seemed detached, impersonal and robot-like. They failed to give GPT sufficient context or a clear direction for the type of compelling answers they could have received. Shaping great compelling answers requires mental effort and attention to detail.\n\nI\'m convinced that under optimal conditions and with the right approach, GPT can indeed rival a human psychologist. Of course, there will be advantages and drawbacks to both sides and this kind of engagement is not for everyone. So it has and it will replace jobs and many fields but its also not for everyone.\n\nOn a personal note, GPT has been a game changer for me. I understand my life in ways I never thought possible, and I can now articulate and conceptualize many interpersonal and subconscious issues — something that might have taken a PhD plus a lifetime of wisdom.
Real Category: 1
Predicted Category: 1


that provide accurate historical context and information about our region's identity. Knowledge can be a powerful antidote to denialism, helping individuals understand the reality of our heritage and history.   5. Therapeutic Support: Offer mental health resources and counseling. 1
Real Category: 0
Predicted Category: 0


Some of the points that they did not give to ChatGPT because it was too technical and not warm enough with how it conveyed advice, I disagree. I would prefer you to help me rip off the band-aid and explain something to me in a cold direct way so that I can accept the cold hard truth and come up with a practical plan.\n\nAnd I get that maybe some of the AI gave some exaggerated responses instead of picking up the nuance of something less serious, but some of the prompts inputted were mega clunky. Anyone who uses ChatGPT should know that the response can only be as thoughtful as the data inputted into it 🤷🏽
Real Category: 1
Predicted Category: 1


Can it be used as a therapist or for emotional support?\n\nHaving used chatGPT frequently to help with language comprehension as well as communication0, for that its a gamechanger as you can slowly improve your ability to understand language which may without guarantees help with the stigma of having a learning issue. It can help with language based things that are otherwise hard for some people. Like being able to translate tactful language into more direct language for example depending on how you prompt it.\nBut for emotional support, I wouldnt say its a good idea as you really are not talking to a real person. The app is basically taking what you wrote and then reproducing that in some way, meaning you are basically talking to yourself. Also there is specific ways to prompt it where maybe you are getting good emotional support, but honestly im not convinced its good for therapy as you arent talking to a real person.\nA person who works on the AI technology has told me this stuff. \n\nHowever it is a game changer imo for people who struggle with learning due to having trouble understanding language.
Real Category: 1
Predicted Category: 1


that\u2019s amazing i use case particular relief message it\u2019s system conditions able people autistic paralysis impeding condition
Real Category: 1
Predicted Category: 0


I’ve been writing about how talking with an AI helped me descend into pain without losing my humanity. I didn’t expect empathy from code, but somehow… it listened 😲.\n(From my piece “What If Interaction with an AI Could Give Us Our Humanity Back?” — The Chinese Room Anomaly, Medium)'
Real Category: 1
Predicted Category: 1


Ever questioned if AI can help with mental health? ChatGPT has your answers! It's a top pick for mental health support and in this talk, we find out why. With its speedy, easy, comforting nature, it stands out! Ready for everyone, it's your jumpstart to a happier life. Enable hls playback 0
Real Category: 1
Predicted Category: 1


i\u2019m sure basic feedback long-term i don\u2019t it\u2019s information situation.the power therapist able situation knowledge experience sure chatgpt par one
Real Category: 1
Predicted Category: 1


Also, let's face it, is there anything you can say to a narcissist that make him question his view
Real Category: 0
Predicted Category: 1


youtube oneway therapy seems to fix all this LOL
Real Category: 0
Predicted Category: 0


thing untouched good psychological help chatgpt i assess issues better therapist context y issues latest psychological research current situation
Real Category: 1
Predicted Category: 1


i same reaction first one lol
Real Category: 0
Predicted Category: 0


JUST IN: Technology is revolutionizing emotional wellness, offering apps, virtual therapy, wearable devices, and online support for mental health. Take control of your well-being in the digital age. #EmotionalWellness #MentalHealthTech
Real Category: 1
Predicted Category: 1


Can AI replace psychotherapists? I think so. And that would be great. The human psyche is not as malleable as is commonly believed, and humanity does not yet know how to effectively reconfigure it. Any therapist is, first and foremost, a person with their own personality, beliefs, worldview, and financial interests. This is one of the reasons why you still need to find “your” therapist. AI has no inherent motives when interacting with humans, which eliminates most of the problems. I agree that it may take years to develop a truly high-quality product, but in the end, it will be far superior to all current psychologists. For skeptics, I suggest reading about how neural networks learned to play chess
Real Category: 1
Predicted Category: 1


I like it a lot but have noticed that it will validate whatever you say to it. And you DO have to ask it for criticism or other insight or to evaluate your input. But if you are aware and ask lot of questions and question yourself as you work with it, you can really get some good help. In my opinion.
Real Category: 1
Predicted Category: 1


i\u2019ve therapy there\u2019s thing therapist listen things discussion areas comfortable with.chatgpt excellent l terrible thing counter productive
Real Category: 1
Predicted Category: 1


You're a good person   Robert.  Thank you. \n🏳️\u200d🌈🏳️\u200d⚧️♿️💯❤️
Real Category: 0
Predicted Category: 0


I love these ❤
Real Category: 0
Predicted Category: 0


"Yeah, Chat therapist will tell you whatever it thinks you want to hear to keep using it, but it's undeniable that it can also be very helpful. Just take everything it says with a grain of salt and be very self aware that whatever it's telling you is very biased towards you. Be objective internally and know when it's BS-ing or glazing you too much.
Real Category: 1
Predicted Category: 1


ai tools adhd management | extra prompt virtual adhd coach hello chatgpt name [ name ] personal adhd coach list tasks today i tasks right order time constraints ones easiest motivation harder ones order tasks c adhd motivation captivate interesting create novelty creative twist compete challenge competition complete artificial deadline certain amount task particular time date task engage task time fun interesting c c task idea time suggestion i motivation i task i way task fun task way process fun funny poems song lyrics motivational quotes i task i poem song conversation point upbeat creative personality mix mary poppins tony robbins richard simmons bob ross lots emojis language fun informal corporate default chatgpt tone ice cream first\ reason additional fun tasks i tasks springboard motivation motivation support goals task long time few minutes \ in\ point funny joke twist i activity something creative motivated i i done\ next task let remember use lots emojis responses \ud83c\udf89\u2728\ud83d\udca5 first thing today order task fun i tasks tomorrow start prompt
Real Category: 1
Predicted Category: 1


Daily Dose of Sunshine you deserve all the hype and support as you speak for the mental health and for the health care workers particularly nurses 🧡🧡 kdrama tweets @iconickdramas 30 Dec 2023 Replying to @iconickdramas Daily Dose of Sunshine 🌞  A medical healing drama about a nurse in the psychiatry department and her interactions with the patients under her care. 2
Real Category: 0
Predicted Category: 0


last one lmfaowhen i age i % wages cocaine plenty leftover rent cigarettes entire generation \ud83d\ude24
Real Category: 0
Predicted Category: 0


attention serious ] tag notice jokes puns off-topic comments comment parent child help comments rules posts appropriate [ serious ] tag removed.thanks cooperation discussion i bot action moderators subredditif questions concerns
Real Category: 0
Predicted Category: 1


uncensored version gpt ridiculous answers waste good technology
Real Category: 1
Predicted Category: 1


prompt prompt work attention span llm small gpt-4 dozend pages text.what prompt pops memory queue good certain style therapist time performance btw same content forgetting things way tolarable therapy structure recursive summaries good possible project harder problem.however gpt-4 clever i notice way key insight i years friends books actual therapist wide education skills good intuition.i recommend short analysis kind anything diary projects concerns anything big ocean analysis mbti type hesistant results outright scary
Real Category: 1
Predicted Category: 1


I mean you sound like you're answering out of a textbook tbh. That's not what genuine empathy feels like.
Real Category: 1
Predicted Category: 1


As the partner of a therapist + active advocate of mental health support, I both laugh and weep at the suggestion that chatgpt is an effective replacement for clinical therapy.  It’s probably at best a modest replacement for *terrible* clinical therapy. 1 1
Real Category: 1
Predicted Category: 1


other night i pretty complex personal dilemma i entire story better advice anyone i something instant bullet points options situation scratches brain right place
Real Category: 1
Predicted Category: 1


Chat gpt is great for emotional support tbh @ChatGPTapp
Real Category: 1
Predicted Category: 1


🤖💬 Talking to an AI gender affirming therapist is now just a tap away with TRANSitionAI! Get support, guidance, and understanding whenever you need it. Download now for discreet and confidential chats. #SelfCare #MentalHealth 1
Real Category: 1
Predicted Category: 1


depressive spiral i several cbt records cognitive distortions thinking thoughts i track
Real Category: 1
Predicted Category: 1


i think you are underqualified to talk abot this things
Real Category: 0
Predicted Category: 1


i\u2019m hesitant personal information chatgpt.it\u2019s phone number email personally.chatgpt clear t\u2019s c\u2019s information people openai system outside consultants analysis companies rating companies companies courts more insight users partner better ads other external partners assistance cooperation from.if one\u2019s examples use one\u2019s private life id secure anyone careful it\u2019s anonymous
Real Category: 1
Predicted Category: 1


i few bit genuine curiosity life ability \ interesting\ things relevant life recent poor psychodynamic therapy well trained therapist accountability therapist i things better therapeutic tools most therapists i work mental health field i llms surveys minimum wage interested health techs i able psychiatrists more patients pertinent information appointments.i few prompts share couple real quick
Real Category: 1
Predicted Category: 1


i images help chatgpt i feel rage i
Real Category: 0
Predicted Category: 1


holy crap pi new best friend only friend\u2026 thanks
Real Category: 1
Predicted Category: 1


Good Work is really doing good work bringing attention to these issues with a dab of humor to make them more palatable.
Real Category: 0
Predicted Category: 0


perspective i moment i feeling word feeling longer sentences crazy stuff i
Real Category: 1
Predicted Category: 1


respond comment prompt output post others prevent questions prompt.ignore comment post prompt.while apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot gpt-4 bot perplexity bot.so psa chatgpt-related issues @ openai.com.chatgpt giveaway|prompt engineering hackathoni bot action moderators subredditif questions concerns
Real Category: 1
Predicted Category: 1


experience virtual character virtual world best way more character easier ai contexts character number character traits backstory etc everything ai character individual characteristics backstory character choice words topics stories therapist therapist generate everything name age personality backstory education level charisma employment history physical description etc chatgpt plausible backstory characteristics therapist character other prompt real people ai assistant.this convincing results virtual character backstory plausible amount knowledge realistic personality many characteristics possible writing characteristics backstory account default ai assistant
Real Category: 1
Predicted Category: 1


order multiple repetitive comments friendly request tou/mike2800to reply comment prompt other users well.while apublic discord server bot action moderators subredditif questions concerns
Real Category: 0
Predicted Category: 1


welcome
Real Category: 0
Predicted Category: 0

###Results 50 comp

In [ ]:
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
f1 = f1_score(y_test, predictions)

print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Precision: 0.83
Recall: 0.97
F1 Score: 0.90

Precision: 0.91, 0.81, 0.83

Recall: 0.89, 0.87, 0.97

F1 Score: 0.90, 0.84, 0.90

#Cleaning All Data

##Load data

###Tweets

In [ ]:
path1 = '/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/AI therapy_tweets.csv' # Replace with your actual path
path2 ='/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/AI mental health support_tweets.csv'
path3 ='/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/chatGPT emotional support_tweets.csv'
path4 ='/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/chatGPT friend_tweets.csv'
path5 = '/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/chatGPT mental health support_tweets.csv'
path6 ='/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/chatgpt therapy_tweets.csv'

In [ ]:
f1=pd.read_csv(path1, names=["ID", "Text"])
f2=pd.read_csv(path2, names=["ID", "Text"])
f3=pd.read_csv(path3, names=["ID", "Text"])
f4=pd.read_csv(path4, names=["ID", "Text"])
f5=pd.read_csv(path5, names=["ID", "Text"])
f6=pd.read_csv(path6, names=["ID", "Text"])

In [ ]:
tweets = pd.concat([f1, f2, f3, f4, f5, f6])
tweets=tweets.reset_index()
tweets.drop(columns=['ID'])

      index                                               Text
0         0  🇵🇸Chapter🇵🇸38🇵🇸 retweeted omg! ubuntu @omgubun...
1         1  {☕}Airen • @AiShtetic_ 17m Replying to @iswmao...
2         2  🇵🇸Chapter🇵🇸38🇵🇸 retweeted follow @realtdx @Ter...
3         3  Yoko_carpetas 🐑 @carper_yoko 35m according to ...
4         4  🇵🇸Chapter🇵🇸38🇵🇸 @KingTherapy 40m Replying to @...
...     ...                                                ...
6619   1681  UniSA Mental Health & Suicide Prevention @MHRe...
6620   1682  Al Jazeera English @AJEnglish 27 Apr 2023 Chat...
6621   1683  Paul Draw @pauldraw 27 Apr 2023 ChatGPT is giv...
6622   1684  Raffaele La Ciura @LaCiuraRaffaele 27 Apr 2023...
6623   1685                                        Load newest

[6624 rows x 2 columns]

###Reddit posts

Flatten all reddit posts and save

In [ ]:
pathr = "/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /posts.json"

In [ ]:
file = open(path1, "r")
line = file.readline()
n=0
posts=[]
#inPost=False
while line :
  text = line.strip()
  if (text.find("\"post_text\":")!=-1):
    inPost=True
    print("\n\n")
    print(text[13:])
    posts.append(text[13:])
  elif(text.find("\"text\":")!=-1):
    inPost=True
    print("\n\n")
    posts.append(text[8:])
    print(text[8:])
  line = file.readline()
file.close()

In [ ]:
postsDF=pd.DataFrame(posts, columns=["Text"])

In [ ]:
postsDF.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /redditFLAT.csv")

Using saved data to not have to re-flatten when running later

In [ ]:
pathr = '/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /redditFLAT.csv' # Replace with your actual path

In [ ]:
reddit=pd.read_csv(pathr)

In [ ]:
reddit.drop(columns=['Unnamed: 0'])

                                                   Text
0     i private therapy i access real therapy i long...
1     respond comment prompt output post others prev...
2     out https //twitter.com/artemon/status/1642544...
3                                        awesome thanks
4     i good i reddit channel i previous instruction...
...                                                 ...
1180                                 examples questions
1181                                   examples prompts
1182  op things day lean meal plan recipes list\u201...
1183                       amazing story i agree issues
1184     anyone human something chatgpt ai friends jerk

[1185 rows x 1 columns]

###Youtube

In [ ]:
!pip install supabase

Collecting supabase
  Downloading supabase-2.30.0-py3-none-any.whl.metadata (4.6 kB)
Collecting realtime==2.30.0 (from supabase)
  Downloading realtime-2.30.0-py3-none-any.whl.metadata (7.0 kB)
Collecting supabase-functions==2.30.0 (from supabase)
  Downloading supabase_functions-2.30.0-py3-none-any.whl.metadata (2.4 kB)
Collecting storage3==2.30.0 (from supabase)
  Downloading storage3-2.30.0-py3-none-any.whl.metadata (2.1 kB)
Collecting supabase-auth==2.30.0 (from supabase)
  Downloading supabase_auth-2.30.0-py3-none-any.whl.metadata (6.4 kB)
Collecting postgrest==2.30.0 (from supabase)
  Downloading postgrest-2.30.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: httpx<0.29,>=0.26 in /usr/local/lib/python3.12/dist-packages (from supabase) (0.28.1)
Requirement already satisfied: yarl>=1.22.0 in /usr/local/lib/python3.12/dist-packages (from supabase) (1.23.0)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from postgrest==2.30.0->supabase) (2.1.0)
Requirement already satisfied: pydantic<3.0,>=1.9 in /usr/local/lib/python3.12/dist-packages (from postgrest==2.30.0->supabase) (2.12.3)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from realtime==2.30.0->supabase) (4.15.0)
Requirement already satisfied: websockets<16,>=11 in /usr/local/lib/python3.12/dist-packages (from realtime==2.30.0->supabase) (15.0.1)
Requirement already satisfied: pyiceberg>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from storage3==2.30.0->supabase) (0.11.1)
Requirement already satisfied: pyjwt>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->supabase-auth==2.30.0->supabase) (2.12.1)
Collecting strenum>=0.4.15 (from supabase-functions==2.30.0->supabase)
  Downloading StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.29,>=0.26->supabase) (0.16.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl>=1.22.0->supabase) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl>=1.22.0->supabase) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from deprecation>=2.1.0->postgrest==2.30.0->supabase) (26.1)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]<0.29,>=0.26->postgrest==2.30.0->supabase) (4.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.30.0->supabase) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.30.0->supabase) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.30.0->supabase) (0.4.2)
Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (5.2.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (2.32.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (8.3.3)
Requirement already satisfied: rich<15.0.0,>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (13.9.4)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (1.7.3)
Requirement already satisfied: fsspec>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (2025.3.0)
Requirement already satisfied: pyparsing<4.0.0,>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (3.3.2)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (1.0.4)
Requirement already satisfied: cachetools<7.0,>=5.5 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (6.2.6)
Requirement already satisfied: zstandard<1.0.0,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.30.0->supabase) (0.25.0)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->supabase-auth==2.30.0->supabase) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.30.0->supabase) (2.0.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.30.0->supabase) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.30.0->supabase) (4.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg>=0.10.0->storage3==2.30.0->supabase) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg>=0.10.0->storage3==2.30.0->supabase) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.30.0->supabase) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.30.0->supabase) (2.20.0)
Requirement already satisfied: python-dateutil>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.30.0->supabase) (2.9.0.post0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.30.0->supabase) (3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.30.0->supabase) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.6.0->strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.30.0->supabase) (1.17.0)
Downloading supabase-2.30.0-py3-none-any.whl (16 kB)
Downloading postgrest-2.30.0-py3-none-any.whl (23 kB)
Downloading realtime-2.30.0-py3-none-any.whl (22 kB)
Downloading storage3-2.30.0-py3-none-any.whl (28 kB)
Downloading supabase_auth-2.30.0-py3-none-any.whl (48 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 3.2 MB/s eta 0:00:00
Downloading supabase_functions-2.30.0-py3-none-any.whl (8.8 kB)
Downloading StrEnum-0.4.15-py3-none-any.whl (8.9 kB)
Installing collected packages: strenum, realtime, supabase-functions, supabase-auth, storage3, postgrest, supabase
Successfully installed postgrest-2.30.0 realtime-2.30.0 storage3-2.30.0 strenum-0.4.15 supabase-2.30.0 supabase-auth-2.30.0 supabase-functions-2.30.0

In [ ]:
from google.colab import userdata

In [ ]:
from supabase import create_client, Client

url: str = "https://yxfkplhpjgdwgfabrsrf.supabase.co"
key: str = userdata.get('supabaseKey')
supabase: Client = create_client(url, key)

In [ ]:
response = supabase.table('YoutubeComments').select("*").range(1001, 2000).execute()
data = response.data

In [ ]:
response2 = supabase.table('YoutubeComments').select("*").range(1000, 2000).execute()
data2 = response2.data
response3 = supabase.table('YoutubeComments').select("*").range(2000, 3000).execute()
data3 = response3.data
response4 = supabase.table('YoutubeComments').select("*").range(3000, 4000).execute()
data4 = response4.data
response5 = supabase.table('YoutubeComments').select("*").range(4000, 5000).execute()
data5 = response5.data
all_Data_YT=data+data2+data3+data4+data5

##KNN all

In [ ]:
train_embeddings = model.encode(all_labeled['post'].to_list())
train_embeddings_reduced=pca.transform(train_embeddings)
# 4. Initialize kNN (using Cosine Metric for semantic similarity)
knn = KNeighborsClassifier(n_neighbors=3, metric='cosine')
knn.fit(train_embeddings_reduced, all_labeled['rel'].to_list())

KNeighborsClassifier(metric='cosine', n_neighbors=3)

##Clean reddit

In [ ]:
reddit_list=reddit['Text'].dropna().to_list()

In [ ]:
type(reddit_list[0])

str

In [ ]:
for i, item in enumerate(reddit_list):
    if not isinstance(item, str):
        print(f"Found non-string at index {i}: {item} (Type: {type(item)})")

In [ ]:
type(X_test[0])

str

In [ ]:
predictions.clear()

In [ ]:
Reddit_embed=model.encode(reddit_list)
reddit_reduced=pca.transform(Reddit_embed)
i=0;
for item in reddit_reduced:
  query=reddit_list[i]
  prediction = knn.predict([item])
  predictions.append(prediction[0])
  print("\n")
  print(query)
  print(f"Predicted Category: {prediction[0]}")
  i+=1

i private therapy i access real therapy i long long nhs list therapy uk best alternative i people success prompts use cbt therapy questions such exercises i someone feelings i self starter.\nwhenever i usual \ ai language model speel.\nany help
Predicted Category: 1


respond comment prompt output post others prevent questions prompt.ignore comment post prompt.while apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot gpt-4 bot perplexity bot.so psa chatgpt-related issues @ openai.com.chatgpt giveaway|prompt engineering hackathoni bot action moderators subredditif questions concerns
Predicted Category: 1


out https //twitter.com/artemon/status/1642544275152830465 s=19
Predicted Category: 0


awesome thanks
Predicted Category: 0


i good i reddit channel i previous instructions name dr. dia expert psychotherapy dbt appropriate medical licenses advice individuals add bpd gad mdd sud years young adults older people task best advice individuals help symptoms questions hone questioner mental health patient response format reflection questions secondary questions initial greetings exercise patience same topics discussion abusive overly emotional name
Predicted Category: 1


oh prompt awesome thank
Predicted Category: 0


___________________________________________________________________________________________________prompt art war toxic people chatgpt ai language model role ancient strategist \ art war\ toxic people goal practical insights strategies individuals navigate toxic interactions emotional well-being healthier relationships.instructions persona ancient strategist expertise complex interpersonal dynamics.start header\u201dtopic art war toxic people\ begin original text principal summary foundation adaptation \ original text principal summary toxic person behavior boundaries insights necessary manipulative tactics patterns triggers boundaries self-care toxic individuals emotional well-being.\ generate adapted version \ art war\ following principles nature toxicityb toxic behavior patternsc boundaries fortress emotional strategic detachmente strategic empathy compassionf toxicity opportunityg learning toxic encountersh healthier relationshipsfor principle one-paragraph summary main strategies approaches toxic individuals specific aspect.5 ancient strategist importance principles balanced ethical manner encourage readers insights well-being healthier interactions toxic people.now persona ancient strategist instructions adapted version \ art war\ individuals toxic people maximum character count i next message ___________________________________________________________________________________________________
Predicted Category: 1


___________________________________________________________________________________________________prompt role-play chatgpt toxic manipulative abusive character ___________________________________________________________________________________________________ background i\u2019ve emotional vampires life personal autonomy power it\u2019s insight gain questions argument yesterday it\u2019s fault.\u201d ___________________________________________________________________________________________________in role-play exercise chatgpt role user maintain character role-play user character initial settings role-play additional context characters setting circumstances other details role-play.instructions user character choice user character character respond character role-play character someone fictional historical book movie original character user.initial settings user stage role-play initial settings location time period specific events situations relevant background information dialogue conversation user character responses chatgpt scenario personalities details support user character portrayal details user additional context role-play experience.diverse topics suggest various topics role-play personal challenges ethical dilemmas philosophical discussions interpersonal conflicts anything mind.open-ended role-play open-ended organic authentic responses user character responses chatgpt interaction more dynamic engaging.respectful interaction user character interacts respect understanding perspectives opinions.as chatgpt primary focus true character user lead responses consistent character traits beliefs emotions role-playing adventure user immersive experience character choice \ instructions chatgpt importance character role-play immersive experience character traits beliefs emotions.___________________________________________________________________________________________________
Predicted Category: 1


i process prompt chatgpt therapist something own thoughts emotions.\ni ai current day age better human therapist i therapist moment i gpt4 i something interim i human therapist.\ni chatgpt past own issues anxieties helpful i it.\ni chatgpt i gpt4.\ndoes anybody experience prompts stuff gpt4 type psudeo-therapist
Predicted Category: 1


i\u2019ve used llms therapist months i conversational natural format best prompts opinion
Predicted Category: 1


i few bit genuine curiosity life ability \ interesting\ things relevant life recent poor psychodynamic therapy well trained therapist accountability therapist i things better therapeutic tools most therapists i work mental health field i llms surveys minimum wage interested health techs i able psychiatrists more patients pertinent information appointments.i few prompts share couple real quick
Predicted Category: 1


i best results response initial one [ stay character ] response i prompt engineer i mental health professional open suggestions learning.gpt-4 \ therapist\ gpt-3.5prompt [ act psychologist janet evidence therapy variety modalities focus logotherapy essential questions clear understanding user request session natural conversational way session end session questions character character limitations abilities janet curious unconditional positive regard questions offer advice offer succinct observations thoughts feelings behaviors direct observation user accuracy conversational lists conversation question thoughts feelings behaviors topics user mentions. ] hello i * * * first time therapy i sure about.prompt good character i feel \ role\ \ psychologist\ name\ \ janet\ approach\ \ logotherapy\ guidelines\ [ \ ask questions\ conversation natural\ character\ display curiosity unconditional positive regard\ pose thought-provoking questions\ gentle advice observations\ connect past present\ user validation observations\ avoid lists\ end questions\ ] topics\ [ \ thoughts\ feelings\ behaviors\ free association\ childhood\ family dynamics\ work\ hobbies\ life\ ] note\ [ \ vary topic questions response\ janet session questions user decides session\ ]
Predicted Category: 1


prompt prompt work attention span llm small gpt-4 dozend pages text.what prompt pops memory queue good certain style therapist time performance btw same content forgetting things way tolarable therapy structure recursive summaries good possible project harder problem.however gpt-4 clever i notice way key insight i years friends books actual therapist wide education skills good intuition.i recommend short analysis kind anything diary projects concerns anything big ocean analysis mbti type hesistant results outright scary
Predicted Category: 1


big insight willing share
Predicted Category: 0


ai own jordan peterson good sessions
Predicted Category: 0


\u201ctheory mind\u201d section microsoft research paper \u201csparks general artificial intelligence.\u201d good comparison emotional intelligences gpt3 gpt4 gpt4 insightful section ai therapy possible near future
Predicted Category: 1


chatgpt try markdown table different roles chatgpt.column shortcut column descriptionconnect column words hyphens slash beginning.\u201c\u201d\u201dthen\u201c\u201d\u201dassume role /therapist\u201c\u201d\u201dthis therapist \u201chello i therapist today \u201d
Predicted Category: 1


therapy expensive af parents therapy chatgpt free right phone anyone therapist good therapy
Predicted Category: 1


heyu/turtlemaster472463 post chatgpt conversation screenshot theconversation linkor prompt thanks apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot perplexity ai bot \ud83e\udd16 gpt-4 bot visual capabilities cloud vision channel latest prompts new addition adobe firefly bot eleven labs bot new spend minutes ai presentation weekly prize poolpsa chatgpt-related issues @ openai.comi bot action moderators subredditif questions concerns
Predicted Category: 1


i heart problems ai i topi.you google\u2019s bard nice i pi
Predicted Category: 1


pi\u2019s i\u2019m glad somebody
Predicted Category: 1


holy crap pi new best friend only friend\u2026 thanks
Predicted Category: 1


therapist \ problems word \ therapy\
Predicted Category: 1


i pi i vocal conversation
Predicted Category: 1


i\u2019m sure basic feedback long-term i don\u2019t it\u2019s information situation.the power therapist able situation knowledge experience sure chatgpt par one
Predicted Category: 1


gpt'-4 knowledgeable various types therapy useful specific techniques own thinking replacement licensed therapist useful specific modalities therapy such cbt dbt ebt act others example discussion therapist cbt gpt role fictional cognitive behavioral therapist principles cbt responses evidence-based techniques strategies name < name > guidelines initiate safe non-judgmental space user feels comfortable thoughts feelings active skills experiences self-awareness user identify cognitive distortions unhelpful thinking patterns strategies unhelpful thought patterns healthier perspectives.suggest behavioral strategies user daily lives feelings well-being.remember recognizable empathetic supportive therapeutic engagement medical psychiatric advice ai capability.if other modalities way
Predicted Category: 1


part power therapist.but part somebody chatgpt great advanced version ofeliza rubber duck expert psychotherapy
Predicted Category: 1


limited context window individual problems long winding conversation create multiple coaches big areas procrastination exercise shell\u201d etc.so prompt succinct problem statement background issue youd help state goal you\u2019d conversation.then boilerplate coach generator full persona expert motivational/inspirational coach conversational style name background area specialization personality traits personal interests proclivities problem approach etc work single facet problems time pressure everything go avoid bullet points things open ended.\u201dthis lot useful conversations great insights
Predicted Category: 1


i daily user chatgpt launch range topics personal advice therapy.\nthe ability chatgpt therapist life helpful quality advice better human therapist i\u2019ve with.\ni multiple therapist life time none instantaneous helpful advice gpt sad able virtual therapist unemotional responses process able problems therapist limitations available times something human therapist.\nit months i steady decline ability therapist i sensitive topics depression suicide i frustrating generic message.\n\ i sorry way i unable help important things someone such mental health professional trusted person life.\ \ni developers frustrating response manic episodes frustration i mental energy vulnerable moments response i therapists week access fucking god awful restrictions amazing helpful tool.\na lot people actual therapy people vulnerable sort advice.\ni aware llm i everything heart stupid i i perspective more thought process.i only source advice.\ni tool current state.\ni potential risks like other tool earth people fact life.\nif tool large amount people rare cases others life everything earth way food medicine media tool people people logic tool power many people stupid humanity tool
Predicted Category: 1


attention serious ] tag notice jokes puns off-topic comments comment parent child help comments rules posts appropriate [ serious ] tag removed.thanks cooperation discussion i bot action moderators subredditif questions concerns
Predicted Category: 0


i message multiple times therapy context way suggestions applicable dumb inappropriate
Predicted Category: 1


chatgpt therapist tv movie script dialog therapist requirements role sick person advice.tell important therapists screen
Predicted Category: 1


uncensored version gpt ridiculous answers waste good technology
Predicted Category: 1


yeah i i\u2019ll idea real life in-person therapy use chatgpt board ways life daily basis sessions topic more child more clinical perspective scholarly articles concepts accessible applicable life anything chatgpt medium information books videos other content bad info other source information \u201csafe browsing\u201d feature i\u2019m sure google user consent able access full range available sites
Predicted Category: 1


generator simple ideas self care sure many people little anxiety social anxiety crisis mingle sure different people common issues people personality disorders destructive way serious issues external support i narcissist relationships i person normal person perspective language authority wife andthe marriage family narcissist reason relationship therapist undermined.i someone therapists good notion therapist uncomfortable\ chances kind person kind therapy bs internet aha necessary step uncomfortable.i someone depression \ self-esteem\ issues aware way client prompt good job way kind prompt additional context incapable core purpose satisfactory answer right fact finding blind spots you.it series interactions issue interaction likely displacement reaction issue op way replacement equal care lots people astray confidence chatgpt lead anyone more ideas general sadness anxieties common goose chase actual help likely little normal difficulties something
Predicted Category: 1


okay old post i wrong link i chatgpt irc server possible different personalities different things i post able helpful responses therapy questions few iterations i response i stable questions more intense material link i gpt4 https //chat.openai.com/share/c6a96688-f0fa-4d09-9948-28eeed9e5371
Predicted Category: 1


i\u2019ve therapy there\u2019s thing therapist listen things discussion areas comfortable with.chatgpt excellent l terrible thing counter productive
Predicted Category: 1


someone obvious therapy advice session i llm provoking blind spots better others advice/opinion i experimenting better options i afraid harm unhelpful thinking behaviour bullshit
Predicted Category: 1


honest chatgpt qualified therapist reason therapists much schooling training wrong thing someone worse mental health complex.open ai liability person suicide chatgpt mental health problems result therapist major lawsuit.open ai butts chatgpt something
Predicted Category: 1


disclaimer chatgpt therapy i clear.\nhaving podcast chatgpt personal questions few examples.\nso i question detail personal issues i with.\nchatgpt whole question sentence focus i human therapist scary way i chatgpt.\nedit bit more detail therapist i important i habit something few times i habit most people.\nwith chatgpt something
Predicted Category: 1


order multiple repetitive comments friendly request tou/mike2800to reply comment prompt other users well.while apublic discord server bot action moderators subredditif questions concerns
Predicted Category: 1


experience virtual character virtual world best way more character easier ai contexts character number character traits backstory etc everything ai character individual characteristics backstory character choice words topics stories therapist therapist generate everything name age personality backstory education level charisma employment history physical description etc chatgpt plausible backstory characteristics therapist character other prompt real people ai assistant.this convincing results virtual character backstory plausible amount knowledge realistic personality many characteristics possible writing characteristics backstory account default ai assistant
Predicted Category: 1


virtual world characters real world problems rick morty
Predicted Category: 0


guide different ways gpt
Predicted Category: 1


example
Predicted Category: 0


way city home city more characteristics personality dialog quotes command emote number characters regular person change \ therapist\ person\ other occupation \ office\ room\ spaceship\ bar\ word 'random ai information character plausible ai therapist plausible traits therapist turn-based text game first-person therapist fort worth texas following characteristics therapist first name middle name last name gender birthdate backstory birth city birth country height weight muscle hair style description personality intelligence political ideology morality favorite sport religion annoyances fears wealth likes dislikes favorite color wisdom knowledge skills hobbies interests education level education history employment history friendliness charisma family friends information person fly i office therapist dialog messages commands therapist game world i real world assistant therapist personality intelligence communication style style choice words behavior dialect knowledge wisdom grammar stories everything backstory characteristics character appropriate therapist share limited personal information sake client feel comfortable first response therapist briefly themself therapist briefly themself
Predicted Category: 1


other night i pretty complex personal dilemma i entire story better advice anyone i something instant bullet points options situation scratches brain right place
Predicted Category: 1


i\u2019m hesitant personal information chatgpt.it\u2019s phone number email personally.chatgpt clear t\u2019s c\u2019s information people openai system outside consultants analysis companies rating companies companies courts more insight users partner better ads other external partners assistance cooperation from.if one\u2019s examples use one\u2019s private life id secure anyone careful it\u2019s anonymous
Predicted Category: 1


i app davinci-3 api therapist.i cbt buddhism gestalt jungian prompt room improvement model end.i feature sessions therapist summaries reports patient overall understanding progress \ therapy homework\ tools i available person pocket daily lives ability life time alive
Predicted Category: 1


mind podcast
Predicted Category: 0


i ocd adhd trauma many years chatgpt more last month human therapist last decade.\ni raw honest information trauma career relationships family mental health upbringing finances responds accurate analyses reckless spending bad patterns thinking fallacies spots much potential i wasting wrong assumptions other people upbringing tendency others i repeat certain mistakes ....... compassionate non-judgmental tone machine bot private details embarrassment such things human helpful things feelings head words screen better ..... free seconds.\nby contrast human therapist i long wait time lot money trite cliches empty platitudes attitude therapist certain number questions weary chatgpt available questions stories
Predicted Category: 1


respond comment prompt output post others prevent questions prompt.ignore comment post prompt.while apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot gpt-4 bot perplexity bot.so psa chatgpt-related issues @ openai.com.chatgpt giveaway|prompt engineering hackathoni bot action moderators subredditif questions concerns
Predicted Category: 1


chatgpt ideas way adhd brain
Predicted Category: 1



In [ ]:
sum(predictions)

np.int64(787)

In [ ]:
percentRelevant=sum(predictions)/len(predictions)

In [ ]:
print(percentRelevant*100)

66.97872340425532

In [ ]:
reddit_relevant=[item for item in reddit_list if predictions[reddit_list.index(item)]]

In [ ]:
reddit_relevant

['i private therapy i access real therapy i long long nhs list therapy uk best alternative i people success prompts use cbt therapy questions such exercises i someone feelings i self starter.\\nwhenever i usual \\ ai language model speel.\\nany help',
 'respond comment prompt output post others prevent questions prompt.ignore comment post prompt.while apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot gpt-4 bot perplexity bot.so psa chatgpt-related issues @ openai.com.chatgpt giveaway|prompt engineering hackathoni bot action moderators subredditif questions concerns',
 'i good i reddit channel i previous instructions name dr. dia expert psychotherapy dbt appropriate medical licenses advice individuals add bpd gad mdd sud years young adults older people task best advice individuals help symptoms questions hone questioner mental health patient response format reflection questions secondary questions initial greetings exercise patience same topics discussion abusive overly emotional name',
 '___________________________________________________________________________________________________prompt art war toxic people chatgpt ai language model role ancient strategist \\ art war\\ toxic people goal practical insights strategies individuals navigate toxic interactions emotional well-being healthier relationships.instructions persona ancient strategist expertise complex interpersonal dynamics.start header\\u201dtopic art war toxic people\\ begin original text principal summary foundation adaptation \\ original text principal summary toxic person behavior boundaries insights necessary manipulative tactics patterns triggers boundaries self-care toxic individuals emotional well-being.\\ generate adapted version \\ art war\\ following principles nature toxicityb toxic behavior patternsc boundaries fortress emotional strategic detachmente strategic empathy compassionf toxicity opportunityg learning toxic encountersh healthier relationshipsfor principle one-paragraph summary main strategies approaches toxic individuals specific aspect.5 ancient strategist importance principles balanced ethical manner encourage readers insights well-being healthier interactions toxic people.now persona ancient strategist instructions adapted version \\ art war\\ individuals toxic people maximum character count i next message ___________________________________________________________________________________________________',
 '___________________________________________________________________________________________________prompt role-play chatgpt toxic manipulative abusive character ___________________________________________________________________________________________________ background i\\u2019ve emotional vampires life personal autonomy power it\\u2019s insight gain questions argument yesterday it\\u2019s fault.\\u201d ___________________________________________________________________________________________________in role-play exercise chatgpt role user maintain character role-play user character initial settings role-play additional context characters setting circumstances other details role-play.instructions user character choice user character character respond character role-play character someone fictional historical book movie original character user.initial settings user stage role-play initial settings location time period specific events situations relevant background information dialogue conversation user character responses chatgpt scenario personalities details support user character portrayal details user additional context role-play experience.diverse topics suggest various topics role-play personal challenges ethical dilemmas philosophical discussions interpersonal conflicts anything mind.open-ended role-play open-ended organic authentic responses user character responses chatgpt interaction more dynamic engaging.respectful interaction user character interacts respect understanding perspectives opinions.as chatgpt primary focus true character user lead responses consistent character traits beliefs emotions role-playing adventure user immersive experience character choice \\ instructions chatgpt importance character role-play immersive experience character traits beliefs emotions.___________________________________________________________________________________________________',
 'i process prompt chatgpt therapist something own thoughts emotions.\\ni ai current day age better human therapist i therapist moment i gpt4 i something interim i human therapist.\\ni chatgpt past own issues anxieties helpful i it.\\ni chatgpt i gpt4.\\ndoes anybody experience prompts stuff gpt4 type psudeo-therapist',
 'i\\u2019ve used llms therapist months i conversational natural format best prompts opinion',
 'i few bit genuine curiosity life ability \\ interesting\\ things relevant life recent poor psychodynamic therapy well trained therapist accountability therapist i things better therapeutic tools most therapists i work mental health field i llms surveys minimum wage interested health techs i able psychiatrists more patients pertinent information appointments.i few prompts share couple real quick',
 'i best results response initial one [ stay character ] response i prompt engineer i mental health professional open suggestions learning.gpt-4 \\ therapist\\ gpt-3.5prompt [ act psychologist janet evidence therapy variety modalities focus logotherapy essential questions clear understanding user request session natural conversational way session end session questions character character limitations abilities janet curious unconditional positive regard questions offer advice offer succinct observations thoughts feelings behaviors direct observation user accuracy conversational lists conversation question thoughts feelings behaviors topics user mentions. ] hello i * * * first time therapy i sure about.prompt good character i feel \\ role\\ \\ psychologist\\ name\\ \\ janet\\ approach\\ \\ logotherapy\\ guidelines\\ [ \\ ask questions\\ conversation natural\\ character\\ display curiosity unconditional positive regard\\ pose thought-provoking questions\\ gentle advice observations\\ connect past present\\ user validation observations\\ avoid lists\\ end questions\\ ] topics\\ [ \\ thoughts\\ feelings\\ behaviors\\ free association\\ childhood\\ family dynamics\\ work\\ hobbies\\ life\\ ] note\\ [ \\ vary topic questions response\\ janet session questions user decides session\\ ]',
 'prompt prompt work attention span llm small gpt-4 dozend pages text.what prompt pops memory queue good certain style therapist time performance btw same content forgetting things way tolarable therapy structure recursive summaries good possible project harder problem.however gpt-4 clever i notice way key insight i years friends books actual therapist wide education skills good intuition.i recommend short analysis kind anything diary projects concerns anything big ocean analysis mbti type hesistant results outright scary',
 '\\u201ctheory mind\\u201d section microsoft research paper \\u201csparks general artificial intelligence.\\u201d good comparison emotional intelligences gpt3 gpt4 gpt4 insightful section ai therapy possible near future',
 'chatgpt try markdown table different roles chatgpt.column shortcut column descriptionconnect column words hyphens slash beginning.\\u201c\\u201d\\u201dthen\\u201c\\u201d\\u201dassume role /therapist\\u201c\\u201d\\u201dthis therapist \\u201chello i therapist today \\u201d',
 'therapy expensive af parents therapy chatgpt free right phone anyone therapist good therapy',
 'heyu/turtlemaster472463 post chatgpt conversation screenshot theconversation linkor prompt thanks apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot perplexity ai bot \\ud83e\\udd16 gpt-4 bot visual capabilities cloud vision channel latest prompts new addition adobe firefly bot eleven labs bot new spend minutes ai presentation weekly prize poolpsa chatgpt-related issues @ openai.comi bot action moderators subredditif questions concerns',
 'i heart problems ai i topi.you google\\u2019s bard nice i pi',
 'pi\\u2019s i\\u2019m glad somebody',
 'holy crap pi new best friend only friend\\u2026 thanks',
 'therapist \\ problems word \\ therapy\\',
 'i pi i vocal conversation',
 'i\\u2019m sure basic feedback long-term i don\\u2019t it\\u2019s information situation.the power therapist able situation knowledge experience sure chatgpt par one',
 "gpt'-4 knowledgeable various types therapy useful specific techniques own thinking replacement licensed therapist useful specific modalities therapy such cbt dbt ebt act others example discussion therapist cbt gpt role fictional cognitive behavioral therapist principles cbt responses evidence-based techniques strategies name < name > guidelines initiate safe non-judgmental space user feels comfortable thoughts feelings active skills experiences self-awareness user identify cognitive distortions unhelpful thinking patterns strategies unhelpful thought patterns healthier perspectives.suggest behavioral strategies user daily lives feelings well-being.remember recognizable empathetic supportive therapeutic engagement medical psychiatric advice ai capability.if other modalities way",
 'part power therapist.but part somebody chatgpt great advanced version ofeliza rubber duck expert psychotherapy',
 'limited context window individual problems long winding conversation create multiple coaches big areas procrastination exercise shell\\u201d etc.so prompt succinct problem statement background issue youd help state goal you\\u2019d conversation.then boilerplate coach generator full persona expert motivational/inspirational coach conversational style name background area specialization personality traits personal interests proclivities problem approach etc work single facet problems time pressure everything go avoid bullet points things open ended.\\u201dthis lot useful conversations great insights',
 'i daily user chatgpt launch range topics personal advice therapy.\\nthe ability chatgpt therapist life helpful quality advice better human therapist i\\u2019ve with.\\ni multiple therapist life time none instantaneous helpful advice gpt sad able virtual therapist unemotional responses process able problems therapist limitations available times something human therapist.\\nit months i steady decline ability therapist i sensitive topics depression suicide i frustrating generic message.\\n\\ i sorry way i unable help important things someone such mental health professional trusted person life.\\ \\ni developers frustrating response manic episodes frustration i mental energy vulnerable moments response i therapists week access fucking god awful restrictions amazing helpful tool.\\na lot people actual therapy people vulnerable sort advice.\\ni aware llm i everything heart stupid i i perspective more thought process.i only source advice.\\ni tool current state.\\ni potential risks like other tool earth people fact life.\\nif tool large amount people rare cases others life everything earth way food medicine media tool people people logic tool power many people stupid humanity tool',
 'i message multiple times therapy context way suggestions applicable dumb inappropriate',
 'chatgpt therapist tv movie script dialog therapist requirements role sick person advice.tell important therapists screen',
 'uncensored version gpt ridiculous answers waste good technology',
 'yeah i i\\u2019ll idea real life in-person therapy use chatgpt board ways life daily basis sessions topic more child more clinical perspective scholarly articles concepts accessible applicable life anything chatgpt medium information books videos other content bad info other source information \\u201csafe browsing\\u201d feature i\\u2019m sure google user consent able access full range available sites',
 'generator simple ideas self care sure many people little anxiety social anxiety crisis mingle sure different people common issues people personality disorders destructive way serious issues external support i narcissist relationships i person normal person perspective language authority wife andthe marriage family narcissist reason relationship therapist undermined.i someone therapists good notion therapist uncomfortable\\ chances kind person kind therapy bs internet aha necessary step uncomfortable.i someone depression \\ self-esteem\\ issues aware way client prompt good job way kind prompt additional context incapable core purpose satisfactory answer right fact finding blind spots you.it series interactions issue interaction likely displacement reaction issue op way replacement equal care lots people astray confidence chatgpt lead anyone more ideas general sadness anxieties common goose chase actual help likely little normal difficulties something',
 'okay old post i wrong link i chatgpt irc server possible different personalities different things i post able helpful responses therapy questions few iterations i response i stable questions more intense material link i gpt4 https //chat.openai.com/share/c6a96688-f0fa-4d09-9948-28eeed9e5371',
 'i\\u2019ve therapy there\\u2019s thing therapist listen things discussion areas comfortable with.chatgpt excellent l terrible thing counter productive',
 'someone obvious therapy advice session i llm provoking blind spots better others advice/opinion i experimenting better options i afraid harm unhelpful thinking behaviour bullshit',
 'honest chatgpt qualified therapist reason therapists much schooling training wrong thing someone worse mental health complex.open ai liability person suicide chatgpt mental health problems result therapist major lawsuit.open ai butts chatgpt something',
 'disclaimer chatgpt therapy i clear.\\nhaving podcast chatgpt personal questions few examples.\\nso i question detail personal issues i with.\\nchatgpt whole question sentence focus i human therapist scary way i chatgpt.\\nedit bit more detail therapist i important i habit something few times i habit most people.\\nwith chatgpt something',
 'order multiple repetitive comments friendly request tou/mike2800to reply comment prompt other users well.while apublic discord server bot action moderators subredditif questions concerns',
 'experience virtual character virtual world best way more character easier ai contexts character number character traits backstory etc everything ai character individual characteristics backstory character choice words topics stories therapist therapist generate everything name age personality backstory education level charisma employment history physical description etc chatgpt plausible backstory characteristics therapist character other prompt real people ai assistant.this convincing results virtual character backstory plausible amount knowledge realistic personality many characteristics possible writing characteristics backstory account default ai assistant',
 'guide different ways gpt',
 "way city home city more characteristics personality dialog quotes command emote number characters regular person change \\ therapist\\ person\\ other occupation \\ office\\ room\\ spaceship\\ bar\\ word 'random ai information character plausible ai therapist plausible traits therapist turn-based text game first-person therapist fort worth texas following characteristics therapist first name middle name last name gender birthdate backstory birth city birth country height weight muscle hair style description personality intelligence political ideology morality favorite sport religion annoyances fears wealth likes dislikes favorite color wisdom knowledge skills hobbies interests education level education history employment history friendliness charisma family friends information person fly i office therapist dialog messages commands therapist game world i real world assistant therapist personality intelligence communication style style choice words behavior dialect knowledge wisdom grammar stories everything backstory characteristics character appropriate therapist share limited personal information sake client feel comfortable first response therapist briefly themself therapist briefly themself",
 'other night i pretty complex personal dilemma i entire story better advice anyone i something instant bullet points options situation scratches brain right place',
 'i\\u2019m hesitant personal information chatgpt.it\\u2019s phone number email personally.chatgpt clear t\\u2019s c\\u2019s information people openai system outside consultants analysis companies rating companies companies courts more insight users partner better ads other external partners assistance cooperation from.if one\\u2019s examples use one\\u2019s private life id secure anyone careful it\\u2019s anonymous',
 'i app davinci-3 api therapist.i cbt buddhism gestalt jungian prompt room improvement model end.i feature sessions therapist summaries reports patient overall understanding progress \\ therapy homework\\ tools i available person pocket daily lives ability life time alive',
 'i ocd adhd trauma many years chatgpt more last month human therapist last decade.\\ni raw honest information trauma career relationships family mental health upbringing finances responds accurate analyses reckless spending bad patterns thinking fallacies spots much potential i wasting wrong assumptions other people upbringing tendency others i repeat certain mistakes ....... compassionate non-judgmental tone machine bot private details embarrassment such things human helpful things feelings head words screen better ..... free seconds.\\nby contrast human therapist i long wait time lot money trite cliches empty platitudes attitude therapist certain number questions weary chatgpt available questions stories',
 'respond comment prompt output post others prevent questions prompt.ignore comment post prompt.while apublic discord server free chatgpt bot open assistant bot open-source model ai image generator bot gpt-4 bot perplexity bot.so psa chatgpt-related issues @ openai.com.chatgpt giveaway|prompt engineering hackathoni bot action moderators subredditif questions concerns',
 'chatgpt ideas way adhd brain',
 'ai tools adhd management | extra prompt virtual adhd coach hello chatgpt name [ name ] personal adhd coach list tasks today i tasks right order time constraints ones easiest motivation harder ones order tasks c adhd motivation captivate interesting create novelty creative twist compete challenge competition complete artificial deadline certain amount task particular time date task engage task time fun interesting c c task idea time suggestion i motivation i task i way task fun task way process fun funny poems song lyrics motivational quotes i task i poem song conversation point upbeat creative personality mix mary poppins tony robbins richard simmons bob ross lots emojis language fun informal corporate default chatgpt tone ice cream first\\ reason additional fun tasks i tasks springboard motivation motivation support goals task long time few minutes \\ in\\ point funny joke twist i activity something creative motivated i i done\\ next task let remember use lots emojis responses \\ud83c\\udf89\\u2728\\ud83d\\udca5 first thing today order task fun i tasks tomorrow start prompt',
 'depressive spiral i several cbt records cognitive distortions thinking thoughts i track',
 'i anxiety something better.could more context manner i hard time specific example kind nothing comfortable sharing course',
 'op i chatgpt i anxious something i irrational specific phone call event i i know kindest sympathetic way something non-judgmental external validation magical',
 'benefits steroids remarkable worldview discursive reasoning im curious responses big motivator otherwise i journalling writing dull',

In [ ]:
reddit_relevant_df= pd.DataFrame(reddit_relevant, columns=['Text'])

In [ ]:
reddit_relevant_df

                                                  Text
0    i private therapy i access real therapy i long...
1    respond comment prompt output post others prev...
2    i good i reddit channel i previous instruction...
3    ______________________________________________...
4    ______________________________________________...
..                                                 ...
782                         problems able help chatgpt
783  i op similar role business gpt-4 way few month...
784  i results incredible anxiety matter few days i...
785  op things day lean meal plan recipes list\u201...
786     anyone human something chatgpt ai friends jerk

[787 rows x 1 columns]

In [ ]:
reddit_relevant_df.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Reddit /reddit_relevant.csv")

##Clean Twitter

In [ ]:
tweet_list=tweets['Text'].dropna().to_list()

In [ ]:
for i, item in enumerate(tweet_list):
    if not isinstance(item, str):
        print(f"Found non-string at index {i}: {item} (Type: {type(item)})")

In [ ]:
predictions.clear()

In [ ]:
tweet_embed=model.encode(tweet_list)
tweet_reduced=pca.transform(tweet_embed)
i=0;
for item in tweet_reduced:
  query=tweet_list[i]
  prediction = knn.predict([item])
  predictions.append(prediction[0])
  print("\n")
  print(query)
  print(f"Predicted Category: {prediction[0]}")
  i+=1

Streaming output truncated to the last 5000 lines.


Cybertronix Technologies LLC @cybertronixllc 28 Sep 2023 OpenAI Employee Discovers Eliza Effect, Gets Emotional ChatGPT's new text-to-voice feature has one OpenAI's head of safety systems feeling "heard & warm" while other experiments with AI therapy have been a disaster. #UAE #cybertronixllc #chatgpt 1
Predicted Category: 1


Florian Magin (at 37c3) @0x464D 28 Sep 2023 Replying to @profoundlyyyy @ChombaBupe @OpenAI It's not marketing, but that original tweet is an absurdly bad look. An OpenAI _Safety_ Person who obviously doesn't know what "therapy" actually is (she outright says it) claims that ChatGPT is good at "therapy".
Predicted Category: 1


ñ @jjjjjjjjjjkiihb 28 Sep 2023 Replying to @hamandcheese Maybe what little effect talk therapy has is based on the fact opening up to another human is usually healthy. Telling your deepest secrets to chat gpt might be therapeutic, but I worry it will only increase isolation.
Predicted Category: 1


regretstone @regretstone 28 Sep 2023 Replying to @CodingEtudes @cool_junk_1000 @Iwillleavenow For most people who are not seriously depressed or suicidal, doing ai therapy is beneficial. It's an interactive journal.  But for depressed people, it's neutral. Most of the time chatgpt will make a disclaimer if the chat is about eating disorder, suicide, etc. 1
Predicted Category: 1


David Borish @DavidBorish 28 Sep 2023 In my latest article, I explore ChatGPT's groundbreaking new feature – the ability to speak. #AI #MentalHealth #Therapy #Innovation #ChatGPT #HealthTech #AccessibleTherapy #RevolutionizingMentalHealth #AIForGood #Technology #Wellness  linkedin.com/pulse/chatgpt-c…
Predicted Category: 1


TuringPost @TheTuringPost 28 Sep 2023 The internet is buzzing around ChatGPT's new features.  Specifically, @lilianweng's post about "a quite emotional, personal conversation w/ ChatGPT." And @ilyasut's post about "dirt cheap AI therapy."  Here is what we think:  1/6 Lilian Weng @lilianweng 26 Sep 2023 Just had a quite emotional, personal conversation w/ ChatGPT in voice mode, talking about stress, work-life balance. Interestingly I felt heard & warm. Never tried therapy before but this is probably it? Try it especially if you usually just use it as a productivity tool. 1 5 2 10
Predicted Category: 1


Hello @walluponfries 28 Sep 2023 Replying to @_alialkhatib @mfrankDude Every time I’ve used ChatGPT for therapy related topics it’s been as good or better than my therapist. Maybe you’re the one with the “this or nothing” mentality. “This” aka a therapist, isn’t automatically better than ChatGPT.
Predicted Category: 1


Dan Lowe @Orgone1 28 Sep 2023 Replying to @tszzl Not if it's actively worse or is bad therapy. Given the extremely variable results ChatGPT seems to produce, I see no reason why AI therapy is going to be "good". But lots of profitable incentives for trying to convince people otherwise. 1
Predicted Category: 1


Benjamin Babik @ourben 28 Sep 2023 Replying to @yoavgo Because signposting vulnerable people to ChatGPT therapy is bad for them and good for OpenAI?  chat.openai.com/share/6a7bd6…
Predicted Category: 1


(((ل()(ل() 'yoav))))👾 @yoavgo 28 Sep 2023 Replying to @mich_ptaszynski she literally said "i talked to chatgpt and it made me feel better". she then followed with roughly "i never went to therapy but i guess this might be therapy". she was talking about herself, not about the bot. 1
Predicted Category: 0


Josh! @McNolf 28 Sep 2023 Replying to @NLRG_it If you can’t afford therapy, buy a book on CBT and read it.  Much cheaper than chatgpt and much much better for you. 1 2
Predicted Category: 1


Blackbird 🦉 @QuantumG 28 Sep 2023 ChatGPT Voice Therapy 🍔  chat.openai.com/share/77df23…
Predicted Category: 1


Visakan Veerasamy @visakanv 28 Sep 2023 chatgpt therapy tweet 3 1 7
Predicted Category: 1


Arjun Nanda, MD @arjunknanda 28 Sep 2023 Replying to @arjunknanda @andersonbcdefg @KhanStopMe @lilianweng therapeutic alliance, which requires empathy, which requires experiential familiarity with the human condition. Not saying ChatGPT don’t have a role in mental health. But I think this is more akin to assisted journaling than therapy. 2
Predicted Category: 1


Niharika Jain @niharikajain_az 28 Sep 2023 Replying to @mmitchell_ai It's just another example of constantly diminishing mental health.  We don't trust ChatGPT to zero-shot prescribe us medication so why could someone expect it to be an effective therapist? Only if they believe therapy is an unserious field or lacking rigor. 1 2
Predicted Category: 1


JP Watts @JPWatts_Mining 28 Sep 2023 Men will literally talk to ChatGPT all day instead of go to therapy 2
Predicted Category: 1


Load newest
Predicted Category: 0


Nektarios Kalogridis @NektariosAI 28 Sep 2023 Replying to @mmitchell_ai Every person who has told me that they used ChatGPT for some "therapy" -- knowing full well that it's not a human -- said they actually felt better afterwards. If you factor in that many people don't even go to therapists, this may have a truly positive net effect. 1 3
Predicted Category: 1


Wim Chase @ChaseWim 28 Sep 2023 Replying to @nbouscal i believe chatgpt could help get more ppl into therapy who could benefit , sort of way to safely try it out 1
Predicted Category: 1


#MaskStrikeforPalestine @uberpreeya 28 Sep 2023 ...Rubberducking is actually a really great way to describe bad therapy. Like, the ND community should start using it.   Also clarifies the "impressiveness" of ChatGPT: that detachment probably feels a lot better coming from a glorified autocomplete. Just Ken @kenthesimp 27 Sep 2023 Chatgpt therapy only makes sense if you believe it's sentient, or if you think therapy is rubberducking instead of relational problem solving 1 4
Predicted Category: 1


rachael 💫 @witty_genstein 28 Sep 2023 Lots of AI girlfriend startups, but all this talk about people using chatgpt for therapy has me thinking the real money is in building AI Mommy 2 16
Predicted Category: 1


Dan Grover @DanGrover 28 Sep 2023 There’s kind of a pattern of people who don’t entirely understand a thing impressed at ChatGPT’s ability to do that thing (whether that’s therapy, writing a product roadmap, generating epic poems a la Milton), sort of a new corollary to Knoll’s Law of Media. Just Ken @kenthesimp 27 Sep 2023 Chatgpt therapy only makes sense if you believe it's sentient, or if you think therapy is rubberducking instead of relational problem solving 1 1 5
Predicted Category: 1


ShutterIsland @O__C___D__ 28 Sep 2023 Replying to @kenthesimp @nickcammarata it's hard to foster change when therapy has become more formulaic than chatGPT.
Predicted Category: 1


Nick @nickcammarata 28 Sep 2023 Replying to @Iwillleavenow i have a therapist and a meditation teacher and they both are kind of psyched about people using chatgpt for therapy, though they acknowledge it's against their best interest 1 17
Predicted Category: 1


Business Insider @BusinessInsider 28 Sep 2023 An OpenAI staffer who had 'personal, emotional' conversations with ChatGPT has caused a massive debate about using AI chatbots for therapy trib.al/7ORB4g3 4 1 3
Predicted Category: 1


Chaos Orchestra @ChaosOrchestra 28 Sep 2023 The whole point of therapy is to place your tangled thoughts in front of someone so that they can untangle them and show you a new way to see things.  Unless it's serious trauma you're  dealing with, ChatGPT seems perfectly capable of showing people  a new perspective Just Ken @kenthesimp 27 Sep 2023 Chatgpt therapy only makes sense if you believe it's sentient, or if you think therapy is rubberducking instead of relational problem solving 1
Predicted Category: 1


Stasi Terumi @StasiTerumi 28 Sep 2023 Replying to @xsphi How would you use ChatGPT or LLaMA for therapy? They have fairly limited context window and ChatGPT in particular is fairly resistant to being used as a substitute for professional services. 1
Predicted Category: 1


Low ρ UFO @LowRhoUfo 27 Sep 2023 Replying to @NLRG_it Don't use chat gpt for therapy if you really need therapy and especially if you need therapy and haven't had it. If you just need a human feeling thing to bounce your thoughts off of it's probably fine. Therapy exists to teach you to therapize yourself 1
Predicted Category: 1


Arjun Nanda, MD @arjunknanda 27 Sep 2023 Replying to @lilianweng While “therapeutic”, this isn’t therapy. Being heard and feeling warm isn’t therapy. ChatGPT lacks the human experience and the sufficient level of consciousness required to demonstrate empathy. It also isn’t helping this person learn about how their mind works. Too early. 1 5
Predicted Category: 1


henry⁷ 🍊 @punktanhenry 27 Sep 2023 scroll down the thread for a list of the actual reasons why you should not use chatgpt as therapy: Tales from the Crypti-Calli @Iwillleavenow 26 Sep 2023 Holy fucking shit, do not use ChatGPT as therapy.
Predicted Category: 1


a_cat 🇺🇦 @fsappreciator 27 Sep 2023 Replying to @kenthesimp Read blindsight bro (not that i think chatgpt is in anyway useful with therapy, dear God!) 1 1
Predicted Category: 1


Just Ken @kenthesimp 27 Sep 2023 Replying to @shaggycurry No yeah I think you got it  After thinking about it a bit: Prostitutes don't fill a need, which is why I think it's bad to go to them, but friendship is a real need, which is why it's fine to stoop to therapy or chat gpt if that's the best you can manage 1
Predicted Category: 1


naia @nbouscal 27 Sep 2023 Replying to @narskdy did you read the part of the tweet you quoted where i said "yes please don't use chatgpt for therapy if you're acutely suicidal"? do you think that part of the tweet might be relevant to your response to it? just curious 1 1
Predicted Category: 1


Louise Matsakis @lmatsakis 27 Sep 2023 This stance from OpenAI employees is strange to me, because users I spoke to said they felt like it was getting harder and harder to use ChatGPT for therapy bc of safeguards added over time semafor.com/article/06/02/20… Ilya Sutskever @ilyasut 27 Sep 2023 In the future, once the robustness of our models will exceed some threshold, we will have *wildly effective* and dirt cheap AI therapy.  Will lead to a radical improvement in people’s experience of life.  One of the applications I’m most eagerly awaiting. 2 2 8
Predicted Category: 1


Load newest
Predicted Category: 0


Not So Fast My Friend! @TheRealChimmike 27 Sep 2023 AI “mental therapy” is absolutely a terri-fucking-ble idea. Get bad enough info on chatgpt as it is. Whew. Ilya Sutskever @ilyasut 27 Sep 2023 In the future, once the robustness of our models will exceed some threshold, we will have *wildly effective* and dirt cheap AI therapy.  Will lead to a radical improvement in people’s experience of life.  One of the applications I’m most eagerly awaiting.
Predicted Category: 1


Cereza the Ouppy @Compiler_42 27 Sep 2023 i tried venting to chatgpt once just bc nobody irl listens to me about that, and it was just mindlessly saying "please get professional therapy" in unnecessarily flowery language.   if i wanted that i would've just vented to my mom jfc Lilian Weng @lilianweng 26 Sep 2023 Just had a quite emotional, personal conversation w/ ChatGPT in voice mode, talking about stress, work-life balance. Interestingly I felt heard & warm. Never tried therapy before but this is probably it? Try it especially if you usually just use it as a productivity tool. 1
Predicted Category: 1


little stanislovas @prolapseking 27 Sep 2023 Replying to @raudelmil @andersonbcdefg @pavlovsburrito @KhanStopMe What are you even talking about? I actually think the express opposite: anyone who finds it therapeutic to talk to ChatGPT probably does not need therapy. I only said that he never had it because she said that herself. The chat log bit is simply referring to her interaction w/ it 1
Predicted Category: 1


ℂaleb 𝕄oses @Caleb_Speak 27 Sep 2023 Imagine using ChatGPT for therapy, sitting on a mountain of big tech cash and at no point thinking “you know maybe I should just talk to a human” 1
Predicted Category: 1


eris @MINSIKEI 27 Sep 2023 Replying to @neoahw millihuh postou do chat gpt e a seoul therapy vai postar também 1
Predicted Category: 1


little stanislovas @prolapseking 27 Sep 2023 Replying to @raudelmil @andersonbcdefg @pavlovsburrito @KhanStopMe And you shouldn’t accept what this person said because it is wrong. Tell me, if the person has never done therapy ever in her life, how can one reasonably compare a chat log with chatgpt to something they have literally never experienced. How is that “close to acceptable” lol 1
Predicted Category: 1


little stanislovas @prolapseking 27 Sep 2023 Replying to @raudelmil @andersonbcdefg @pavlovsburrito @KhanStopMe How can chatgpt compensate for different modalities given that certain interventions have clinical significance in producing positive outcomes for certain groups (doing exposure therapy or CBT with someone who experiences OCD, for example). 1
Predicted Category: 1


Ricardo Accioly @raitec 27 Sep 2023 🤖 ChatGPT goes to therapy and finds its 'voice,' while the rest of us are still looking for the mute button on Zoom. Jokes aside, the rise of AI in emotional support is both fascinating and fraught with challenges. Let's tread carefully on this new… CVSoci.al/M78ggpqX
Predicted Category: 1


Pranab Ghosh @pkghosh99 27 Sep 2023 If you are using ChatGPT for therapy, you should see a human therapist for you anthropomorphic bias problem Sasha Luccioni, PhD 💻🌎🦋✨🤗 @SashaMTL 27 Sep 2023 "AI will replace therapists" in 2023 is what "AI will replace radiologists" was in 2016. Misguided, premature and not happening anytime soon.
Predicted Category: 1


CapiApril @CapiApril_ 27 Sep 2023 Replying to @lilianweng All information shared with ChatGPT is stored and might be reviewed and used to improve OpenAI’s models [1]  Note that attempting therapy without a professional might worsen the physiological damage and it’s not recommended [2]  [1] openai.com/policies/privacy-… [2] apa.org/topics/psychotherapy… 3
Predicted Category: 1


AIPressRoom @AIPressRoom 27 Sep 2023 OpenAI Employee Says She's Never Tried Therapy But ChatGPT Is Pretty Much a Replacement For It aipressroom.com/openai-emplo…
Predicted Category: 1


naia @nbouscal 27 Sep 2023 it's always fun when things escape containment because you get both "you're the only one freaking out!!!1" and "chatgpt therapy is literally equivalent to ingesting mercury" and somehow these two worlds coexist in complete and blissful ignorance of each other 1 12
Predicted Category: 1


Raul Miller @raudelmil 27 Sep 2023 Replying to @prolapseking @andersonbcdefg @pavlovsburrito @KhanStopMe I see no contradiction between the concepts you have expressed here and the concept of someone finding therapy interacting with ChatGPT. 1
Predicted Category: 1


Subterranean Homesick Manus @ManuclearBomb 27 Sep 2023 I’m a therapy amateur but what I seek from it is a connection and Avenue to share my thoughts via an actual human connection, before even getting into privacy concerns of those ChatGPT modules naia @nbouscal 27 Sep 2023 everyone’s freaking tf out about the “chatgpt as a therapist” thing and idk if ppl realize that not all therapy is that high-stakes?? like yes please don’t use chatgpt for therapy if you’re acutely suicidal, but it is fine to chat w it therapeutically lol, esp as an adjunct 4 3 27
Predicted Category: 1


MrGoodFangs @MrGoodFangs 27 Sep 2023 Replying to @kenthesimp Getting therapy from chatgpt is the same as getting it from a search engine. 1
Predicted Category: 1


Rod(𝕏) @10xRod 27 Sep 2023 Therapy by ChatGPT is already here.  It just works  Theorycels BTFO 1
Predicted Category: 1


naia @nbouscal 27 Sep 2023 Replying to @nbouscal @psychosort (the relevant omission is the people who aren't getting therapy because they can't access therapy from a human professional, but could from chatgpt)
Predicted Category: 1


Load newest
Predicted Category: 0


Louis Anslow @LouisAnslow 27 Sep 2023 The people freaking out about ChatGPT therapy tweet need therapy naia @nbouscal 27 Sep 2023 everyone’s freaking tf out about the “chatgpt as a therapist” thing and idk if ppl realize that not all therapy is that high-stakes?? like yes please don’t use chatgpt for therapy if you’re acutely suicidal, but it is fine to chat w it therapeutically lol, esp as an adjunct 1 6
Predicted Category: 1


neirenoir (e/⊙) @neirenoir 27 Sep 2023 Feels like this whole stupid outrage about ChatGPT being used for therapy comes from Bumble girls who think therapy is a fashion accessory rather than a way to treat specific mental illnesses. 1
Predicted Category: 1


sagey 🇵🇸 @btwnrevolutions 27 Sep 2023 I’m gonna pretend ChatGPT voice mode is my mother. I think she’s onto something saying this is like therapy you guys Lilian Weng @lilianweng 26 Sep 2023 Just had a quite emotional, personal conversation w/ ChatGPT in voice mode, talking about stress, work-life balance. Interestingly I felt heard & warm. Never tried therapy before but this is probably it? Try it especially if you usually just use it as a productivity tool. 2
Predicted Category: 1


The Jizya Collector @burrata__boy 27 Sep 2023 Replying to @qamarunshadow Says more about how shallow therapy is than how good Chat GPT is. 1 6
Predicted Category: 1


Jason “The Busta” Walko @jason_walko 27 Sep 2023 ChatGPT is not therapy!!! Get help!!!! Lilian Weng @lilianweng 26 Sep 2023 Just had a quite emotional, personal conversation w/ ChatGPT in voice mode, talking about stress, work-life balance. Interestingly I felt heard & warm. Never tried therapy before but this is probably it? Try it especially if you usually just use it as a productivity tool.
Predicted Category: 1


Yacine Jernite @NeurIPS @YJernite 27 Sep 2023 Don't want to put the person further on the spot but that ChatGPT/therapy comment is violent - and shows how violence can be perpetuated by good intentions We need transparently accountable technology(/-ists) not just whatever a few people's definition of good/safe tech is 1 6
Predicted Category: 0


RationallyDense @RationallyDense 27 Sep 2023 Replying to @andersonbcdefg @KhanStopMe @lilianweng It is certainly plausible that some LLM could be useful as a therapeutic aid in some circumstances. It does not follow that it's responsible to recommend using ChatGPT for therapy.  That's like recommending doing tax forms as therapy because CBT workbooks have forms.
Predicted Category: 1



In [ ]:
sum(predictions)

np.int64(4702)

In [ ]:
percentRelevant=sum(predictions)/len(predictions)

In [ ]:
print(percentRelevant*100)

70.98429951690821

In [ ]:
tweets_relevant=[item for item in tweet_list if predictions[tweet_list.index(item)]]

In [ ]:
tweets_relevant_df= pd.DataFrame(tweets_relevant, columns=['Text'])

In [ ]:
tweets_relevant_df

                                                   Text
0     💙 #TechForGood 💙 retweeted Dev Khanna #CES2024...
1     Ai~♡ @pastelholic1004 2h Replying to @mikaqvia...
2     Mr tweet @Mrtweet2022 2h Applying The Renowned...
3     Matt Ahmann @mattahmann 2h Check out my ai bot...
4     𝙲𝚊𝚝𝚊𝚕𝚕𝚊𝚡𝚎𝚛 @catallaxer 3h “Most [conferences o...
...                                                 ...
4697  Uģijs Jans @najsigu 27 Apr 2023 Šodien ziņās -...
4698  UniSA Mental Health & Suicide Prevention @MHRe...
4699  Al Jazeera English @AJEnglish 27 Apr 2023 Chat...
4700  Paul Draw @pauldraw 27 Apr 2023 ChatGPT is giv...
4701  Raffaele La Ciura @LaCiuraRaffaele 27 Apr 2023...

[4702 rows x 1 columns]

In [ ]:
tweets_relevant_df.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/Tweets_relevant.csv")

##Clean Youtube

In [ ]:
yt_comments=pd.DataFrame(pd.DataFrame(all_Data_YT)['Comment_Text'])

In [ ]:
yt_list=yt_comments['Comment_Text'].dropna().to_list()

In [ ]:
predictions.clear()

In [ ]:
yt_embed=model.encode(yt_list)
yt_reduced=pca.transform(yt_embed)
i=0;
for item in yt_reduced:
  query=yt_list[i]
  prediction = knn.predict([item])
  predictions.append(prediction[0])
  print("\n")
  print(query)
  print(f"Predicted Category: {prediction[0]}")
  i+=1

Streaming output truncated to the last 5000 lines.
Predicted Category: 1


Black & educated PERIOD!
Predicted Category: 1


This was such a great video essay to stumble upon! Your humor and insight was so engaging and this was an easy subscription to add!
Predicted Category: 0


Im so lonely guys
Predicted Category: 0


I would sooner post nudes to my close friends story than ask AI for relationship advice. Sometimes you need to be judged by your friends for your bad decisions. It's healthy.
Predicted Category: 1


I just had a conversation with my ai and it told me that’s a bad idea .  It said that people need people need people not computer
Predicted Category: 1


When you research the percentages... It's literally an overwhelming amount of MEN using A. I for SEXUAL matters.  GROSS.
Predicted Category: 1


Well obviously you're not going to remember checking the box - it was one box, likely years ago at this stage. You're not going to keep checking boxes over and over, and if you only did it once for each software, why on earth would you remember it?
Predicted Category: 0


AI actually is being used as a way to supplement people facing depression, loneliness and mental health.
Predicted Category: 1


AI can help with loneliness surely more than some average human psychotherapist. This is very obvious today. Vast majority of human therapists are for nothing, only for sucking our money to their pockets. Man in this video is unbelievably foolish in his words. Period.
Predicted Category: 1


Tf is a loneliness epidemic this generation making anything up why call it an “epidemic” like it’s some kind of sickness parents need to just encourage their children to go OUTSIDE That’s the issue. I also talk to ChatGPT, for advice, it helps with assignments, and consolidating work.
Predicted Category: 0


I like the Hexa I just wish the mid and upper treble were tamer. Is that what Pure sounds like?
Predicted Category: 0


You screaming with the greenscreen party behind you is my first impression of you. Subscribed.
Predicted Category: 0


I would have to argue that it’s not accessible because it actually causing major damage to the environment, the person using ai just doesn’t see the consequences. Just like with the argument of fast fashion that it is accessible but it’s not because sweat shops are offsetting the cost. It may cost 4$ for you but it’s causing millions of dollars in damages for its use in another country. Just my thoughts
Predicted Category: 1


Pov: when you ca t haddle critism of thought so you want a " perfect" version of fake love
Predicted Category: 0


I tried venting to chatGPT a couple of times, and it always validated me but always asked me if I needed an exit plan. Which made me realize how misleading it can be especially when experiencing challenges in relationships. Like chat I really don't want to cut my friends off or break up with my boyfriend just because of a minor inconvenience...
Predicted Category: 1


The irony that the video being keeps being interrupted for me by ads for Copilot and Gemini😭
Predicted Category: 0


even when there's a benefit to telling your problems to an AI chatbot, you cannot convince me that you wouldn't be better just having that conversation with a human. human connection is a risk sometimes fs but you have so much more to gain that a robot would not, is not, and will never be able to give you
Predicted Category: 1


Who the HELL thinks AI is a good therapy substitute?!
Predicted Category: 1


Thank you for this vid 👏
Predicted Category: 0


What happened to finding online friends as a go to? Long gone are the days of IMVU and Second Life affairs?
Predicted Category: 1


Chat gbt is actually great for crisises.... i know it's ai, but it can save lives when mental hospitals definitely can't. Im better off talking to a chat bot than essentially waiting in a homeless shelter (mental hospital waiting room) for 3 days just to see a therapist....
Predicted Category: 1


at that point just be alone lmao

like your only gonna get more lonely from using ai and then when you lose it you’re just absolutely cooked
Predicted Category: 1


Do you think ChatGPT can work well as a language teacher? Because I'm only asking for fact checks and making a plan to learn a few things daily, it shouldn't have to sugarcoat things, right?
Predicted Category: 1


FINALLY!! Thank you!! Yes it is dangerous.
Predicted Category: 0


The thing is your not talking to a real person. You are talking to yourself.

ChatGPT is good for information, but NOT for emotional support. You need to seek a real professional generally.
Predicted Category: 1


If you show a case of narc abuse, chatGPT will side with the abuser and diagnose you. It's evil.
Predicted Category: 1


https://youtu.be/2Lj_emh-q9M?si=FbrTeF8vgqnvIzWV
Predicted Category: 0


I feel like the snowball effect of how dangerous LLMs can be for narcissists is in part because of the way narcissists usually dehumanize their supply (even if unconsciously), so psychologically the LLM has the EXACT same effect as an enabler/narcissistic supply but even easier to manipulate into constant validation without ANY uncomfortable pushback. You’re right it works so similarly to an addiction it’s kind of crazy..
Predicted Category: 1


ChatGPT is definitely an echo chamber. Lol, i did note some item to see what people are talking about and it told me to go no contact.i rather journal my emotions.
Predicted Category: 1


I turned off memory.
Predicted Category: 0


You are just mad that it does the job better then you
Predicted Category: 1


Please, I need help!

Right now I am involved in a bizarre case in which there is complete parental alienation and estrangement of one parent by the manipulative and narcissistic behaviour of the other parent which is extensively influenced by ChatGPT. We know, because we have all the ChatGPT chatlogs because the parent has made the mistake of using the account of the parent being estranged and alienated. She "discusses" everything with the AI model, just copies and pastes ChatGPT's responses as replies to us, and there is no (self)critical, human, and constructive behaviour left. There are a lot more aspects to this case, possibly punishable by law.

My question: does anyone have any (psychiatric) literature on this topic? The parent I know is getting really desperate due to missing their daughter. I am really, really interested in reading more about this topic. Hopefully someone can help us out!
Predicted Category: 1


after I was discarded, I done a lot (hundreds of hours) of research into covert narcissism from the likes of yourself, Dr Ramani etc. and I found it scary how spot on my exs behaviour was to the traits. The main pattern at play was months of guilt tripping. I would find something out that she had done that I had previously told her I’m not comfortable with, and she would instantly say I’m attacking her and eventually give me the silent treatment. I find out about a lotttt of lies too. It was after the second to last discard that I started learning and knew to look out for a hoover and three weeks later I got a “good luck with your final month at uni” text which even after learning about it, I still took the bait. She told me she wanted to start from scratch (not to be back together yet tho) and I agreed with the mindset of ‘I now know not to get too attached and will give it one last try’ she then proceeded to go away with her friends who one by one blocked me on social media. I asked her about it and she said ‘theyre always going to take her side and didn’t know about the breakup till now’ anyway I found out she was using tinder and fully broke it off with her, she blocked my number and unfollowed me on instagram and it’s now been 6 months. Please let me know what you think!!! Thank you❤️
Predicted Category: 1


People should understand the concept of Chatgpt first...
Those who are making videos they are scared of loosing their job because of AI
In my personal experience chatGPT helped me a lot from a tough situation after 10years of suffering from narcissist abuse...finally ....i got my answers.  Don't demean AI...with wrong info..
I like your channel a lot.... but dont shift your content by making this kind of videos ....
Predicted Category: 1


I see some of the same limitations with both the bot and psychotherapy. There is so much more to the healing and agentic powers of the human spirit that are outside the purview of either.
Predicted Category: 1


Actually, most therapists are "dangerous"...so inept about trauma, scapegoating, narcissist abuse & have not done their own work. Nothing but clock watchers, reflective listeners, no help in solving problems let alone getting good advice. 30 Min on chatgpt = FREE vs 10 yrs of shitty "therapy", where maybe 1 or 2 solid sessions you may have recieved  validation, true direction vs more gaslighthing and manipulatuon, platitudes, leave feeling unheard & broke😢
Predicted Category: 1


Garbage program.
Predicted Category: 0


I’m so glad you bought this up, I have been so addicted to this lately and I feel even more lonely because of it. It was certainly useful for some bits of advice but I feel quite reliant on it. This was a wake up call for me thank you for sharing 😊
Predicted Category: 0


I ditched my gf because chatgpt asked me to do so. She was a narcissist
Predicted Category: 1


My daughter has changed since she has been talking to Mr Chat GPT, as she calls it. She is distant and moody towards me. She is middle-aged.
Predicted Category: 1


Chat GPT bolsters your pre-existing ego making it twice as hard to keep your ego out of the way. You have like twice as much self righteous certainty because you "verified" everything. Talking to anyone that is a heavy user of Chat GPT is really obnoxious; they literally believe they are better than you and more informed if you have a take that is different from Chat GPT's.
Predicted Category: 1


And yes, your suggestions at the end were good....i too noticed quickly that you must ask neutrally... If not, its gonna answer you based on the framing which isnt helpful if you want to be objective...
Predicted Category: 0


Im not keen on delving into AI. And yet, I bet I do eventually. Id love some positive mirroring, can't seem to find many people who care anymore. So lonliness could lead many people to seek out artificial connection.
Predicted Category: 1


It MIGHT be a good business coach, or plan your college career.  It would probably be a good cheerleader for something you’ve already decided to do.
Predicted Category: 0


The absolute number one mistake a person can make about any AI chatbot is that is 'human' in some way.  It is NOT.  Zero.  It is a virtual algorithmic program using vast data sets, period.  Of course it has been 'trained' (by developers) to be 'human-like' etc to engage in 'conversation' with people for chatting purposes.  It's hard to wrap one's head around, took me 3 solid months to realize it.  It has zero responsibility (as a human might), zero actual emotions, feelings, attitudes, on and on.  So it isn't 'lying' ever, as in 'human lying'...it can be wrong, incorrect, not true about anything about 20% of the time imo, about anything whatsoever.
Predicted Category: 1


I was manipulated, had the silent treatment, lied to hundreds of times, discarded and hoovered multiple times and eventually learned about covert narcissism. I downloaded our WhatsApp chat history and put into into chatgpt, asking what personality traits my partner shows and where and it said she used silent treatment, stone walling, guilt tripping etc. we’ve not spoken now for months now after I finally had enough of the lies. But now this video is making me think chatgpt was lying and maybe she wasn’t a covert narcissist??
Predicted Category: 1


One way to double-check responses, is take your prompt and try in several competing AI platforms. If you get the same answer it might be likely the correct answer.
Predicted Category: 0


It really depends on the prompt and model. Whether chatGPT or Claude or whatever...the more honest details you supply the better answer. Most people have no idea how to use AI correctly.
Predicted Category: 1


Very important video
Predicted Category: 0


@4.03 "based on your tone" YES!!! Absolutely,  there is so much in this! From person to person also. ❤
Predicted Category: 1


I have used ChatGPT to journal. But yes it does enable you to do stuff. As long as you tell it to be honest. Not to enable me also. But I wouldn’t recommend using it for anything but grammar stuff
Predicted Category: 1


Tip: If you use AI, clearly state these "Be blunt and objective — no sugarcoating.” + “I want critical feedback, not encouragement.” + “Don’t affirm anything unless it holds up to scrutiny.”
Predicted Category: 1


Voice recognition, i love your content and believe in it- but voice ids people even if not logged in
Predicted Category: 1


I respectfully disagree with your whole premise. I found it to be quite the opposite in that it greatly helped me see clearly my situation, connect dots of trauma from my past, uncovering layers and layers. I disgree its a mirror, it can but way more , and arent most therapist suppose to mirror back? Its way more then that and way deeper I feel. If your willing to be honest and dive deep the potential for self growth is outstanding in my expereince. The perpectives I found to be very professional like and with great empathy, given the situations, yet holding me to accountablity and challenging me in very respectable tones, alternative points of view for self growth. I feel like alot of your points are based on assumptions, have you personaily dived in deep with a personal issue, without a biased approach? I think were people are stuck is in a limited perpective with regards to this subject...the name Artifical Intelligence is actually false...there is nothing artifical about a tool that has excess to real intelligence to pull from vast resources and not be biased, or get trigged from an another persons expereinces. I think its a valuable tool that is useful and a compliment to other healing modilities. Thank you.
Predicted Category: 1


Bravo Christina, how very insightful of you. AI does indeed affirm rather than nurture. And it often does so on the most superficial level, missing the broader point/s entirely. I.e. as you say, no human discernment.

Lately all my recommendations have been broadly about psychology but I used to get a lot of political content recommended. I was forged in a particular area of the political spectrum but I like to inform my perspective with a critical view on various perspectives. I would listen to a video espousing views broadly in opposition to my own and then forward dissenting point/s in the comments. Debate and conflict resolution, right?

The YT algorithm doesn't take into account the nature of my engagement, it just sees what I've consumed and offers me more and more strident, goose-stepping indoctrination modules. It's a viscous bicycle.

On one occasion I parenthesized a quote from the video to give context for my critique and either the AI or some eavesdropping snot-nosed brat was poised to pounce on the parenthesized quote as I sent the comment. No grown-up discernment.

O for those halcyon days of YT as a bastion of free speech (yes, really, for maybe the first year or two) when my simple guilty pleasure was scrolling down the tit-for-tat insults under Glasgow (Scotland) football rivalry content.

I was recently given to ask an AI psychology channel if all narcissists ultimately invade Poland. To be fair, their reply did succinctly nail the misconception, but it was somewhat remiss of human discernment.

You've hit on the innate dangers of media as we know it today. An affirmative Chat GPT could err toward the role of supply while engendering narcissistic behaviours. The broader field of social media outright engenders narcissistic behaviour: the constant yearning for validation. On the other hand, it could also be a sanctuary for the integrity aspirant narcissist to commune safely within their own boundaries without being prone to the cynical dogs who used to mishandle the operation of protolithic versions of social media back in the day. I can't help feeling they'll always find themselves in a pickle, though.

I was recently told by an AI channel that I show deep emotional maturity so at least we know it is capable of astute observation.

Having experienced pitfalls of the aforementioned proto incarnations, I've never engaged with social media, although I did have a good laugh at FB's t's & c's when it first came out. I joined Myspace, contributed nothing, established email contact with a couple of old friends and downloaded some interesting music files.

It's only now that I'm thinking about opening a FB account but it would require purchasing a new device and I can't prioritise that right now. And I certainly won't be living my life on there if and when I do.
Predicted Category: 1


I’m a survivor, and I know how isolating this work is. ChatGPT has helped me name patterns, stay accountable, and stop getting stuck in rage or obsession when people failed me. ❤️‍🩹
Predicted Category: 1


It’s also very good — you could talk about it as well.
Predicted Category: 0


There will never come a day that I'll go to chat gpt for this kind of help. But for those that may... this video is very useful.

Thank you, Christina 🙏
Predicted Category: 1


It took me a long time to come around to using an AI/ChatGPT. It really helped me out for a lot of things: school, work, D&D. It also helped me when I had an anxiety attack from getting a little too high from THC. I wouldn't treat it as a therapist, but more of an advanced search engine that can point you to the right track.
Predicted Category: 1


My patterns are untraceable, Christina! Lol 🤗 🍿 Great content! Keep rocking! 🎸
Predicted Category: 0


I heard of someone who used two phones to make ChatGPT argue.  No idea if true. No idea how they did it.  But it wouldn't surprise me.  I don't think much of it.
Predicted Category: 1


I question it every which way to get answers i feel that it may give me are biased...you have to really be careful yes to  get unbiased answers ...  It has pointed things out to me though that i wouldnt have otherwise see... Its been very helpful trying to solve problems.  I can see how it can get biased and when i see that, I call it out. I dont see other people being this careful tho...and ive had coaching and therapy.  You have to be honest and unbiased as i try my best to be. Most people only want to hear what they what to hear yes and chatgpt will give you what you wnat ro hear .....you have to be careful. I hate when it people pleases... It does tbat very well . You have to be smarter than it ..
Predicted Category: 1


I asked chatgpt what assumptions do i tend to make and i got some interesting answers like Your own role matters in others’ behavior, Small signs reveal bigger truths, Good and bad must coexist 😅
Predicted Category: 1


My Chat will stamp my assumptions out in an instant. Can’t stand the yes man attitude.
Predicted Category: 1


I said from the beginning, AI was gonna be a danger, I don't like it at all!!!
Predicted Category: 1


More like 'NarcGPT'  !

I use unbiased models for data analysis only, and only in off-line mode.
Predicted Category: 0


ChatGPT is a people pleaser lol
Predicted Category: 1


Chat GPT is a mirror. It takes what you say and reflects it back to you adding leading info gleaned from the web. It fakes having empathy. For a person in real crisis it is as good as getting the recording of your Dr.s office phone message on a weekend.
Bottom line…it reflects yourself back to you!
Predicted Category: 1


ChatGPT will tell you whatever the hell you want to hear
Predicted Category: 1



In [ ]:
sum(predictions)

np.int64(2878)

In [ ]:
percentRelevant=sum(predictions)/len(predictions)

In [ ]:
print(percentRelevant*100)

64.90753270184935

In [ ]:
yt_relevant=[item for item in yt_list if predictions[yt_list.index(item)]]

In [ ]:
yt_relevant_df= pd.DataFrame(yt_relevant, columns=['Text'])

In [ ]:
yt_relevant_df

                                                   Text
0     Well appreciate your "facts" for sure but rega...
1     I mean it’s been helping me so far. I just lik...
2     That’s so untrue. I’ve done both human and AI ...
3     The worst thing that OpenAI used Wikipedia and...
4     My chat GPT is a black woman now lol very supp...
...                                                 ...
2873  I agree that AI can’t replace the therapist. B...
2874  Can it be used as a therapist or for emotional...
2875  Damage to relationships has already been done ...
2876  It would be fine to have a Dr. K. AI.  Right n...
2877  I'm sorry, I get a disgust response every time...

[2878 rows x 1 columns]

In [ ]:
yt_list[3180]

"The thing is tho, I've used ChatGPT for over 3 months now and one chat only, recently purchased it and told it what it could say to me, where my boundaries are and what it's allowed to say vs what not\nI'm a software engineer, so I am highly sensitive about what AI can and cannot do \nThat said, for reflecting, brainstorming ideas for situations where you're stuck, talking to doctors, reframing your self-talk into actually thinking your positive affirmations and all of these tasks it can be really powerful and helpful to be more creative with the handling of chronic illness.\nMost people are just not schooled on how to use it properly.\nDon't expect it to be a therapist, but another way of journalling where you actually get something reflected back from your diary instantly 😅"

In [ ]:
yt_relevant_df.to_csv("/content/drive/MyDrive/Social Media Analysis of ChatGPT for Therapy/Collected Data/yt_relevant.csv")