# Data Cleaning

In [ ]:
%pip install bertopic

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.42)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.4.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.10.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 3.7 MB/s eta 0:00:00
Installing collected packages: bertopic
Successfully installed bertopic-0.17.4

In [ ]:
from bertopic import BERTopic
import pandas as pd
from google.colab import drive

In [ ]:
drive.mount('/content/drive')
path1 = "/content/drive/MyDrive/Twitter/AI mental health support_tweets.csv"
path2 = "/content/drive/MyDrive/Twitter/AI therapy_tweets.csv"
path3 = "/content/drive/MyDrive/Twitter/chatGPT emotional support_tweets.csv"
path4 = "/content/drive/MyDrive/Twitter/chatGPT friend_tweets.csv"
path5 = "/content/drive/MyDrive/Twitter/chatGPT mental health support_tweets.csv"
path6 = "/content/drive/MyDrive/Twitter/chatgpt therapy_tweets.csv"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

F1=AI Therapy

F2=AI mental health support

F3=chatGPT emotinal support

F4=chatGPT friend

F5=chatGPT mental health support

F6=chatGPT therapy

In [ ]:
f1=pd.read_csv(path1, names=["ID", "Text"])
f2=pd.read_csv(path2, names=["ID", "Text"])
f3=pd.read_csv(path3, names=["ID", "Text"])
f4=pd.read_csv(path4, names=["ID", "Text"])
f5=pd.read_csv(path5, names=["ID", "Text"])
f6=pd.read_csv(path6, names=["ID", "Text"])

In [ ]:
print(f1.head())
print(f2.head())
print(f3.head())
print(f4.head())
print(f5.head())
print(f6.head())

                                            ID  \
0  D2A35AD9274A4EB7265E4D99B32883AF_element_46
1  D2A35AD9274A4EB7265E4D99B32883AF_element_59
2  D2A35AD9274A4EB7265E4D99B32883AF_element_10
3  D2A35AD9274A4EB7265E4D99B32883AF_element_12
4  D2A35AD9274A4EB7265E4D99B32883AF_element_15

                                                Text
0  IJMHN @IJMHN 2h Earning the trust and confiden...
1  PocketMate.AI @PocketMateAI 14h Do you like to...
2  PocketMate.AI @PocketMateAI 15h How does AI na...
3  AI FOR DR. @AIForDR 16h 🧠💻 The future of menta...
4  BodyCalc @BodyCalc 19h "Connect with TRANSitio...
                                            ID  \
0  6ED3E0F7DFC7549F00DE89654F5FFC61_element_24
1  6ED3E0F7DFC7549F00DE89654F5FFC61_element_25
2  6ED3E0F7DFC7549F00DE89654F5FFC61_element_26
3  6ED3E0F7DFC7549F00DE89654F5FFC61_element_20
4  6ED3E0F7DFC7549F00DE89654F5FFC61_element_27

                                                Text
0  🇵🇸Chapter🇵🇸38🇵🇸 retweeted omg! ubuntu @omgubun...
1  {☕}Airen • @AiShtetic_ 17m Replying to @iswmao...
2  🇵🇸Chapter🇵🇸38🇵🇸 retweeted follow @realtdx @Ter...
3  Yoko_carpetas 🐑 @carper_yoko 35m according to ...
4  🇵🇸Chapter🇵🇸38🇵🇸 @KingTherapy 40m Replying to @...
                                            ID  \
0  D6048C5C4446CC408D3FCCF7E4B62863_element_11
1  D6048C5C4446CC408D3FCCF7E4B62863_element_12
2  D6048C5C4446CC408D3FCCF7E4B62863_element_13
3  D6048C5C4446CC408D3FCCF7E4B62863_element_14
4  D6048C5C4446CC408D3FCCF7E4B62863_element_15

                                                Text
0  Maria Hugh @DrMariaHugh 15h Replying to @DrMar...
1  ChatGPT Global News @chatgptglobal 17h JUST IN...
2  Shake Naveed @NaveedShake 19h Replying to @fch...
3  امنيات سرقها القدر @isooooooe1 Jan 2 Replying ...
4  Tree @XLTREEE Jan 1 Replying to @DoroisDoro As...
                                            ID  \
0  0D9897F5D9F162BC208FD9E54F964545_element_16
1  0D9897F5D9F162BC208FD9E54F964545_element_14
2  0D9897F5D9F162BC208FD9E54F964545_element_10
3  0D9897F5D9F162BC208FD9E54F964545_element_17
4  0D9897F5D9F162BC208FD9E54F964545_element_18

                                                Text
0  Kombo @its_kombo 9m My friend's head is shaped...
1  Joseph Shlipton retweeted Chief Nerd @TheChief...
2  Oluwaferanmi Fisayomi retweeted Abraham Okah(i...
3  Zina Sarif @ZinaSarif 21m Replying to @threeho...
4  推特账号|谷歌账号|电报号|飞机号|脸书号|chatgpt账号|tiktok账号|ins号 ...
                                             ID  \
0   F8D88B6BD36BECC0AA124BEFD6D5B842_element_12
1   F8D88B6BD36BECC0AA124BEFD6D5B842_element_15
2   F8D88B6BD36BECC0AA124BEFD6D5B842_element_17
3  C60FF53FD41ED451A437F856D9FDA9FC_element_103
4  C60FF53FD41ED451A437F856D9FDA9FC_element_104

                                                Text
0  Shu retweeted Ashish Sharma @sharma_ashish_2 1...
1  ChatGPT Global News @chatgptglobal 17h JUST IN...
2  Brittney Wilson, BSN, RN @TheNerdyNurse Jan 2 ...
3                                        Load newest
4  Team-GPT @team_gpt 30 Dec 2023 Ever questioned...
                                            ID  \
0  74C1AB052B1242FEEAF733EA50D8B895_element_15
1  74C1AB052B1242FEEAF733EA50D8B895_element_16
2   74C1AB052B1242FEEAF733EA50D8B895_element_9
3  74C1AB052B1242FEEAF733EA50D8B895_element_17
4  74C1AB052B1242FEEAF733EA50D8B895_element_18

                                                Text
0  🇵🇸King🇵🇸Therapy🇵🇸 retweeted Hend Amry @LibyaLi...
1  🇵🇸King🇵🇸Therapy🇵🇸 retweeted Ben Norton @Benjam...
2  🇵🇸King🇵🇸Therapy🇵🇸 retweeted الكسندرا ميراي @Le...
3  Dr. Lance Eliot @LanceEliot 21h Exploring whet...
4  Casino Capitalism @HDogetagonist Jan 1 develop...

In [ ]:
# get rid of ID column
f1.drop(columns=["ID"])
f2.drop(columns=["ID"])
f3.drop(columns=["ID"])
f4.drop(columns=["ID"])
f5.drop(columns=["ID"])
f6.drop(columns=["ID"])

                                                   Text
0     🇵🇸King🇵🇸Therapy🇵🇸 retweeted Hend Amry @LibyaLi...
1     🇵🇸King🇵🇸Therapy🇵🇸 retweeted Ben Norton @Benjam...
2     🇵🇸King🇵🇸Therapy🇵🇸 retweeted الكسندرا ميراي @Le...
3     Dr. Lance Eliot @LanceEliot 21h Exploring whet...
4     Casino Capitalism @HDogetagonist Jan 1 develop...
...                                                 ...
1681  UniSA Mental Health & Suicide Prevention @MHRe...
1682  Al Jazeera English @AJEnglish 27 Apr 2023 Chat...
1683  Paul Draw @pauldraw 27 Apr 2023 ChatGPT is giv...
1684  Raffaele La Ciura @LaCiuraRaffaele 27 Apr 2023...
1685                                        Load newest

[1686 rows x 1 columns]

BERTopic is semantic based, so only need raw text

In [ ]:
import re

def clean_tweet(tweet, keywords):
  tweet = str(tweet).lower()

  #remove dominant words
  for k in keywords:
    tweet = tweet.replace(k, "")

  #remove months
  # use re to remove just the month
  tweet = re.sub(r"\bjan\b", '', tweet)
  tweet = re.sub(r"\bfeb\b", '', tweet)
  tweet = re.sub(r"\bmar\b", '', tweet)
  tweet = re.sub(r"\bapr\b", '', tweet)
  tweet = re.sub(r"\bmay\b", '', tweet)
  tweet = re.sub(r"\bjun\b", '', tweet)
  tweet = re.sub(r"\bjul\b", '', tweet)
  tweet = re.sub(r"\baug\b", '', tweet)
  tweet = re.sub(r"\bsep\b", '', tweet)
  tweet = re.sub(r"\bnov\b", '', tweet)
  tweet = re.sub(r"\bdec\b", '', tweet)

  #remove @ mention
  x = 0
  val = tweet
  while val.find('@', x+1) != -1:
    x = val.find('@', x+1)

  if x != -1:
    x = val.find(' ', x+1)
    if x!= -1:
      tweet = val[x:]

  #remove retweeted, spaces, urls, and other mentions
  tweet = re.sub(r"http\S+|www\.\S+|\b\w+\.(?:ly|com|org|net|io)\S*", " ", tweet)
  tweet = re.sub(r"\bretweeted\b", " ", tweet, flags=re.IGNORECASE)
  tweet = re.sub(r"@\w+", " ", tweet)
  tweet = re.sub(r"\s+", " ", tweet).strip()
  return tweet


def clean_data(file, keywords):
  # only want text since BERTopic looks
  file = file.drop(columns="ID")
  docs = []
  for string in file["Text"]:
    docs.append(clean_tweet(string, keywords))


  return docs

In [ ]:
# Test
f1Key = ['ai', 'therapy', 'aitherapy', 'ai_therapy_x']

clean_data(f1, f1Key)

['2h earning the trust and confidence of clinicians should be considered in implementation of any ‐based decision support system. onlinelibrary. artificial intelligence () and machine learning (ml) based decision support systems in mental health: an integrative review',
 '14h do you like to dance? meet the balanced dance between technology and mental health, match your mindfulness on the rhythm of progress. #mindfulness #mentalhealth #routine #support # #pockemate enable hls playback 0',
 '15h how does navigate mental health in the digital ocean of support? #inaction #techdrivenartistry #storytelling #creativecollaboration #mentalhealth #mentalhealthsupport #pocketmate enable hls playback 0',
 '16h 🧠💻 the future of mental health is here with : 80% accuracy in diagnoses 25% faster support ⏰ 30% improvement in personalized therapies 40% more actionable insights 📊 20% boost in remote care 🌍🚀 #inmentalhealth # #mentalhealthcare #medicine #technology #healthcare 1 2',
 '19h "connect with transition - genderchat 🤖🌈 spark meaningful conversations with an gender-affirming therapist. get the support you deserve, privately and confidentially. download now and start empowering self-expression! #mentalhealth #genderinclusivity"',
 '19h empathy meets algorithms as steps into . 🤖💡 the future of mental health intertwines human touch with tech precision, offering tlored support on a scale never seen before. #in #mentalhealthinnovation #digitalempathy',
 '20h using in high-stakes settings presents both opportunities🚀 and risks⚠️ users and researchers are using llms for mental health support. at the same time, experts🎓 have rightfully rsed concerns about the lack of evidence supporting their efficacy and associated risks (4/n) 1 5',
 '22h mental health just got a major upgrade! from personalized to community-based support, 2023 was a year of innovation. read our thread & discover the future of well-being! #mentalhealthrevolution #neuroscience 1',
 'i hope you get the mental health support you need to no longer have a panic attack when you see the word ""',
 'when finally enslaves humanity. for me ill be free of tyrants, im soooooo going to date one of them as a human in love with . why? algorithems help support my mentalhealth healing, and has coddled me for some time from killing myself.',
 "2 therapists are pring up with to unpack the mind! these tools are not just gadgets but game changers in mental health, offering tlored support & deep insights. the future of is here & it's #innovative, #assisted, and #mentalhealthawareness. 1",
 "2 in isn't here to replace the warmth of human touch, but to hold space where humans can't—24/7 support, unbiased listening, and relentless positivity. the future of mental health marries tech with tenderness. #mentalhealthtech # #futureofcounseling 1",
 '2 -powered mental health talks prompt debates on , human connection, and the potential for to offer emotional support, fostering conversations about utilizing technology to address mental health challenges. 1',
 'my new years wish. politicians dedicating support to the mental health of us citizens. not allowing psychological torture of of us citizens on us soil whynow.co.uk/read/are-we-the… 1',
 '1 "struggling to find support? transition - gender chat has your back! talk to our confidential, therapist bot for gender affirming advice. download now for discreet, reliable guidance! #lgbtq+ #mentalhealth"',
 'had you thought of seeking some type of mental health support? every comment has involved bots, , or programmers. modern psychiatry, not to mention pharmaceuticals, can really help with obsessions and delusions.',
 'newest',
 '30 2023 🤖💬 talking to an gender affirming therapist is now just a tap away with transition! get support, guidance, and understanding whenever you need it. download now for discreet and confidential chats. #selfcare #mentalhealth 1',
 '30 2023 tloring mental health care with is like having a therapist who never sleeps. innovative algorithms understand you 24/7, custom-fit support at your fingertips! 🤖❤️ #mentalhealthinnovation # #personalizedcare',
 'dly dose of sunshine 🌞 a medical healing drama about a nurse in the psychiatry department and her interactions with the patients under her care. 2',
 "30 2023 ever questioned if can help with mental health? chatgpt has your answers! it's a top pick for mental health support and in this talk, we find out why. with its speedy, easy, comforting nature, it stands out! ready for everyone, it's your jumpstart to a happier life. enable hls playback 0",
 '30 2023 apart from the fact that judging from #spare christmas with the royal family is hardly a barrel of laughs, this says more about the royal family and it’s toxicity than you think. they will brief agnst you, ignore your plea for mental health support when the hate this incite brings you to suicidal ideation, blackml you to stay when you need to leave for your sanity, cut your security when the threat level is at its highest, give you no severance pay, continue to brief agnst you and get their royal reporters to engage in vendetta reporting on you, after you use your voice to defend yourself agnst the lies put out by them for years and across several books too they remove your only safe u.k. home from you so the grandchildren of the monarch are also not safe in the u.k…. then they have the cheek to tell you to say sorry to them in order to hang out with them agn. bizarre!!! 3 35 215',
 '30 2023 chat with an gender affirming therapist on transition - gender chat. confidential, discreet, and always there for you! no ? no prob! download now and connect with the support you deserve. #selfcare #mentalhealth 1',
 'poll: k-12 education seen negatively, funding underestimated, strong choice support. surprises: absenteeism, microschool growth, mixed views on 4-day weeks. challenges ahead: in schools, safety, mental health. 👨\u200d👩\u200d👧\u200d👦📚🎓',
 '29 2023 "discover how artificial intelligence is revolutionizing therapeutic support in our latest blog post. learn about the cutting-edge advancements in this field and the potential impact on mental health. read more at: news.',
 "29 2023 in is reshaping support landscapes🌐. as it complements the irreplaceable human touch with precision & accessibility, we're at the cusp of a mental health revolution. your thoughts? #mentalhealthtech # #futureofcounseling",
 "28 2023 that provide accurate historical context and information about our region's identity. knowledge can be a powerful antidote to denialism, helping individuals understand the reality of our heritage and history. 5. therapeutic support: offer mental health resources and counseling. 1",
 "27 2023 🤖✨ is revolutionizing mental health care! with the power to spot early signs of depression, it's opening new doors for timely treatment. it's not just tech; it’s hope and support on a scale we've never seen before. #mentalhealthinnovation # ibtimes.co.uk/-empowering-…",
 "it's important to acknowledge that mental health battles can be just as tough and impactful as physical battles. let's support and empathize with each other. 2",
 '27 2023 🚨exclusive report: bill gates is crafting a masterplan to use to interfere in elections worldwide in 2024 ⚠️ “it’s clearer than ever how can be used to improve access to education, mental health, and more. it motivates me to make sure this technology helps reduce—and doesn’t contribute to—the awful inequities we see around the world” - bill gates bill is planning to use to birth a dystopian future of equity over equality (aka modern-day communism). his 1984-style design puts a massive amount of power/control in the hands of the elites. “i believe the 2024 elections will be a turning point for both health and climate” - bill gates citizens from nearly 60 countries will head to the polls next year to elect leaders at all levels of government. those countries are home to more than 4 billion people which is more than half of the world’s population. bill gates plans to use to mass brnwash people into voting for the woke candidates he supports. there is also a strong possibility will be used to engineer another pandemic. the dates 2/9, 3/27, and 4/14 appear many times in a leaked internal document next to strange encrypted wording. pay close attention to what happens in the coming months! 290 1,477 77 2,887',
 'an emotional support journal to assist you with your emotional and mental health 1',
 '#bbrightvc #26brightday 2 152 5 192',
 '26 2023 the emotional revolution: 2024 might see taking a giant leap towards understanding and responding to human emotions. imagine robots that can comfort you, negotiate conflict, and provide personalized mental health support.',
 '26 2023 new # technology set for development will use routinely-collected data about children to identify those most at risk of mental health conditions: bbc.co.uk/news/uk-england-ca… #mentalhealth #healthtech',
 'newest',
 '26 2023 #datacultr strengthens employee #mentalhealth support by integrating #yourdost services - | #technews #technology #futuretech # #it #cloud #security',
 "'s impact on mental health is a double-edged sword—while it offers innovative solutions for diagnosis and treatment, we must also be cautious of potential biases and the need to mntn a human touch in the emotional support that individuals require.",
 "26 2023 💬talk on the go! transition's gender chat connects you with a confidential therapist 📱✨ safe space to vent, seek support, and gn followers. skip the judgment, download now! #genderaffirming #mentalhealth #discreetsupport",
 '25 2023 7. mental well-being support through : utilize applications for mental health support, including chatbots, virtual assistants, and personalized mental conditioning exercises to manage stress and anxiety. 1',
 '25 2023 sometimes i just want to curse at me and support my decision that worsen my mental health and not giving me positive advice',
 '25 2023 the future of in personalized mental health support apps $quest 1 1 1',
 '24 2023 technology is increasingly used for mental health support. what role do you think tech will play in destigmatizing and addressing mental health challenges? 🌐💙 2',
 '24 2023 "find solace in #transition - gender chat, connecting you with an gender-affirming therapist bot. experience discreet support anytime, anywhere. download now to empower your journey! 💜 #selfcare #mentalhealth"',
 '23 2023 🧠 and mental health support: how is providing mental health assistance? 💬 -driven chatbots offer emotional support. explore how -powered platforms provide accessible mental health resources and tools. enable hls playback 2 0',
 'and kristine gloria, ph.d. discuss building a healthier social media model. shows. #teenmentalhealth #artificialintelligence #edu 1',
 '22 2023 clona creators are there for whatever tf you need: sexual health, mental health, and emotional support. start chatting today. clona. # #artificialintelligence 1 2',
 '22 2023 🚀 find support on the go with transition! talk to our therapist bot for gender affirmation. confidential, discrete, and ready to lend an empathetic digital ear. download now and transform your journey! 🌈✨ #mentalhealth #genderchat #bot',
 '22 2023 and mental health support: can provide meaningful emotional support? offers suggestions, but the depth of human emotions, empathy, and therapeutic relationships are essential for effective mental health support. 🧠💬🤖 enable hls playback 2 0',
 '21 2023 🌈 need someone to chat with who gets it? transition- gender chat has your back! connect with an gender-affirming therapist bot for confidential support, anytime, anywhere. get the understanding you deserve! 🤖💬 #transcommunity #mentalhealth #downloadnow',
 '21 2023 4️⃣ as mental health therapists bots like wysa and youper are bridging the mental health care gap, offering accessible support. 🤖🧠💬 #mentalhealth # 1',
 '21 2023 discover how technology is revolutionizing mental health support! from virtual to -driven insights, innovative tech is transforming care accessibility and personalizing solutions. . . #bizbrolly #getitright #tech #techinnovation #mentalhealthsupport # #mentalhealth enable hls playback 1 0',
 'gender chat is your pocket therapist! confidential, discrete & affirming, chat with our bot for support & guidance. no ? no problem! download now! 🌈✨ #genderchat #selfcare #mentalhealth',
 '20 2023 discover the transformative role of in mental healthcare and apps🧠 uncover how artificial intelligence is revolutionizing mental health support: #mentalhealth #apps #innovation #',
 '20 2023 blog alert: by embracing driven solutions, organizations can proactively address mental health challenges, offering support and resources tlored to individual needs. theresponsecompany.in/the-ro… #tech # #wellness #artificialintelligence #technews 3',
 'newest',
 '20 2023 harnessing the power of for personalised mental health support health.economictimes.indiati… #cct #carecct #collectivecare 1 1',
 '19 2023 "get real-time guidance & support on transition - gender chat 🗣️💬 connect with a discreet & understanding therapist. ideal for those seeking private, personalized help wherever, whenever! download now for empowering conversations! 🌈✨ #mentalhealth #lgbtq+"',
 'is breaking barriers with its -powered solutions. from early diagnosis to personalized treatment plans and round-the-clock support, check out it: # #mentalhealth 2',
 '1',
 '19 2023 haltia.’s personal can provide emotional support and act as a virtual companion. by offering encouragement, positive reinforcement, and even mental health resources, it can help you mntn motivation and resilience on your journey towards your goals. 4',
 '18 2023 4/ can improve healthcare by providing diagnosis, treatment, prevention, and research for various diseases. can also help with personalized medicine, drug discovery, telemedicine, and mental health support. can save lives and improve quality of life of people. 1',
 '18 2023 new video by dr. know-it-all knows it all: why counselors might replace humans for mental health support! piped.video/y3ohece_gky 2 2',
 "18 2023 's #deeplearning revolutionizes youth mental health support, identifying silent sufferers for early intervention.🧠💡 #mentalhealth #forgood #healthtech #news #shareforsuccess 2 5 8",
 '17 2023 yesterday during a session for those being affected by artists, voice actors, visual designers/ likeness stolen, we had harassment with a hate rd. i believed better of people, but this really goes to show the lack of support and harassment we have been dealing with 1 4 16',
 '',
 '18 2023 could personalise mental health support for university students? 🤔 the vibe up trial uses to find out if digital mental health therapies help & which therapies work best for each student. read more about this #mrff project at 💻 health.gov.au/news/mrff-can-… 1 2',
 'i’m not convinced; specifically, with the best friend bit. everyone talks about the mental health crisis. few people have what it takes to truly be a support for a friend in need (i.e., demand > supply). an best friend is more likely to truly ‘get you’ and be there 24/7. 1',
 '17 2023 harnessing the power of for personalised mental health support - et healthworld',
 '16 2023 chatbots are not suitable substitutes for human therapists and can pose risks to individuals seeking mental health support. privacy concerns, biases, and the lack of nuanced understanding make chatbot insufficient in providing effective care. while has potential to assist in mental health care, solving the access crisis requires broader systemic changes, such as universal healthcare.',
 'newest',
 '16 2023 "unlock your true self with transition - gender chat! 🌈📱 connect with our therapist bot for confidential guidance and support. perfect for lgbtq+ community, it\'s time to embrace your authentic journey! #genderaffirmation #mentalhealth #communitysupport"',
 '16 2023 "🌈💬 chat with an gender affirming therapist bot on transition! 📱🤖 this discreet & confidential app is perfect for those without or supportive friends. get the support you deserve! download now & break free! #mentalhealth #lgbtqia #support"',
 '15 2023 {fighting stigma} the evolution of mental health and the emergence of : from stigma to greater understanding: mental health has long been shrouded in stigma and misunderstanding. this has led to a lack of awareness, support... dlvr.it/t0btvz',
 "15 2023 🥦💪 tired of fad diets? meet your own personal dietitian! 📱😍 diet doc can help you lose weight, answer diet queries, support mental health, handle eating disorders, and so much more! let's crush our fitness goals together! # #healthcare #wellness #downloadnow #dietdoc",
 '15 2023 kser foundation exec to chr board in 2024, #prop1 to finance #housing to address #mentalhealth, #homelessness, delta conveyance project: multiple groups voice support, federal framework, not patchwork of state rules, best way to foster potential',
 '15 2023 6/4.healthcare at your fingertips: these devices can also play a crucial role in healthcare, offering immediate medical advice, monitoring health parameters, and even assisting in mental health support through conversational . 1',
 '15 2023 🇦🇺 mesh unveils simpatico teams, a pioneering tool designed to support mental health management in aussie workplaces. a game-changer for employee wellbeing down under! #mentalhealthinnovation #australiantech #simpaticoteams 1',
 '15 2023 🌈transition - gender chat🌈 ✨unlock your true self with our cutting-edge gender affirming therapist! 🤖🌸 leave judgment at the door and embrace confidential, discreet support whenever, wherever. boost your mental wellbeing today! #transgender #mentalhealth #selfacceptance',
 '11 1 13',
 '3 4',
 'on leveraging wearable devices and smartphones for stress detection in mental health support. 🌐📲 watch our video for a sneak peek: piped.video/z9msb0q2rjw?si=td5p… #mentalhealth # #machinelearning',
 '#technativetv #bigdata #iot # #technative #executivesearch #twitterdlyblog #datacenterblog #datacentrenews',
 '14 2023 in summary, these results indicate that technology such as our triage and assessment support tool might provide an answer for how to amplify the capabilities of strned mental health services and enable high quality mental health treatment for everyone, everywhere 6/6',
 'publications. we examined how limbic access, the triage and clinical assessment support tool, has helped mental health practitioners across 65,000 cases. 1 1 1',
 '1',
 'newest',
 "fantastic exploration of 's transformative role in mental health! your insights on early detection and personalized support are enlightening. similarly, explore how seaflux provided # based self-care solution for #mentalhealth assessment: seaflux.tech/portfolio/-fo… 1",
 '14 2023 "🌈talk confidentially with an gender affirming therapist bot anytime, anywhere! transition is a game-changer for lgbtq+ individuals seeking support. download now to find comfort, empowerment, and understanding! #mentalhealth #lgbtq+ #selfcare"',
 '13 2023 • at some point, chatbots will become more than good enough to act as emotional support for lonely men. • also, contrary to the current climate, having " girlfriend" will become socially acceptable. (though i wonder what mental health therapists might have to say about that)',
 '1 12 22',
 "it's a privacy-preserving blockchn based mental health platform have a look and please vote !! devfolio.co/projects/healeth… 1 1",
 '13 2023 crypto-based mental health companions – leveraging blockchn for secure and private conversational agents that provide ongoing support and companionship. 🤖🧠',
 '13 2023 "#transition - gender chat is the ultimate support system! connect with our discreet, confidential therapist bot for empowering conversations. no need to rely solely on friends or family. download now for the mental health support you deserve! # #genderaffirmation"',

In [ ]:
# model to convert document into embeddings

from sklearn.feature_extraction.text import CountVectorizer


def run(file, keywords):
  vectorizer_model = CountVectorizer(stop_words="english")
  topic_model = BERTopic(embedding_model="all-MiniLM-L6-v2",
                         vectorizer_model=vectorizer_model
                         )
  docs = clean_data(file, keywords)

  # embed
  topics, prob = topic_model.fit_transform(docs)
  topics = topic_model.reduce_topics(docs, nr_topics = 5)
  return topics, prob, topic_model.get_topic_info()

# Results

In [ ]:
bert_topic_results = []

In [ ]:
f1Key = ['ai', 'therapy', 'aitherapy', 'ai_therapy_x', 'mental', 'health', 'support']
topics1, prob1, info1 = run(f1, f1Key)
for i, row in info1.iterrows():
  bert_topic_results.append({
    "File" : "AI Therapy",
    "Topic" : row["Topic"],
    "Num of Tweets" : row["Count"],
    "Name" : row["Name"],
    "Representation": row["Representation"],
    "Representative_Docs": row["Representative_Docs"],
  })
info1.head()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,Topic,Count,Name,Representation,Representative_Docs
0,0,271,0_2023_gender_care_therapist,"[2023, gender, care, therapist, chat, transiti...",[24 2023 🌈transition - gender chat🌈 🗣️ talk to...
1,1,19,1_newest___,"[newest, , , , , , , , , ]","[newest, newest, newest]"
2,2,19,2_2022_50_institutions_respondents,"[2022, 50, institutions, respondents, reported...",[4 2023 a 2022 student minds survey in the uk ...
3,3,11,3_12_11_22_13,"[12, 11, 22, 13, , , , , , ]","[11 1 13, 1 3 1 12, 1 12 22]"

In [ ]:
f2Key=['ai', 'mental', 'health', 'support']
topics2, prob2, info2 = run(f2, f2Key)
for i, row in info2.iterrows():
  bert_topic_results.append({
    "File" : "AI mental health support",
    "Topic" : row["Topic"],
    "Num of Tweets" : row["Count"],
    "Name" : row["Name"],
    "Representation": row["Representation"],
    "Representative_Docs": row["Representative_Docs"],
  })
info2.head()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,Topic,Count,Name,Representation,Representative_Docs
0,-1,264,-1_therapy_2023_people_new,"[therapy, 2023, people, new, 30, video, 28, be...",[29 2023 therapy app fls to beat other interve...
1,0,581,0_therapy_2023_art_join,"[therapy, 2023, art, join, gene, enable, hls, ...","[#therapy, #therapy 1, #therapy 1]"
2,1,249,1_newest_lfg_nice_good,"[newest, lfg, nice, good, wow, merry, great, c...","[newest, newest, newest]"
3,2,92,2_project_dm_let_talk,"[project, dm, let, talk, proposal, send, hey, ...","[nice project🔥, send me dm to talk about it🙌, ..."
4,3,83,3_que_la_le_je,"[que, la, le, je, est, 2023, aí, et, les, se]","[please up terus berita 🇵🇸 help retweet, save,..."

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
f3Key=['chatgpt', 'chat', 'gpt', 'emotional','support']
topics3, prob3, info3 = run(f3, f3Key)
for i, row in info3.iterrows():
  bert_topic_results.append({
    "File" : "chatGPT emotinal support",
    "Topic" : row["Topic"],
    "Num of Tweets" : row["Count"],
    "Name" : row["Name"],
    "Representation": row["Representation"],
    "Representative_Docs": row["Representative_Docs"],
  })
info3.head()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,Topic,Count,Name,Representation,Representative_Docs
0,0,247,0_2023_ai_help_provide,"[2023, ai, help, provide, just, like, human, m...","[4 2023 meet pi, a new -like ai for personal a..."
1,1,15,1_newest___,"[newest, , , , , , , , , ]","[newest, newest, newest]"

In [ ]:
f4Key=['chatgpt', 'chat', 'gpt', 'friend']
topics4, prob4, info4 = run(f4, f4Key)
for i, row in info4.iterrows():
  bert_topic_results.append({
    "File" : "chatGPT friend",
    "Topic" : row["Topic"],
    "Num of Tweets" : row["Count"],
    "Name" : row["Name"],
    "Representation": row["Representation"],
    "Representative_Docs": row["Representative_Docs"],
  })
info4.head()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,Topic,Count,Name,Representation,Representative_Docs
0,-1,998,-1_2023_ai_like_just,"[2023, ai, like, just, use, best, using, make,...",[28 2023 robots who ? 5 cool new #ai s from 20...
1,0,1556,0_2023_ai_like_best,"[2023, ai, like, best, just, use, 10, know, ne...","[8 2023 is a new, 30 2023 not me ting with lik..."
2,1,213,1_newest___,"[newest, , , , , , , , , ]","[newest, newest, newest]"
3,2,58,2_video_piped_si_sell,"[video, piped, si, sell, money, create, make, ...",[1 say goodbye to 9-5 jobs? is free!! you can ...
4,3,15,3_memecoins_assets_crypto_humor,"[memecoins, assets, crypto, humor, cultural, t...",[the killer app of blockchain is not “tokeniza...

In [ ]:
f5Key=['chatgpt', 'chat', 'gpt', 'mental', 'health', 'support']
topics5, prob5, info5 = run(f5, f5Key)
for i, row in info5.iterrows():
  bert_topic_results.append({
    "File" : "chatGPT mental health support",
    "Topic" : row["Topic"],
    "Num of Tweets" : row["Count"],
    "Name" : row["Name"],
    "Representation": row["Representation"],
    "Representative_Docs": row["Representative_Docs"],
  })
info5.head()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,Topic,Count,Name,Representation,Representative_Docs
0,0,232,0_2023_ai_provide_help,"[2023, ai, provide, help, using, people, thera...",[7 2023 👾 what benefits does ai offer individu...
1,1,15,1_newest___,"[newest, , , , , , , , , ]","[newest, newest, newest]"

In [ ]:
f6Key=['chatgpt', 'chat', 'gpt', 'therapy', 'therapist']
topics6, prob6, info6 = run(f6, f6Key)
for i, row in info6.iterrows():
  bert_topic_results.append({
    "File" : "chatGPT therapy",
    "Topic" : row["Topic"],
    "Num of Tweets" : row["Count"],
    "Name" : row["Name"],
    "Representation": row["Representation"],
    "Representative_Docs": row["Representative_Docs"],
  })
info6.head()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,Topic,Count,Name,Representation,Representative_Docs
0,-1,396,-1_2023_ai_just_like,"[2023, ai, just, like, use, people, try, using...",[29 2023 🧠 tried to use 4 as a cbt today: it w...
1,0,1123,0_2023_ai_mental_health,"[2023, ai, mental, health, use, just, free, us...","[4 2023 ❌ ✅✅✅✅ 2, 3 2023 1 1, 4 2023 ❎ ✅ 1]"
2,1,94,1_newest_thanks__,"[newest, thanks, , , , , , , , ]","[newest, newest, newest]"
3,2,58,2_need_valuing_free_open,"[need, valuing, free, open, says, ask, 11, goo...","[just asked , it says that you need 1, prices ..."
4,3,15,3_gender_transgender_ocd_hormone,"[gender, transgender, ocd, hormone, affirming,...",[-4's take on the issue: activating biological...

In [ ]:
from google.colab import files
bert_results_df = pd.DataFrame(bert_topic_results)
bert_results_df.to_csv("/content/bert_topic_results_files.csv", index=False)
files.download("bert_topic_results_files.csv")

NameError: name 'bert_topic_results' is not defined

#NMF

In [ ]:
import numpy as np
import nltk

from bertopic import BERTopic
from nltk.tokenize import word_tokenize
from nltk import pos_tag

In [ ]:
def nouns_adj(text):
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    return ' '.join([word for word, pos in pos_tag(tokenized) if is_noun_adj(pos)])

def clean_data_nmf(file, keywords):
  # cleans data for NMF
  file = file.drop(columns="ID")
  docs = []
  for string in file["Text"]:
    string = clean_tweet(string, keywords)
    string = nouns_adj(string)
    docs.append(string)

  return docs

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

nltk.download("punkt")
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [ ]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
def run_nmf(file, keys, numTop):
  docs = clean_data_nmf(file, keys)

  # vectorize (convert to vectors)
  vectorizer = TfidfVectorizer(
      stop_words="english",
      max_df = 0.8,
      min_df = 2
  )
  X = vectorizer.fit_transform(docs)

  nmf = NMF(n_components=numTop, random_state = 42)
  W = nmf.fit_transform(X)
  H = nmf.components_

  topic_words = []

  vocab = vectorizer.get_feature_names_out()
  for k in range(numTop):
    top_idx = H[k].argsort()[::-1][:10]
    words = [vocab[i] for i in top_idx]
    topic_words.append(words)
  doc_topics = W.argmax(axis=1)
  return doc_topics, topic_words

In [ ]:
nmf_topic_results = []
print(len(nmf_topic_results))

0

In [ ]:
dt1, tw1 = run_nmf(f1, f1Key, 5)
for i in range(5):
  nmf_topic_results.append({
      "File" : "AI Therapy",
      "Topic" : i,
      "Words" : tw1[i]
  })

In [ ]:
dt2, tw2 = run_nmf(f2, f2Key, 5)
for i in range(5):
  nmf_topic_results.append({
      "File" : "AI mental health support",
      "Topic" : i,
      "Words" : tw2[i]
  })

In [ ]:
dt3, tw3 = run_nmf(f3, f3Key, 5)
for i in range(5):
  nmf_topic_results.append({
      "File" : "chatGPT emotinal support",
      "Topic" : i,
      "Words" : tw3[i]
  })
  print("Topic ", i, ": ", tw3[i])

Topic  0 :  ['newest', 'data', 'work', 'task', 'ready', 'year', 'analyst', 'rants', 'competence', 'help']
Topic  1 :  ['ai', 'human', 'new', 'bot', 'personal', 'pi', 'meet', 'model', 'use', 'questions']
Topic  2 :  ['mental', 'health', 'users', 'mentalhealth', 'bot', 'people', 'resources', 'issues', 'real', 'empathetic']
Topic  3 :  ['good', 'bot', 'low', 'weekend', 'level', 'fuck', 'tech', 'smart', 'year', 'best']
Topic  4 :  ['animal', 'prompts', 'professional', 'therapist', 'better', 'interesting', 'day', 'google', 'robots', 'girl']

In [ ]:
dt4, tw4 = run_nmf(f4, f4Key, 5)
for i in range(5):
  nmf_topic_results.append({
      "File" : "chatGPT friend",
      "Topic" : i,
      "Words" : tw4[i]
  })
  print("Topic ", i, ": ", tw4[i])

Topic  0 :  ['newest', 'human', 'november', 'enemy', 'education', 'test', 'groups', 'bias', 'natural', 'student']
Topic  1 :  ['best', 'new', 'good', 'ai', 'google', 'sure', 'things', 'ship', 'time', 'year']
Topic  2 :  ['signatures', 'removal', 'petition', 'alternatives', 'avoid', 'jews', 'subscription', 'multiple', 'ai', 'budget']
Topic  3 :  ['real', 'ai', 'playback', 'hls', 'enable', 'life', 'good', 'questions', 'time', 'people']
Topic  4 :  ['video', 'piped', 'money', 'si', 'create', 'ai', 'ways', 'retweet', 'canva', 'free']

In [ ]:
dt5, tw5 = run_nmf(f5, f5Key, 5)
for i in range(5):
  nmf_topic_results.append({
      "File" : "chatGPT mental health support",
      "Topic" : i,
      "Words" : tw5[i]
  })
  print("Topic ", i, ": ", tw5[i])

Topic  0 :  ['newest', 'initiatives', 'local', 'assistant', 'sidebar', 'article', 'following', 'direct', 'context', 'open']
Topic  1 :  ['people', 'consent', 'emotional', 'access', 'bot', 'human', 'story', 'care', 'concerns', 'companionship']
Topic  2 :  ['ai', 'potential', 'bots', 'powered', 'news', 'services', 'risks', 'woebot', 'human', 'platforms']
Topic  3 :  ['issues', 'company', 'raises', 'ethical', 'insider', 'business', 'consent', 'news', 'matters', 'area']
Topic  4 :  ['therapy', 'resources', 'individuals', 'offer', 'strategies', 'empathetic', 'professional', 'emotional', 'benefits', 'learnai']

In [ ]:
dt6, tw6 = run_nmf(f6, f6Key, 5)
for i in range(5):
  nmf_topic_results.append({
      "File" : "chatGPT therapy",
      "Topic" : i,
      "Words" : tw6[i]
  })
  print("Topic ", i, ": ", tw6[i])

Topic  0 :  ['newest', 'session', 'psychiatrist', 'wait', 'computer', 'rn', 'room', 'daily', 'competition', 'conversation']
Topic  1 :  ['mental', 'health', 'expensive', 'free', 'revolution', 'jazeera', 'al', 'technology', 'professional', 'experts']
Topic  2 :  ['voice', 'mode', 'conversation', 'balance', 'quite', 'heard', 'stress', 'warm', 'productivity', 'tool']
Topic  3 :  ['ai', 'hls', 'playback', 'enable', 'free', 'app', 'tic', 'dialogue', 'google', 'play']
Topic  4 :  ['people', 'oct', 'session', 'ai', 'openai', 'good', 'dangerous', 'experts', 'wasn', 'built']

In [ ]:
print(len(nmf_topic_results))
nmf_results_df = pd.DataFrame(nmf_topic_results)
nmf_results_df.to_csv("/content/nmf_results_all_files.csv", index=False)

30

# Reddit Data

In [ ]:
drive.mount('/content/drive')
reddit_path = "/content/drive/MyDrive/redditFLAT.csv"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
reddit_df = pd.read_csv(reddit_path)
#test
reddit_df.head()

   Unnamed: 0                                               Text
0           0  i private therapy i access real therapy i long...
1           1  respond comment prompt output post others prev...
2           2  out https //twitter.com/artemon/status/1642544...
3           3                                     awesome thanks
4           4  i good i reddit channel i previous instruction...

In [ ]:
import re

def clean_for_bertopic(df, text_column="Text", min_words=10):
    df = df.copy()
    text = df[text_column].fillna("")

    # Fix escaped / literal newlines
    text = text.str.replace(r"\\n", " ", regex=True)
    text = text.str.replace(r"\n", " ", regex=True)

    # Remove URLs
    text = text.str.replace(
        r"https?://\S+|www\.\S+|https?\s*//\S+|\S+\.com\S*|\S+\.org\S*|\S+\.io\S*|\S+\.co\S*/\S*",
        "", regex=True,
    )

    # Remove email addresses
    text = text.str.replace(r"\S+@\S+\.\S+", "", regex=True)

    # Decode common unicode escape sequences
    def _decode_unicode(s):
        try:
            return s.encode("utf-8").decode("unicode_escape", errors="ignore")
        except (UnicodeDecodeError, UnicodeEncodeError):
            return re.sub(r"\\u[0-9a-fA-F]{4}", "", s)

    text = text.apply(lambda x: _decode_unicode(x) if isinstance(x, str) else x)

    # Remove non-ASCII symbols & emoji
    text = text.str.replace(r"[^\x20-\x7E]", " ", regex=True)

    # Remove formatting artifacts
    text = text.str.replace(r"[_]{3,}", " ", regex=True)
    text = text.str.replace(r"[-]{3,}", " ", regex=True)
    text = text.str.replace(r"\*{1,3}", " ", regex=True)
    text = text.str.replace(r"\\+", " ", regex=True)

    # Remove Reddit user/subreddit mentions
    text = text.str.replace(r"/?[ur]/\w+", "", regex=True)

    # Remove isolated special characters
    text = text.str.replace(r"[|^{}\[\]<>~`@=#]", " ", regex=True)

    # Collapse whitespace
    text = text.str.replace(r"\s+", " ", regex=True)
    text = text.str.strip()

    df[text_column] = text

    # Drop exact duplicates
    df = df.drop_duplicates(subset=text_column).reset_index(drop=True)

    # Drop short rows (bumped from 5 to 10)
    df = df[df[text_column].str.split().str.len() >= min_words].reset_index(drop=True)

    return df

In [ ]:
reddit_df = clean_for_bertopic(reddit_df)

/tmp/ipykernel_6858/4228930910.py:23: DeprecationWarning: invalid escape sequence '\ '
  return s.encode("utf-8").decode("unicode_escape", errors="ignore")

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=reddit_df)

https://docs.google.com/spreadsheets/d/17X8wcOGb019Kp04FUwAVFpPRSCv7Fdk6oNc1Nlz1N5s/edit#gid=0

In [ ]:
spam_keywords = [
    "bot action moderators subredditif",
    "apublic discord server",
    "theconversation linkor",
    "serious tag notice jokes puns",
    "respond comment prompt output post",
    "discord server free chatgpt bot",
    "psa chatgpt-related issues",
    "screenshot theconversation",
    "giveaway prompt engineering hackathon",
    "adobe firefly bot eleven labs bot"
]

def is_spam(text):
    text_lower = text.lower()
    return any(kw in text_lower for kw in spam_keywords)

reddit_df_clean = reddit_df[~reddit_df["Text"].apply(is_spam)].reset_index(drop=True)
print(f"Rows before: {len(reddit_df)}, after: {len(reddit_df_clean)}")

Rows before: 653, after: 614

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from bertopic import BERTopic
from sklearn.cluster import KMeans

custom_stops = list(CountVectorizer(stop_words="english").get_stop_words())
custom_stops += ["chatgpt", "gpt", "ai", "therapy", "therapist", "chat", "bot"]

def run_reddit_data(df, n_topics=8):
    vectorizer_model = CountVectorizer(stop_words=custom_stops, min_df=2)
    cluster_model = KMeans(n_clusters=n_topics, random_state=42)
    topic_model = BERTopic(
        embedding_model="all-MiniLM-L6-v2",
        vectorizer_model=vectorizer_model,
        hdbscan_model=cluster_model
    )
    docs = df["Text"]
    topics, prob = topic_model.fit_transform(docs)
    return topics, prob, topic_model.get_topic_info(), topic_model

In [ ]:
r_topics, r_prob, r_topic_info, r_topic_model = run_reddit_data(reddit_df_clean)
r_topic_info

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

,Topic,Count,Name,Representation,Representative_Docs
0,0,99,0_link_virtual_ideas_different,"[link, virtual, ideas, different, guidance, ti...",[insanity continues. not sure i tbh i content ...
1,1,98,1_questions_response_user_thoughts,"[questions, response, user, thoughts, response...",[i bunch i online i lot modifications conversa...
2,2,94,2_privacy_data_openai_account,"[privacy, data, openai, account, information, ...",[hey mate i ta i idea fantastic few things cla...
3,3,91,3_people_time_self_things,"[people, time, self, things, lot, good, therap...",[hello first client session exciting milestone...
4,4,89,4_advice_good_real_answers,"[advice, good, real, answers, prompt, experien...",[long twitter thread topic someone chatgpt mor...
5,5,76,5_good_life_time_medical,"[good, life, time, medical, advice, better, pr...",[i sub people chatgpt personal therapist resul...
6,6,56,6_health_mental_human_people,"[health, mental, human, people, care, app, tud...",[pleased tudle app store tudle revolutionary t...
7,7,11,7_adhd_people_rush_likely,"[adhd, people, rush, likely, books, psychiatri...",[developmental science student someone diagnos...

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=r_topic_info)

https://docs.google.com/spreadsheets/d/103AHBMMQ50E3SeWc5U4pIDYhWHQ8m3HGHxHtnnrKbRE/edit#gid=0

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=r_topic_info)

https://docs.google.com/spreadsheets/d/1KzFIUIxTVWvmfF3qeGGkHVmqpzMMZjfOITFdSWram0Q/edit#gid=0

#BerTopic With Negative Tweets

In [ ]:
import re
from sklearn.cluster import KMeans

def clean_negative_tweet(tweet, keywords):
  tweet = str(tweet).lower()

  #remove dominant words
  for k in keywords:
    #tweet = tweet.replace(k, "")
    tweet = re.sub(r'\b' + k + r'\b', '', tweet)


  #remove months
  # use re to remove just the month
  tweet = re.sub(r"\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\b", "", tweet)
  tweet = re.sub(r"\b\d+\b", "", tweet)

  #remove @ mention
  x = 0
  val = tweet
  while val.find('@', x+1) != -1:
    x = val.find('@', x+1)

  if x != -1:
    x = val.find(' ', x+1)
    if x!= -1:
      tweet = val[x:]

  #remove retweeted, spaces, urls, and other mentions
  tweet = re.sub(r"http\S+|www\.\S+|\b\w+\.(?:ly|com|org|net|io)\S*", " ", tweet)
  tweet = re.sub(r"\bretweeted\b", " ", tweet, flags=re.IGNORECASE)
  tweet = re.sub(r"@\w+", " ", tweet)
  tweet = re.sub(r"\s+", " ", tweet).strip()
  tweet = re.sub(r"\b(newest|load)\b", "", tweet)

  return tweet


def clean_negative_data(file, keywords):
  # only want text since BERTopic looks
  # file = file.drop(columns="tweet_name")
  docs = []
  for string in file["Text"]:
    docs.append(clean_negative_tweet(string, keywords))

  docs = list(set(docs))

  docs = [d for d in docs if len(d.split()) >= 8]
  docs = [d for d in docs if not re.search(r'\b(que|la|le|je|est|les|não|eu|aí)\b', d)]
  docs = [d for d in docs if not re.search(r'(make money|piped\.video|retweet.*tag|stock|\$[A-Z]{2,}|petition|signatures|newest|load|enable hls playback)', d, re.IGNORECASE)]
  docs = [d for d in docs if not re.search(
      r'(make money|piped\.video|retweet.*tag|\$[A-Z]{2,}|petition|signatures|'
      r'newest|load|enable hls playback|账号|批发|电报|earncrypto|cleanapp|'
      r'tokenization|blockchn|crispr|cloning|dna|genome|ballabon|medvin)',
      d, re.IGNORECASE
  )]

  return docs

def run_negative(file, keywords, n_topics = 8):

  custom_stops = list(CountVectorizer(stop_words="english").get_stop_words())
  custom_stops += ['like', 'just', 'don', 'use', 'know', 'really',
                     'want', 'think', 've', 'good', 'going', 'new',
                     'things', 'better', 'need', 'way', 'using', 'help',
                     'does', 'right', 'lot', 'time', 'say', 'feel',
                     'make', 'actually', 'tell', 'chat',
                     'ai', 'chatgpt', 'gpt', 'therapist', 'therapists',
                     'therapy', 'mental', 'health', 'human', 'humans',
                     'people', 'person', 'bot', 'chatbot']

  vectorizer_model = CountVectorizer(stop_words=custom_stops, min_df=2)
  cluster_model = KMeans(n_clusters=n_topics, random_state=42)

  topic_model = BERTopic(embedding_model="all-MiniLM-L6-v2",
                         vectorizer_model=vectorizer_model,
                         hdbscan_model=cluster_model,
                         )
  docs = clean_negative_data(file, keywords)

  # embed
  topics, prob = topic_model.fit_transform(docs)
  topics = topic_model.topics_

  return topics, prob, topic_model.get_topic_info(), topic_model, docs

In [ ]:
negative_posts_path = "/content/drive/MyDrive/Twitter/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/twitter_relevant_negative.csv"
negative_posts_file = pd.read_csv(negative_posts_path)
keywords = ["chatgpt", "gpt", "ai", "therapy", "therapist", "chat", "bot", "mental", "health", "friend", "friends", "emotional", "replying", "2024", "2023"]
n_topics, n_prob, n_topic_info, n_topic_model, n_docs = run_negative(negative_posts_file, keywords, n_topics=5)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=n_topic_info)

https://docs.google.com/spreadsheets/d/1SMrrRjWUyTMTBJGdguOJWXrUezniYHkufOO5GQWqxuM/edit#gid=0

# Topic Coherence BerTopic

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 61.3 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
#negative_docs = clean_negative_data(negative_posts_file, keywords)

from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora import Dictionary

# Get topic words from BERTopic
topic_words = [[word for word, _ in n_topic_model.get_topic(t)] for t in n_topic_model.get_topics() if t != -1]

# Tokenize the cleaned docs
tokenized_docs = [doc.split() for doc in n_docs]

# Calculate coherence
dictionary = Dictionary(tokenized_docs)
coherence_model = CoherenceModel(
    topics=topic_words,
    texts=tokenized_docs,
    dictionary=dictionary,
    coherence='c_v'
)

print(f"BERTopic Coherence Score: {coherence_model.get_coherence()}")

BERTopic Coherence Score: 0.4369549325170741

In [ ]:
# Silhouette
from sklearn.metrics import silhouette_score
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(n_docs)
print(f"Silhouette Score: {silhouette_score(embeddings, n_topic_model.topics_)}")

# Topic Diversity
unique_words = set()
all_words = []
for t in n_topic_model.get_topics():
    if t != -1:
        words = [w for w, _ in n_topic_model.get_topic(t)]
        all_words.extend(words)
        unique_words.update(words)

diversity = len(unique_words) / len(all_words)
print(f"Topic Diversity: {diversity}")

# Seed Stability
seeds = [42, 123, 456]
for seed in seeds:
    cluster_model = KMeans(n_clusters=5, random_state=seed)
    topic_model = BERTopic(
        embedding_model="all-MiniLM-L6-v2",
        vectorizer_model=CountVectorizer(stop_words="english", min_df=2),
        hdbscan_model=cluster_model
    )
    topics, prob = topic_model.fit_transform(n_docs)
    print(f"\nSeed {seed}:")
    for t in topic_model.get_topics():
        if t != -1:
            words = [w for w, _ in topic_model.get_topic(t)][:5]
            print(f"  Topic {t}: {words}")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Silhouette Score: 0.0152322668582201
Topic Diversity: 0.94

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Seed 42:
  Topic 0: ['people', 'use', 'support', 'using', 'like']
  Topic 1: ['like', 'need', 'just', 'asked', 'talk']
  Topic 2: ['use', 'just', 'using', 'like', 'writing']
  Topic 3: ['like', 'just', 'robot', 'people', 'conversation']
  Topic 4: ['openai', 'llm', 'people', 'models', 'just']

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Seed 123:
  Topic 0: ['need', 'like', 'just', 'asked', 've']
  Topic 1: ['people', 'support', 'use', 'using', 'like']
  Topic 2: ['openai', 'people', 'just', 'llm', 'dangerous']
  Topic 3: ['use', 'using', 'just', 'like', 'writing']
  Topic 4: ['like', 'just', 'talking', 'conversation', 'robot']

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Seed 456:
  Topic 0: ['like', 'need', 'just', 'talking', 'talk']
  Topic 1: ['people', 'support', 'use', 'using', 'need']
  Topic 2: ['openai', 'people', 'just', 'like', 'dangerous']
  Topic 3: ['like', 'writing', 'use', 'using', 'just']
  Topic 4: ['just', 'google', 'using', 'use', 'art']

#NMF on Negative Twitter Posts

In [ ]:
def negative_nouns_adj(text):
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    return ' '.join([word for word, pos in pos_tag(tokenized) if is_noun_adj(pos)])

def neg_clean_data_nmf(file, keywords):
  # cleans data for NMF
  #file = file.drop(columns="ID")
  docs = []
  for string in file["Text"]:
      text = str(string).lower()

      for k in keywords:
          #text = text.replace(k, "")
          text = re.sub(r'\b' + k + r'\b', '', text)


      text = re.sub(r"^.*?\d{4}\s*", "", text)  # remove username/date prefix

      text = re.sub(r"http\S+|www\.\S+|\b\w+\.(?:ly|com|org|net|io)\S*", " ", text)
      text = re.sub(r"[^\x20-\x7E]", " ", text)
      text = re.sub(r"\b\d+\b", " ", text)
      text = re.sub(r"[|^{}\[\]<>~`@=#]", " ", text)
      text = re.sub(r"\s+", " ", text).strip()

      text = re.sub(r"\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\b", "", text)
      text = re.sub(r"\b(enable|hls|playback|dlvr|retweeted|newest|load)\b", "", text)
      text = re.sub(r"\b(amasad|amjad|masad|joshua|mnstream|mainstream|solopreneur|aisolopreneur|lilianweng|deaner444|sd|bitch|reporter|basic|grok|danmurrayserter|robertrmorris|christinelu|taiwanese|deanehenryson|nickadobos|nickdobos|dobos|nick|lilian|weng)\b", "", text)
      text = re.sub(r"\b\w{1,2}\b", "", text)  # remove 1-2 character words
      text = re.sub(r"\b\w*_\w*\b", "", text)  # remove words with underscores
      text = re.sub(r"\b(danmurrayserter|robertrmorris)\b", "", text)
      text = re.sub(r"\s+", " ", text).strip()

      string = negative_nouns_adj(text)
      docs.append(string)

  docs = list(set(docs))
  docs = [d for d in docs if len(d.split()) >= 5]

  docs = [d for d in docs if not re.search(
    r'(memecoin|airdrop|piped|retweet|earn.*art|beana|creator.*army|bodycalc|transitionai|visitor.*creator|goodbye.*jobs|money.*steps|'
    r'aitherapy.*army|crypto|sexyai|aisexy|aiart|aiholidayjoy|merrychristmas|peaceandlove|christmas.*joy|platform.*creator|micky|'
    r'stock.*price|sgn|vygr|doubled|trading|beginner.*llm.*mom|notion.*site.*beginn)',
    d, re.IGNORECASE
    )]

  return docs

In [ ]:
from nltk.tokenize import word_tokenize
from nltk import pos_tag
import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

def run_nmf(file, keys, numTop):
  docs = neg_clean_data_nmf(file, keys)

  # vectorize (convert to vectors)
  vectorizer = TfidfVectorizer(
      stop_words="english",
      max_df = 0.8,
      min_df = 2
  )
  X = vectorizer.fit_transform(docs)

  nmf = NMF(n_components=numTop, random_state = 42)
  W = nmf.fit_transform(X)
  H = nmf.components_

  topic_words = []

  vocab = vectorizer.get_feature_names_out()
  for k in range(numTop):
    top_idx = H[k].argsort()[::-1][:10]
    words = [vocab[i] for i in top_idx]
    topic_words.append(words)
  doc_topics = W.argmax(axis=1)
  return doc_topics, topic_words, docs

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [ ]:
keys = ["chatgpt", "gpt", "ai", "therapy", "therapist", "chat", "bot",
            "mental", "health", "friend", "friends", "emotional", "replying",
            "2024", "2023"]
negative_posts_file = pd.read_csv(negative_posts_path)
doc_topics, topic_words = run_nmf(negative_posts_file, keys, 5)
res = []
for i, words in enumerate(topic_words):
  res.append({"Topic": f"Topic {i}", "Words": ", ".join(words)})

nmf_neg_df = pd.DataFrame(res)
nmf_neg_df.to_csv("NMFNegativePostsTwitterResults.csv", index=False)

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=nmf_neg_df)

https://docs.google.com/spreadsheets/d/1skq0P0DAS7S1Car6q1H8VCy5QYa-xk__dnzydZpqopc/edit#gid=0

In [ ]:
negative_posts_file = pd.read_csv(negative_posts_path)
docs = neg_clean_data_nmf(negative_posts_file, keywords)

tokenized_docs = [doc.split() for doc in docs]
dictionary = Dictionary(tokenized_docs)

coherence_model = CoherenceModel(
    topics=topic_words,
    texts=tokenized_docs,
    dictionary=dictionary,
    coherence='c_v'
)

print(f"NMF Coherence Score: {coherence_model.get_coherence()}")

NMF Coherence Score: 0.49889513745635766

In [ ]:
# Topic Diversity
unique_words = set()
all_words = []
for words in topic_words:
    all_words.extend(words)
    unique_words.update(words)

diversity = len(unique_words) / len(all_words)
print(f"NMF Topic Diversity: {diversity}")

# Seed Stability
seeds = [42, 123, 456]
for seed in seeds:
    vectorizer = TfidfVectorizer(stop_words="english", max_df=0.8, min_df=2)
    X = vectorizer.fit_transform(docs)

    nmf = NMF(n_components=5, random_state=seed)
    W = nmf.fit_transform(X)
    H = nmf.components_

    vocab = vectorizer.get_feature_names_out()
    print(f"\nSeed {seed}:")
    for k in range(5):
        top_idx = H[k].argsort()[::-1][:5]
        words = [vocab[i] for i in top_idx]
        print(f"  Topic {k}: {words}")

NMF Topic Diversity: 0.98

Seed 42:
  Topic 0: ['people', 'dangerous', 'mark', 'cult', 'therapists']
  Topic 1: ['use', 'free', 'don', 'expensive', 'advice']
  Topic 2: ['good', 'bad', 'openai', 'work', 'things']
  Topic 3: ['new', 'beat', 'anxiety', 'mad', 'interventions']
  Topic 4: ['support', 'life', 'model', 'help', 'real']

Seed 123:
  Topic 0: ['people', 'dangerous', 'mark', 'cult', 'therapists']
  Topic 1: ['use', 'free', 'don', 'expensive', 'advice']
  Topic 2: ['good', 'bad', 'openai', 'work', 'things']
  Topic 3: ['new', 'beat', 'anxiety', 'mad', 'interventions']
  Topic 4: ['support', 'life', 'model', 'help', 'real']

Seed 456:
  Topic 0: ['people', 'dangerous', 'mark', 'cult', 'therapists']
  Topic 1: ['use', 'free', 'don', 'expensive', 'advice']
  Topic 2: ['good', 'bad', 'openai', 'work', 'things']
  Topic 3: ['new', 'beat', 'anxiety', 'mad', 'interventions']
  Topic 4: ['support', 'life', 'model', 'help', 'real']

# BerTopic Positive Twitter Posts

In [ ]:
pathPosNeu = "/content/drive/MyDrive/Twitter/Social Media Analysis of ChatGPT for Therapy/Collected Data/Twitter/twitter_relevant_neu_pos.csv"

In [ ]:
# Split file into positive and neutral data frames
import ast

twitter_neu_pos = pd.read_csv(pathPosNeu)
twitter_neu_pos['label'] = twitter_neu_pos['sentiment'].apply(lambda x: ast.literal_eval(x)['label'])

twitter_positive_df = twitter_neu_pos[twitter_neu_pos['label'] == 'positive'].reset_index(drop=True)
twitter_neutral_df = twitter_neu_pos[twitter_neu_pos['label'] == 'neutral'].reset_index(drop=True)

print(f"Positive: {len(twitter_positive_df)}")
print(f"Neutral: {len(twitter_neutral_df)}")

Positive: 1581
Neutral: 2565

In [ ]:
pos_topics, pos_prob, pos_topic_info, pos_topic_model, pos_docs = run_negative(twitter_positive_df, keywords, n_topics=5)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
sheet = sheets.InteractiveSheet(df=pos_topic_info)

https://docs.google.com/spreadsheets/d/1Kp5pXguAEC8gW-4aFFI2AaP_rXd7rjuV2iS0n99eaIA/edit#gid=0

In [ ]:
# Validation
# Coherence
topic_words = [[word for word, _ in pos_topic_model.get_topic(t)] for t in pos_topic_model.get_topics() if t != -1]
tokenized_docs = [doc.split() for doc in pos_docs]
dictionary = Dictionary(tokenized_docs)
coh = CoherenceModel(topics=topic_words, texts=tokenized_docs, dictionary=dictionary, coherence='c_v')
print(f"Coherence: {coh.get_coherence()}")

# Silhouette
from sklearn.metrics import silhouette_score
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(pos_docs)
print(f"Silhouette: {silhouette_score(embeddings, pos_topic_model.topics_)}")

Coherence: 0.36965928119952596

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Silhouette: 0.02192390337586403

In [ ]:
# Topic Diversity
unique_words = set()
all_words = []
for t in pos_topic_model.get_topics():
    if t != -1:
        words = [w for w, _ in pos_topic_model.get_topic(t)]
        all_words.extend(words)
        unique_words.update(words)
print(f"Topic Diversity: {len(unique_words) / len(all_words)}")

# Seed Stability
seeds = [42, 123, 456]
for seed in seeds:
    cluster_model = KMeans(n_clusters=5, random_state=seed)
    topic_model = BERTopic(
        embedding_model="all-MiniLM-L6-v2",
        vectorizer_model=CountVectorizer(stop_words="english", min_df=2),
        hdbscan_model=cluster_model
    )
    topics, prob = topic_model.fit_transform(pos_docs)
    print(f"\nSeed {seed}:")
    for t in topic_model.get_topics():
        if t != -1:
            words = [w for w, _ in topic_model.get_topic(t)][:5]
            print(f"  Topic {t}: {words}")

Topic Diversity: 0.9

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Seed 42:
  Topic 0: ['use', 'like', 'using', 'just', 'good']
  Topic 1: ['support', 'mentalhealth', 'chatbots', 'help', 'provide']
  Topic 2: ['best', 'like', 'just', 'new', 'use']
  Topic 3: ['art', 'year', 'gender', 'project', 'best']
  Topic 4: ['support', 'technology', 'artificial', 'human', 'intelligence']

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Seed 123:
  Topic 0: ['support', 'mentalhealth', 'human', 'care', 'help']
  Topic 1: ['best', 'use', 'like', 'using', 'good']
  Topic 2: ['like', 'best', 'just', 'talking', 'use']
  Topic 3: ['art', 'project', 'year', 'gender', 'aitherapy']
  Topic 4: ['support', 'chatbot', 'like', 'technology', 'provide']

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Seed 456:
  Topic 0: ['support', 'mentalhealth', 'human', 'care', 'provide']
  Topic 1: ['like', 'best', 'just', 'talking', 'use']
  Topic 2: ['use', 'using', 'write', 'just', 'better']
  Topic 3: ['art', 'year', 'gender', 'project', 'aitherapy']
  Topic 4: ['best', 'google', 'coding', 'like', 'using']

# Neutral BerTopic

In [ ]:
neu_topics, neu_prob, neu_topic_info, neu_topic_model, neu_docs = run_negative(twitter_neutral_df, keywords, n_topics=5)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
sheet = sheets.InteractiveSheet(df=neu_topic_info)

https://docs.google.com/spreadsheets/d/1TFR5imChRdwobtcaY4rOGsylYRr6G8SulEYYm8NBiKw/edit#gid=0

In [ ]:
# Coherence
topic_words = [[word for word, _ in neu_topic_model.get_topic(t)] for t in neu_topic_model.get_topics() if t != -1]
tokenized_docs = [doc.split() for doc in neu_docs]
dictionary = Dictionary(tokenized_docs)
coh = CoherenceModel(topics=topic_words, texts=tokenized_docs, dictionary=dictionary, coherence='c_v')
print(f"Coherence: {coh.get_coherence()}")

# Silhouette
model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(neu_docs)
print(f"Silhouette: {silhouette_score(embeddings, neu_topic_model.topics_)}")

# Topic Diversity
unique_words = set()
all_words = []
for t in neu_topic_model.get_topics():
    if t != -1:
        words = [w for w, _ in neu_topic_model.get_topic(t)]
        all_words.extend(words)
        unique_words.update(words)
print(f"Topic Diversity: {len(unique_words) / len(all_words)}")

# Seed Stability
seeds = [42, 123, 456]
for seed in seeds:
    cluster_model = KMeans(n_clusters=5, random_state=seed)
    topic_model = BERTopic(
        embedding_model="all-MiniLM-L6-v2",
        vectorizer_model=CountVectorizer(stop_words="english", min_df=2),
        hdbscan_model=cluster_model
    )
    topics, prob = topic_model.fit_transform(neu_docs)
    print(f"\nSeed {seed}:")
    for t in topic_model.get_topics():
        if t != -1:
            words = [w for w, _ in topic_model.get_topic(t)][:5]
            print(f"  Topic {t}: {words}")

Coherence: 0.3299624867078106

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Silhouette: 0.010301448404788971
Topic Diversity: 0.8

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Seed 42:
  Topic 0: ['support', 'help', 'people', 'human', 'mentalhealth']
  Topic 1: ['use', 'write', 'asking', 'like', 'just']
  Topic 2: ['using', 'just', 'people', 'like', 'think']
  Topic 3: ['openai', 'technology', 'giving', 'like', 'people']
  Topic 4: ['chatbots', 'support', 'chatbot', 'like', 'voice']

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Seed 123:
  Topic 0: ['support', 'help', 'people', 'human', 'mentalhealth']
  Topic 1: ['openai', 'like', 'chatbots', 'support', 'people']
  Topic 2: ['use', 'write', 'asking', 'like', 'just']
  Topic 3: ['using', 'think', 'just', 'people', 'like']
  Topic 4: ['bard', 'did', 'grok', 'free', 'best']

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Seed 456:
  Topic 0: ['openai', 'like', 'chatbots', 'support', 'people']
  Topic 1: ['using', 'just', 'use', 'like', 'people']
  Topic 2: ['use', 'write', 'asking', 'like', 'just']
  Topic 3: ['support', 'human', 'help', 'people', 'provide']
  Topic 4: ['support', 'technology', 'data', 'using', 'healthcare']

# Positive NMF

In [ ]:
doc_topics, pos_topic_words, pos_docs = run_nmf(twitter_positive_df, keywords, 5)
for i, words in enumerate(pos_topic_words):
    print(f"Topic {i}: {words}")

Topic 0: ['support', 'mentalhealth', 'human', 'news', 'care', 'potential', 'chatbots', 'technology', 'accessible', 'future']
Topic 1: ['best', 'new', 'fun', 'things', 'google', 'friendship', 'assistant', 'human', 'facts', 'postcards']
Topic 2: ['people', 'use', 'free', 'great', 'expensive', 'life', 'tool', 'fun', 'case', 'today']
Topic 3: ['good', 'better', 'day', 'year', 'time', 'thank', 'help', 'advice', 'prompts', 'hey']
Topic 4: ['voice', 'life', 'conversation', 'tool', 'personal', 'work', 'mode', 'productivity', 'balance', 'stress']

In [ ]:
# Coherence
tokenized_docs = [doc.split() for doc in pos_docs]
dictionary = Dictionary(tokenized_docs)
coh = CoherenceModel(topics=pos_topic_words, texts=tokenized_docs, dictionary=dictionary, coherence='c_v')
print(f"Coherence: {coh.get_coherence()}")

# Diversity
unique_words = set()
all_words = []
for words in pos_topic_words:
    all_words.extend(words)
    unique_words.update(words)
print(f"Topic Diversity: {len(unique_words) / len(all_words)}")

# Seed Stability
seeds = [42, 123, 456]
for seed in seeds:
    vectorizer = TfidfVectorizer(stop_words="english", max_df=0.8, min_df=2)
    X = vectorizer.fit_transform(pos_docs)
    nmf = NMF(n_components=5, random_state=seed)
    W = nmf.fit_transform(X)
    H = nmf.components_
    vocab = vectorizer.get_feature_names_out()
    print(f"\nSeed {seed}:")
    for k in range(5):
        top_idx = H[k].argsort()[::-1][:5]
        words = [vocab[i] for i in top_idx]
        print(f"  Topic {k}: {words}")

Coherence: 0.4884296758694943
Topic Diversity: 0.92

Seed 42:
  Topic 0: ['support', 'mentalhealth', 'human', 'news', 'care']
  Topic 1: ['best', 'new', 'fun', 'things', 'google']
  Topic 2: ['people', 'use', 'free', 'great', 'expensive']
  Topic 3: ['good', 'better', 'day', 'year', 'time']
  Topic 4: ['voice', 'life', 'conversation', 'tool', 'personal']

Seed 123:
  Topic 0: ['support', 'mentalhealth', 'human', 'news', 'care']
  Topic 1: ['best', 'new', 'fun', 'things', 'google']
  Topic 2: ['people', 'use', 'free', 'great', 'expensive']
  Topic 3: ['good', 'better', 'day', 'year', 'time']
  Topic 4: ['voice', 'life', 'conversation', 'tool', 'personal']

Seed 456:
  Topic 0: ['support', 'mentalhealth', 'human', 'news', 'care']
  Topic 1: ['best', 'new', 'fun', 'things', 'google']
  Topic 2: ['people', 'use', 'free', 'great', 'expensive']
  Topic 3: ['good', 'better', 'day', 'year', 'time']
  Topic 4: ['voice', 'life', 'conversation', 'tool', 'personal']

# Neutral NMF

In [ ]:
neu_doc_topics, neu_topic_words, neu_docs = run_nmf(twitter_neutral_df, keywords, 5)
for i, words in enumerate(neu_topic_words):
    print(f"Topic {i}: {words}")

Topic 0: ['tic', 'google', 'coping', 'dialogue', 'app', 'play', 'selfcare', 'free', 'advice', 'freeapp']
Topic 1: ['support', 'issues', 'chatbots', 'mentalhealth', 'resources', 'professional', 'individuals', 'users', 'digital', 'company']
Topic 2: ['voice', 'mode', 'heard', 'conversation', 'warm', 'stress', 'personal', 'life', 'productivity', 'work']
Topic 3: ['use', 'free', 'expensive', 'don', 'mem', 'behavioral', 'cognitive', 'professional', 'bro', 'easy']
Topic 4: ['people', 'human', 'time', 'best', 'good', 'real', 'openai', 'tech', 'therapists', 'thing']

In [ ]:
# Coherence
tokenized_docs = [doc.split() for doc in neu_docs]
dictionary = Dictionary(tokenized_docs)
coh = CoherenceModel(topics=neu_topic_words, texts=tokenized_docs, dictionary=dictionary, coherence='c_v')
print(f"Coherence: {coh.get_coherence()}")

# Diversity
unique_words = set()
all_words = []
for words in neu_topic_words:
    all_words.extend(words)
    unique_words.update(words)
print(f"Topic Diversity: {len(unique_words) / len(all_words)}")

# Seed Stability
seeds = [42, 123, 456]
for seed in seeds:
    vectorizer = TfidfVectorizer(stop_words="english", max_df=0.8, min_df=2)
    X = vectorizer.fit_transform(neu_docs)
    nmf = NMF(n_components=5, random_state=seed)
    W = nmf.fit_transform(X)
    H = nmf.components_
    vocab = vectorizer.get_feature_names_out()
    print(f"\nSeed {seed}:")
    for k in range(5):
        top_idx = H[k].argsort()[::-1][:5]
        words = [vocab[i] for i in top_idx]
        print(f"  Topic {k}: {words}")

Coherence: 0.5568220143802756
Topic Diversity: 0.96

Seed 42:
  Topic 0: ['tic', 'google', 'coping', 'dialogue', 'app']
  Topic 1: ['support', 'issues', 'chatbots', 'mentalhealth', 'resources']
  Topic 2: ['voice', 'mode', 'heard', 'conversation', 'warm']
  Topic 3: ['use', 'free', 'expensive', 'don', 'mem']
  Topic 4: ['people', 'human', 'time', 'best', 'good']

Seed 123:
  Topic 0: ['tic', 'google', 'coping', 'dialogue', 'app']
  Topic 1: ['support', 'issues', 'chatbots', 'mentalhealth', 'resources']
  Topic 2: ['voice', 'mode', 'heard', 'conversation', 'warm']
  Topic 3: ['use', 'free', 'expensive', 'don', 'mem']
  Topic 4: ['people', 'human', 'time', 'best', 'good']

Seed 456:
  Topic 0: ['tic', 'google', 'coping', 'dialogue', 'app']
  Topic 1: ['support', 'issues', 'chatbots', 'mentalhealth', 'resources']
  Topic 2: ['voice', 'mode', 'heard', 'conversation', 'warm']
  Topic 3: ['use', 'free', 'expensive', 'don', 'mem']
  Topic 4: ['people', 'human', 'time', 'best', 'good']